import type { EnjazSupabaseClient } from '../../core/supabase/client.ts';
import { DataAccessError, normalizeDataFailure, normalizeThrownDataFailure, type DataFailureLike } from '../../data/contracts/DataAccessError.ts';

export type CrmLeadStage='inquiry'|'qualified'|'quoted'|'accepted'|'lost'|'converted';
export type CrmQuotationStatus='draft'|'pending_approval'|'approved'|'sent'|'accepted'|'rejected'|'expired';
export type IntakeSubmissionStatus='draft'|'submitted'|'under_review'|'approved'|'rejected'|'converted';
export type IntakeFieldType='text'|'textarea'|'email'|'phone'|'select'|'file';
export interface ServiceCatalogSummary{readonly id:string;readonly code:string;readonly name:string;readonly description:string|null;readonly basePrice:string;readonly expectedDurationDays:number|null;readonly requiredInputs:readonly unknown[];readonly active:boolean}
export interface CrmLeadSummary{readonly id:string;readonly displayName:string;readonly organizationName:string|null;readonly phone:string|null;readonly email:string|null;readonly source:string|null;readonly stage:CrmLeadStage;readonly lostReason:string|null;readonly version:number;readonly convertedCompanyId:string|null;readonly convertedTransactionId:string|null}
export interface CrmServiceRequestSummary{readonly id:string;readonly leadId:string;readonly serviceId:string;readonly serviceName:string;readonly status:string;readonly notes:string|null}
export interface CrmQuotationSummary{readonly id:string;readonly leadId:string;readonly serviceRequestId:string|null;readonly status:CrmQuotationStatus;readonly currency:string;readonly subtotal:string;readonly discountPercent:string;readonly discountAmount:string;readonly total:string;readonly validUntil:string|null;readonly approvalRequired:boolean;readonly version:number}
export interface IntakeReviewSummary{readonly id:string;readonly formId:string;readonly formTitle:string;readonly status:IntakeSubmissionStatus;readonly submittedAt:string|null;readonly version:number;readonly fileCount:number;readonly pendingUploadCount:number}
export interface IntakeFormSummary{readonly id:string;readonly name:string;readonly publicTitle:string;readonly active:boolean;readonly version:number;readonly fieldCount:number}
export interface CrmIntakeContext{readonly authority:'crm_pre_transaction_and_reviewed_intake';readonly externalSubmissionAuthority:'non_authoritative';readonly companyWriteAuthority:'guarded_conversion_rpc_only';readonly transactionWriteAuthority:'guarded_conversion_rpc_only';readonly financeLedgerWriteAuthority:'none';readonly services:readonly ServiceCatalogSummary[];readonly leads:readonly CrmLeadSummary[];readonly serviceRequests:readonly CrmServiceRequestSummary[];readonly quotations:readonly CrmQuotationSummary[];readonly reviewQueue:readonly IntakeReviewSummary[];readonly forms:readonly IntakeFormSummary[]}
export interface IntakeFormFieldDefinition{readonly key:string;readonly label:string;readonly type:IntakeFieldType;readonly required:boolean;readonly config:Readonly<Record<string,unknown>>}
export interface PublicIntakeView{readonly publicAuthority:'non_authoritative';readonly form:Readonly<{title:string;description:string|null;fields:readonly IntakeFormFieldDefinition[]}>;readonly expiresAt:string;readonly submission:null|Readonly<{id:string;status:IntakeSubmissionStatus;answers:Readonly<Record<string,string>>;version:number;submittedAt:string|null}>}
export interface IntakeFileMetadata{readonly fieldKey:string;readonly fileName:string;readonly mimeType:string;readonly byteSize:number}
export interface QuotationLineInput{readonly serviceId:string|null;readonly description:string;readonly quantity:number;readonly unitPrice:number}
export interface IntakeFormFieldInput{readonly key:string;readonly label:string;readonly type:IntakeFieldType;readonly required:boolean;readonly config?:Readonly<Record<string,unknown>>}
export interface CrmIntakeGateway{
  loadContext(workspaceId:string):Promise<CrmIntakeContext>;
  saveService(input:Readonly<{workspaceId:string;serviceId:string|null;code:string;name:string;description:string|null;basePrice:number;expectedDurationDays:number|null;requiredInputs:readonly unknown[];rules:Readonly<Record<string,unknown>>;active:boolean}>):Promise<Readonly<Record<string,unknown>>>;
  createLead(input:Readonly<{workspaceId:string;displayName:string;organizationName:string|null;phone:string|null;email:string|null;source:string|null;assignedUserId:string|null}>):Promise<Readonly<Record<string,unknown>>>;
  advanceLead(workspaceId:string,leadId:string,expectedVersion:number,nextStage:Exclude<CrmLeadStage,'inquiry'|'converted'>,lostReason:string|null):Promise<Readonly<Record<string,unknown>>>;
  createServiceRequest(workspaceId:string,leadId:string,serviceId:string,notes:string|null):Promise<Readonly<Record<string,unknown>>>;
  createQuotation(input:Readonly<{workspaceId:string;leadId:string;serviceRequestId:string|null;currency:string;discountPercent:number;validUntil:string|null;items:readonly QuotationLineInput[]}>):Promise<Readonly<Record<string,unknown>>>;
  approveQuotation(workspaceId:string,quotationId:string,expectedVersion:number):Promise<Readonly<Record<string,unknown>>>;
  acceptQuotation(workspaceId:string,quotationId:string,expectedVersion:number):Promise<Readonly<Record<string,unknown>>>;
  saveIntakeForm(input:Readonly<{workspaceId:string;formId:string|null;name:string;publicTitle:string;publicDescription:string|null;active:boolean;fields:readonly IntakeFormFieldInput[]}>):Promise<Readonly<Record<string,unknown>>>;
  issueIntakeLink(workspaceId:string,formId:string,leadId:string|null,expiresInHours:number):Promise<Readonly<{linkId:string;token:string;expiresAt:string}>>;
  revokeIntakeLink(workspaceId:string,linkId:string):Promise<Readonly<Record<string,unknown>>>;
  getPublicIntake(token:string):Promise<PublicIntakeView>;
  savePublicIntake(token:string,answers:Readonly<Record<string,string>>,files:readonly IntakeFileMetadata[],finalize:boolean):Promise<Readonly<{submissionId:string;status:IntakeSubmissionStatus;version:number;authoritative:false;pendingUploadCount:number}>>;
  reviewSubmission(input:Readonly<{workspaceId:string;submissionId:string;expectedVersion:number;decision:'approve'|'reject';mapping:Readonly<Record<string,string>>;note:string|null}>):Promise<Readonly<Record<string,unknown>>>;
  convertLead(input:Readonly<{workspaceId:string;leadId:string;reuseCompanyId:string|null;transactionType:string;department:string}>):Promise<Readonly<Record<string,unknown>>>;
}

interface RpcResponse{readonly data:unknown;readonly error:DataFailureLike|null} interface RpcLike{rpc(name:string,args:Readonly<Record<string,unknown>>):PromiseLike<RpcResponse>}
const TIMEOUT=15000,U=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,T=/^[0-9a-f]{64}$/,D=/^\d{4}-\d{2}-\d{2}$/,C=/^[A-Z]{3}$/;
const ST=['inquiry','qualified','quoted','accepted','lost','converted'] as const,QS=['draft','pending_approval','approved','sent','accepted','rejected','expired'] as const,SS=['draft','submitted','under_review','approved','rejected','converted'] as const,FT=['text','textarea','email','phone','select','file'] as const;
function bad(validation=false):never{throw new DataAccessError('Invalid CRM/intake data',validation?'DATA_VALIDATION_FAILED':'DATA_OPERATION_FAILED')}
function rec(v:unknown):Readonly<Record<string,unknown>>{if(!v||typeof v!=='object'||Array.isArray(v))bad();return v as Readonly<Record<string,unknown>>} function arr(v:unknown):readonly unknown[]{if(!Array.isArray(v))bad();return v}
function str(v:unknown,max=2400){if(typeof v!=='string'||!v.trim()||v.length>max)bad();return v.trim()} function opt(v:unknown,max=2400){return v===null||v===undefined||v===''?null:str(v,max)} function id(v:unknown){const s=str(v,64);if(!U.test(s))bad(true);return s} function oid(v:unknown){return v===null||v===undefined||v===''?null:id(v)} function uint(v:unknown){if(typeof v!=='number'||!Number.isSafeInteger(v)||v<0)bad();return v} function count(v:unknown){const n=typeof v==='number'?v:Number(v);if(!Number.isSafeInteger(n)||n<0)bad();return n} function num(v:unknown){const n=typeof v==='number'?v:Number(v);if(!Number.isFinite(n)||n<0)bad();return String(v)} function one<T extends string>(v:unknown,a:readonly T[]):T{if(!a.includes(v as T))bad();return v as T}
function parseService(v:unknown):ServiceCatalogSummary{const r=rec(v);return Object.freeze({id:id(r.id),code:str(r.code,80),name:str(r.name,240),description:opt(r.description),basePrice:num(r.basePrice),expectedDurationDays:r.expectedDurationDays===null||r.expectedDurationDays===undefined?null:count(r.expectedDurationDays),requiredInputs:Object.freeze(arr(r.requiredInputs)),active:r.active===true})}
function parseLead(v:unknown):CrmLeadSummary{const r=rec(v);return Object.freeze({id:id(r.id),displayName:str(r.displayName,240),organizationName:opt(r.organizationName,400),phone:opt(r.phone,80),email:opt(r.email,320),source:opt(r.source,160),stage:one(r.stage,ST),lostReason:opt(r.lostReason,1200),version:count(r.version),convertedCompanyId:oid(r.convertedCompanyId),convertedTransactionId:oid(r.convertedTransactionId)})}
function parseRequest(v:unknown):CrmServiceRequestSummary{const r=rec(v);return Object.freeze({id:id(r.id),leadId:id(r.leadId),serviceId:id(r.serviceId),serviceName:str(r.serviceName,240),status:str(r.status,40),notes:opt(r.notes)})}
function parseQuote(v:unknown):CrmQuotationSummary{const r=rec(v);return Object.freeze({id:id(r.id),leadId:id(r.leadId),serviceRequestId:oid(r.serviceRequestId),status:one(r.status,QS),currency:str(r.currency,3),subtotal:num(r.subtotal),discountPercent:num(r.discountPercent),discountAmount:num(r.discountAmount),total:num(r.total),validUntil:opt(r.validUntil,16),approvalRequired:r.approvalRequired===true,version:count(r.version)})}
function parseReview(v:unknown):IntakeReviewSummary{const r=rec(v);return Object.freeze({id:id(r.id),formId:id(r.formId),formTitle:str(r.formTitle,240),status:one(r.status,SS),submittedAt:opt(r.submittedAt,64),version:count(r.version),fileCount:count(r.fileCount),pendingUploadCount:count(r.pendingUploadCount)})}
function parseFormSummary(v:unknown):IntakeFormSummary{const r=rec(v);return Object.freeze({id:id(r.id),name:str(r.name,240),publicTitle:str(r.publicTitle,240),active:r.active===true,version:count(r.version),fieldCount:count(r.fieldCount)})}
function parseContext(v:unknown):CrmIntakeContext{const r=rec(v);if(r.authority!=='crm_pre_transaction_and_reviewed_intake'||r.externalSubmissionAuthority!=='non_authoritative'||r.companyWriteAuthority!=='guarded_conversion_rpc_only'||r.transactionWriteAuthority!=='guarded_conversion_rpc_only'||r.financeLedgerWriteAuthority!=='none')bad();return Object.freeze({authority:r.authority,externalSubmissionAuthority:r.externalSubmissionAuthority,companyWriteAuthority:r.companyWriteAuthority,transactionWriteAuthority:r.transactionWriteAuthority,financeLedgerWriteAuthority:r.financeLedgerWriteAuthority,services:Object.freeze(arr(r.services).map(parseService)),leads:Object.freeze(arr(r.leads).map(parseLead)),serviceRequests:Object.freeze(arr(r.serviceRequests).map(parseRequest)),quotations:Object.freeze(arr(r.quotations).map(parseQuote)),reviewQueue:Object.freeze(arr(r.reviewQueue).map(parseReview)),forms:Object.freeze(arr(r.forms).map(parseFormSummary))})}
function parseField(v:unknown):IntakeFormFieldDefinition{const r=rec(v),config=rec(r.config);return Object.freeze({key:str(r.key,80),label:str(r.label,240),type:one(r.type,FT),required:r.required===true,config:Object.freeze({...config})})}
function parsePublic(v:unknown):PublicIntakeView{const r=rec(v);if(r.publicAuthority!=='non_authoritative')bad();const f=rec(r.form),s=r.submission===null?null:rec(r.submission),answers=s?rec(s.answers):null;return Object.freeze({publicAuthority:r.publicAuthority,form:Object.freeze({title:str(f.title,240),description:opt(f.description),fields:Object.freeze(arr(f.fields).map(parseField))}),expiresAt:str(r.expiresAt,64),submission:s?Object.freeze({id:id(s.id),status:one(s.status,SS),answers:Object.freeze(Object.fromEntries(Object.entries(answers!).map(([k,x])=>[k,typeof x==='string'?x:'']))),version:count(s.version),submittedAt:opt(s.submittedAt,64)}):null})}
function token(v:string){if(!T.test(v))bad(true);return v} function version(v:number){if(!Number.isSafeInteger(v)||v<1)bad(true);return v} function date(v:string|null){if(v===null)return null;if(!D.test(v)||!Number.isFinite(Date.parse(`${v}T00:00:00Z`)))bad(true);return v} function text(v:string,max:number,required=true){const s=v.trim();if((required&&!s)||s.length>max)bad(true);return s||null} function recordPayload(v:Readonly<Record<string,unknown>>){return Object.freeze({...v})}
function validateFiles(files:readonly IntakeFileMetadata[]){if(files.length>40)bad(true);return files.map(f=>{const fieldKey=text(f.fieldKey,80),fileName=text(f.fileName,320),mimeType=text(f.mimeType,160);if(!Number.isSafeInteger(f.byteSize)||f.byteSize<1||f.byteSize>52428800)bad(true);return {fieldKey,fileName,mimeType,byteSize:f.byteSize}})}
async function settle<T>(p:PromiseLike<T>,write:boolean,t:number):Promise<T>{let timer:ReturnType<typeof setTimeout>|undefined;const deadline=new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new DataAccessError('CRM/intake request timeout',write?'DATA_OUTCOME_UNKNOWN':'DATA_UNAVAILABLE')),t)});try{return await Promise.race([Promise.resolve(p),deadline])}catch(e){throw normalizeThrownDataFailure(e,write?'write':'read')}finally{if(timer)clearTimeout(timer)}} async function rpc(c:RpcLike,n:string,a:Readonly<Record<string,unknown>>,write:boolean,t:number){const r=await settle(c.rpc(n,a),write,t);if(r.error)throw normalizeDataFailure(r.error);return r.data}

export function createCrmIntakeGateway(client:EnjazSupabaseClient,timeoutMs=TIMEOUT):CrmIntakeGateway{
  if(!Number.isSafeInteger(timeoutMs)||timeoutMs<1||timeoutMs>120000)throw new Error('Invalid CRM/intake timeout');const c=client as unknown as RpcLike;
  return Object.freeze({
    async loadContext(workspaceId){return parseContext(await rpc(c,'get_crm_intake_context_v1',{p_workspace_id:id(workspaceId)},false,timeoutMs))},
    async saveService(x){if(!Number.isFinite(x.basePrice)||x.basePrice<0||x.expectedDurationDays!==null&&(!Number.isSafeInteger(x.expectedDurationDays)||x.expectedDurationDays<0||x.expectedDurationDays>3650))bad(true);return recordPayload(rec(await rpc(c,'save_service_catalog_item_v1',{p_workspace_id:id(x.workspaceId),p_service_id:x.serviceId? id(x.serviceId):null,p_code:text(x.code,80),p_name:text(x.name,240),p_description:x.description?.trim()||null,p_base_price:x.basePrice,p_expected_duration_days:x.expectedDurationDays,p_required_inputs:x.requiredInputs,p_rules:x.rules,p_active:x.active},true,timeoutMs)))},
    async createLead(x){return recordPayload(rec(await rpc(c,'create_crm_lead_v1',{p_workspace_id:id(x.workspaceId),p_display_name:text(x.displayName,240),p_organization_name:x.organizationName?.trim()||null,p_phone:x.phone?.trim()||null,p_email:x.email?.trim().toLowerCase()||null,p_source:x.source?.trim()||null,p_assigned_user_id:x.assignedUserId?id(x.assignedUserId):null},true,timeoutMs)))},
    async advanceLead(workspaceId,leadId,expectedVersion,nextStage,lostReason){if(!['qualified','quoted','accepted','lost'].includes(nextStage))bad(true);if(nextStage==='lost'&&(!lostReason||lostReason.trim().length<3))bad(true);return recordPayload(rec(await rpc(c,'advance_crm_lead_v1',{p_workspace_id:id(workspaceId),p_lead_id:id(leadId),p_expected_version:version(expectedVersion),p_next_stage:nextStage,p_lost_reason:lostReason?.trim()||null},true,timeoutMs)))},
    async createServiceRequest(workspaceId,leadId,serviceId,notes){return recordPayload(rec(await rpc(c,'create_crm_service_request_v1',{p_workspace_id:id(workspaceId),p_lead_id:id(leadId),p_service_id:id(serviceId),p_notes:notes?.trim()||null},true,timeoutMs)))},
    async createQuotation(x){if(!C.test(x.currency)||!Number.isFinite(x.discountPercent)||x.discountPercent<0||x.discountPercent>30||!x.items.length||x.items.length>50)bad(true);const items=x.items.map(i=>{if(!Number.isFinite(i.quantity)||i.quantity<=0||!Number.isFinite(i.unitPrice)||i.unitPrice<0)bad(true);return {serviceId:i.serviceId?id(i.serviceId):null,description:text(i.description,500),quantity:i.quantity,unitPrice:i.unitPrice}});return recordPayload(rec(await rpc(c,'create_crm_quotation_v1',{p_workspace_id:id(x.workspaceId),p_lead_id:id(x.leadId),p_service_request_id:x.serviceRequestId?id(x.serviceRequestId):null,p_currency:x.currency,p_discount_percent:x.discountPercent,p_valid_until:date(x.validUntil),p_items:items},true,timeoutMs)))},
    async approveQuotation(workspaceId,quotationId,expectedVersion){return recordPayload(rec(await rpc(c,'approve_crm_quotation_v1',{p_workspace_id:id(workspaceId),p_quotation_id:id(quotationId),p_expected_version:version(expectedVersion)},true,timeoutMs)))},
    async acceptQuotation(workspaceId,quotationId,expectedVersion){return recordPayload(rec(await rpc(c,'accept_crm_quotation_v1',{p_workspace_id:id(workspaceId),p_quotation_id:id(quotationId),p_expected_version:version(expectedVersion)},true,timeoutMs)))},
    async saveIntakeForm(x){if(!x.fields.length||x.fields.length>80)bad(true);const fields=x.fields.map(f=>({key:text(f.key,80),label:text(f.label,240),type:one(f.type,FT),required:f.required,config:f.config??{}}));return recordPayload(rec(await rpc(c,'save_intake_form_v1',{p_workspace_id:id(x.workspaceId),p_form_id:x.formId?id(x.formId):null,p_name:text(x.name,240),p_public_title:text(x.publicTitle,240),p_public_description:x.publicDescription?.trim()||null,p_active:x.active,p_fields:fields},true,timeoutMs)))},
    async issueIntakeLink(workspaceId,formId,leadId,expiresInHours){if(!Number.isSafeInteger(expiresInHours)||expiresInHours<1||expiresInHours>720)bad(true);const r=rec(await rpc(c,'issue_intake_link_v1',{p_workspace_id:id(workspaceId),p_form_id:id(formId),p_lead_id:leadId?id(leadId):null,p_expires_in_hours:expiresInHours},true,timeoutMs));return Object.freeze({linkId:id(r.linkId),token:token(str(r.token,64)),expiresAt:str(r.expiresAt,64)})},
    async revokeIntakeLink(workspaceId,linkId){return recordPayload(rec(await rpc(c,'revoke_intake_link_v1',{p_workspace_id:id(workspaceId),p_link_id:id(linkId)},true,timeoutMs)))},
    async getPublicIntake(rawToken){return parsePublic(await rpc(c,'get_public_intake_v1',{p_token:token(rawToken)},false,timeoutMs))},
    async savePublicIntake(rawToken,answers,files,finalize){for(const [k,v] of Object.entries(answers)){if(!/^[A-Za-z0-9_.-]{1,80}$/.test(k)||typeof v!=='string'||v.length>4000)bad(true)}const r=rec(await rpc(c,'save_public_intake_v1',{p_token:token(rawToken),p_answers:answers,p_files:validateFiles(files),p_finalize:finalize},true,timeoutMs));if(r.authoritative!==false)bad();return Object.freeze({submissionId:id(r.submissionId),status:one(r.status,SS),version:count(r.version),authoritative:false,pendingUploadCount:count(r.pendingUploadCount)})},
    async reviewSubmission(x){if(x.decision==='approve'&&!Object.keys(x.mapping).length)bad(true);return recordPayload(rec(await rpc(c,'review_intake_submission_v1',{p_workspace_id:id(x.workspaceId),p_submission_id:id(x.submissionId),p_expected_version:version(x.expectedVersion),p_decision:x.decision,p_mapping:x.mapping,p_note:x.note?.trim()||null},true,timeoutMs)))},
    async convertLead(x){return recordPayload(rec(await rpc(c,'convert_crm_lead_v1',{p_workspace_id:id(x.workspaceId),p_lead_id:id(x.leadId),p_reuse_company_id:x.reuseCompanyId?id(x.reuseCompanyId):null,p_transaction_type:text(x.transactionType,180),p_department:text(x.department,240)},true,timeoutMs)))}
  });
}
