import {useEffect,useRef,useState,type FormEvent} from 'react';
import {useDataLayerFactory} from '../../data/react/DataLayerContext.tsx';
import type {DocumentFactoryGateway} from '../../features/documents/documentFactoryCommands.ts';
import type {DocumentIntelligenceGateway} from '../../features/documents/documentIntelligenceCommands.ts';
import type {DocumentVaultGateway} from '../../features/documents/documentVaultCommands.ts';
import {DOCUMENT_VAULT_ALLOWED_MIME,formatVaultBytes,type DocumentUploadInput,type VaultDetail,type VaultDocument} from '../../features/documents/documentVaultContract.ts';
import {createDocumentUploadRetryTicket,executeDocumentUploadRetry,type DocumentUploadRetryTicket} from '../../features/documents/documentUploadRetry.ts';
import {DocumentFactoryPanel} from './DocumentFactoryPanel.tsx';
import {DocumentIntelligencePanel} from './DocumentIntelligencePanel.tsx';
import '../regulatory/regulatory-knowledge.css';

type Option=Readonly<{id:string;label:string;companyId?:string}>;
type Props=Readonly<{gateway:DocumentVaultGateway;workspace:Promise<string|null>;intelligenceGateway?:DocumentIntelligenceGateway;documentFactoryGateway?:DocumentFactoryGateway}>;
type State={ws:string|null;docs:readonly VaultDocument[];total:number;offset:number;query:string;archived:boolean;loading:boolean;busy:boolean;error:string;detail:VaultDetail|null;companies:readonly Option[];transactions:readonly Option[]};
type PendingUpload=Readonly<{ticket:DocumentUploadRetryTicket;after:()=>Promise<void>}>;
const label=(s:string)=>s==='ready'?'جاهز':s==='processing'?'جارٍ الرفع':s==='needs_review'?'مراجعة':s==='failed'?'فشل':'مؤرشف',kind=(m:string)=>m==='application/pdf'?'PDF':m.startsWith('image/')?'صورة':m.includes('wordprocessingml')?'Word':m.includes('spreadsheetml')?'Excel':'ملف',text=(f:FormData,k:string)=>String(f.get(k)||'').trim();

export function ConnectedDocumentVault({gateway,workspace,intelligenceGateway,documentFactoryGateway}:Props){
 const factory=useDataLayerFactory(),versionInput=useRef<HTMLInputElement|null>(null),pendingUpload=useRef<PendingUpload|null>(null),[s,set]=useState<State>({ws:null,docs:[],total:0,offset:0,query:'',archived:false,loading:true,busy:false,error:'',detail:null,companies:[],transactions:[]}),patch=(p:Partial<State>)=>set(v=>({...v,...p}));
 const load=async(ws=s.ws,q=s.query,a=s.archived,offset=s.offset)=>{if(!ws)return;patch({loading:true});try{const r=await gateway.list(ws,q,a,offset);patch({docs:r.documents,total:r.total,offset:r.offset,error:''})}catch{patch({error:'تعذر تحميل خزنة الوثائق.'})}finally{patch({loading:false})}};
 const runPending=async(pending:PendingUpload)=>{patch({busy:true});try{const outcome=await executeDocumentUploadRetry(gateway,pending.ticket);if(outcome.status==='uploaded'){pendingUpload.current=null;patch({error:''});await pending.after();return}if(outcome.status==='deferred_offline'){pendingUpload.current={ticket:outcome.ticket,after:pending.after};patch({error:'انقطع الاتصال. تم تعليق الرفع بأمان وسيُستأنف بنفس العملية عند عودة الشبكة.'});return}pendingUpload.current=null;throw outcome.error}finally{patch({busy:false})}};
 const queueUpload=async(input:DocumentUploadInput,after:()=>Promise<void>)=>{const pending:PendingUpload={ticket:createDocumentUploadRetryTicket(input),after};pendingUpload.current=pending;await runPending(pending)};

 useEffect(()=>{let live=true;void workspace.then(async ws=>{if(!live)return;if(!ws){patch({loading:false,error:'لا توجد مساحة عمل صالحة.'});return}patch({ws});try{const l=factory.forWorkspace(ws),[c,t]=await Promise.all([l.companies.list({orderBy:[{column:'updated_at',ascending:false}],limit:100}),l.transactions.list({orderBy:[{column:'updated_at',ascending:false}],limit:100})]);if(!live)return;patch({companies:c.items.map(x=>({id:x.id,label:x.display_name?.trim()||x.legal_name})),transactions:t.items.map(x=>({id:x.id,label:`${x.type} · ${x.status}`,companyId:x.company_id}))});await load(ws,'',false,0)}catch{if(live)patch({loading:false,error:'تعذر تهيئة الخزنة.'})}});return()=>{live=false}},[workspace,factory]);
 useEffect(()=>{if(!s.ws)return;const id=new URLSearchParams(location.search).get('entity');if(id)void gateway.detail(s.ws,id).then(detail=>patch({detail})).catch(()=>undefined)},[s.ws,gateway]);
 useEffect(()=>{const resume=()=>{const pending=pendingUpload.current;if(pending)void runPending(pending).catch(()=>{pendingUpload.current=null;patch({error:'تعذر استئناف الرفع بعد عودة الاتصال؛ لم تُعتمد نسخة غير متحققة.'})})};window.addEventListener('online',resume);return()=>window.removeEventListener('online',resume)},[gateway]);

 const open=async(d:VaultDocument)=>{if(!s.ws)return;try{patch({detail:await gateway.detail(s.ws,d.id),error:''})}catch{patch({error:'تعذر فتح الوثيقة.'})}},download=async(id:string,v?:number)=>{if(!s.ws)return;try{location.assign(await gateway.downloadUrl(s.ws,id,v??null))}catch{patch({error:'تعذر إنشاء رابط تنزيل آمن.'})}},archive=async(id:string)=>{if(!s.ws)return;try{await gateway.archive(s.ws,id);patch({detail:null});await load(s.ws)}catch{patch({error:'تعذر أرشفة الوثيقة.'})}};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!s.ws)return;const form=e.currentTarget,f=new FormData(form),file=f.get('file');if(!(file instanceof File))return;try{await queueUpload({workspaceId:s.ws,title:text(f,'title'),documentType:text(f,'kind')||null,companyId:text(f,'company')||null,transactionId:text(f,'transaction')||null,file},async()=>{form.reset();await load(s.ws,'',s.archived,0)})}catch{patch({error:'فشل الرفع أو التحقق؛ لم تُعتمد نسخة غير متحققة.'})}};
 const addVersion=async(file:File)=>{if(!s.ws||!s.detail)return;const d=s.detail.document;try{await queueUpload({workspaceId:s.ws,documentId:d.id,title:d.title,documentType:d.documentType,companyId:d.companyId,transactionId:d.transactionId,file},async()=>{patch({detail:await gateway.detail(s.ws!,d.id),error:''});await load(s.ws)})}catch{patch({error:'تعذر اعتماد النسخة الجديدة.'})}finally{if(versionInput.current)versionInput.current.value=''}};
 const relation=(d:VaultDocument)=>s.companies.find(x=>x.id===d.companyId)?.label||s.transactions.find(x=>x.id===d.transactionId)?.label||'غير مرتبط',end=Math.min(s.offset+s.docs.length,s.total),canNext=s.offset+100<s.total;
 return <section className="rk-center" dir="rtl" data-phase10-1="document-vault" data-phase10-6="zero-escape" data-vault-authority="documents+document_versions" data-binary-boundary="signed-broker-only" data-binary-hardening="server-inspection+checksum">
  <header className="rk-hero"><div><span className="rk-kicker">Document Vault · 10.6 hardened</span><h1>خزنة الوثائق</h1><p>حفظ خاص، فحص بنيوي للملف، ربط بالسجلات، ونسخ متعاقبة لا تكتب فوق بعضها.</p></div><div className="rk-hero__stats"><div><span>{s.total}</span><small>وثيقة</small></div><div><span>{s.docs.length}</span><small>في الصفحة</small></div><div><span>خاص</span><small>وصول موقّع</small></div></div></header>
  <form className="rk-official-text" aria-label="رفع وثيقة" onSubmit={e=>void submit(e)}><div className="rk-section-title"><div><span className="rk-kicker">إضافة آمنة</span><h2>وثيقة جديدة</h2></div><span className="rk-truth-chip">فحص + SHA‑256 · بدون overwrite</span></div><div className="rk-provenance"><div><span>الملف</span><label className="rk-search"><input name="file" required type="file" accept={DOCUMENT_VAULT_ALLOWED_MIME.join(',')}/></label><small>PDF / صورة / Word / Excel · 50 MB</small></div><div><span>العنوان</span><label className="rk-search"><input name="title" required maxLength={320}/></label></div><div><span>النوع</span><label className="rk-search"><input name="kind" maxLength={120} placeholder="عقد، شهادة، كتاب…"/></label></div><div><span>الشركة</span><select name="company"><option value="">بدون ربط</option>{s.companies.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></div><div><span>المعاملة</span><select name="transaction"><option value="">بدون ربط</option>{s.transactions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></div><div><span>اعتماد النسخة</span><button type="submit" className="rk-button rk-button--primary" disabled={s.busy}>{s.busy?'جارٍ الرفع والتحقق…':'رفع واعتماد النسخة'}</button></div></div></form>
  <form className="rk-toolbar" onSubmit={e=>{e.preventDefault();const q=text(new FormData(e.currentTarget),'q');patch({query:q,offset:0});void load(s.ws,q,s.archived,0)}}><label className="rk-search"><span aria-hidden="true">⌕</span><input name="q" defaultValue={s.query} maxLength={120} placeholder="ابحث بالعنوان أو النوع…"/></label><div className="rk-filter-row"><button type="submit">بحث</button><button type="button" className={s.archived?'is-active':''} aria-pressed={s.archived} onClick={()=>{const a=!s.archived;patch({archived:a,offset:0});void load(s.ws,s.query,a,0)}}>إظهار المؤرشف</button></div></form>
  {s.error?<section className="rk-empty rk-empty--error" role="alert"><div className="rk-empty__mark">!</div><h2>تعذر إكمال العملية</h2><p>{s.error}</p></section>:null}
  {s.loading?<div className="rk-skeletons"><div className="rk-skeleton"/><div className="rk-skeleton"/></div>:!s.docs.length?<section className="rk-empty"><div className="rk-empty__mark">↥</div><h2>الخزنة جاهزة</h2><p>لا توجد وثائق مطابقة حتى الآن.</p></section>:<><div className="rk-result-grid">{s.docs.map(d=><article className="rk-result" key={d.id} data-document-status={d.status}><div className="rk-result__top"><span className="rk-authority rk-authority--official">{label(d.status)}</span><span className="rk-kind">{kind(d.mimeType)}</span></div><strong>{d.title}</strong><span className="rk-result__excerpt">{d.fileName||'اسم الملف غير متاح'}</span><span className="rk-result__foot"><span>{formatVaultBytes(d.sizeBytes)}</span><span>{relation(d)}</span></span><div className="rk-source-actions"><button type="button" className="rk-button" onClick={()=>void open(d)}>سجل النسخ</button>{d.status==='ready'?<button type="button" className="rk-button rk-button--primary" onClick={()=>void download(d.id)}>تنزيل</button>:null}{!['archived','processing'].includes(d.status)?<button type="button" className="rk-button" onClick={()=>void archive(d.id)}>أرشفة</button>:null}</div></article>)}</div><div className="rk-filter-row"><span>{s.total?`${s.offset+1}–${end} من ${s.total}`:'0'}</span><button type="button" disabled={!s.offset} onClick={()=>void load(s.ws,s.query,s.archived,Math.max(0,s.offset-100))}>السابق</button><button type="button" disabled={!canNext} onClick={()=>void load(s.ws,s.query,s.archived,s.offset+100)}>التالي</button></div></>}
  {s.detail?<div className="rk-detail-wrap"><button type="button" className="rk-detail-backdrop" aria-label="إغلاق التفاصيل" onClick={()=>patch({detail:null})}/><aside className="rk-detail" role="dialog" aria-modal="true" aria-label="تفاصيل الوثيقة"><div className="rk-detail__head"><div><span className="rk-kicker">سجل النسخ</span><h2>{s.detail.document.title}</h2><p>{s.detail.document.fileName||'—'}</p></div><button type="button" className="rk-detail__close" onClick={()=>patch({detail:null})} aria-label="إغلاق">×</button></div><section className="rk-provenance"><div><span>الحجم</span><strong>{formatVaultBytes(s.detail.document.sizeBytes)}</strong></div><div><span>الحالة</span><strong>{label(s.detail.document.status)}</strong></div><div><span>النسخ</span><strong>{s.detail.versions.length}</strong></div></section><section className="rk-derived"><div className="rk-section-title"><h3>النسخ المعتمدة</h3><span className="rk-non-authority-chip">تاريخ محفوظ</span></div>{s.detail.versions.length?s.detail.versions.map(v=><article className="rk-derived-card" key={v.id}><strong>الإصدار {v.versionNumber}</strong><p>{v.fileName||'ملف'} · {formatVaultBytes(v.sizeBytes)}</p><button type="button" className="rk-button" onClick={()=>void download(s.detail!.document.id,v.versionNumber)}>تنزيل</button></article>):<p>لا توجد نسخة معتمدة بعد.</p>}</section>{intelligenceGateway&&s.ws?<DocumentIntelligencePanel gateway={intelligenceGateway} workspaceId={s.ws} documentId={s.detail.document.id} currentVersionNumber={s.detail.versions.length?Math.max(...s.detail.versions.map(v=>v.versionNumber)):null}/>:null}{documentFactoryGateway&&s.ws?<DocumentFactoryPanel gateway={documentFactoryGateway} vaultGateway={gateway} {...(intelligenceGateway?{intelligenceGateway}:{})} workspaceId={s.ws} documentId={s.detail.document.id} sourceTitle={s.detail.document.title} companyId={s.detail.document.companyId} transactionId={s.detail.document.transactionId}/>:null}<div className="rk-source-actions">{s.detail.document.status!=='archived'&&s.detail.document.status!=='processing'?<><input ref={versionInput} hidden type="file" accept={DOCUMENT_VAULT_ALLOWED_MIME.join(',')} onChange={e=>{const f=e.target.files?.[0];if(f)void addVersion(f)}}/><button type="button" className="rk-button rk-button--primary" disabled={s.busy} onClick={()=>versionInput.current?.click()}>رفع نسخة جديدة</button><button type="button" className="rk-button" onClick={()=>void archive(s.detail!.document.id)}>أرشفة الوثيقة بدون حذف تاريخها</button></>:null}</div></aside></div>:null}
 </section>}
