import { useEffect,useRef,useState } from 'react';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import type { DocumentVaultGateway } from '../../features/documents/documentVaultCommands.ts';
import { DOCUMENT_VAULT_ALLOWED_MIME,formatVaultBytes,type VaultDetail,type VaultDocument } from '../../features/documents/documentVaultContract.ts';
import '../regulatory/regulatory-knowledge.css';

type Option=Readonly<{id:string;label:string;companyId?:string}>;type Props=Readonly<{gateway:DocumentVaultGateway;workspace:Promise<string|null>}>;
const stateLabel=(s:string)=>s==='ready'?'جاهز':s==='processing'?'جارٍ الرفع':s==='needs_review'?'مراجعة':s==='failed'?'فشل':'مؤرشف';
const fileKind=(m:string)=>m==='application/pdf'?'PDF':m.startsWith('image/')?'صورة':m.includes('wordprocessingml')?'Word':m.includes('spreadsheetml')?'Excel':'ملف';
export function ConnectedDocumentVault({gateway,workspace}:Props){
 const factory=useDataLayerFactory(),fileInput=useRef<HTMLInputElement|null>(null),[ws,setWs]=useState<string|null>(null),[query,setQuery]=useState(''),[archived,setArchived]=useState(false),[docs,setDocs]=useState<readonly VaultDocument[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(''),[detail,setDetail]=useState<VaultDetail|null>(null),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[kind,setKind]=useState(''),[company,setCompany]=useState(''),[transaction,setTransaction]=useState(''),[companies,setCompanies]=useState<readonly Option[]>([]),[transactions,setTransactions]=useState<readonly Option[]>([]),[uploading,setUploading]=useState(false);
 const refresh=async(id=ws,q=query,showArchived=archived)=>{if(!id)return;setLoading(true);try{const r=await gateway.list(id,q,showArchived);setDocs(r.documents);setTotal(r.total);setError('')}catch{setError('تعذر تحميل خزنة الوثائق.')}finally{setLoading(false)}};
 useEffect(()=>{let live=true;void workspace.then(async id=>{if(!live)return;if(!id){setError('لا توجد مساحة عمل صالحة.');setLoading(false);return}setWs(id);try{const layer=factory.forWorkspace(id),[c,t]=await Promise.all([layer.companies.list({orderBy:[{column:'updated_at',ascending:false}],limit:100}),layer.transactions.list({orderBy:[{column:'updated_at',ascending:false}],limit:100})]);if(!live)return;setCompanies(c.items.map(x=>({id:x.id,label:x.display_name?.trim()||x.legal_name})));setTransactions(t.items.map(x=>({id:x.id,label:`${x.type} · ${x.status}`,companyId:x.company_id})));await refresh(id,'',false)}catch{if(live){setError('تعذر تهيئة الخزنة.');setLoading(false)}}});return()=>{live=false}},[workspace,factory]);
 useEffect(()=>{if(!ws)return;const timer=setTimeout(()=>void refresh(ws,query,archived),220);return()=>clearTimeout(timer)},[ws,query,archived]);
 useEffect(()=>{if(!ws)return;const id=new URLSearchParams(location.search).get('entity');if(id)void gateway.detail(ws,id).then(setDetail).catch(()=>undefined)},[ws]);
 const choose=(next:File|null)=>{setFile(next);if(next&&!title.trim())setTitle((next.name.replace(/\.[^.]+$/,'').trim()||'وثيقة جديدة').slice(0,320))};
 const upload=async()=>{if(!ws||!file||!title.trim())return;setUploading(true);try{await gateway.upload({workspaceId:ws,title,documentType:kind.trim()||null,companyId:company||null,transactionId:transaction||null,file});setFile(null);setTitle('');setKind('');setCompany('');setTransaction('');if(fileInput.current)fileInput.current.value='';await refresh(ws)}catch{setError('فشل الرفع أو التحقق؛ لم تُعتمد نسخة غير متحققة.')}finally{setUploading(false)}};
 const open=async(d:VaultDocument)=>{if(!ws)return;try{setDetail(await gateway.detail(ws,d.id))}catch{setError('تعذر فتح الوثيقة.')}};
 const download=async(id:string,version?:number)=>{if(!ws)return;try{location.assign(await gateway.downloadUrl(ws,id,version??null))}catch{setError('تعذر إنشاء رابط تنزيل آمن.')}};
 const archive=async(id:string)=>{if(!ws)return;try{await gateway.archive(ws,id);setDetail(null);await refresh(ws)}catch{setError('تعذر أرشفة الوثيقة.')}};
 const versions=docs.reduce((n,d)=>n+d.versionCount,0),selectedTransaction=transactions.find(x=>x.id===transaction);
 return <section className="rk-center" dir="rtl" data-phase10-1="document-vault" data-vault-authority="documents+document_versions" data-binary-boundary="signed-broker-only">
  <header className="rk-hero"><div><span className="rk-kicker">Document Vault · 10.1</span><h1>خزنة الوثائق</h1><p>حفظ خاص، ربط بالسجلات، ونسخ متعاقبة لا تكتب فوق بعضها.</p></div><div className="rk-hero__stats"><div><span>{total}</span><small>وثيقة</small></div><div><span>{versions}</span><small>نسخة</small></div><div><span>خاص</span><small>وصول موقّع</small></div></div></header>
  <section className="rk-official-text" aria-label="رفع وثيقة"><div className="rk-section-title"><div><span className="rk-kicker">إضافة آمنة</span><h2>وثيقة جديدة</h2></div><span className="rk-truth-chip">بدون overwrite</span></div><div className="rk-provenance"><div><span>الملف</span><label className="rk-search"><input ref={fileInput} type="file" accept={DOCUMENT_VAULT_ALLOWED_MIME.join(',')} onChange={e=>choose(e.target.files?.[0]??null)}/></label><small>{file?`${fileKind(file.type)} · ${formatVaultBytes(file.size)}`:'PDF / صورة / Word / Excel · 50 MB'}</small></div><div><span>العنوان</span><label className="rk-search"><input value={title} maxLength={320} onChange={e=>setTitle(e.target.value)}/></label></div><div><span>النوع</span><label className="rk-search"><input value={kind} maxLength={120} onChange={e=>setKind(e.target.value)} placeholder="عقد، شهادة، كتاب…"/></label></div><div><span>الشركة</span><select value={selectedTransaction?.companyId||company} disabled={Boolean(selectedTransaction?.companyId)} onChange={e=>setCompany(e.target.value)}><option value="">بدون ربط</option>{companies.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></div><div><span>المعاملة</span><select value={transaction} onChange={e=>setTransaction(e.target.value)}><option value="">بدون ربط</option>{transactions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></div><div><span>اعتماد النسخة</span><button type="button" className="rk-button rk-button--primary" disabled={!file||!title.trim()||uploading} onClick={()=>void upload()}>{uploading?'جارٍ الرفع والتحقق…':'رفع واعتماد النسخة'}</button></div></div></section>
  <div className="rk-toolbar"><label className="rk-search"><span aria-hidden="true">⌕</span><input value={query} maxLength={120} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالعنوان أو النوع…"/></label><div className="rk-filter-row"><button type="button" className={archived?'is-active':''} aria-pressed={archived} onClick={()=>setArchived(v=>!v)}>إظهار المؤرشف</button></div></div>
  {error?<section className="rk-empty rk-empty--error" role="alert"><div className="rk-empty__mark">!</div><h2>تعذر إكمال العملية</h2><p>{error}</p></section>:null}
  {loading?<div className="rk-skeletons">{[0,1].map(x=><div className="rk-skeleton" key={x}/>)}</div>:!docs.length?<section className="rk-empty"><div className="rk-empty__mark">↥</div><h2>الخزنة جاهزة</h2><p>لا توجد وثائق مطابقة حتى الآن.</p></section>:<div className="rk-result-grid">{docs.map(d=><article className="rk-result" key={d.id} data-document-status={d.status}><div className="rk-result__top"><span className="rk-authority rk-authority--official">{stateLabel(d.status)}</span><span className="rk-kind">{fileKind(d.mimeType)}</span></div><strong>{d.title}</strong><span className="rk-result__excerpt">{d.fileName||'اسم الملف غير متاح'}</span><span className="rk-result__foot"><span>{formatVaultBytes(d.sizeBytes)} · v{d.currentVersion||'—'}</span><span>{d.companyName||d.transactionLabel||'غير مرتبط'}</span></span><div className="rk-source-actions"><button type="button" className="rk-button" onClick={()=>void open(d)}>سجل النسخ</button>{d.status==='ready'?<button type="button" className="rk-button rk-button--primary" onClick={()=>void download(d.id)}>تنزيل</button>:null}{!['archived','processing'].includes(d.status)?<button type="button" className="rk-button" onClick={()=>void archive(d.id)}>أرشفة</button>:null}</div></article>)}</div>}
  {detail?<div className="rk-detail-wrap"><button type="button" className="rk-detail-backdrop" aria-label="إغلاق التفاصيل" onClick={()=>setDetail(null)}/><aside className="rk-detail" role="dialog" aria-modal="true" aria-label="تفاصيل الوثيقة"><div className="rk-detail__head"><div><span className="rk-kicker">سجل النسخ</span><h2>{detail.document.title}</h2><p>{detail.document.fileName||'—'}</p></div><button type="button" className="rk-detail__close" onClick={()=>setDetail(null)} aria-label="إغلاق">×</button></div><section className="rk-provenance"><div><span>الحجم</span><strong>{formatVaultBytes(detail.document.sizeBytes)}</strong></div><div><span>الحالة</span><strong>{stateLabel(detail.document.status)}</strong></div><div><span>النسخ</span><strong>{detail.versions.length}</strong></div></section><section className="rk-derived"><div className="rk-section-title"><h3>النسخ المعتمدة</h3><span className="rk-non-authority-chip">تاريخ محفوظ</span></div>{detail.versions.length?detail.versions.map(v=><article className="rk-derived-card" key={v.id}><strong>الإصدار {v.versionNumber}</strong><p>{v.fileName||detail.document.fileName||'ملف'} · {formatVaultBytes(v.sizeBytes)}</p><button type="button" className="rk-button" onClick={()=>void download(detail.document.id,v.versionNumber)}>تنزيل</button></article>):<p>لا توجد نسخة معتمدة بعد.</p>}</section>{!['archived','processing'].includes(detail.document.status)?<button type="button" className="rk-button" onClick={()=>void archive(detail.document.id)}>أرشفة الوثيقة بدون حذف تاريخها</button>:null}</aside></div>:null}
 </section>
}
