import { useEffect,useMemo,useRef,useState } from 'react';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import type { DocumentVaultGateway } from '../../features/documents/documentVaultCommands.ts';
import { DOCUMENT_VAULT_ALLOWED_MIME,formatVaultBytes,type VaultDetail,type VaultDocument } from '../../features/documents/documentVaultContract.ts';
import './document-vault.css';

type RelationOption=Readonly<{id:string;label:string;companyId?:string}>;
type Props=Readonly<{gateway:DocumentVaultGateway;workspace:Promise<string|null>}>;
const statusLabel=(s:string)=>s==='ready'?'جاهز':s==='processing'?'جارٍ الرفع':s==='needs_review'?'يحتاج مراجعة':s==='failed'?'فشل الرفع':'مؤرشف';
const typeLabel=(m:string)=>m==='application/pdf'?'PDF':m.startsWith('image/')?'صورة':m.includes('wordprocessingml')?'Word':m.includes('spreadsheetml')?'Excel':'ملف';
function titleFromFile(name:string){const clean=name.replace(/\.[^.]+$/,'').trim();return clean.slice(0,320)||'وثيقة جديدة'}
export function ConnectedDocumentVault({gateway,workspace}:Props){
 const dataFactory=useDataLayerFactory(),fileRef=useRef<HTMLInputElement|null>(null),[workspaceId,setWorkspaceId]=useState<string|null>(null),[query,setQuery]=useState(''),[includeArchived,setIncludeArchived]=useState(false),[docs,setDocs]=useState<readonly VaultDocument[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[selected,setSelected]=useState<VaultDetail|null>(null),[busy,setBusy]=useState<string|null>(null),[file,setFile]=useState<File|null>(null),[title,setTitle]=useState(''),[documentType,setDocumentType]=useState(''),[companyId,setCompanyId]=useState(''),[transactionId,setTransactionId]=useState(''),[companies,setCompanies]=useState<readonly RelationOption[]>([]),[transactions,setTransactions]=useState<readonly RelationOption[]>([]);
 const refresh=async(w=workspaceId,q=query,archived=includeArchived)=>{if(!w)return;setLoading(true);setError(null);try{const r=await gateway.list(w,q,archived);setDocs(r.documents);setTotal(r.total)}catch{setError('تعذر تحميل خزنة الوثائق. لم يتم عرض بيانات بديلة أو وهمية.')}finally{setLoading(false)}};
 useEffect(()=>{let live=true;void workspace.then(async w=>{if(!live)return;setWorkspaceId(w);if(!w){setError('لا توجد مساحة عمل صالحة لهذا الحساب.');setLoading(false);return}try{const layer=dataFactory.forWorkspace(w),[c,t]=await Promise.all([layer.companies.list({orderBy:[{column:'updated_at',ascending:false}],limit:100}),layer.transactions.list({orderBy:[{column:'updated_at',ascending:false}],limit:100})]);if(!live)return;setCompanies(c.items.map(x=>({id:x.id,label:x.display_name?.trim()||x.legal_name})));setTransactions(t.items.map(x=>({id:x.id,label:`${x.type} · ${x.status}`,companyId:x.company_id})));await refresh(w,'',false)}catch{if(live){setError('تعذر تهيئة خزنة الوثائق.');setLoading(false)}}});return()=>{live=false}},[workspace,dataFactory]);
 useEffect(()=>{if(!workspaceId)return;const id=setTimeout(()=>void refresh(workspaceId,query,includeArchived),260);return()=>clearTimeout(id)},[query,includeArchived,workspaceId]);
 useEffect(()=>{if(!workspaceId)return;const entity=new URLSearchParams(window.location.search).get('entity');if(!entity)return;void gateway.detail(workspaceId,entity).then(setSelected).catch(()=>undefined)},[workspaceId]);
 const chosenTransaction=useMemo(()=>transactions.find(x=>x.id===transactionId)??null,[transactions,transactionId]);
 useEffect(()=>{if(chosenTransaction?.companyId)setCompanyId(chosenTransaction.companyId)},[chosenTransaction?.companyId]);
 const chooseFile=(next:File|null)=>{setFile(next);if(next&&!title.trim())setTitle(titleFromFile(next.name))};
 const upload=async()=>{if(!workspaceId||!file||!title.trim())return;setBusy('upload');setError(null);try{await gateway.upload({workspaceId,title,documentType:documentType.trim()||null,companyId:companyId||null,transactionId:transactionId||null,file});setFile(null);setTitle('');setDocumentType('');setCompanyId('');setTransactionId('');if(fileRef.current)fileRef.current.value='';await refresh(workspaceId,query,includeArchived)}catch{setError('فشل رفع الوثيقة أو التحقق منها؛ لم تُعتمد نسخة غير متحققة.')}finally{setBusy(null)}};
 const open=async(doc:VaultDocument)=>{if(!workspaceId)return;setBusy(`detail:${doc.id}`);try{setSelected(await gateway.detail(workspaceId,doc.id))}catch{setError('تعذر فتح تفاصيل الوثيقة.')}finally{setBusy(null)}};
 const download=async(documentId:string,versionNumber?:number)=>{if(!workspaceId)return;setBusy(`download:${documentId}`);try{const url=await gateway.downloadUrl(workspaceId,documentId,versionNumber??null);window.location.assign(url)}catch{setError('تعذر إنشاء رابط تنزيل آمن.')}finally{setBusy(null)}};
 const archive=async(documentId:string)=>{if(!workspaceId)return;setBusy(`archive:${documentId}`);try{await gateway.archive(workspaceId,documentId);setSelected(null);await refresh(workspaceId,query,includeArchived)}catch{setError('تعذر أرشفة الوثيقة.')}finally{setBusy(null)}};
 return <section className="dv" data-phase10-1="document-vault" data-vault-authority="documents+document_versions" data-binary-boundary="signed-broker-only">
  <header className="dv-hero"><div><p className="r2-eyebrow">Document Vault · 10.1</p><h1>خزنة الوثائق</h1><p>ملفات خاصة مرتبطة بسجلات إنجاز، بتاريخ نسخ لا يكتب فوق نفسه.</p></div><div className="dv-hero__metrics"><div><strong>{total}</strong><span>وثيقة</span></div><div><strong>{docs.reduce((n,d)=>n+d.versionCount,0)}</strong><span>نسخة</span></div><div><strong>خاص</strong><span>وصول موقّع</span></div></div></header>
  <section className="dv-upload" aria-label="رفع وثيقة"><div className="dv-section-head"><div><p className="r2-eyebrow">إضافة آمنة</p><h2>وثيقة جديدة</h2></div><span className="dv-chip">لا يوجد overwrite</span></div><div className="dv-upload-grid"><label className="dv-file"><input ref={fileRef} type="file" accept={DOCUMENT_VAULT_ALLOWED_MIME.join(',')} onChange={e=>chooseFile(e.target.files?.[0]??null)}/><strong>{file?file.name:'اختر PDF أو صورة أو Word أو Excel'}</strong><small>{file?`${typeLabel(file.type)} · ${formatVaultBytes(file.size)}`:'الحد الأقصى 50 MB'}</small></label><label>عنوان الوثيقة<input value={title} maxLength={320} onChange={e=>setTitle(e.target.value)}/></label><label>نوع الوثيقة<input value={documentType} maxLength={120} onChange={e=>setDocumentType(e.target.value)} placeholder="عقد، شهادة، كتاب…"/></label><label>الشركة<select value={companyId} onChange={e=>setCompanyId(e.target.value)} disabled={Boolean(chosenTransaction?.companyId)}><option value="">بدون ربط</option>{companies.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label>المعاملة<select value={transactionId} onChange={e=>setTransactionId(e.target.value)}><option value="">بدون ربط</option>{transactions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><button type="button" className="dv-primary" disabled={!file||!title.trim()||busy==='upload'} onClick={()=>void upload()}>{busy==='upload'?'جارٍ الرفع والتحقق…':'رفع واعتماد النسخة'}</button></div></section>
  <div className="dv-toolbar"><label className="dv-search">بحث<input value={query} maxLength={120} onChange={e=>setQuery(e.target.value)} placeholder="اسم الوثيقة أو نوعها…"/></label><label className="dv-toggle"><input type="checkbox" checked={includeArchived} onChange={e=>setIncludeArchived(e.target.checked)}/>إظهار المؤرشف</label></div>
  {error?<div className="dv-state dv-state--error" role="alert">{error}</div>:null}{loading?<div className="dv-state">جارٍ تحميل الخزنة…</div>:!docs.length?<div className="dv-state"><strong>الخزنة جاهزة</strong><span>لا توجد وثائق مطابقة حتى الآن.</span></div>:<div className="dv-grid">{docs.map(doc=><article className="dv-card" key={doc.id} data-document-status={doc.status}><button type="button" className="dv-card__main" onClick={()=>void open(doc)}><div className="dv-filemark">{typeLabel(doc.mimeType)}</div><div><div className="dv-card__title"><strong>{doc.title}</strong><span>{statusLabel(doc.status)}</span></div><p>{doc.fileName||'اسم الملف غير متاح'}</p><div className="dv-meta"><span>{formatVaultBytes(doc.sizeBytes)}</span><span>v{doc.currentVersion||'—'}</span>{doc.companyName?<span>{doc.companyName}</span>:null}{doc.transactionLabel?<span>{doc.transactionLabel}</span>:null}</div></div></button><div className="dv-card__actions">{doc.status==='ready'?<button type="button" onClick={()=>void download(doc.id)}>تنزيل</button>:null}{doc.status!=='archived'&&doc.status!=='processing'?<button type="button" onClick={()=>void archive(doc.id)}>أرشفة</button>:null}</div></article>)}</div>}
  {selected?<div className="dv-detail-wrap"><button type="button" className="dv-backdrop" aria-label="إغلاق التفاصيل" onClick={()=>setSelected(null)}/><aside className="dv-detail" role="dialog" aria-modal="true" aria-label="تفاصيل الوثيقة"><header><div><p className="r2-eyebrow">سجل النسخ</p><h2>{selected.document.title}</h2></div><button type="button" className="dv-close" onClick={()=>setSelected(null)}>×</button></header><div className="dv-detail__facts"><span>{selected.document.fileName||'—'}</span><span>{formatVaultBytes(selected.document.sizeBytes)}</span><span>{statusLabel(selected.document.status)}</span></div><section><h3>النسخ المعتمدة</h3>{selected.versions.length?selected.versions.map(v=><div className="dv-version" key={v.id}><div><strong>الإصدار {v.versionNumber}</strong><small>{v.fileName||selected.document.fileName||'ملف'}</small></div><div><span>{formatVaultBytes(v.sizeBytes)}</span><button type="button" onClick={()=>void download(selected.document.id,v.versionNumber)}>تنزيل</button></div></div>):<div className="dv-state">لا توجد نسخة معتمدة بعد.</div>}</section>{selected.document.status!=='archived'&&selected.document.status!=='processing'?<button type="button" className="dv-danger" disabled={busy===`archive:${selected.document.id}`} onClick={()=>void archive(selected.document.id)}>أرشفة الوثيقة بدون حذف تاريخها</button>:null}</aside></div>:null}
 </section>
}
