import {useEffect,useMemo,useState} from 'react';
import type {DocumentFactoryDraft,DocumentFactoryGateway,DocumentFactoryManagedTemplate,DocumentFactoryTemplate,DocumentSubmissionPack} from '../../features/documents/documentFactoryCommands.ts';
import type {FactoryTokenSchema,FactoryTokenSource} from '../../features/documents/documentFactoryContract.ts';
import type {DocumentIntelligenceGateway} from '../../features/documents/documentIntelligenceCommands.ts';
import type {DocumentVaultGateway} from '../../features/documents/documentVaultCommands.ts';

type Props=Readonly<{gateway:DocumentFactoryGateway;vaultGateway:DocumentVaultGateway;intelligenceGateway?:DocumentIntelligenceGateway;workspaceId:string;documentId:string;sourceTitle:string;companyId:string|null;transactionId:string|null}>;
const statusLabel:Record<DocumentFactoryDraft['status'],string>={draft:'مُعاد للتعديل',review_required:'بانتظار المراجعة',approved:'معتمد للإصدار',registered:'مسجل',final:'نهائي',failed:'فشل'};
const packLabel:Record<DocumentSubmissionPack['status'],string>={queued:'بانتظار التجميع',running:'جارٍ التجميع',succeeded:'حزمة نهائية',failed:'فشل التجميع'};
const allowed:Record<Exclude<FactoryTokenSource,'ocr'>,readonly string[]>={company:['legal_name','display_name','capital','address','registration_number','legal_status'],transaction:['type','department','status','priority','current_fee'],contact:['display_name','phone','email']};
const errorText=(e:unknown)=>{const raw=e instanceof Error?e.message:'';if(/required fact|missing/i.test(raw))return'القالب يحتاج بيانات غير متوفرة في السجلات الحالية.';if(/ocr.*verified|ocr.*stale/i.test(raw))return'تحليل الوثيقة غير متحقق أو أصبح قديمًا؛ أعد الفحص والتحقق أولًا.';if(/approval|required|approvable/i.test(raw))return'لا يمكن إصدار المستند قبل اعتماد المسودة.';if(/template|token/i.test(raw))return'القالب أو حقول الدمج غير صالحة. راجع أسماء الحقول والصياغة.';if(/submission.pack/i.test(raw))return'تعذر إنشاء حزمة التقديم من المستندات النهائية الحالية.';return'تعذر إكمال عملية مصنع الوثائق. لم يتم اعتماد مستند ناقص أو مكرر.'};
function deriveSchema(body:string,previous:FactoryTokenSchema={}):FactoryTokenSchema{const schema:Record<string,{source:FactoryTokenSource;field:string;required:boolean}>={};for(const match of body.matchAll(/\{\{([A-Za-z][A-Za-z0-9_.-]{0,127})\}\}/g)){const key=match[1];if(!key)continue;const dot=key.indexOf('.');if(dot<1)throw new Error('token source missing');const sourceRaw=key.slice(0,dot),field=key.slice(dot+1).toLowerCase();if(!['company','transaction','contact','ocr'].includes(sourceRaw))throw new Error('token source invalid');const source=sourceRaw as FactoryTokenSource;if(!/^[a-z][a-z0-9_]{0,63}$/.test(field))throw new Error('token field invalid');if(source!=='ocr'&&!allowed[source].includes(field))throw new Error('token field unsupported');schema[key]={source,field,required:previous[key]?.required===true}}return Object.freeze(schema)}

export function DocumentFactoryPanel({gateway,vaultGateway,intelligenceGateway,workspaceId,documentId,sourceTitle,companyId,transactionId}:Props){
 const[templates,setTemplates]=useState<readonly DocumentFactoryTemplate[]>([]),[managed,setManaged]=useState<readonly DocumentFactoryManagedTemplate[]>([]),[drafts,setDrafts]=useState<readonly DocumentFactoryDraft[]>([]),[packs,setPacks]=useState<readonly DocumentSubmissionPack[]>([]),[templateId,setTemplateId]=useState(''),[title,setTitle]=useState(`كتاب رسمي — ${sourceTitle}`),[verifiedAnalysisId,setVerifiedAnalysisId]=useState<string|null>(null),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[managerOpen,setManagerOpen]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[templateName,setTemplateName]=useState(''),[templateKind,setTemplateKind]=useState('official-letter'),[templateBody,setTemplateBody]=useState(''),[templateActive,setTemplateActive]=useState(true);
 const selectedTemplate=useMemo(()=>templates.find(x=>x.versionId===templateId)??null,[templates,templateId]);
 const editing=useMemo(()=>managed.find(x=>x.id===editingId)??null,[managed,editingId]);
 const finalForTransaction=useMemo(()=>drafts.filter(d=>d.status==='final'&&transactionId&&d.transactionId===transactionId).slice(0,20),[drafts,transactionId]);
 const tokenSchema=useMemo(()=>{try{return deriveSchema(templateBody,editing?.tokenSchema)}catch{return null}},[templateBody,editing]);
 const load=async()=>{setLoading(true);try{const [t,m,d,p,intel]=await Promise.all([gateway.listTemplates(workspaceId),gateway.listManagedTemplates(workspaceId),gateway.listDrafts(workspaceId,companyId,100),transactionId?gateway.listSubmissionPacks(workspaceId,transactionId):Promise.resolve([] as readonly DocumentSubmissionPack[]),intelligenceGateway?intelligenceGateway.detail(workspaceId,documentId):Promise.resolve(null)]);setTemplates(t);setManaged(m);setDrafts(d);setPacks(p);setTemplateId(v=>t.some(x=>x.versionId===v)?v:t[0]?.versionId??'');const verified=intel?.analyses.find(x=>x.state==='verified'&&!x.stale)??null;setVerifiedAnalysisId(verified?.id??null);setError('')}catch(e){setError(errorText(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[gateway,intelligenceGateway,workspaceId,documentId,companyId,transactionId]);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();setNote('');setError('');await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const generate=()=>{if(!templateId)return Promise.resolve();return act(()=>gateway.generate({workspaceId,templateVersionId:templateId,title:title.trim(),companyId,transactionId,ocrAnalysisId:verifiedAnalysisId}))};
 const review=(draftId:string,decision:'approve'|'return')=>act(()=>gateway.review(workspaceId,draftId,decision,note.trim()||null));
 const issue=(draftId:string)=>act(()=>gateway.renderAndFinalize(workspaceId,draftId));
 const openDocument=async(documentId:string|null)=>{if(!documentId)return;setBusy(true);try{location.assign(await vaultGateway.downloadUrl(workspaceId,documentId))}catch(e){setError(errorText(e));setBusy(false)}};
 const editTemplate=(t:DocumentFactoryManagedTemplate)=>{setEditingId(t.id);setTemplateName(t.name);setTemplateKind(t.kind);setTemplateBody(t.bodySource);setTemplateActive(t.active);setManagerOpen(true)};
 const newTemplate=()=>{setEditingId(null);setTemplateName('');setTemplateKind('official-letter');setTemplateBody('');setTemplateActive(true);setManagerOpen(true)};
 const saveTemplate=(publish:boolean)=>act(async()=>{if(!tokenSchema||!templateName.trim()||!templateBody.trim())throw new Error('template invalid');const id=await gateway.saveTemplate({workspaceId,templateId:editingId,name:templateName,kind:templateKind,bodySource:templateBody,tokenSchema,active:templateActive});setEditingId(id);if(publish){const version=await gateway.createTemplateVersion(workspaceId,id,templateBody,tokenSchema);await gateway.publishTemplateVersion(workspaceId,version.id)}});
 const buildPack=()=>transactionId?act(()=>gateway.buildSubmissionPack(workspaceId,transactionId,`حزمة تقديم — ${sourceTitle}`,finalForTransaction.map(d=>d.id))):Promise.resolve();
 return <section className="rk-derived df-panel" data-phase10-3="document-factory" data-factory-authority="governed-rpc+render-proof">
  <div className="rk-section-title"><div><span className="rk-kicker">Document Factory · 10.3</span><h3>مصنع الوثائق الرسمية</h3><p>قوالب مُنسّخة، حقائق ثابتة، مراجعة، PDF عربي نهائي، وهوية QR وحزم تقديم مرتبطة بالمعاملة.</p></div><span className="rk-truth-chip">Generate → Review → Render → Finalize</span></div>
  <div className="rk-source-actions"><button type="button" className="rk-button" onClick={()=>setManagerOpen(v=>!v)}>{managerOpen?'إغلاق إدارة القوالب':'إدارة القوالب'}</button><button type="button" className="rk-button" onClick={newTemplate}>قالب جديد</button></div>
  {error?<section className="rk-empty rk-empty--error" role="alert"><div className="rk-empty__mark">!</div><strong>تعذر إكمال العملية</strong><p>{error}</p></section>:null}
  {managerOpen?<section className="rk-official-text" aria-label="إدارة القوالب"><div className="rk-section-title"><div><span className="rk-kicker">Template Management</span><h4>{editingId?'تحرير النسخة العاملة':'إنشاء قالب جديد'}</h4></div><span className={tokenSchema?'rk-truth-chip':'rk-non-authority-chip'}>{tokenSchema?`${Object.keys(tokenSchema).length} حقول دمج`:'صياغة الحقول تحتاج مراجعة'}</span></div>
   <div className="rk-result-grid"><label className="rk-derived-card"><strong>اسم القالب</strong><span className="rk-search"><input value={templateName} maxLength={240} onChange={e=>setTemplateName(e.target.value)}/></span></label><label className="rk-derived-card"><strong>النوع</strong><span className="rk-search"><input value={templateKind} maxLength={120} onChange={e=>setTemplateKind(e.target.value)}/></span></label></div>
   <label className="rk-derived-card"><strong>محتوى القالب</strong><p>استخدم مثلًا <code>{'{{company.legal_name}}'}</code> و <code>{'{{transaction.type}}'}</code>. للأقسام الشرطية: <code>[[IF company.address]] … [[END]]</code>. للتكرار: <code>[[EACH ocr.items]] | [[ITEM]] | [[END]]</code>. أي سطور محاطة بـ | تُرسم كجدول PDF.</p><textarea className="rk-search" value={templateBody} onChange={e=>setTemplateBody(e.target.value)} rows={12} maxLength={1_000_000}/></label>
   <label className="rk-derived-card"><input type="checkbox" checked={templateActive} onChange={e=>setTemplateActive(e.target.checked)}/> <strong>القالب نشط</strong></label>
   <div className="rk-source-actions"><button type="button" className="rk-button" disabled={busy||!tokenSchema||!templateName.trim()||!templateBody.trim()} onClick={()=>void saveTemplate(false)}>حفظ النسخة العاملة</button><button type="button" className="rk-button rk-button--primary" disabled={busy||!tokenSchema||!templateName.trim()||!templateBody.trim()} onClick={()=>void saveTemplate(true)}>حفظ + إنشاء نسخة ثابتة ونشرها</button></div>
   {managed.length?<div className="rk-result-grid">{managed.map(t=><article className="rk-result" key={t.id}><div className="rk-result__top"><strong>{t.name}</strong><span className={t.active?'rk-truth-chip':'rk-non-authority-chip'}>{t.active?'نشط':'موقوف'}</span></div><p>{t.kind} · {Object.keys(t.tokenSchema).length} حقول · {t.versions.length} نسخ</p><div className="rk-scope-row">{t.versions.slice(0,5).map(v=><span className={v.status==='published'?'rk-truth-chip':'rk-kind'} key={v.id}>v{v.versionNumber} · {v.status==='published'?'منشور':'مسودة'}</span>)}</div><button type="button" className="rk-button" onClick={()=>editTemplate(t)}>تحرير النسخة العاملة</button></article>)}</div>:null}
  </section>:null}
  {loading?<div className="rk-skeleton" aria-label="تحميل مصنع الوثائق"/>:<>
   <section className="rk-official-text df-compose" aria-label="إنشاء مستند رسمي"><div className="rk-section-title"><div><strong>إنشاء مسودة من الحقائق المعتمدة</strong><p>{verifiedAnalysisId?'سيُضمَّن OCR المتحقق إذا احتاجه القالب.':'لا يوجد OCR متحقق حاليًا؛ سيستخدم القالب بيانات السجلات المتاحة فقط.'}</p></div>{verifiedAnalysisId?<span className="rk-truth-chip">OCR متحقق</span>:<span className="rk-non-authority-chip">OCR اختياري</span>}</div>
    <div className="rk-result-grid"><label className="rk-derived-card"><strong>القالب المنشور</strong><select value={templateId} onChange={e=>setTemplateId(e.target.value)} disabled={busy||!templates.length}><option value="">{templates.length?'اختر قالبًا':'لا توجد قوالب منشورة'}</option>{templates.map(t=><option key={t.versionId} value={t.versionId}>{t.name} · v{t.versionNumber}</option>)}</select></label><label className="rk-derived-card"><strong>عنوان المستند</strong><span className="rk-search"><input value={title} maxLength={320} onChange={e=>setTitle(e.target.value)}/></span></label></div>
    {selectedTemplate?<div className="rk-scope-row"><span className="rk-kind">{selectedTemplate.kind}</span><span className="rk-kind">{Object.keys(selectedTemplate.tokenSchema).length} حقول دمج</span><span className="rk-kind">نسخة {selectedTemplate.versionNumber}</span></div>:null}
    <button type="button" className="rk-button rk-button--primary" disabled={busy||!templateId||!title.trim()} onClick={()=>void generate()}>{busy?'جارٍ التنفيذ…':'توليد مسودة رسمية'}</button>
   </section>
   <section className="rk-derived"><div className="rk-section-title"><div><span className="rk-kicker">سجل الإصدار</span><h4>المسودات المرتبطة</h4></div><span className="rk-non-authority-chip">{drafts.length} مسودة</span></div>
    {!drafts.length?<div className="rk-empty">لم تُنشأ مسودة مرتبطة بعد.</div>:<div className="rk-result-grid">{drafts.map(d=><article className="rk-result df-draft" key={d.id} data-draft-status={d.status}><div className="rk-result__top"><div><span className={d.status==='final'?'rk-truth-chip':'rk-non-authority-chip'}>{statusLabel[d.status]}</span><strong>{d.title}</strong></div><small>{d.updatedAt?new Date(d.updatedAt).toLocaleString('ar-IQ'):'—'}</small></div><details><summary>معاينة المحتوى والحقائق</summary><div className="rk-derived-card"><p>{d.compiledContent}</p><div className="rk-provenance">{Object.entries(d.facts).map(([k,v])=><div key={k}><span>{k}</span><strong>{String(v??'')}</strong></div>)}</div></div></details>
      {d.status==='review_required'?<div className="rk-derived-card"><label><strong>ملاحظة المراجعة</strong><textarea className="rk-search" value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="اختياري — سبب الاعتماد أو الإرجاع…"/></label><div className="rk-source-actions"><button type="button" className="rk-button rk-button--primary" disabled={busy} onClick={()=>void review(d.id,'approve')}>اعتماد المسودة</button><button type="button" className="rk-button" disabled={busy} onClick={()=>void review(d.id,'return')}>إرجاع دون إصدار</button></div></div>:null}
      {d.status==='approved'?<button type="button" className="rk-button rk-button--primary" disabled={busy} onClick={()=>void issue(d.id)}>{busy?'جارٍ إنشاء PDF…':'إصدار PDF واعتماد نهائي'}</button>:null}
      {d.status==='final'?<div className="rk-result__foot"><span className="rk-truth-chip">نهائي · QR ثابت · محفوظ في Vault</span><button type="button" className="rk-button" disabled={busy||!d.finalDocumentId} onClick={()=>void openDocument(d.finalDocumentId)}>فتح PDF النهائي</button></div>:null}
      {d.status==='draft'?<p className="rk-derived-card">أُعيدت هذه المسودة ولم تعد قابلة للإصدار؛ أنشئ مسودة جديدة بعد تصحيح المصدر أو القالب.</p>:null}
     </article>)}</div>}
   </section>
   {transactionId?<section className="rk-official-text" data-submission-pack="transaction"><div className="rk-section-title"><div><span className="rk-kicker">Submission Pack</span><h4>حزمة التقديم للمعاملة</h4><p>تجمع النسخ الرسمية النهائية فقط، بنفس ترتيبها وchecksums، وتنتج PDF واحدًا محفوظًا في الـVault.</p></div><span className={finalForTransaction.length>=2?'rk-truth-chip':'rk-non-authority-chip'}>{finalForTransaction.length} مستندات نهائية</span></div><button type="button" className="rk-button rk-button--primary" disabled={busy||finalForTransaction.length<2} onClick={()=>void buildPack()}>إنشاء حزمة التقديم من جميع المستندات النهائية</button>{finalForTransaction.length<2?<p className="rk-derived-card">يلزم مستندان نهائيان على الأقل مرتبطان بهذه المعاملة.</p>:null}{packs.length?<div className="rk-result-grid">{packs.map(p=><article className="rk-result" key={p.packId}><div className="rk-result__top"><strong>{p.title}</strong><span className={p.status==='succeeded'?'rk-truth-chip':'rk-non-authority-chip'}>{packLabel[p.status]}</span></div><p>{p.itemCount} مرفقات · Manifest {p.manifestChecksum.slice(0,12)}…</p>{p.outputDocumentId?<button type="button" className="rk-button" onClick={()=>void openDocument(p.outputDocumentId)}>فتح الحزمة النهائية</button>:null}</article>)}</div>:null}</section>:null}
  </>}
 </section>
}
