import {useEffect,useMemo,useState} from 'react';
import type {DocumentIntelligenceGateway} from '../../features/documents/documentIntelligenceCommands.ts';
import type {DocumentIntelligenceAnalysis,IntelligenceField} from '../../features/documents/documentIntelligenceContract.ts';

type Props=Readonly<{gateway:DocumentIntelligenceGateway;workspaceId:string;documentId:string;currentVersionNumber:number|null}>;
type Corrections=Record<string,string>;
const labels:Record<DocumentIntelligenceAnalysis['state'],string>={queued:'بانتظار الاستخراج',extracting:'جارٍ الاستخراج',review_required:'تحتاج مراجعة',reviewed:'مراجعة مكتملة',verified:'متحقق منها',rejected:'مرفوضة',failed:'فشل الاستخراج',superseded:'نسخة مصدر أحدث',legacy_unverified:'نتيجة قديمة غير متحققة'};
const pct=(v:number|null)=>v==null?'—':`${Math.round(v*100)}%`;
const uniqueFields=(a:DocumentIntelligenceAnalysis|null)=>{const seen=new Set<string>(),out:IntelligenceField[]=[];for(const p of a?.pages??[])for(const f of p.fields)if(!seen.has(f.key)){seen.add(f.key);out.push(f)}return out};
const errorText=(e:unknown)=>e instanceof Error&&/provider is not configured/i.test(e.message)?'مزود OCR غير مهيأ على الخادم بعد. لم تُرسل الوثيقة إلى أي مزود.':'تعذر إكمال عملية ذكاء الوثيقة. بقي الملف الأصلي دون تغيير.';
const ctaState=(selected:DocumentIntelligenceAnalysis|null,busy:boolean)=>{
 if(busy||selected?.state==='extracting'||selected?.state==='queued')return{tone:'working',title:'جارٍ فحص الوثيقة…',subtitle:'يتم تحليل النسخة الحالية واستخراج البيانات دون تعديل الأصل',status:'قيد التحليل'} as const;
 if(selected?.stale||selected?.state==='superseded')return{tone:'stale',title:'إعادة فحص النسخة الحالية',subtitle:'توجد نسخة أحدث؛ أعد التحليل قبل استخدام البيانات',status:'نسخة أحدث'} as const;
 if(selected?.state==='review_required')return{tone:'review',title:'مراجعة نتيجة الفحص',subtitle:'اكتمل الاستخراج وتحتاج البيانات إلى مراجعتك',status:`ثقة ${pct(selected.confidence)}`} as const;
 if(selected?.state==='reviewed')return{tone:'reviewed',title:'إكمال التحقق من الوثيقة',subtitle:'المراجعة مكتملة وتنتظر التحقق النهائي',status:`ثقة ${pct(selected.confidence)}`} as const;
 if(selected?.state==='verified')return{tone:'verified',title:'إعادة فحص وتحليل الوثيقة',subtitle:'النتيجة الحالية متحققة ويمكن إعادة الفحص عند الحاجة',status:`متحقق · ${pct(selected.confidence)}`} as const;
 if(selected?.state==='failed')return{tone:'failed',title:'إعادة فحص وتحليل الوثيقة',subtitle:'فشلت المحاولة السابقة وبقي الأصل دون تغيير',status:'إعادة المحاولة'} as const;
 return{tone:'ready',title:'فحص وتحليل الوثيقة',subtitle:'قراءة ذكية للمحتوى واستخراج البيانات',status:'جاهز للفحص'} as const;
};

export function DocumentIntelligencePanel({gateway,workspaceId,documentId,currentVersionNumber}:Props){
 const[detail,setDetail]=useState<Awaited<ReturnType<DocumentIntelligenceGateway['detail']>>|null>(null),[selectedId,setSelectedId]=useState<string|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState(''),[corrections,setCorrections]=useState<Corrections>({});
 const selected=useMemo(()=>detail?.analyses.find(a=>a.id===selectedId)??detail?.analyses[0]??null,[detail,selectedId]),fields=useMemo(()=>uniqueFields(selected),[selected]),cta=useMemo(()=>ctaState(selected,busy),[selected,busy]);
 const hydrate=(a:DocumentIntelligenceAnalysis|null)=>{const next:Corrections={};for(const f of uniqueFields(a))next[f.key]=f.value??'';setCorrections(next)};
 const load=async(preferred?:string|null)=>{setLoading(true);try{const r=await gateway.detail(workspaceId,documentId),id=preferred&&r.analyses.some(a=>a.id===preferred)?preferred:r.analyses[0]?.id??null;setDetail(r);setSelectedId(id);hydrate(r.analyses.find(a=>a.id===id)??r.analyses[0]??null);setError('')}catch(e){setError(errorText(e))}finally{setLoading(false)}};
 useEffect(()=>{void load(null)},[gateway,workspaceId,documentId,currentVersionNumber]);
 useEffect(()=>{hydrate(selected)},[selectedId]);
 const act=async(fn:()=>Promise<{analysisId:string}>)=>{setBusy(true);try{const r=await fn();setNote('');await load(r.analysisId)}catch(e){const message=errorText(e);try{await load(null)}finally{setError(message)}}finally{setBusy(false)}};
 const extract=()=>act(()=>gateway.extract({workspaceId,documentId,versionNumber:currentVersionNumber}));
 const review=(decision:'accept'|'reject')=>{if(!selected)return Promise.resolve();const correctedFields=decision==='accept'&&fields.length?Object.fromEntries(fields.map(f=>[f.key,{value:corrections[f.key]??'',confidence:f.confidence,pageNumber:f.pageNumber}])):null;return act(()=>gateway.review({workspaceId,analysisId:selected.id,decision,correctedFields,note:note.trim()||null}))};
 const verify=()=>selected?act(()=>gateway.verify({workspaceId,analysisId:selected.id,note:note.trim()||null})):Promise.resolve();
 const ctaDisabled=busy||loading||currentVersionNumber==null||selected?.state==='review_required'||selected?.state==='reviewed';
 return <section className="rk-derived di-panel" data-phase10-2="document-intelligence" data-source-authority="source-file" data-intelligence-authority="derived-even-when-verified">
  <div className="rk-section-title di-head"><div><span className="rk-kicker">Document Intelligence · 10.2</span><h3>ذكاء الوثيقة</h3><p>الاستخراج مساعد للمراجعة فقط؛ الملف ونسخته المحفوظة يبقيان المرجع الأصلي.</p></div></div>
  <button type="button" className="di-scan-cta" data-scan-tone={cta.tone} disabled={ctaDisabled} onClick={()=>void extract()} aria-label={cta.title}>
   <span className="di-scan-cta__icon" aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><path d="M7 3.75H5.75a2 2 0 0 0-2 2V7M17 3.75h1.25a2 2 0 0 1 2 2V7M7 20.25H5.75a2 2 0 0 1-2-2V17M17 20.25h1.25a2 2 0 0 0 2-2V17M8 7.75h6.5l2.5 2.5v6H8zM14.5 7.75v2.5H17M6 12h12"/></svg></span>
   <span className="di-scan-cta__copy"><strong>{cta.title}</strong><small>{cta.subtitle}</small></span>
   <span className="di-scan-cta__status">{cta.status}</span>
  </button>
  <div className="rk-scope-row di-law"><strong className="rk-truth-chip">الأصل لا يُستبدل</strong><span className="rk-kind">EXTRACT → REVIEW → VERIFY</span><span className="rk-non-authority-chip">أي نسخة أحدث تُبطل التحقق القديم تلقائيًا</span></div>
  {error?<section className="rk-empty rk-empty--error di-alert" role="alert"><div className="rk-empty__mark">!</div><strong>تعذر إكمال العملية</strong><p>{error}</p></section>:null}
  {loading?<div className="rk-skeleton di-loading" aria-label="تحميل ذكاء الوثيقة"/>:!detail?.analyses.length?<section className="rk-empty di-empty"><div className="rk-empty__mark">⌁</div><strong>لا يوجد استخراج بعد</strong><span>ابدأ من النسخة الحالية ثم راجع النتيجة قبل اعتمادها كمعلومة متحققة.</span></section>:<div className="rk-result-grid di-layout">
   <nav className="rk-scope-row di-runs" aria-label="سجل الاستخراج">{detail.analyses.map(a=><button type="button" key={a.id} className={a.id===selected?.id?'is-active':''} onClick={()=>setSelectedId(a.id)}><span>تحليل #{a.analysisVersion}</span> · <strong>{labels[a.state]}</strong> · <small>نسخة {a.sourceVersionNumber??'قديمة'} · ثقة {pct(a.confidence)}</small></button>)}</nav>
   {selected?<article className="rk-official-text di-review" data-analysis-state={selected.state} data-analysis-stale={selected.stale?'true':'false'}>
    <header className="rk-results__heading"><div><span className={selected.state==='verified'&&!selected.stale?'rk-truth-chip di-state':'rk-non-authority-chip di-state'}>{labels[selected.state]}</span>{selected.stale?<span className="rk-kind di-stale">مصدر أقدم من النسخة الحالية</span>:null}</div><strong>المصدر: نسخة {selected.sourceVersionNumber??'غير مثبتة'} · {selected.provider??'مزود غير مسجل'}</strong></header>
    <section className="rk-provenance di-metrics"><div><span>الثقة العامة</span><strong>{pct(selected.confidence)}</strong></div><div><span>الصفحات</span><strong>{selected.pages.length}</strong></div><div><span>التصنيف</span><strong>{selected.classification??'غير مصنف'}</strong></div></section>
    {fields.length?<section className="rk-derived di-fields"><div className="rk-section-title"><div><span className="rk-kicker">حقول مستخرجة</span><h4>راجع القيم مع الصفحة المصدر</h4></div><span className="rk-non-authority-chip">غير معتمدة قبل التحقق</span></div>{fields.map(f=><label key={f.key} className="rk-derived-card di-field"><span><strong>{f.key}</strong> · <small>صفحة {f.pageNumber} · ثقة {pct(f.confidence)}</small></span><span className="rk-search"><input value={corrections[f.key]??''} disabled={selected.state!=='review_required'} onChange={e=>setCorrections(v=>({...v,[f.key]:e.target.value}))}/></span>{f.sourceText?<small className="di-source">المصدر: {f.sourceText}</small>:null}</label>)}</section>:null}
    {selected.pages.length?<details className="rk-derived di-pages"><summary>النص المستخرج حسب الصفحات</summary>{selected.pages.map(p=><article className="rk-derived-card" key={p.pageNumber}><strong>صفحة {p.pageNumber} · ثقة {pct(p.confidence)}</strong><p>{p.text||'لا يوجد نص مستخرج في هذه الصفحة.'}</p></article>)}</details>:selected.ocrText?<section className="rk-derived di-pages"><strong>نص OCR قديم غير موثق بالصفحات</strong><p>{selected.ocrText}</p></section>:null}
    {(selected.state==='review_required'||selected.state==='reviewed')?<label className="rk-derived-card di-note"><span>ملاحظة المراجع</span><textarea className="rk-search" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="دوّن المطابقة أو سبب التصحيح…"/></label>:null}
    <div className="rk-source-actions di-actions">{selected.state==='review_required'?<><button type="button" className="rk-button rk-button--primary" disabled={busy||selected.stale} onClick={()=>void review('accept')}>اعتماد المراجعة</button><button type="button" className="rk-button" disabled={busy} onClick={()=>void review('reject')}>رفض النتيجة</button></>:null}{selected.state==='reviewed'?<button type="button" className="rk-button rk-button--primary" disabled={busy||selected.stale} onClick={()=>void verify()}>تحقق نهائي من النتيجة</button>:null}{selected.state==='legacy_unverified'?<button type="button" className="rk-button" disabled={busy} onClick={()=>void review('reject')}>رفض النتيجة القديمة</button>:null}{selected.state==='verified'&&!selected.stale?<span className="rk-truth-chip di-verified">✓ تمت المراجعة والتحقق — تبقى معلومة مشتقة من الأصل</span>:null}{selected.state==='superseded'||selected.stale?<span className="rk-derived-card di-warning">توجد نسخة أصلية أحدث؛ أعد الاستخراج من النسخة الحالية.</span>:null}{selected.state==='failed'?<span className="rk-derived-card di-warning">فشل الاستخراج ({selected.failureCode??'سبب غير محدد'}). يمكن بدء محاولة جديدة دون المساس بالأصل.</span>:null}</div>
   </article>:null}
  </div>}
 </section>
}
