import {useEffect,useMemo,useState} from 'react';
import type {DocumentFactoryDraft,DocumentFactoryGateway} from '../../features/documents/documentFactoryCommands.ts';
import type {EngagementContractGateway,EngagementContractRuntimeRevision} from '../../features/engagements/engagementContractCommands.ts';
import type {EngagementContractStatus} from '../../features/engagements/engagementContract.ts';
import {useFinanceCommandGateway} from '../../features/finance/FinanceCommandContext.tsx';
import type {FinanceEngagementContext} from '../../features/finance/financeCommands.ts';

type Props=Readonly<{gateway:EngagementContractGateway;documentFactoryGateway:DocumentFactoryGateway;workspaceId:string}>;
const labels:Record<EngagementContractStatus,string>={draft:'مسودة عقد',under_review:'قيد المراجعة',approved:'معتمد',signature_pending:'بانتظار التوقيع',signed:'موقّع',effective:'نافذ',expired:'منتهي',terminated:'منهى',superseded:'مستبدل'};
const today=()=>new Date().toISOString().slice(0,10);
const errorText=(e:unknown)=>{const raw=e instanceof Error?e.message:'';if(/previous.*superseded/i.test(raw))return'يوجد إصدار سابق يجب استبداله رسميًا قبل إنشاء إصدار جديد.';if(/artifact|required|final/i.test(raw))return'لا يمكن متابعة التوقيع قبل وجود PDF نهائي صادر من مصنع الوثائق.';if(/date|expired/i.test(raw))return'راجع تاريخ النفاذ والانتهاء؛ التواريخ الحالية غير صالحة.';if(/workspace|forbidden|rls|permission/i.test(raw))return'لا تملك صلاحية عقدية داخل مساحة العمل الحالية.';if(/transition/i.test(raw))return'هذا الانتقال غير مسموح في دورة حياة العقد.';return'تعذر إكمال عملية العقد. لم يتم تجاوز سلطة M16 أو اعتماد حالة جزئية.'};

export function EngagementContractPanel({gateway,documentFactoryGateway,workspaceId}:Props){
 const finance=useFinanceCommandGateway(),[engagements,setEngagements]=useState<readonly FinanceEngagementContext[]>([]),[drafts,setDrafts]=useState<readonly DocumentFactoryDraft[]>([]),[revisions,setRevisions]=useState<readonly EngagementContractRuntimeRevision[]>([]),[engagementId,setEngagementId]=useState(''),[draftId,setDraftId]=useState(''),[title,setTitle]=useState('عقد خدمات'),[effectiveOn,setEffectiveOn]=useState(today()),[expiresOn,setExpiresOn]=useState(''),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const selectedEngagement=useMemo(()=>engagements.find(x=>x.id===engagementId)??null,[engagements,engagementId]);
 const eligibleDrafts=useMemo(()=>drafts.filter(d=>d.status==='final'&&!!d.templateVersionId&&!!d.finalDocumentId&&!!d.finalDocumentVersionId&&!!selectedEngagement&&d.companyId===selectedEngagement.companyId&&(!d.transactionId||selectedEngagement.transactionIds.includes(d.transactionId))),[drafts,selectedEngagement]);
 const draftMap=useMemo(()=>new Map(drafts.map(d=>[d.id,d] as const)),[drafts]);
 const load=async()=>{setLoading(true);try{const[context,nextDrafts,nextRevisions]=await Promise.all([finance.loadContext(workspaceId),documentFactoryGateway.listDrafts(workspaceId,null,100),gateway.list(workspaceId)]);setEngagements(context.engagements);setDrafts(nextDrafts);setRevisions(nextRevisions);setEngagementId(v=>context.engagements.some(x=>x.id===v)?v:context.engagements[0]?.id??'');setError('')}catch(e){setError(errorText(e))}finally{setLoading(false)}};
 useEffect(()=>{void load()},[workspaceId,gateway,documentFactoryGateway,finance]);
 useEffect(()=>{setDraftId(v=>eligibleDrafts.some(d=>d.id===v)?v:eligibleDrafts[0]?.id??'')},[eligibleDrafts]);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();setError('');setNote('');await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}};
 const create=()=>{const draft=eligibleDrafts.find(d=>d.id===draftId);if(!selectedEngagement||!draft?.templateVersionId)return Promise.resolve();return act(()=>gateway.create({workspaceId,engagementId:selectedEngagement.id,templateVersionId:draft.templateVersionId!,draftId:draft.id,title:title.trim(),idempotencyKey:crypto.randomUUID()}))};
 const transition=(r:EngagementContractRuntimeRevision,toStatus:EngagementContractStatus)=>{const draft=draftMap.get(r.draftId);const common={workspaceId,revisionId:r.id,operationId:crypto.randomUUID(),expectedVersion:r.version,toStatus} as const;if(toStatus==='signature_pending'){if(!draft?.finalDocumentId||!draft.finalDocumentVersionId)return Promise.resolve();return act(()=>gateway.transition({...common,documentId:draft.finalDocumentId,documentVersionId:draft.finalDocumentVersionId}))}if(toStatus==='signed')return act(()=>gateway.transition({...common,signatureProvenance:{method:'authenticated_user_confirmation',source:'enjaz_contract_ui',documentId:r.documentId,documentVersionId:r.documentVersionId,confirmedAt:new Date().toISOString()},note:note.trim()||null}));if(toStatus==='effective')return act(()=>gateway.transition({...common,effectiveOn,expiresOn:expiresOn||null}));if(toStatus==='terminated')return act(()=>gateway.transition({...common,note:note.trim()||'إنهاء العقد من مركز العقود'}));return act(()=>gateway.transition(common))};
 const actions=(r:EngagementContractRuntimeRevision)=>{const draft=draftMap.get(r.draftId),canSign=!!draft?.finalDocumentId&&!!draft.finalDocumentVersionId;if(r.status==='draft')return <button type="button" className="rk-button rk-button--primary" disabled={busy} onClick={()=>void transition(r,'under_review')}>إرسال للمراجعة</button>;if(r.status==='under_review')return <><button type="button" className="rk-button rk-button--primary" disabled={busy} onClick={()=>void transition(r,'approved')}>اعتماد</button><button type="button" className="rk-button" disabled={busy} onClick={()=>void transition(r,'draft')}>إرجاع للمسودة</button></>;if(r.status==='approved')return <><button type="button" className="rk-button rk-button--primary" disabled={busy||!canSign} onClick={()=>void transition(r,'signature_pending')}>إرسال للتوقيع</button><button type="button" className="rk-button" disabled={busy} onClick={()=>void transition(r,'under_review')}>إعادة للمراجعة</button></>;if(r.status==='signature_pending')return <><button type="button" className="rk-button rk-button--primary" disabled={busy} onClick={()=>void transition(r,'signed')}>تأكيد أن النسخة موقعة</button><button type="button" className="rk-button" disabled={busy} onClick={()=>void transition(r,'approved')}>إرجاع قبل التوقيع</button></>;if(r.status==='signed')return <><button type="button" className="rk-button rk-button--primary" disabled={busy||!effectiveOn} onClick={()=>void transition(r,'effective')}>تفعيل العقد</button><button type="button" className="rk-button" disabled={busy} onClick={()=>void transition(r,'superseded')}>استبدال دون تفعيل</button></>;if(r.status==='effective')return <><button type="button" className="rk-button" disabled={busy||!note.trim()} onClick={()=>void transition(r,'terminated')}>إنهاء العقد</button><button type="button" className="rk-button" disabled={busy} onClick={()=>void transition(r,'superseded')}>استبدال بإصدار أحدث</button></>;if(r.status==='expired'||r.status==='terminated')return <button type="button" className="rk-button" disabled={busy} onClick={()=>void transition(r,'superseded')}>فتح الطريق لإصدار جديد</button>;return null};
 return <section className="rk-derived ec-panel" data-phase10-5="engagement-contracts" data-contract-authority="engagement_contract_revisions" data-money-authority="phase7-finance">
  <div className="rk-section-title"><div><span className="rk-kicker">Contracts & Retainers · M16 · 10.5</span><h3>مركز العقود والاتفاقيات</h3><p>إصدارات غير قابلة للطمس، مراجعة وتوقيع ونفاذ مرتبطون بسلطة التعامل التجاري والوثيقة النهائية نفسها.</p></div><span className="rk-truth-chip">Finance + Factory + Vault · بلا مخزن موازٍ</span></div>
  {error?<section className="rk-empty rk-empty--error" role="alert"><div className="rk-empty__mark">!</div><strong>تعذر إكمال العملية</strong><p>{error}</p></section>:null}
  {loading?<div className="rk-skeleton" aria-label="تحميل مركز العقود"/>:<>
   <section className="rk-official-text" aria-label="إنشاء إصدار عقد"><div className="rk-section-title"><div><strong>إنشاء إصدار من وثيقة نهائية</strong><p>يظهر فقط PDF نهائي مرتبط بنفس شركة/معاملة التعامل التجاري المختار.</p></div><span className={eligibleDrafts.length?'rk-truth-chip':'rk-non-authority-chip'}>{eligibleDrafts.length?`${eligibleDrafts.length} وثائق مؤهلة`:'لا توجد وثيقة نهائية مؤهلة'}</span></div>
    <div className="rk-result-grid"><label className="rk-derived-card"><strong>التعامل التجاري</strong><select value={engagementId} onChange={e=>setEngagementId(e.target.value)} disabled={busy}><option value="">{engagements.length?'اختر التعامل':'لا توجد تعاملات تجارية'}</option>{engagements.map(e=><option key={e.id} value={e.id}>{e.title} · {e.type}</option>)}</select></label><label className="rk-derived-card"><strong>الوثيقة النهائية</strong><select value={draftId} onChange={e=>setDraftId(e.target.value)} disabled={busy||!engagementId}><option value="">{eligibleDrafts.length?'اختر الوثيقة':'لا توجد وثيقة مطابقة'}</option>{eligibleDrafts.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><label className="rk-derived-card"><strong>عنوان إصدار العقد</strong><span className="rk-search"><input value={title} maxLength={320} onChange={e=>setTitle(e.target.value)}/></span></label></div>
    <button type="button" className="rk-button rk-button--primary" disabled={busy||!engagementId||!draftId||!title.trim()} onClick={()=>void create()}>{busy?'جارٍ التنفيذ…':'إنشاء الإصدار الخاضع للحوكمة'}</button>
   </section>
   <section className="rk-official-text" aria-label="إعدادات النفاذ والتوقيع"><div className="rk-section-title"><div><strong>بيانات الانتقال</strong><p>تُستخدم فقط عند تأكيد التوقيع أو تفعيل/إنهاء الإصدار المحدد.</p></div></div><div className="rk-result-grid"><label className="rk-derived-card"><strong>تاريخ النفاذ</strong><span className="rk-search"><input type="date" value={effectiveOn} onChange={e=>setEffectiveOn(e.target.value)}/></span></label><label className="rk-derived-card"><strong>تاريخ الانتهاء</strong><span className="rk-search"><input type="date" value={expiresOn} onChange={e=>setExpiresOn(e.target.value)}/></span></label><label className="rk-derived-card"><strong>ملاحظة/سبب</strong><span className="rk-search"><input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="مثلاً سبب الإنهاء أو ملاحظة التوقيع"/></span></label></div></section>
   <div className="rk-section-title"><div><span className="rk-kicker">Contract Revision Ledger</span><h4>سجل إصدارات العقود</h4></div><span className="rk-non-authority-chip">{revisions.length} إصدار</span></div>
   {!revisions.length?<div className="rk-empty"><div className="rk-empty__mark">§</div><h4>لا توجد إصدارات عقدية بعد</h4><p>أنشئ الإصدار الأول من تعامل تجاري ووثيقة نهائية معتمدين.</p></div>:<div className="rk-result-grid">{revisions.map(r=><article className="rk-result ec-revision" key={r.id} data-contract-status={r.status}><div className="rk-result__top"><div><span className={r.status==='effective'||r.status==='signed'?'rk-truth-chip':'rk-non-authority-chip'}>{labels[r.status]}</span><strong>{r.title}</strong></div><span className="rk-kind">R{r.revision}</span></div><p>التعامل: {engagements.find(e=>e.id===r.engagementId)?.title||r.engagementId}</p><div className="rk-scope-row"><span className="rk-kind">{r.effectiveOn?`نفاذ ${r.effectiveOn}`:'لم يبدأ النفاذ'}</span><span className="rk-kind">{r.expiresOn?`انتهاء ${r.expiresOn}`:'بلا انتهاء محدد'}</span><span className="rk-kind">{r.signedAt?'نسخة موقعة':'غير موقع'}</span></div><div className="rk-source-actions">{actions(r)}</div></article>)}</div>}
  </>}
 </section>;
}
