import {useEffect,useMemo,useState} from 'react';
import type {DocumentFactoryDraft,DocumentFactoryGateway} from '../../features/documents/documentFactoryCommands.ts';
import type {EngagementContractGateway,EngagementContractRuntimeRevision,UnifiedAttentionItem} from '../../features/engagements/engagementContractCommands.ts';
import type {EngagementContractStatus} from '../../features/engagements/engagementContract.ts';
import {useFinanceCommandGateway} from '../../features/finance/FinanceCommandContext.tsx';
import type {FinanceEngagementContext} from '../../features/finance/financeCommands.ts';

type Props=Readonly<{gateway:EngagementContractGateway;documentFactoryGateway:DocumentFactoryGateway;workspaceId:string}>;
type A=readonly [EngagementContractStatus,string,boolean?];
const labels:Record<EngagementContractStatus,string>={draft:'مسودة عقد',under_review:'قيد المراجعة',approved:'معتمد',signature_pending:'بانتظار التوقيع',signed:'موقّع',effective:'نافذ',expired:'منتهي',terminated:'منهى',superseded:'مستبدل'};
const moves:Partial<Record<EngagementContractStatus,readonly A[]>>={
 draft:[['under_review','إرسال للمراجعة',true]],
 under_review:[['approved','اعتماد',true],['draft','إرجاع للمسودة']],
 approved:[['signature_pending','إرسال للتوقيع',true],['under_review','إعادة للمراجعة']],
 signature_pending:[['signed','تأكيد أن النسخة موقعة',true],['approved','إرجاع قبل التوقيع']],
 signed:[['effective','تفعيل العقد',true],['superseded','استبدال دون تفعيل']],
 effective:[['terminated','إنهاء العقد'],['superseded','استبدال بإصدار أحدث']],
 expired:[['superseded','فتح الطريق لإصدار جديد']],
 terminated:[['superseded','فتح الطريق لإصدار جديد']],
};
const today=()=>new Date().toISOString().slice(0,10);
const err=(e:unknown)=>{const s=e instanceof Error?e.message:'';return /artifact|required|final/i.test(s)?'يلزم PDF نهائي قبل التوقيع.':/workspace|forbidden|rls|permission/i.test(s)?'لا تملك الصلاحية.':/date|expired/i.test(s)?'راجع تواريخ العقد.':/transition/i.test(s)?'الانتقال غير مسموح.':'تعذر إكمال العملية دون تجاوز سلطة العقد.'};

export function EngagementContractPanel({gateway,documentFactoryGateway,workspaceId}:Props){
 const finance=useFinanceCommandGateway();
 const[engagements,setEngagements]=useState<readonly FinanceEngagementContext[]>([]),[drafts,setDrafts]=useState<readonly DocumentFactoryDraft[]>([]),[revisions,setRevisions]=useState<readonly EngagementContractRuntimeRevision[]>([]),[attention,setAttention]=useState<readonly UnifiedAttentionItem[]|null>(null);
 const[engagementId,setEngagementId]=useState(''),[draftId,setDraftId]=useState(''),[title,setTitle]=useState('عقد خدمات'),[effectiveOn,setEffectiveOn]=useState(today()),[expiresOn,setExpiresOn]=useState(''),[note,setNote]=useState(''),[error,setError]=useState(''),[attentionError,setAttentionError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[online,setOnline]=useState(()=>navigator.onLine);
 const selected=useMemo(()=>engagements.find(x=>x.id===engagementId)??null,[engagements,engagementId]);
 const eligible=useMemo(()=>drafts.filter(d=>d.status==='final'&&d.templateVersionId&&d.finalDocumentId&&d.finalDocumentVersionId&&selected&&d.companyId===selected.companyId&&(!d.transactionId||selected.transactionIds.includes(d.transactionId))),[drafts,selected]);
 const draftMap=useMemo(()=>new Map(drafts.map(d=>[d.id,d] as const)),[drafts]);
 const load=async()=>{setLoading(true);try{const[x,d,r]=await Promise.all([finance.loadContext(workspaceId),documentFactoryGateway.listDrafts(workspaceId,null,100),gateway.list(workspaceId)]);setEngagements(x.engagements);setDrafts(d);setRevisions(r);setEngagementId(v=>x.engagements.some(e=>e.id===v)?v:x.engagements[0]?.id??'');setError('')}catch(e){setError(err(e))}finally{setLoading(false)}};
 const loadAttention=async()=>{try{setAttention(await gateway.listAttention(workspaceId));setAttentionError('')}catch{setAttentionError('تعذر تحديث المتابعة؛ مركز العقود الأصلي متاح.')}};
 useEffect(()=>{void load();void loadAttention()},[workspaceId,gateway,documentFactoryGateway,finance]);
 useEffect(()=>{setDraftId(v=>eligible.some(d=>d.id===v)?v:eligible[0]?.id??'')},[eligible]);
 useEffect(()=>{const sync=()=>{setOnline(navigator.onLine);if(navigator.onLine)void loadAttention()};addEventListener('online',sync);addEventListener('offline',sync);return()=>{removeEventListener('online',sync);removeEventListener('offline',sync)}},[workspaceId,gateway]);
 const act=async(fn:()=>Promise<unknown>)=>{setBusy(true);try{await fn();setError('');setNote('');await load();void loadAttention()}catch(e){setError(err(e))}finally{setBusy(false)}};
 const create=()=>{const d=eligible.find(x=>x.id===draftId);return !selected||!d?.templateVersionId?Promise.resolve():act(()=>gateway.create({workspaceId,engagementId:selected.id,templateVersionId:d.templateVersionId!,draftId:d.id,title:title.trim(),idempotencyKey:crypto.randomUUID()}))};
 const transition=(r:EngagementContractRuntimeRevision,toStatus:EngagementContractStatus)=>{const d=draftMap.get(r.draftId),base={workspaceId,revisionId:r.id,operationId:crypto.randomUUID(),expectedVersion:r.version,toStatus} as const;if(toStatus==='signature_pending')return !d?.finalDocumentId||!d.finalDocumentVersionId?Promise.resolve():act(()=>gateway.transition({...base,documentId:d.finalDocumentId,documentVersionId:d.finalDocumentVersionId}));if(toStatus==='signed')return act(()=>gateway.transition({...base,signatureProvenance:{method:'authenticated_user_confirmation',source:'enjaz_contract_ui',documentId:r.documentId,documentVersionId:r.documentVersionId,confirmedAt:new Date().toISOString()},note:note.trim()||null}));if(toStatus==='effective')return act(()=>gateway.transition({...base,effectiveOn,expiresOn:expiresOn||null}));if(toStatus==='terminated')return act(()=>gateway.transition({...base,note:note.trim()||'إنهاء العقد من مركز العقود'}));return act(()=>gateway.transition(base))};
 const actions=(r:EngagementContractRuntimeRevision)=>{const canSign=!!draftMap.get(r.draftId)?.finalDocumentId&&!!draftMap.get(r.draftId)?.finalDocumentVersionId;return moves[r.status]?.map(([to,label,primary])=><button key={to} type="button" className={primary?'rk-button rk-button--primary':'rk-button'} disabled={busy||(to==='signature_pending'&&!canSign)||(to==='effective'&&!effectiveOn)||(to==='terminated'&&!note.trim())} onClick={()=>void transition(r,to)}>{label}</button>)??null};
 return <section className="rk-derived ec-panel" data-phase10-5="engagement-contracts" data-contract-authority="engagement_contract_revisions" data-money-authority="phase7-finance">
  <div className="rk-section-title"><div><span className="rk-kicker">Contracts & Retainers · M16 · 10.5</span><h3>مركز العقود والاتفاقيات</h3></div><span className="rk-truth-chip">Finance + Factory + Vault · بلا مخزن موازٍ</span></div>
  {error?<section className="rk-empty rk-empty--error" role="alert"><strong>تعذر إكمال العملية</strong><p>{error}</p></section>:null}
  <section className="rk-official-text" data-phase11-6d="unified-attention" data-projection-only="true"><div className="rk-section-title"><div><span className="rk-kicker">11.6-D · Unified Attention</span><h4>المتابعة الموحدة</h4></div><span className={online?'rk-truth-chip':'rk-non-authority-chip'}>{online?'بيانات حية':'غير متصل'}</span></div>
   {attentionError?<div className="rk-empty rk-empty--error" role="status"><p>{attentionError}</p></div>:attention===null?<div className="rk-skeleton" aria-label="تحميل المتابعة"/>:!attention.length?<div className="rk-empty"><strong>لا توجد متابعة معلقة</strong></div>:<div className="rk-result-grid">{attention.map(i=><article className="rk-result" key={i.id} data-attention-stale={i.stale?'true':'false'}><div className="rk-result__top"><div><span>{i.kindLabel}</span><strong>{i.title}</strong></div><span className="rk-kind">{i.attentionLabel}</span></div><div className="rk-scope-row">{i.dueAt?<span className="rk-kind">{i.dueAt.slice(0,10)}</span>:null}{i.decisionLabel?<span className="rk-kind">{i.decisionLabel}</span>:null}{i.communicationEvidence?<span className="rk-kind">اتصال موثق</span>:null}{i.stale?<span className="rk-non-authority-chip">حالة أحدث</span>:null}</div>{i.ownerPath?<a className="rk-button" href={i.ownerPath}>فتح المصدر</a>:null}</article>)}</div>}
  </section>
  {loading?<div className="rk-skeleton" aria-label="تحميل مركز العقود"/>:<>
   <section className="rk-official-text"><div className="rk-section-title"><strong>إنشاء إصدار من وثيقة نهائية</strong><span className={eligible.length?'rk-truth-chip':'rk-non-authority-chip'}>{eligible.length?eligible.length+' وثائق مؤهلة':'لا توجد وثيقة نهائية مؤهلة'}</span></div><div className="rk-result-grid">
    <label className="rk-derived-card"><strong>التعامل التجاري</strong><select value={engagementId} onChange={e=>setEngagementId(e.target.value)} disabled={busy}><option value="">{engagements.length?'اختر التعامل':'لا توجد تعاملات تجارية'}</option>{engagements.map(e=><option key={e.id} value={e.id}>{e.title} · {e.type}</option>)}</select></label>
    <label className="rk-derived-card"><strong>الوثيقة النهائية</strong><select value={draftId} onChange={e=>setDraftId(e.target.value)} disabled={busy||!engagementId}><option value="">{eligible.length?'اختر الوثيقة':'لا توجد وثيقة مطابقة'}</option>{eligible.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label>
    <label className="rk-derived-card"><strong>عنوان إصدار العقد</strong><span className="rk-search"><input value={title} maxLength={320} onChange={e=>setTitle(e.target.value)}/></span></label>
   </div><button type="button" className="rk-button rk-button--primary" disabled={busy||!engagementId||!draftId||!title.trim()} onClick={()=>void create()}>{busy?'جارٍ التنفيذ…':'إنشاء الإصدار الخاضع للحوكمة'}</button></section>
   <section className="rk-official-text"><div className="rk-result-grid"><label className="rk-derived-card"><strong>تاريخ النفاذ</strong><span className="rk-search"><input type="date" value={effectiveOn} onChange={e=>setEffectiveOn(e.target.value)}/></span></label><label className="rk-derived-card"><strong>تاريخ الانتهاء</strong><span className="rk-search"><input type="date" value={expiresOn} onChange={e=>setExpiresOn(e.target.value)}/></span></label><label className="rk-derived-card"><strong>ملاحظة/سبب</strong><span className="rk-search"><input value={note} maxLength={1000} onChange={e=>setNote(e.target.value)} placeholder="مثلاً سبب الإنهاء أو ملاحظة التوقيع"/></span></label></div></section>
   <div className="rk-section-title"><h4>سجل إصدارات العقود</h4><span className="rk-non-authority-chip">{revisions.length} إصدار</span></div>
   {!revisions.length?<div className="rk-empty"><strong>لا توجد إصدارات عقدية بعد</strong></div>:<div className="rk-result-grid">{revisions.map(r=><article className="rk-result ec-revision" key={r.id} data-contract-status={r.status}><div className="rk-result__top"><div><span className={r.status==='effective'||r.status==='signed'?'rk-truth-chip':'rk-non-authority-chip'}>{labels[r.status]}</span><strong>{r.title}</strong></div><span className="rk-kind">R{r.revision}</span></div><div className="rk-scope-row"><span className="rk-kind">{r.effectiveOn?'نفاذ '+r.effectiveOn:'لم يبدأ النفاذ'}</span><span className="rk-kind">{r.expiresOn?'انتهاء '+r.expiresOn:'بلا انتهاء محدد'}</span></div><div className="rk-source-actions">{actions(r)}</div></article>)}</div>}
  </>}
 </section>;
}
