export type ReportKind='period'|'company'|'transaction'|'cashbox';
export type Company={id:string;workspace_id:string;legal_name:string;display_name:string|null};
export type Transaction={id:string;workspace_id:string;company_id:string;type:string;current_fee:number;deleted_at:string|null;legacy_id:string|null};
export type Payment={id:string;workspace_id:string;transaction_id:string;company_id:string;amount:number;paid_at:string;status:string;receipt_ref:string;cashbox_id:string|null};
export type Reversal={id:string;workspace_id:string;payment_id:string};
export type Ledger={id:string;workspace_id:string;transaction_id:string|null;company_id:string|null;entry_type:string;direction:string;amount:number;category:string|null;occurred_at:string;status:string};
export type Cashbox={id:string;workspace_id:string;name:string;opening_balance:number;active:boolean};
export type Source={companies:Company[];transactions:Transaction[];payments:Payment[];paymentReversals:Reversal[];ledger:Ledger[];cashboxes:Cashbox[]};
export type Query={kind:ReportKind;from?:string|null;to?:string|null;companyId?:string|null;transactionId?:string|null;cashboxId?:string|null};
export type Movement={id:string;source:'payment'|'ledger';sourceId:string;occurredAt:string;direction:'in'|'out';amountCents:bigint;effectiveCents:bigint;status:'posted'|'reversed';title:string;companyId:string|null;companyLabel:string|null;transactionId:string|null;transactionLabel:string|null;evidenceRef:string};
export type Receivable={transactionId:string;transactionLabel:string;companyId:string;companyLabel:string;currentFeeCents:bigint;collectedCents:bigint;outstandingCents:bigint;creditCents:bigint};
export type Snapshot={version:'7.4';kind:ReportKind;title:string;generatedAt:string;from:string|null;to:string|null;scope:{kind:ReportKind;companyId:string|null;companyLabel:string|null;transactionId:string|null;transactionLabel:string|null;cashboxId:string|null;cashboxLabel:string|null};totals:{currentFeesCents:bigint;collectedCents:bigint;ledgerInCents:bigint;ledgerOutCents:bigint;netCashMovementCents:bigint;outstandingAtSnapshotCents:bigint;creditAtSnapshotCents:bigint;openingBalanceCents:bigint};movements:Movement[];receivables:Receivable[];disclosures:string[];fingerprint:string};

export class ReportInputError extends Error{constructor(message:string){super(message);this.name='ReportInputError'}}
const cents=(value:number,label:string)=>{if(!Number.isFinite(value))throw new ReportInputError(`unsafe ${label}`);const scaled=value*100,rounded=Math.round(scaled);if(!Number.isSafeInteger(rounded)||Math.abs(scaled-rounded)>1e-6)throw new ReportInputError(`unsafe ${label}`);return BigInt(rounded)};
const parse=(value:string,label:string)=>{const ms=Date.parse(value);if(!Number.isFinite(ms))throw new ReportInputError(`invalid ${label}`);return ms};
const bound=(value:string|null|undefined,end:boolean)=>{if(!value?.trim())return{iso:null as string|null,ms:null as number|null};const s=value.trim(),dateOnly=/^\d{4}-\d{2}-\d{2}$/.test(s),normalized=dateOnly?`${s}T${end?'23:59:59.999':'00:00:00.000'}Z`:s,ms=parse(normalized,end?'to':'from');return{iso:new Date(ms).toISOString(),ms}};
const companyName=(s:Source,id:string|null)=>{if(!id)return null;const r=s.companies.find(x=>x.id===id);return r?(r.display_name?.trim()||r.legal_name.trim()||'شركة بلا اسم صالح'):'شركة غير متاحة'};
const transactionName=(s:Source,id:string|null)=>{if(!id)return null;const r=s.transactions.find(x=>x.id===id);return r?(r.legacy_id?.trim()?`معاملة ${r.legacy_id.trim()}`:r.type.trim()||`معاملة ${r.id.slice(0,8)}`):'معاملة غير متاحة'};
const cashboxName=(s:Source,id:string|null)=>id?(s.cashboxes.find(x=>x.id===id)?.name.trim()||'صندوق غير متاح'):null;
const inPeriod=(ms:number,from:number|null,to:number|null)=>(from===null||ms>=from)&&(to===null||ms<=to);
const fnv=(text:string)=>{let hash=0xcbf29ce484222325n;for(const ch of text){hash^=BigInt(ch.codePointAt(0)??0);hash=BigInt.asUintN(64,hash*0x100000001b3n)}return`ENJAZ-FR-${hash.toString(16).padStart(16,'0')}`};

export function buildServerFinancialReport(source:Source,query:Query,generatedAtInput:Date|string=new Date()):Snapshot{
 const generated=generatedAtInput instanceof Date?new Date(generatedAtInput):new Date(generatedAtInput);if(!Number.isFinite(generated.getTime()))throw new ReportInputError('invalid generatedAt');
 const from=bound(query.from,false),to=bound(query.to,true);if(from.ms!==null&&to.ms!==null&&from.ms>to.ms)throw new ReportInputError('from after to');
 const companyId=query.kind==='company'?(query.companyId?.trim()||null):null,transactionId=query.kind==='transaction'?(query.transactionId?.trim()||null):null,cashboxId=query.kind==='cashbox'?(query.cashboxId?.trim()||null):null;
 if(query.kind==='company'&&!companyId)throw new ReportInputError('companyId required');if(query.kind==='transaction'&&!transactionId)throw new ReportInputError('transactionId required');if(query.kind==='cashbox'&&!cashboxId)throw new ReportInputError('cashboxId required');
 if(companyId&&!source.companies.some(x=>x.id===companyId))throw new ReportInputError('unknown companyId');if(transactionId&&!source.transactions.some(x=>x.id===transactionId))throw new ReportInputError('unknown transactionId');if(cashboxId&&!source.cashboxes.some(x=>x.id===cashboxId))throw new ReportInputError('unknown cashboxId');
 const resolvedCompanyId=query.kind==='transaction'&&transactionId?source.transactions.find(x=>x.id===transactionId)?.company_id??null:companyId;
 const scope={kind:query.kind,companyId:resolvedCompanyId,companyLabel:companyName(source,resolvedCompanyId),transactionId,transactionLabel:transactionName(source,transactionId),cashboxId,cashboxLabel:cashboxName(source,cashboxId)};
 const inScope=(cid:string|null,tid:string|null)=>scope.kind==='company'?cid===scope.companyId:scope.kind==='transaction'?tid===scope.transactionId:scope.kind==='cashbox'?false:true;
 const reversalIds=new Set(source.paymentReversals.map(x=>x.payment_id)),movements:Movement[]=[];let collected=0n,ledgerIn=0n,ledgerOut=0n;
 for(const p of source.payments){if(!inScope(p.company_id,p.transaction_id))continue;const ms=parse(p.paid_at,`payment:${p.id}`);if(!inPeriod(ms,from.ms,to.ms))continue;const amount=cents(p.amount,`payment:${p.id}`),reversed=p.status.trim().toLowerCase()==='reversed'||reversalIds.has(p.id);if(!reversed)collected+=amount;movements.push({id:`payment:${p.id}`,source:'payment',sourceId:p.id,occurredAt:new Date(ms).toISOString(),direction:'in',amountCents:amount,effectiveCents:reversed?0n:amount,status:reversed?'reversed':'posted',title:`إيصال ${p.receipt_ref.trim()}`,companyId:p.company_id,companyLabel:companyName(source,p.company_id),transactionId:p.transaction_id,transactionLabel:transactionName(source,p.transaction_id),evidenceRef:`payments:${p.id}:${p.receipt_ref.trim()}`})}
 for(const e of source.ledger){if(!inScope(e.company_id,e.transaction_id))continue;const ms=parse(e.occurred_at,`ledger:${e.id}`);if(!inPeriod(ms,from.ms,to.ms))continue;const amount=cents(e.amount,`ledger:${e.id}`),reversed=e.status.trim().toLowerCase()==='reversed',direction=e.direction.trim().toLowerCase()==='out'?'out' as const:'in' as const;if(!reversed)(direction==='out'?ledgerOut+=amount:ledgerIn+=amount);movements.push({id:`ledger:${e.id}`,source:'ledger',sourceId:e.id,occurredAt:new Date(ms).toISOString(),direction,amountCents:amount,effectiveCents:reversed?0n:direction==='out'?-amount:amount,status:reversed?'reversed':'posted',title:e.category?.trim()||e.entry_type.trim()||'قيد مالي',companyId:e.company_id,companyLabel:companyName(source,e.company_id),transactionId:e.transaction_id,transactionLabel:transactionName(source,e.transaction_id),evidenceRef:`financial_ledger_entries:${e.id}`})}
 movements.sort((a,b)=>Date.parse(a.occurredAt)-Date.parse(b.occurredAt)||a.id.localeCompare(b.id));
 const txs=scope.kind==='period'?source.transactions:scope.kind==='cashbox'?[]:source.transactions.filter(x=>scope.kind==='company'?x.company_id===scope.companyId:x.id===scope.transactionId),txIds=new Set(txs.map(x=>x.id)),payments=source.payments.filter(x=>txIds.has(x.transaction_id)),paid=new Map<string,bigint>();for(const p of payments){const reversed=p.status.trim().toLowerCase()==='reversed'||reversalIds.has(p.id);if(!reversed)paid.set(p.transaction_id,(paid.get(p.transaction_id)??0n)+cents(p.amount,`payment:${p.id}`))}
 let fees=0n,outstanding=0n,credit=0n;const receivables:Receivable[]=[];for(const t of txs){if(t.deleted_at!==null)continue;const fee=cents(t.current_fee,`fee:${t.id}`),got=paid.get(t.id)??0n,o=fee>got?fee-got:0n,c=got>fee?got-fee:0n;fees+=fee;outstanding+=o;credit+=c;if(o>0n||c>0n)receivables.push({transactionId:t.id,transactionLabel:transactionName(source,t.id)!,companyId:t.company_id,companyLabel:companyName(source,t.company_id)!,currentFeeCents:fee,collectedCents:got,outstandingCents:o,creditCents:c})}receivables.sort((a,b)=>a.outstandingCents===b.outstandingCents?a.transactionId.localeCompare(b.transactionId):a.outstandingCents>b.outstandingCents?-1:1);
 const opening=scope.kind==='cashbox'?source.cashboxes.filter(x=>x.id===scope.cashboxId).reduce((s,x)=>s+cents(x.opening_balance,`cashbox:${x.id}`),0n):source.cashboxes.reduce((s,x)=>s+cents(x.opening_balance,`cashbox:${x.id}`),0n);
 const totals={currentFeesCents:fees,collectedCents:collected,ledgerInCents:ledgerIn,ledgerOutCents:ledgerOut,netCashMovementCents:collected+ledgerIn-ledgerOut,outstandingAtSnapshotCents:outstanding,creditAtSnapshotCents:credit,openingBalanceCents:opening};
 const canonical=JSON.stringify({version:'7.4',kind:scope.kind,from:from.iso,to:to.iso,scope,totals:Object.fromEntries(Object.entries(totals).map(([k,v])=>[k,v.toString()])),movements:movements.map(x=>[x.id,x.occurredAt,x.status,x.direction,x.amountCents.toString(),x.effectiveCents.toString(),x.evidenceRef]),receivables:receivables.map(x=>[x.transactionId,x.currentFeeCents.toString(),x.collectedCents.toString(),x.outstandingCents.toString(),x.creditCents.toString()])});
 const title=scope.kind==='company'?`تقرير مالي — ${scope.companyLabel}`:scope.kind==='transaction'?`تقرير مالي — ${scope.transactionLabel}`:scope.kind==='cashbox'?`تقرير الصندوق — ${scope.cashboxLabel}`:'التقرير المالي للفترة';
 return{version:'7.4',kind:scope.kind,title,generatedAt:generated.toISOString(),from:from.iso,to:to.iso,scope,totals,movements,receivables,disclosures:['إجمالي الأتعاب والرصيد المفتوح يعكسان الحالة الحالية للسجلات المختارة؛ أما التحصيل وحركة القيود فمقيدان بالفترة المحددة.','الدفعات والقيود المعكوسة تظهر في تفاصيل المصدر بقيمة فعالة صفر ولا تدخل في الإجماليات.',scope.kind==='cashbox'?'المخطط الحالي لا يربط الدفعات أو القيود المالية بصندوق محدد؛ لذلك يعرض تقرير الصندوق الرصيد الافتتاحي وحالة الصندوق فقط ولا ينسب حركة مالية إليه تخميناً.':'كل سطر حركة يحتفظ بمرجع مباشر إلى سجل الدفعة أو القيد المالي المستخدم في الإجمالي.','تكامل M16 محجوز كخطاف تقارير فقط؛ لا يتم إنشاء مخزن مالي موازٍ للعقود أو الأتعاب المحتجزة.'],fingerprint:fnv(canonical)}
}

export function reportIdentity(workspaceId:string,report:Snapshot){const scope=report.scope,scoped=scope.transactionId??scope.companyId??scope.cashboxId??'workspace',from=report.from?.slice(0,10)??'start',to=report.to?.slice(0,10)??'end',id=`${report.kind}-${scoped}-${from}-${to}`.replace(/[^A-Za-z0-9._-]+/g,'-').slice(0,160),fp=report.fingerprint.replace(/[^A-Za-z0-9._-]+/g,'_');return`ENJAZ:REPORT:v1:${workspaceId}:finance-${report.kind}:${id}:${fp}`}
