import type { HomeDashboardLoadState } from '../../features/home/useHomeDashboard.ts';

export const REBIRTH_HOME_PREVIEW_STATE: HomeDashboardLoadState = Object.freeze({
  status: 'ready',
  errorMessage: null,
  snapshot: Object.freeze({
    activeTransactions: 18,
    urgentTransactions: 3,
    stalledTransactions: 2,
    openFollowups: 11,
    overdueFollowups: 4,
    openBlockers: 3,
    criticalBlockers: 1,
    finance: Object.freeze({
      activeFees: 9_850_000,
      collectedAgainstActive: 6_450_000,
      outstandingActive: 3_400_000,
      precisionSafe: true,
    }),
    priorities: Object.freeze([
      Object.freeze({
        id: 'preview:blocker:1',
        transactionId: 'preview-transaction-1',
        companyId: 'preview-company-1',
        companyLabel: 'شركة أفق بغداد',
        title: 'استكمال موافقة التسجيل قبل نهاية الدوام',
        reason: 'عائق حرج يوقف إكمال المعاملة ويحتاج قرارًا مباشرًا.',
        level: 'critical',
        score: 120,
        destination: '/app/transactions',
      }),
      Object.freeze({
        id: 'preview:followup:2',
        transactionId: 'preview-transaction-2',
        companyId: 'preview-company-2',
        companyLabel: 'مجموعة الرافدين',
        title: 'متابعة كتاب الجهة المختصة',
        reason: 'متابعة متأخرة منذ 6 أيام.',
        level: 'high',
        score: 106,
        destination: '/app/transactions',
      }),
      Object.freeze({
        id: 'preview:urgent:3',
        transactionId: 'preview-transaction-3',
        companyId: 'preview-company-3',
        companyLabel: 'تاج الرافدين',
        title: 'معاملة عاجلة: تعديل عقد الشركة',
        reason: 'الأولوية مصنفة عاجلة وتحتاج انتباهًا مباشرًا.',
        level: 'high',
        score: 90,
        destination: '/app/transactions',
      }),
      Object.freeze({
        id: 'preview:stalled:4',
        transactionId: 'preview-transaction-4',
        companyId: 'preview-company-4',
        companyLabel: 'بوابة العراق',
        title: 'معاملة متلكئة: تحديث بيانات المفوض',
        reason: 'الحالة متلكئة وتحتاج تحديد سبب التوقف والخطوة التالية.',
        level: 'medium',
        score: 80,
        destination: '/app/transactions',
      }),
    ]),
    signals: Object.freeze([
      Object.freeze({
        id: 'overdue-followups',
        label: 'متابعات متأخرة',
        value: 4,
        detail: 'تحتاج معالجة قبل تراكم التأخير.',
        tone: 'danger',
      }),
      Object.freeze({
        id: 'open-blockers',
        label: 'عوائق مفتوحة',
        value: 3,
        detail: '1 منها حرج.',
        tone: 'danger',
      }),
      Object.freeze({
        id: 'stalled-transactions',
        label: 'معاملات متلكئة',
        value: 2,
        detail: 'تحتاج تحديد سبب التوقف والخطوة التالية.',
        tone: 'warning',
      }),
    ]),
  }),
});
