import { DataAccessError } from '../../data/contracts/DataAccessError.ts';
export const DOCUMENT_VAULT_MAX_BYTES=52_428_800;
export const DOCUMENT_VAULT_ALLOWED_MIME=['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'] as const;
export type DocumentVaultStatus='ready'|'processing'|'needs_review'|'failed'|'archived';
export interface VaultDocument{readonly id:string;readonly title:string;readonly documentType:string|null;readonly fileName:string|null;readonly mimeType:string;readonly sizeBytes:number;readonly status:DocumentVaultStatus;readonly companyId:string|null;readonly companyName:string|null;readonly transactionId:string|null;readonly transactionLabel:string|null;readonly createdAt:string;readonly updatedAt:string;readonly capturedAt:string|null;readonly archivedAt:string|null;readonly currentVersion:number;readonly versionCount:number}
export interface VaultVersion{readonly id:string;readonly versionNumber:number;readonly fileName:string|null;readonly mimeType:string;readonly sizeBytes:number;readonly checksum:string|null;readonly createdAt:string;readonly uploadedBy:string|null}
export interface VaultList{readonly workspaceId:string;readonly total:number;readonly offset:number;readonly limit:number;readonly documents:readonly VaultDocument[]}
export interface VaultDetail{readonly document:VaultDocument;readonly versions:readonly VaultVersion[]}
export interface DocumentUploadInput{readonly workspaceId:string;readonly title:string;readonly documentType:string|null;readonly companyId:string|null;readonly transactionId:string|null;readonly documentId?:string|null;readonly file:File}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,ST=['ready','processing','needs_review','failed','archived'] as const;
const bad=()=>{throw new DataAccessError('Invalid Document Vault data','DATA_OPERATION_FAILED')};
const R=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:bad(),A=(v:unknown)=>Array.isArray(v)?v:bad(),S=(v:unknown,n=1200)=>typeof v==='string'&&v.trim()&&v.length<=n?v:bad(),O=(v:unknown,n=1200)=>v==null?null:S(v,n),I=(v:unknown,min=0)=>{const n=Number(v);return Number.isSafeInteger(n)&&n>=min?n:bad()},ID=(v:unknown)=>{const s=S(v,64);return UUID.test(s)?s:bad()};
function doc(v:unknown):VaultDocument{const x=R(v),s=S(x.status,32) as DocumentVaultStatus;if(!ST.includes(s))bad();return{id:ID(x.id),title:S(x.title,320),documentType:O(x.documentType,120),fileName:O(x.fileName,240),mimeType:S(x.mimeType,160),sizeBytes:I(x.sizeBytes),status:s,companyId:x.companyId?ID(x.companyId):null,companyName:O(x.companyName,400),transactionId:x.transactionId?ID(x.transactionId):null,transactionLabel:O(x.transactionLabel,240),createdAt:S(x.createdAt,80),updatedAt:S(x.updatedAt,80),capturedAt:O(x.capturedAt,80),archivedAt:O(x.archivedAt,80),currentVersion:I(x.currentVersion),versionCount:I(x.versionCount)}}
export function parseVaultList(v:unknown):VaultList{const r=R(v);if(r.schema!=='enjaz.document-vault.v1')bad();return{workspaceId:ID(r.workspaceId),total:I(r.total),offset:I(r.offset),limit:I(r.limit,1),documents:A(r.documents).map(doc)}}
export function parseVaultDetail(v:unknown):VaultDetail{const r=R(v);if(r.schema!=='enjaz.document-detail.v1')bad();const versions:VaultVersion[]=A(r.versions).map(v=>{const x=R(v);return{id:ID(x.id),versionNumber:I(x.versionNumber,1),fileName:O(x.fileName,240),mimeType:S(x.mimeType,160),sizeBytes:I(x.sizeBytes),checksum:O(x.checksum,64),createdAt:S(x.createdAt,80),uploadedBy:x.uploadedBy?ID(x.uploadedBy):null}}),base=R(r.document);return{document:doc({...base,currentVersion:versions.length?Math.max(...versions.map(x=>x.versionNumber)):0,versionCount:versions.length,companyName:base.companyName??null,transactionLabel:base.transactionLabel??null}),versions}}
export function validateUploadInput(x:DocumentUploadInput){const invalidId=(v:string|null|undefined)=>v&&!UUID.test(v);if(invalidId(x.workspaceId)||invalidId(x.documentId)||invalidId(x.companyId)||invalidId(x.transactionId))throw new DataAccessError('Invalid document relation','DATA_VALIDATION_FAILED');if(!x.title.trim()||x.title.length>320||x.documentType&&x.documentType.length>120)throw new DataAccessError('Invalid document metadata','DATA_VALIDATION_FAILED');const f=x.file;if(!f.name.trim()||f.name.length>240||/[\\/\u0000-\u001f]/.test(f.name)||!Number.isSafeInteger(f.size)||f.size<1||f.size>DOCUMENT_VAULT_MAX_BYTES||!DOCUMENT_VAULT_ALLOWED_MIME.includes(f.type.toLowerCase() as typeof DOCUMENT_VAULT_ALLOWED_MIME[number]))throw new DataAccessError('Invalid document file','DATA_VALIDATION_FAILED')}
export function formatVaultBytes(n:number){return n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`}
