import {DataAccessError} from '../../data/contracts/DataAccessError.ts';
export const DOCUMENT_VAULT_MAX_BYTES=52_428_800;
export const DOCUMENT_VAULT_ALLOWED_MIME=['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'] as const;
export type DocumentVaultStatus='ready'|'processing'|'needs_review'|'failed'|'archived';
export interface VaultDocument{readonly id:string;readonly title:string;readonly documentType:string|null;readonly fileName:string|null;readonly mimeType:string;readonly sizeBytes:number;readonly status:DocumentVaultStatus;readonly companyId:string|null;readonly transactionId:string|null;readonly createdAt:string;readonly archivedAt:string|null}
export interface VaultVersion{readonly id:string;readonly versionNumber:number;readonly fileName:string|null;readonly mimeType:string;readonly sizeBytes:number;readonly createdAt:string}
export interface VaultList{readonly total:number;readonly offset:number;readonly limit:number;readonly documents:readonly VaultDocument[]}
export interface VaultDetail{readonly document:VaultDocument;readonly versions:readonly VaultVersion[]}
export interface DocumentUploadInput{readonly workspaceId:string;readonly title:string;readonly documentType:string|null;readonly companyId:string|null;readonly transactionId:string|null;readonly documentId?:string|null;readonly file:File}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,STATUS=['ready','processing','needs_review','failed','archived'] as const;
const bad=(validation=false):never=>{throw new DataAccessError('Invalid Document Vault data',validation?'DATA_VALIDATION_FAILED':'DATA_OPERATION_FAILED')},rec=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:bad(),arr=(v:unknown)=>Array.isArray(v)?v:bad(),str=(v:unknown,n=1200)=>typeof v==='string'&&v.trim()&&v.length<=n?v:bad(),opt=(v:unknown,n=1200)=>v==null?null:str(v,n),num=(v:unknown,min=0)=>{const n=Number(v);return Number.isSafeInteger(n)&&n>=min?n:bad()};
export function assertVaultId(v:unknown){const s=str(v,64);if(!UUID.test(s))bad(true);return s}
const oid=(v:unknown)=>v==null?null:assertVaultId(v);
function doc(v:unknown):VaultDocument{const x=rec(v),status=str(x.status,32) as DocumentVaultStatus;if(!STATUS.includes(status))bad();return{id:assertVaultId(x.id),title:str(x.title,320),documentType:opt(x.documentType,120),fileName:opt(x.fileName,240),mimeType:str(x.mimeType,160),sizeBytes:num(x.sizeBytes),status,companyId:oid(x.companyId),transactionId:oid(x.transactionId),createdAt:str(x.createdAt,80),archivedAt:opt(x.archivedAt,80)}}
export function parseVaultList(v:unknown):VaultList{const x=rec(v);if(x.schema!=='enjaz.document-vault.v1')bad();return{total:num(x.total),offset:num(x.offset),limit:num(x.limit,1),documents:arr(x.documents).map(doc)}}
export function parseVaultDetail(v:unknown):VaultDetail{const x=rec(v);if(x.schema!=='enjaz.document-detail.v1')bad();return{document:doc(x.document),versions:arr(x.versions).map(v=>{const y=rec(v);return{id:assertVaultId(y.id),versionNumber:num(y.versionNumber,1),fileName:opt(y.fileName,240),mimeType:str(y.mimeType,160),sizeBytes:num(y.sizeBytes),createdAt:str(y.createdAt,80)}})}}
export function validateUploadInput(x:DocumentUploadInput){for(const id of[x.workspaceId,x.documentId,x.companyId,x.transactionId])if(id)assertVaultId(id);if(!x.title.trim()||x.title.length>320||x.documentType&&x.documentType.length>120)bad(true);const f=x.file;if(!f.name.trim()||f.name.length>240||/[\\/\u0000-\u001f]/.test(f.name)||!Number.isSafeInteger(f.size)||f.size<1||f.size>DOCUMENT_VAULT_MAX_BYTES||!DOCUMENT_VAULT_ALLOWED_MIME.includes(f.type.toLowerCase() as typeof DOCUMENT_VAULT_ALLOWED_MIME[number]))bad(true)}
export const formatVaultBytes=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
