import { DataAccessError } from '../../data/contracts/DataAccessError.ts';

export const DOCUMENT_VAULT_MAX_BYTES=52_428_800;
export const DOCUMENT_VAULT_ALLOWED_MIME=Object.freeze(['application/pdf','image/jpeg','image/png','image/webp','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'] as const);
export type DocumentVaultStatus='ready'|'processing'|'needs_review'|'failed'|'archived';
export interface VaultDocument{readonly id:string;readonly title:string;readonly documentType:string|null;readonly fileName:string|null;readonly mimeType:string;readonly sizeBytes:number;readonly status:DocumentVaultStatus;readonly companyId:string|null;readonly companyName:string|null;readonly transactionId:string|null;readonly transactionLabel:string|null;readonly createdAt:string;readonly updatedAt:string;readonly capturedAt:string|null;readonly archivedAt:string|null;readonly currentVersion:number;readonly versionCount:number}
export interface VaultVersion{readonly id:string;readonly versionNumber:number;readonly fileName:string|null;readonly mimeType:string;readonly sizeBytes:number;readonly checksum:string|null;readonly createdAt:string;readonly uploadedBy:string|null}
export interface VaultList{readonly workspaceId:string;readonly total:number;readonly offset:number;readonly limit:number;readonly documents:readonly VaultDocument[]}
export interface VaultDetail{readonly document:VaultDocument;readonly versions:readonly VaultVersion[]}
export interface DocumentUploadInput{readonly workspaceId:string;readonly title:string;readonly documentType:string|null;readonly companyId:string|null;readonly transactionId:string|null;readonly documentId?:string|null;readonly file:File}
export interface PreparedUpload{readonly operationId:string;readonly documentId:string;readonly versionNumber:number;readonly path:string;readonly fileName:string;readonly mimeType:string;readonly byteSize:number;readonly signedUrl:string;readonly uploadToken:string}
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const rec=(v:unknown):Readonly<Record<string,unknown>>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new DataAccessError('Invalid Document Vault payload','DATA_OPERATION_FAILED');return v as Readonly<Record<string,unknown>>};
const arr=(v:unknown):readonly unknown[]=>{if(!Array.isArray(v))throw new DataAccessError('Invalid Document Vault array','DATA_OPERATION_FAILED');return v};
const txt=(v:unknown,max=1200):string=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw new DataAccessError('Invalid Document Vault text','DATA_OPERATION_FAILED');return v};
const opt=(v:unknown,max=1200):string|null=>v===null||v===undefined?null:txt(v,max);
const id=(v:unknown):string=>{const x=txt(v,64);if(!UUID.test(x))throw new DataAccessError('Invalid Document Vault id','DATA_OPERATION_FAILED');return x};
const integer=(v:unknown,min=0):number=>{const n=typeof v==='number'?v:Number(v);if(!Number.isSafeInteger(n)||n<min)throw new DataAccessError('Invalid Document Vault number','DATA_OPERATION_FAILED');return n};
const status=(v:unknown):DocumentVaultStatus=>{const x=txt(v,32) as DocumentVaultStatus;if(!['ready','processing','needs_review','failed','archived'].includes(x))throw new DataAccessError('Invalid Document Vault status','DATA_OPERATION_FAILED');return x};
function parseDocument(v:unknown):VaultDocument{const x=rec(v);return Object.freeze({id:id(x.id),title:txt(x.title,320),documentType:opt(x.documentType,120),fileName:opt(x.fileName,240),mimeType:txt(x.mimeType,160),sizeBytes:integer(x.sizeBytes),status:status(x.status),companyId:x.companyId? id(x.companyId):null,companyName:opt(x.companyName,400),transactionId:x.transactionId?id(x.transactionId):null,transactionLabel:opt(x.transactionLabel,240),createdAt:txt(x.createdAt,80),updatedAt:txt(x.updatedAt,80),capturedAt:opt(x.capturedAt,80),archivedAt:opt(x.archivedAt,80),currentVersion:integer(x.currentVersion),versionCount:integer(x.versionCount)})}
export function parseVaultList(value:unknown):VaultList{const r=rec(value);if(r.schema!=='enjaz.document-vault.v1')throw new DataAccessError('Unsupported Document Vault schema','DATA_OPERATION_FAILED');return Object.freeze({workspaceId:id(r.workspaceId),total:integer(r.total),offset:integer(r.offset),limit:integer(r.limit,1),documents:Object.freeze(arr(r.documents).map(parseDocument))})}
export function parseVaultDetail(value:unknown):VaultDetail{const r=rec(value);if(r.schema!=='enjaz.document-detail.v1')throw new DataAccessError('Unsupported document detail schema','DATA_OPERATION_FAILED');const d=rec(r.document),base=parseDocument({...d,currentVersion:Array.isArray(r.versions)&&r.versions.length?Math.max(...(r.versions as unknown[]).map(v=>integer(rec(v).versionNumber,1))):0,versionCount:Array.isArray(r.versions)?r.versions.length:0});const versions=arr(r.versions).map(v=>{const x=rec(v);return Object.freeze({id:id(x.id),versionNumber:integer(x.versionNumber,1),fileName:opt(x.fileName,240),mimeType:txt(x.mimeType,160),sizeBytes:integer(x.sizeBytes),checksum:opt(x.checksum,64),createdAt:txt(x.createdAt,80),uploadedBy:x.uploadedBy?id(x.uploadedBy):null})});return Object.freeze({document:base,versions:Object.freeze(versions)})}
export function validateUploadInput(input:DocumentUploadInput):void{if(!UUID.test(input.workspaceId))throw new DataAccessError('Invalid workspace','DATA_VALIDATION_FAILED');if(input.documentId&&!UUID.test(input.documentId))throw new DataAccessError('Invalid document','DATA_VALIDATION_FAILED');if(input.companyId&&!UUID.test(input.companyId))throw new DataAccessError('Invalid company','DATA_VALIDATION_FAILED');if(input.transactionId&&!UUID.test(input.transactionId))throw new DataAccessError('Invalid transaction','DATA_VALIDATION_FAILED');if(!input.title.trim()||input.title.length>320)throw new DataAccessError('Invalid title','DATA_VALIDATION_FAILED');if(input.documentType&&input.documentType.length>120)throw new DataAccessError('Invalid document type','DATA_VALIDATION_FAILED');if(!input.file.name.trim()||input.file.name.length>240||/[\\/\u0000-\u001f]/.test(input.file.name))throw new DataAccessError('Invalid file name','DATA_VALIDATION_FAILED');if(!Number.isSafeInteger(input.file.size)||input.file.size<1||input.file.size>DOCUMENT_VAULT_MAX_BYTES)throw new DataAccessError('Invalid file size','DATA_VALIDATION_FAILED');if(!DOCUMENT_VAULT_ALLOWED_MIME.includes(input.file.type.toLowerCase() as typeof DOCUMENT_VAULT_ALLOWED_MIME[number]))throw new DataAccessError('Unsupported file type','DATA_VALIDATION_FAILED')}
export function formatVaultBytes(bytes:number):string{if(bytes<1024)return `${bytes} B`;if(bytes<1024*1024)return `${(bytes/1024).toFixed(1)} KB`;return `${(bytes/(1024*1024)).toFixed(1)} MB`}
