import type {EnjazSupabaseClient} from '../../core/supabase/client.ts';
import {DataAccessError,normalizeDataFailure,normalizeThrownDataFailure,type DataFailureLike} from '../../data/contracts/DataAccessError.ts';
import {parseDocumentIntelligence,parseExtractionResult,type DocumentIntelligence,type ExtractionResult} from './documentIntelligenceContract.ts';
import {assertVaultId,parseVaultDetail,parseVaultList,validateUploadInput,type DocumentUploadInput,type VaultDetail,type VaultList} from './documentVaultContract.ts';

export interface DocumentVaultGateway{
 list(workspaceId:string,query?:string,includeArchived?:boolean,offset?:number):Promise<VaultList>;
 detail(workspaceId:string,documentId:string):Promise<VaultDetail>;
 upload(input:DocumentUploadInput):Promise<{documentId:string;versionNumber:number}>;
 downloadUrl(workspaceId:string,documentId:string,versionNumber?:number|null):Promise<string>;
 archive(workspaceId:string,documentId:string):Promise<void>;
 intelligence(workspaceId:string,documentId:string):Promise<DocumentIntelligence>;
 extract(workspaceId:string,documentId:string,versionNumber?:number|null):Promise<ExtractionResult>;
 reviewExtraction(workspaceId:string,analysisId:string,decision:'accept'|'reject',note?:string|null):Promise<void>;
 verifyExtraction(workspaceId:string,analysisId:string,note?:string|null):Promise<void>;
}

type Rpc={rpc(name:string,args:Record<string,unknown>):PromiseLike<{data:unknown;error:DataFailureLike|null}>};
const object=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:(()=>{throw new DataAccessError('Invalid Document Vault response','DATA_OPERATION_FAILED')})();

export function createDocumentVaultGateway(client:EnjazSupabaseClient,url:string,key:string,timeout=20_000):DocumentVaultGateway{
 const rpc=client as unknown as Rpc;
 const wait=async<T>(p:Promise<T>,limit=timeout)=>{let t:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([p,new Promise<never>((_,r)=>{t=setTimeout(()=>r(new Error('vault timeout')),limit)})])}finally{if(t)clearTimeout(t)}};
 const call=async(name:string,args:Record<string,unknown>,write=false)=>{try{const r=await wait(Promise.resolve(rpc.rpc(name,args)));if(r.error)throw normalizeDataFailure(r.error);return r.data}catch(e){throw normalizeThrownDataFailure(e,write?'write':'read')}};
 const edge=async(slug:string,body:Record<string,unknown>,limit=timeout)=>{try{const token=(await client.auth.getSession()).data.session?.access_token;if(!token)throw new DataAccessError('Authentication required','DATA_FORBIDDEN');const res=await wait(fetch(`${url.replace(/\/$/,'')}/functions/v1/${slug}`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),limit),data=object(await res.json().catch(()=>null));if(!res.ok)throw new DataAccessError(typeof data.error==='string'?data.error:`${slug} request failed`,res.status===401||res.status===403?'DATA_FORBIDDEN':'DATA_OPERATION_FAILED');return data}catch(e){if(e instanceof DataAccessError)throw e;throw normalizeThrownDataFailure(e,'write')}};
 return Object.freeze({
  async list(workspaceId:string,query='',includeArchived=false,offset=0){assertVaultId(workspaceId);if(query.length>120||!Number.isSafeInteger(offset)||offset<0)throw new DataAccessError('Invalid vault list request','DATA_VALIDATION_FAILED');return parseVaultList(await call('get_document_vault_v1',{p_workspace_id:workspaceId,p_query:query.trim()||null,p_include_archived:includeArchived,p_limit:100,p_offset:offset}))},
  async detail(workspaceId:string,documentId:string){assertVaultId(workspaceId);assertVaultId(documentId);return parseVaultDetail(await call('get_document_detail_v1',{p_workspace_id:workspaceId,p_document_id:documentId}))},
  async upload(input:DocumentUploadInput){validateUploadInput(input);const operationId=crypto.randomUUID(),p=object(await edge('enjaz-document-vault',{action:'prepare',workspaceId:input.workspaceId,operationId,documentId:input.documentId??null,title:input.title.trim(),documentType:input.documentType?.trim()||null,companyId:input.companyId,transactionId:input.transactionId,fileName:input.file.name,mimeType:input.file.type.toLowerCase(),byteSize:input.file.size}));if(p.ok!==true||typeof p.signedUrl!=='string')throw new DataAccessError('Invalid signed upload','DATA_OPERATION_FAILED');const form=new FormData();form.append('cacheControl','3600');form.append('',input.file);const sent=await wait(fetch(p.signedUrl,{method:'PUT',headers:{'x-upsert':'false'},body:form}));if(!sent.ok)throw new DataAccessError(`Storage upload failed (${sent.status})`,'DATA_OPERATION_FAILED');const a=object(await edge('enjaz-document-vault',{action:'acknowledge',operationId})),ack=object(a.ack),version=Number(ack.versionNumber);if(a.ok!==true||ack.schema!=='enjaz.document-upload-ack.v1'||typeof ack.documentId!=='string'||!Number.isSafeInteger(version)||version<1)throw new DataAccessError('Invalid upload acknowledgement','DATA_OPERATION_FAILED');return{documentId:ack.documentId,versionNumber:version}},
  async downloadUrl(workspaceId:string,documentId:string,versionNumber:number|null=null){assertVaultId(workspaceId);assertVaultId(documentId);if(versionNumber!==null&&(!Number.isSafeInteger(versionNumber)||versionNumber<1))throw new DataAccessError('Invalid version','DATA_VALIDATION_FAILED');const r=await edge('enjaz-document-vault',{action:'download',workspaceId,documentId,versionNumber});if(r.ok!==true||typeof r.signedUrl!=='string'||!r.signedUrl.startsWith('https://'))throw new DataAccessError('Invalid download URL','DATA_OPERATION_FAILED');return r.signedUrl},
  async archive(workspaceId:string,documentId:string){assertVaultId(workspaceId);assertVaultId(documentId);await call('archive_document_v1',{p_workspace_id:workspaceId,p_document_id:documentId},true)},
  async intelligence(workspaceId:string,documentId:string){assertVaultId(workspaceId);assertVaultId(documentId);return parseDocumentIntelligence(await call('get_document_intelligence_v1',{p_workspace_id:workspaceId,p_document_id:documentId}))},
  async extract(workspaceId:string,documentId:string,versionNumber:number|null=null){assertVaultId(workspaceId);assertVaultId(documentId);if(versionNumber!==null&&(!Number.isSafeInteger(versionNumber)||versionNumber<1))throw new DataAccessError('Invalid version','DATA_VALIDATION_FAILED');return parseExtractionResult(await edge('enjaz-document-intelligence',{action:'extract',workspaceId,documentId,requestId:crypto.randomUUID(),versionNumber},120_000))},
  async reviewExtraction(workspaceId:string,analysisId:string,decision:'accept'|'reject',note:string|null=null){assertVaultId(workspaceId);assertVaultId(analysisId);if(!['accept','reject'].includes(decision)||note&&note.length>1000)throw new DataAccessError('Invalid extraction review','DATA_VALIDATION_FAILED');await call('review_document_extraction_v1',{p_workspace_id:workspaceId,p_analysis_id:analysisId,p_decision:decision,p_corrected_fields:null,p_note:note?.trim()||null},true)},
  async verifyExtraction(workspaceId:string,analysisId:string,note:string|null=null){assertVaultId(workspaceId);assertVaultId(analysisId);if(note&&note.length>1000)throw new DataAccessError('Invalid extraction verification','DATA_VALIDATION_FAILED');await call('verify_document_extraction_v1',{p_workspace_id:workspaceId,p_analysis_id:analysisId,p_note:note?.trim()||null},true)}
 })
}
