import type {EnjazSupabaseClient} from '../../core/supabase/client.ts';
import {DataAccessError,normalizeDataFailure,normalizeThrownDataFailure,type DataFailureLike} from '../../data/contracts/DataAccessError.ts';
import {validateDocumentFactoryFinalization,validateDocumentFactoryGenerationInput,validateDocumentFactoryReview,validateFactoryTokenSchema,type DocumentFactoryGenerationInput,type FactoryTokenSchema} from './documentFactoryContract.ts';

export type DocumentFactoryDraftStatus='draft'|'review_required'|'approved'|'registered'|'final'|'failed';
export type DocumentFactoryTemplate=Readonly<{versionId:string;templateId:string;name:string;kind:string;versionNumber:number;tokenSchema:FactoryTokenSchema;publishedAt:string|null}>;
export type DocumentFactoryTemplateVersion=Readonly<{id:string;versionNumber:number;status:'draft'|'published';contentChecksum:string;publishedAt:string|null}>;
export type DocumentFactoryManagedTemplate=Readonly<{id:string;name:string;kind:string;bodySource:string;tokenSchema:FactoryTokenSchema;active:boolean;versions:readonly DocumentFactoryTemplateVersion[]}>;
export type DocumentFactoryDraft=Readonly<{id:string;title:string;status:DocumentFactoryDraftStatus;compiledContent:string;facts:Readonly<Record<string,unknown>>;provenance:Readonly<Record<string,unknown>>;templateVersionId:string|null;companyId:string|null;transactionId:string|null;approvedAt:string|null;approvalNote:string|null;finalDocumentId:string|null;finalDocumentVersionId:string|null;updatedAt:string}>;
export type DocumentFactoryFinalResult=Readonly<{draftId:string;renderJobId:string;documentId:string;documentVersionId:string;wasDuplicate:boolean}>;
export type DocumentSubmissionPack=Readonly<{packId:string;transactionId:string;title:string;status:'queued'|'running'|'succeeded'|'failed';manifestChecksum:string;outputDocumentId:string|null;outputDocumentVersionId:string|null;failureCode:string|null;createdAt:string;updatedAt:string;itemCount:number}>;

export interface DocumentFactoryGateway{
 listTemplates(workspaceId:string):Promise<readonly DocumentFactoryTemplate[]>;
 listManagedTemplates(workspaceId:string):Promise<readonly DocumentFactoryManagedTemplate[]>;
 saveTemplate(input:Readonly<{workspaceId:string;templateId?:string|null;name:string;kind:string;bodySource:string;tokenSchema:unknown;active?:boolean}>):Promise<string>;
 createTemplateVersion(workspaceId:string,templateId:string,bodySource:string,tokenSchema:unknown):Promise<DocumentFactoryTemplateVersion>;
 publishTemplateVersion(workspaceId:string,versionId:string):Promise<void>;
 listDrafts(workspaceId:string,companyId?:string|null,limit?:number):Promise<readonly DocumentFactoryDraft[]>;
 generate(input:DocumentFactoryGenerationInput):Promise<DocumentFactoryDraft>;
 review(workspaceId:string,draftId:string,decision:'approve'|'return',note?:string|null):Promise<DocumentFactoryDraft>;
 renderAndFinalize(workspaceId:string,draftId:string):Promise<DocumentFactoryFinalResult>;
 listSubmissionPacks(workspaceId:string,transactionId?:string|null):Promise<readonly DocumentSubmissionPack[]>;
 buildSubmissionPack(workspaceId:string,transactionId:string,title:string,draftIds:readonly string[]):Promise<DocumentSubmissionPack>;
}

type Rpc={rpc(name:string,args:Record<string,unknown>):PromiseLike<{data:unknown;error:DataFailureLike|null}>};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const STATES=['draft','review_required','approved','registered','final','failed'] as const;
const PACK_STATES=['queued','running','succeeded','failed'] as const;
const ensureId=(v:unknown,label:string)=>typeof v==='string'&&UUID.test(v)?v:(()=>{throw new DataAccessError(`Invalid ${label}`,'DATA_VALIDATION_FAILED')})();
const object=(v:unknown,label='Document Factory response'):Record<string,unknown>=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:(()=>{throw new DataAccessError(`Invalid ${label}`,'DATA_OPERATION_FAILED')})();
const array=(v:unknown,label:string):readonly Record<string,unknown>[]=>Array.isArray(v)?v.map(x=>object(x,label)):(()=>{throw new DataAccessError(`Invalid ${label}`,'DATA_OPERATION_FAILED')})();
const status=(v:unknown):DocumentFactoryDraftStatus=>typeof v==='string'&&STATES.includes(v as DocumentFactoryDraftStatus)?v as DocumentFactoryDraftStatus:(()=>{throw new DataAccessError('Invalid Document Factory draft state','DATA_OPERATION_FAILED')})();
const packStatus=(v:unknown):DocumentSubmissionPack['status']=>typeof v==='string'&&PACK_STATES.includes(v as DocumentSubmissionPack['status'])?v as DocumentSubmissionPack['status']:(()=>{throw new DataAccessError('Invalid submission pack state','DATA_OPERATION_FAILED')})();
const nullableString=(v:unknown)=>typeof v==='string'?v:null;

function parseDraft(row:Record<string,unknown>):DocumentFactoryDraft{return Object.freeze({id:ensureId(row.id,'draft id'),title:String(row.title??''),status:status(row.status),compiledContent:String(row.compiled_content??row.compiledContent??''),facts:Object.freeze({...object(row.fact_snapshot??row.facts??{},'facts')}),provenance:Object.freeze({...object(row.provenance??{},'provenance')}),templateVersionId:nullableString(row.template_version_id??row.templateVersionId),companyId:nullableString(row.company_id??row.companyId),transactionId:nullableString(row.transaction_id??row.transactionId),approvedAt:nullableString(row.approved_at??row.approvedAt),approvalNote:nullableString(row.approval_note??row.approvalNote),finalDocumentId:nullableString(row.final_document_id??row.finalDocumentId),finalDocumentVersionId:nullableString(row.final_document_version_id??row.finalDocumentVersionId),updatedAt:String(row.updated_at??row.updatedAt??'')})}
function parseTemplateVersion(row:Record<string,unknown>):DocumentFactoryTemplateVersion{const s=String(row.status??row.state??'');if(s!=='draft'&&s!=='published')throw new DataAccessError('Invalid template version state','DATA_OPERATION_FAILED');return Object.freeze({id:ensureId(row.id??row.versionId,'template version id'),versionNumber:Number(row.versionNumber??row.version_number),status:s,contentChecksum:String(row.contentChecksum??row.content_checksum??''),publishedAt:nullableString(row.publishedAt??row.published_at)})}
function parsePack(row:Record<string,unknown>):DocumentSubmissionPack{return Object.freeze({packId:ensureId(row.packId??row.id,'submission pack id'),transactionId:ensureId(row.transactionId??row.transaction_id,'transaction id'),title:String(row.title??''),status:packStatus(row.status),manifestChecksum:String(row.manifestChecksum??row.manifest_checksum??''),outputDocumentId:nullableString(row.outputDocumentId??row.output_document_id),outputDocumentVersionId:nullableString(row.outputDocumentVersionId??row.output_document_version_id),failureCode:nullableString(row.failureCode??row.failure_code),createdAt:String(row.createdAt??row.created_at??''),updatedAt:String(row.updatedAt??row.updated_at??''),itemCount:Number(row.itemCount??0)})}

export function createDocumentFactoryGateway(client:EnjazSupabaseClient,url:string,key:string,timeout=25_000):DocumentFactoryGateway{
 const rpc=client as unknown as Rpc;
 const wait=async<T>(p:Promise<T>,ms=timeout)=>{let t:ReturnType<typeof setTimeout>|undefined;try{return await Promise.race([p,new Promise<never>((_,reject)=>{t=setTimeout(()=>reject(new Error('document factory timeout')),ms)})])}finally{if(t)clearTimeout(t)}};
 const call=async(name:string,args:Record<string,unknown>,write=false)=>{try{const r=await wait(Promise.resolve(rpc.rpc(name,args)));if(r.error)throw normalizeDataFailure(r.error);return r.data}catch(e){throw normalizeThrownDataFailure(e,write?'write':'read')}};
 const edge=async(body:Record<string,unknown>)=>{try{const token=(await client.auth.getSession()).data.session?.access_token;if(!token)throw new DataAccessError('Authentication required','DATA_FORBIDDEN');const res=await wait(fetch(`${url.replace(/\/$/,'')}/functions/v1/enjaz-document-render`,{method:'POST',headers:{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)}),120_000);const data=object(await res.json().catch(()=>null));if(!res.ok){const code=typeof data.error==='string'?data.error:'Document render failed';if(res.status===401||res.status===403)throw new DataAccessError(code,'DATA_FORBIDDEN');throw new DataAccessError(code,'DATA_OPERATION_FAILED')}return data}catch(e){if(e instanceof DataAccessError)throw e;throw normalizeThrownDataFailure(e,'write')}};
 const fetchDraft=async(workspaceId:string,draftId:string)=>{ensureId(workspaceId,'workspace id');ensureId(draftId,'draft id');const r=await client.from('document_drafts').select('id,title,status,compiled_content,fact_snapshot,provenance,template_version_id,company_id,transaction_id,approved_at,approval_note,final_document_id,final_document_version_id,updated_at').eq('workspace_id',workspaceId).eq('id',draftId).maybeSingle();if(r.error)throw normalizeDataFailure(r.error as DataFailureLike);if(!r.data)throw new DataAccessError('Document Factory draft not found','DATA_OPERATION_FAILED');return parseDraft(object(r.data,'draft'))};
 const listManaged=async(workspaceId:string)=>{ensureId(workspaceId,'workspace id');const payload=object(await call('get_document_factory_v1',{p_workspace_id:workspaceId}));return Object.freeze(array(payload.templates??[],'managed templates').map(t=>Object.freeze({id:ensureId(t.id,'template id'),name:String(t.name??''),kind:String(t.kind??''),bodySource:String(t.bodySource??t.body_source??''),tokenSchema:validateFactoryTokenSchema(t.tokenSchema??t.token_schema??{},String(t.bodySource??t.body_source??'')),active:t.active===true,versions:Object.freeze(array(t.versions??[],'template versions').map(parseTemplateVersion))}))) };
 return Object.freeze({
  async listTemplates(workspaceId:string){ensureId(workspaceId,'workspace id');try{const [versions,templates]=await Promise.all([client.from('document_template_versions').select('id,template_id,version_number,token_schema,published_at').eq('workspace_id',workspaceId).eq('status','published').order('version_number',{ascending:false}),client.from('document_templates').select('id,name,kind,active').eq('workspace_id',workspaceId).eq('active',true)]);if(versions.error)throw normalizeDataFailure(versions.error as DataFailureLike);if(templates.error)throw normalizeDataFailure(templates.error as DataFailureLike);const templateMap=new Map(array(templates.data??[],'templates').map(t=>[String(t.id),t]));return Object.freeze(array(versions.data??[],'template versions').flatMap(v=>{const t=templateMap.get(String(v.template_id));if(!t)return[];return[Object.freeze({versionId:ensureId(v.id,'template version id'),templateId:ensureId(v.template_id,'template id'),name:String(t.name??'قالب رسمي'),kind:String(t.kind??'official'),versionNumber:Number(v.version_number),tokenSchema:object(v.token_schema??{},'token schema') as FactoryTokenSchema,publishedAt:nullableString(v.published_at)})]}))}catch(e){if(e instanceof DataAccessError)throw e;throw normalizeThrownDataFailure(e,'read')}},
  async listManagedTemplates(workspaceId:string){return listManaged(workspaceId)},
  async saveTemplate(input){const workspaceId=ensureId(input.workspaceId,'workspace id'),templateId=input.templateId?ensureId(input.templateId,'template id'):crypto.randomUUID(),name=String(input.name??'').trim(),kind=String(input.kind??'').trim(),bodySource=String(input.bodySource??'');if(!name||name.length>240||!kind||kind.length>120||!bodySource.trim()||bodySource.length>1_000_000)throw new DataAccessError('Invalid template working copy','DATA_VALIDATION_FAILED');const tokenSchema=validateFactoryTokenSchema(input.tokenSchema,bodySource);await call('save_document_template_v1',{p_workspace_id:workspaceId,p_template_id:templateId,p_name:name,p_kind:kind,p_body_source:bodySource,p_token_schema:tokenSchema,p_active:input.active!==false},true);return templateId},
  async createTemplateVersion(workspaceId:string,templateId:string,bodySource:string,tokenSchema:unknown){ensureId(workspaceId,'workspace id');ensureId(templateId,'template id');const schema=validateFactoryTokenSchema(tokenSchema,bodySource),r=object(await call('create_document_template_version_v1',{p_workspace_id:workspaceId,p_request_id:crypto.randomUUID(),p_template_id:templateId,p_body_source:bodySource,p_token_schema:schema},true));return parseTemplateVersion(r)},
  async publishTemplateVersion(workspaceId:string,versionId:string){ensureId(workspaceId,'workspace id');ensureId(versionId,'template version id');await call('publish_document_template_version_v1',{p_workspace_id:workspaceId,p_version_id:versionId},true)},
  async listDrafts(workspaceId:string,companyId:string|null=null,limit=30){ensureId(workspaceId,'workspace id');if(companyId)ensureId(companyId,'company id');if(!Number.isSafeInteger(limit)||limit<1||limit>100)throw new DataAccessError('Invalid draft limit','DATA_VALIDATION_FAILED');try{let q=client.from('document_drafts').select('id,title,status,compiled_content,fact_snapshot,provenance,template_version_id,company_id,transaction_id,approved_at,approval_note,final_document_id,final_document_version_id,updated_at').eq('workspace_id',workspaceId).order('updated_at',{ascending:false}).limit(limit);if(companyId)q=q.eq('company_id',companyId);const r=await q;if(r.error)throw normalizeDataFailure(r.error as DataFailureLike);return Object.freeze(array(r.data??[],'drafts').map(parseDraft))}catch(e){if(e instanceof DataAccessError)throw e;throw normalizeThrownDataFailure(e,'read')}},
  async generate(input:DocumentFactoryGenerationInput){const v=validateDocumentFactoryGenerationInput(input),r=object(await call('generate_document_draft_v1',{p_workspace_id:v.workspaceId,p_request_id:crypto.randomUUID(),p_template_version_id:v.templateVersionId,p_title:v.title,p_company_id:v.companyId,p_transaction_id:v.transactionId,p_contact_id:v.contactId,p_ocr_analysis_id:v.ocrAnalysisId},true));return fetchDraft(v.workspaceId,ensureId(r.draftId,'draft id'))},
  async review(workspaceId:string,draftId:string,decision:'approve'|'return',note:string|null=null){ensureId(workspaceId,'workspace id');ensureId(draftId,'draft id');const v=validateDocumentFactoryReview(decision,note);await call('review_document_draft_v1',{p_workspace_id:workspaceId,p_draft_id:draftId,p_decision:v.decision,p_note:v.note},true);return fetchDraft(workspaceId,draftId)},
  async renderAndFinalize(workspaceId:string,draftId:string){validateDocumentFactoryFinalization({workspaceId,draftId,renderJobId:crypto.randomUUID()});const session=(await client.auth.getSession()).data.session;if(!session?.user?.id)throw new DataAccessError('Authentication required','DATA_FORBIDDEN');let jobId:string|null=null;try{const existing=await client.from('pdf_jobs').select('id,status,created_at').eq('workspace_id',workspaceId).eq('source_draft_id',draftId).eq('requested_by',session.user.id).in('status',['queued','running','succeeded']).order('created_at',{ascending:false}).limit(1);if(existing.error)throw normalizeDataFailure(existing.error as DataFailureLike);const row=array(existing.data??[],'render jobs')[0];if(row)jobId=ensureId(row.id,'render job id');if(!jobId){const requested=object(await call('request_document_render_v1',{p_workspace_id:workspaceId,p_request_id:crypto.randomUUID(),p_draft_id:draftId},true));jobId=ensureId(requested.jobId,'render job id')}const rendered=object(await edge({workspaceId,jobId}));if(rendered.ok!==true||rendered.status!=='succeeded')throw new DataAccessError('Document render did not complete','DATA_OPERATION_FAILED');const final=object(await call('finalize_document_draft_v1',{p_workspace_id:workspaceId,p_draft_id:draftId,p_render_job_id:jobId},true));return Object.freeze({draftId:ensureId(final.draftId,'draft id'),renderJobId:ensureId(final.renderJobId,'render job id'),documentId:ensureId(final.documentId,'document id'),documentVersionId:ensureId(final.documentVersionId,'document version id'),wasDuplicate:final.wasDuplicate===true})}catch(e){if(e instanceof DataAccessError)throw e;throw normalizeThrownDataFailure(e,'write')}},
  async listSubmissionPacks(workspaceId:string,transactionId:string|null=null){ensureId(workspaceId,'workspace id');if(transactionId)ensureId(transactionId,'transaction id');const rows=await call('list_document_submission_packs_v1',{p_workspace_id:workspaceId,p_transaction_id:transactionId});return Object.freeze(array(rows??[],'submission packs').map(parsePack))},
  async buildSubmissionPack(workspaceId:string,transactionId:string,title:string,draftIds:readonly string[]){ensureId(workspaceId,'workspace id');ensureId(transactionId,'transaction id');const normalizedTitle=title.trim();if(!normalizedTitle||normalizedTitle.length>320||draftIds.length<2||draftIds.length>20)throw new DataAccessError('Invalid submission pack request','DATA_VALIDATION_FAILED');const ids=draftIds.map((id,index)=>ensureId(id,`draft id ${index+1}`));if(new Set(ids).size!==ids.length)throw new DataAccessError('Submission pack contains duplicate documents','DATA_VALIDATION_FAILED');const requested=object(await call('request_document_submission_pack_v1',{p_workspace_id:workspaceId,p_request_id:crypto.randomUUID(),p_transaction_id:transactionId,p_title:normalizedTitle,p_draft_ids:ids},true)),packId=ensureId(requested.packId,'submission pack id');const rendered=object(await edge({mode:'pack',workspaceId,packId}));if(rendered.ok!==true||rendered.status!=='succeeded')throw new DataAccessError('Submission pack render did not complete','DATA_OPERATION_FAILED');const final=object(await call('get_document_submission_pack_v1',{p_workspace_id:workspaceId,p_pack_id:packId}));return parsePack({...final,itemCount:Array.isArray(final.items)?final.items.length:ids.length})}
 })
}
