import { useEffect,useMemo,useRef,useState } from 'react';
import type { RegulatorySourceKind,RegulatorySourceScope } from '../../features/regulatory/regulatoryKnowledgeContract.ts';
import type { RegulatoryKnowledgeEntry,RegulatoryKnowledgeGateway,RegulatoryKnowledgeSearchItem } from '../../features/regulatory/regulatoryKnowledgeCommands.ts';
import { REGULATORY_FILTER_KINDS,REGULATORY_FILTER_SCOPES,REGULATORY_KIND_LABELS,REGULATORY_SCOPE_LABELS,derivedKindLabel,formatRegulatoryDate,shortHash } from './regulatoryKnowledgeViewModel.ts';
import './regulatory-knowledge.css';

type Status='loading'|'ready'|'error';
type Props=Readonly<{gateway:RegulatoryKnowledgeGateway;workspace:Promise<string|null>}>;

function AuthorityBadge({scope}:{scope:RegulatorySourceScope}){return <span className={`rk-authority rk-authority--${scope==='official_global'?'official':'curated'}`}>{REGULATORY_SCOPE_LABELS[scope]}</span>}
function EmptyState({query}:{query:string}){return <section className="rk-empty" data-regulatory-empty="true"><div className="rk-empty__mark">⌕</div><h2>{query?'لا توجد نتائج مطابقة':'مركز المعرفة جاهز'}</h2><p>{query?'جرّب عبارة أوسع أو غيّر نوع المصدر.':'ستظهر هنا القوانين والأنظمة والتعليمات والإجراءات النافذة المسموح لمساحة العمل بقراءتها.'}</p></section>}
function ErrorState({message,retry}:{message:string;retry:()=>void}){return <section className="rk-empty rk-empty--error" role="alert"><div className="rk-empty__mark">!</div><h2>تعذر تحميل المعرفة التنظيمية</h2><p>{message}</p><button type="button" className="rk-button rk-button--primary" onClick={retry}>إعادة المحاولة</button></section>}

function ResultCard({item,active,onOpen}:{item:RegulatoryKnowledgeSearchItem;active:boolean;onOpen:()=>void}){return <button type="button" className={`rk-result${active?' is-active':''}`} onClick={onOpen} data-regulatory-source-scope={item.scope} data-regulatory-authoritative="true">
  <span className="rk-result__top"><AuthorityBadge scope={item.scope}/><span className="rk-kind">{REGULATORY_KIND_LABELS[item.kind]}</span></span>
  <strong>{item.titleAr}</strong><span className="rk-result__meta">{item.issuer} · {item.referenceCode}</span>
  <span className="rk-result__excerpt">{item.excerpt||'النص الرسمي متاح عند فتح المصدر.'}</span>
  <span className="rk-result__foot"><span>نافذ من {formatRegulatoryDate(item.effectiveFrom)}</span><span>الإصدار {item.revision}</span></span>
</button>}

function DetailPanel({entry,close}:{entry:RegulatoryKnowledgeEntry;close:()=>void}){const official=entry.official;if(!official)return <aside className="rk-detail" aria-label="تفاصيل المصدر"><button type="button" className="rk-detail__close" onClick={close} aria-label="إغلاق التفاصيل">×</button><EmptyState query=""/></aside>;
  return <aside className="rk-detail" aria-label="تفاصيل المصدر التنظيمي" data-regulatory-detail="authoritative">
    <div className="rk-detail__head"><div><div className="rk-detail__badges"><AuthorityBadge scope={official.scope}/><span className="rk-kind">{REGULATORY_KIND_LABELS[official.kind]}</span></div><h2>{official.titleAr}</h2><p>{official.issuer} · {official.referenceCode}</p></div><button type="button" className="rk-detail__close" onClick={close} aria-label="إغلاق التفاصيل">×</button></div>
    <section className="rk-provenance" aria-label="توثيق المصدر الرسمي"><div><span>الناشر</span><strong>{official.publisher}</strong></div><div><span>تاريخ النشر</span><strong>{formatRegulatoryDate(official.publicationDate)}</strong></div><div><span>النفاذ</span><strong>{formatRegulatoryDate(official.effectiveFrom)} ← {formatRegulatoryDate(official.effectiveTo)}</strong></div><div><span>آخر جلب</span><strong>{formatRegulatoryDate(official.retrievedOn)}</strong></div><div><span>بصمة المصدر</span><strong dir="ltr">{shortHash(official.sourceHash)}</strong></div><div><span>الإصدار</span><strong>{official.revision}</strong></div></section>
    <div className="rk-source-actions"><a className="rk-button rk-button--primary" href={official.sourceUrl} target="_blank" rel="noopener noreferrer">فتح المصدر الأصلي ↗</a><span>الموضع: {official.sourceLocator}</span></div>
    <section className="rk-official-text"><div className="rk-section-title"><div><span className="rk-kicker">النص المعتمد</span><h3>المصدر الرسمي</h3></div><span className="rk-truth-chip">حقيقة تنظيمية · Authoritative</span></div><p>{official.officialText}</p></section>
    <section className="rk-derived" data-regulatory-derived-authority="false"><div className="rk-section-title"><div><span className="rk-kicker">طبقة مساعدة</span><h3>التفسير والملخصات</h3></div><span className="rk-non-authority-chip">ليست مصدرًا رسميًا</span></div>{entry.derivedArtifacts.length?entry.derivedArtifacts.map(artifact=><article key={artifact.artifactId} className="rk-derived-card" data-authoritative="false"><strong>{derivedKindLabel(artifact.kind)}</strong><p>{artifact.body}</p><small>مرتبط حصراً بالإصدار {official.revision} من هذا المصدر.</small></article>):<p className="rk-muted">لا توجد تفسيرات أو ملخصات مرتبطة بهذا الإصدار. النص الرسمي أعلاه يبقى المرجع الوحيد المعتمد.</p>}</section>
  </aside>}

export function RegulatoryKnowledgeCenter({gateway,workspace}:Props){
  const [workspaceId,setWorkspaceId]=useState<string|null>(null),[status,setStatus]=useState<Status>('loading'),[error,setError]=useState(''),[query,setQuery]=useState(''),[kind,setKind]=useState<RegulatorySourceKind|null>(null),[scope,setScope]=useState<RegulatorySourceScope|null>(null),[items,setItems]=useState<readonly RegulatoryKnowledgeSearchItem[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[entry,setEntry]=useState<RegulatoryKnowledgeEntry|null>(null),[detailStatus,setDetailStatus]=useState<Status>('ready'),[reloadToken,setReloadToken]=useState(0);const searchSeq=useRef(0),detailSeq=useRef(0);
  useEffect(()=>{let live=true;setStatus('loading');void workspace.then(id=>{if(!live)return;if(!id){setError('لا توجد مساحة عمل مرتبطة بالحساب الحالي.');setStatus('error');return}setWorkspaceId(id)}).catch(()=>{if(live){setError('تعذر تحديد مساحة العمل الحالية.');setStatus('error')}});return()=>{live=false}},[workspace]);
  useEffect(()=>{if(!workspaceId)return;const seq=++searchSeq.current;setStatus('loading');const timer=window.setTimeout(()=>{void gateway.search({workspaceId,query,kind,scope,limit:30}).then(rows=>{if(seq!==searchSeq.current)return;setItems(rows);setStatus('ready');setError('');if(selectedId&&!rows.some(row=>row.sourceId===selectedId)){setSelectedId(null);setEntry(null)}}).catch(cause=>{if(seq!==searchSeq.current)return;setError(cause instanceof Error?cause.message:'تعذر تنفيذ البحث.');setStatus('error')})},query?220:0);return()=>window.clearTimeout(timer)},[gateway,workspaceId,query,kind,scope,reloadToken]);
  useEffect(()=>{if(!workspaceId||!selectedId){setEntry(null);return}const seq=++detailSeq.current;setDetailStatus('loading');void gateway.getEntry({workspaceId,sourceId:selectedId}).then(value=>{if(seq!==detailSeq.current)return;setEntry(value);setDetailStatus('ready')}).catch(cause=>{if(seq!==detailSeq.current)return;setError(cause instanceof Error?cause.message:'تعذر فتح المصدر.');setDetailStatus('error')})},[gateway,workspaceId,selectedId]);
  const counts=useMemo(()=>({official:items.filter(x=>x.scope==='official_global').length,curated:items.filter(x=>x.scope==='workspace_curated').length}),[items]);
  const retry=()=>setReloadToken(value=>value+1);
  return <section className="rk-center" dir="rtl" data-phase9-4-runtime="knowledge-center" data-regulatory-browser-dml="rpc-only">
    <header className="rk-hero"><div className="rk-hero__copy"><span className="rk-kicker">M8 · Regulatory Intelligence</span><h1>مركز المعرفة التنظيمية</h1><p>وصول موثّق إلى القوانين والأنظمة والتعليمات والإجراءات، مع فصل صارم بين <strong>النص الرسمي</strong> وبين التفسير أو الملخص المساعد.</p></div><div className="rk-hero__stats"><div><span>{counts.official}</span><small>مصادر رسمية ظاهرة</small></div><div><span>{counts.curated}</span><small>معرفة داخلية موثقة</small></div><div><span>100%</span><small>مرتبطة بالمصدر والإصدار</small></div></div></header>
    <div className="rk-toolbar"><label className="rk-search"><span aria-hidden="true">⌕</span><input value={query} maxLength={160} onChange={event=>setQuery(event.target.value)} placeholder="ابحث في قانون، تعليمات، تعميم، جهة إصدار أو رقم مرجعي…" aria-label="البحث في المعرفة التنظيمية"/>{query?<button type="button" onClick={()=>setQuery('')} aria-label="مسح البحث">×</button>:null}</label><div className="rk-filter-row" aria-label="تصفية نوع المصدر">{REGULATORY_FILTER_KINDS.map(value=><button key={value??'all'} type="button" className={kind===value?'is-active':''} aria-pressed={kind===value} onClick={()=>setKind(value)}>{value===null?'الكل':REGULATORY_KIND_LABELS[value]}</button>)}</div><div className="rk-scope-row" aria-label="تصفية سلطة المصدر">{REGULATORY_FILTER_SCOPES.map(value=><button key={value??'all'} type="button" className={scope===value?'is-active':''} aria-pressed={scope===value} onClick={()=>setScope(value)}>{value===null?'كل المصادر':REGULATORY_SCOPE_LABELS[value]}</button>)}</div></div>
    <div className="rk-layout"><main className="rk-results" aria-live="polite"><div className="rk-results__heading"><div><span className="rk-kicker">النتائج النافذة اليوم</span><h2>{status==='loading'?'جارٍ التحقق من المصادر…':`${items.length} نتيجة`}</h2></div><span className="rk-integrity">قراءة RPC · RLS · fail-closed</span></div>{status==='loading'?<div className="rk-skeletons" aria-label="جارٍ التحميل">{[0,1,2,3].map(i=><div className="rk-skeleton" key={i}/>)}</div>:status==='error'?<ErrorState message={error} retry={retry}/>:items.length?<div className="rk-result-grid">{items.map(item=><ResultCard key={`${item.sourceId}:${item.versionId}`} item={item} active={selectedId===item.sourceId} onOpen={()=>setSelectedId(item.sourceId)}/>)}</div>:<EmptyState query={query}/>}</main>{selectedId?<div className="rk-detail-wrap"><button type="button" className="rk-detail-backdrop" onClick={()=>setSelectedId(null)} aria-label="إغلاق التفاصيل"/>{detailStatus==='loading'?<aside className="rk-detail rk-detail--loading"><div className="rk-skeleton rk-skeleton--detail"/></aside>:detailStatus==='error'?<aside className="rk-detail"><ErrorState message={error} retry={()=>setSelectedId(selectedId)}/></aside>:entry?<DetailPanel entry={entry} close={()=>setSelectedId(null)}/>:null}</div>:null}</div>
  </section>}
