import assert from 'node:assert/strict';
import test from 'node:test';
import {normalizeAzureDocumentIntelligenceEndpoint,parseAzureReadResult,runAzureDocumentIntelligenceRead,type AzureFetch} from '../supabase/functions/enjaz-document-intelligence/azure-provider.ts';

const operation='https://example.cognitiveservices.azure.com/documentintelligence/documentModels/prebuilt-read/analyzeResults/11111111-1111-4111-8111-111111111111?api-version=2024-11-30';
const result={status:'succeeded',analyzeResult:{content:'شركة إنجاز\nرأس المال 100000000',pages:[{pageNumber:1,words:[{content:'شركة',confidence:.96},{content:'إنجاز',confidence:.94},{content:'رأس',confidence:.9},{content:'المال',confidence:.92},{content:'100000000',confidence:.98}]}]}};

test('normalizes Azure Document Intelligence HTTPS endpoint',()=>assert.equal(normalizeAzureDocumentIntelligenceEndpoint('https://example.cognitiveservices.azure.com/').toString(),'https://example.cognitiveservices.azure.com/'));
test('rejects non-HTTPS Azure endpoint',()=>assert.throws(()=>normalizeAzureDocumentIntelligenceEndpoint('http://example.test')));
test('parses Azure Read pages with conservative confidence and no invented fields',()=>{const r=parseAzureReadResult(result,operation);assert.equal(r.text,'شركة إنجاز\nرأس المال 100000000');assert.equal(r.pages[0]?.pageNumber,1);assert.equal(r.pages[0]?.text,'شركة إنجاز رأس المال 100000000');assert.ok((r.pages[0]?.confidence??0)>.9);assert.deepEqual(r.pages[0]?.fields,[]);assert.deepEqual(r.extracted,{});assert.equal(r.classification,null);assert.equal(r.runId,'11111111-1111-4111-8111-111111111111')});
test('rejects duplicate or invalid Azure pages',()=>assert.throws(()=>parseAzureReadResult({status:'succeeded',analyzeResult:{content:'x',pages:[{pageNumber:1,words:[]},{pageNumber:1,words:[]}]}})));
test('rejects non-succeeded Azure result',()=>assert.throws(()=>parseAzureReadResult({status:'failed',analyzeResult:{content:'',pages:[]}})));
test('Azure adapter submits urlSource, polls same origin, and returns governed result',async()=>{const calls:Array<{url:string;init?:RequestInit}>=[];let poll=0;const fetcher:AzureFetch=async(input,init)=>{const url=String(input);calls.push({url,init});if(init?.method==='POST')return new Response(null,{status:202,headers:{'operation-location':operation,'retry-after':'0'}});poll++;return new Response(JSON.stringify(poll===1?{status:'running'}:result),{status:200,headers:{'content-type':'application/json','retry-after':'0'}})};const r=await runAzureDocumentIntelligenceRead({endpoint:'https://example.cognitiveservices.azure.com',key:'server-key',sourceUrl:'https://storage.example.com/signed.pdf',timeoutMs:5000,fetcher});assert.equal(r.pages.length,1);assert.equal(calls.length,3);const body=JSON.parse(String(calls[0]?.init?.body));assert.equal(body.urlSource,'https://storage.example.com/signed.pdf');assert.equal((calls[0]?.init?.headers as Record<string,string>)['Ocp-Apim-Subscription-Key'],'server-key')});
test('Azure adapter rejects cross-origin operation location',async()=>{const fetcher:AzureFetch=async()=>new Response(null,{status:202,headers:{'operation-location':'https://evil.example/analyzeResults/x'}});await assert.rejects(()=>runAzureDocumentIntelligenceRead({endpoint:'https://example.cognitiveservices.azure.com',key:'server-key',sourceUrl:'https://storage.example.com/signed.pdf',fetcher}),/ORIGIN_MISMATCH/)});
