import assert from 'node:assert/strict';
import test from 'node:test';
import type { EnjazDataLayerFactory, EnjazWorkspaceDataLayer } from '../src/data/createDataLayer.ts';
import type { ListRequest, RowOf } from '../src/data/contracts/dataTypes.ts';
import { createContactDraft, updateContactDraft } from '../src/features/contacts/contactModel.ts';
import { ContactDomainError, addCompanyContactRelationship, assignTransactionPrimaryContact, loadContactListSource, saveContact } from '../src/features/contacts/contactService.ts';

const W='11111111-1111-4111-8111-111111111111', U='44444444-4444-4444-8444-444444444444', C='22222222-2222-4222-8222-222222222222', CO='33333333-3333-4333-8333-333333333333', TX='55555555-5555-4555-8555-555555555555';
const contact=(patch:Partial<RowOf<'contacts'>>={}):RowOf<'contacts'>=>({id:C,workspace_id:W,display_name:'نور حسين',contact_type:'محامية',phone:null,email:null,notes:null,status:'active',merged_into_id:null,legacy_id:null,legacy_source:null,created_at:'2026-09-01T08:00:00.000Z',updated_at:'2026-09-06T08:00:00.000Z',deleted_at:null,...patch});
const company=():RowOf<'companies'>=>({id:CO,workspace_id:W,legal_name:'شركة الاختبار',display_name:null,capital:null,address:null,activities:null,registration_number:null,legal_status:null,primary_contact_id:null,status:'active',merged_into_id:null,legacy_id:null,legacy_source:null,created_at:'2026-09-01T08:00:00.000Z',updated_at:'2026-09-06T08:00:00.000Z',deleted_at:null});
const transaction=(patch:Partial<RowOf<'transactions'>>={}):RowOf<'transactions'>=>({id:TX,workspace_id:W,company_id:CO,primary_contact_id:null,type:'تأسيس',department:null,status:'active',priority:'normal',current_fee:1000,created_at:'2026-09-01T08:00:00.000Z',updated_at:'2026-09-06T08:00:00.000Z',last_activity_at:'2026-09-06T08:00:00.000Z',completed_at:null,archived_at:null,deleted_at:null,deleted_by:null,deletion_reason:null,legacy_id:null,legacy_source:null,...patch});
const relation=(patch:Partial<RowOf<'company_contacts'>>={}):RowOf<'company_contacts'>=>({id:'66666666-6666-4666-8666-666666666666',workspace_id:W,company_id:CO,contact_id:C,relation_type:'محامية',valid_from:null,valid_to:null,created_at:'2026-09-06T08:00:00.000Z',...patch});
const factory=(layer:EnjazWorkspaceDataLayer):EnjazDataLayerFactory=>({async resolveWorkspaceId(){return W},forWorkspace(){return layer}});
const isCode=(code:string)=>(error:unknown)=>error instanceof ContactDomainError&&error.code===code;

test('contact source fails closed above the 5000-row safety ceiling',async()=>{const rows=Array.from({length:5001},(_,i)=>contact({id:`c-${i}`}));const layer={contacts:{async list(r:ListRequest<'contacts'>={}){const o=r.offset??0,l=r.limit??100,items=rows.slice(o,o+l);return{items,offset:o,limit:l,total:rows.length,hasMore:o+items.length<rows.length}}}}as unknown as EnjazWorkspaceDataLayer;await assert.rejects(()=>loadContactListSource(factory(layer),U),isCode('capacity'));});

test('contact create retry is idempotent and payload drift is rejected',async()=>{const id='77777777-7777-4777-8777-777777777777';let existing:RowOf<'contacts'>|null=null,count=0;const layer={contacts:{async getById(){return existing},async create(values:Omit<RowOf<'contacts'>,'workspace_id'|'created_at'|'updated_at'>){count++;existing=contact({...values,id});return existing}}}as unknown as EnjazWorkspaceDataLayer;let draft=createContactDraft();draft=updateContactDraft(draft,'displayName','نور حسين');draft=updateContactDraft(draft,'contactType','محامية');await saveContact(factory(layer),U,'create',draft,{createOperationId:id});await saveContact(factory(layer),U,'create',draft,{createOperationId:id});assert.equal(count,1);await assert.rejects(()=>saveContact(factory(layer),U,'create',updateContactDraft(draft,'displayName','مختلف'),{createOperationId:id}),isCode('conflict'));});

test('contact edit rejects stale updated_at',async()=>{const layer={contacts:{async getById(){return contact({updated_at:'new'})},async update(){throw new Error('must not update')}}}as unknown as EnjazWorkspaceDataLayer;await assert.rejects(()=>saveContact(factory(layer),U,'edit',createContactDraft(contact()),{contactId:C,expectedUpdatedAt:'old'}),isCode('conflict'));});

test('company-contact relationship is idempotent by operation id and semantic current relation',async()=>{let saved:RowOf<'company_contacts'>|null=null,createCount=0;const layer={companies:{async getById(){return company()}},contacts:{async getById(){return contact()}},companyContacts:{async getById(id:string){return saved?.id===id?saved:null},async list(){return{items:saved?[saved]:[],offset:0,limit:100,total:saved?1:0,hasMore:false}},async create(values:Omit<RowOf<'company_contacts'>,'workspace_id'|'created_at'>){createCount++;saved=relation(values);return saved}}}as unknown as EnjazWorkspaceDataLayer;const first=await addCompanyContactRelationship(factory(layer),U,{relationOperationId:relation().id,companyId:CO,contactId:C,relationType:'محامية'});const replay=await addCompanyContactRelationship(factory(layer),U,{relationOperationId:'88888888-8888-4888-8888-888888888888',companyId:CO,contactId:C,relationType:'محامية'});assert.equal(first.id,replay.id);assert.equal(createCount,1);});

test('company-contact relationship rejects inactive contacts',async()=>{const layer={companies:{async getById(){return company()}},contacts:{async getById(){return contact({status:'inactive'})}},companyContacts:{async getById(){return null},async list(){return{items:[],offset:0,limit:100,total:0,hasMore:false}}}}as unknown as EnjazWorkspaceDataLayer;await assert.rejects(()=>addCompanyContactRelationship(factory(layer),U,{relationOperationId:relation().id,companyId:CO,contactId:C,relationType:'محامية'}),isCode('relation'));});

test('transaction primary contact requires a current same-company relationship and rejects stale writes',async()=>{let updated:string|null=null;const layer={transactions:{async getById(){return transaction()},async update(_id:string,values:Partial<RowOf<'transactions'>>){updated=values.primary_contact_id??null;return transaction({primary_contact_id:updated})}},contacts:{async getById(){return contact()}},companyContacts:{async list(){return{items:[relation()],offset:0,limit:100,total:1,hasMore:false}}}}as unknown as EnjazWorkspaceDataLayer;const saved=await assignTransactionPrimaryContact(factory(layer),U,{transactionId:TX,contactId:C,expectedUpdatedAt:transaction().updated_at});assert.equal(saved.primary_contact_id,C);assert.equal(updated,C);await assert.rejects(()=>assignTransactionPrimaryContact(factory(layer),U,{transactionId:TX,contactId:C,expectedUpdatedAt:'stale'}),isCode('conflict'));});
