import test from 'node:test';
import assert from 'node:assert/strict';
import { DataAccessError } from '../src/data/contracts/DataAccessError.ts';
import { createCrmIntakeGateway } from '../src/features/crm-intake/crmIntakeCommands.ts';

const W='11111111-1111-4111-8111-111111111111',S='22222222-2222-4222-8222-222222222222',L='33333333-3333-4333-8333-333333333333',Q='44444444-4444-4444-8444-444444444444',F='55555555-5555-4555-8555-555555555555',SUB='66666666-6666-4666-8666-666666666666';
const TOKEN='a'.repeat(64);
function client(handler:(name:string,args:Readonly<Record<string,unknown>>)=>unknown){return {rpc(name:string,args:Readonly<Record<string,unknown>>){return Promise.resolve({data:handler(name,args),error:null})}} as never}
const context={authority:'crm_pre_transaction_and_reviewed_intake',externalSubmissionAuthority:'non_authoritative',companyWriteAuthority:'guarded_conversion_rpc_only',transactionWriteAuthority:'guarded_conversion_rpc_only',financeLedgerWriteAuthority:'none',services:[{id:S,code:'REG',name:'تسجيل شركة',description:null,basePrice:250000,expectedDurationDays:7,requiredInputs:[],active:true}],leads:[{id:L,displayName:'أحمد',organizationName:'شركة جديدة',phone:'07700000000',email:'a@example.com',source:'referral',stage:'qualified',lostReason:null,version:2,convertedCompanyId:null,convertedTransactionId:null}],serviceRequests:[],quotations:[{id:Q,leadId:L,serviceRequestId:null,status:'pending_approval',currency:'IQD',subtotal:100000,discountPercent:15,discountAmount:15000,total:85000,validUntil:'2026-09-30',approvalRequired:true,version:1}],reviewQueue:[{id:SUB,formId:F,formTitle:'طلب خدمة',status:'submitted',submittedAt:'2026-09-08T10:00:00Z',version:1,fileCount:0,pendingUploadCount:0}],forms:[{id:F,name:'طلب',publicTitle:'طلب خدمة',active:true,version:1,fieldCount:3}]};

test('context rejects any drift that gives CRM direct finance or unguarded core write authority',async()=>{const g=createCrmIntakeGateway(client(()=>context));const c=await g.loadContext(W);assert.equal(c.externalSubmissionAuthority,'non_authoritative');assert.equal(c.financeLedgerWriteAuthority,'none');assert.equal(c.quotations[0]?.approvalRequired,true);for(const patch of [{financeLedgerWriteAuthority:'direct'},{companyWriteAuthority:'direct_table'},{externalSubmissionAuthority:'authoritative'}]){const bad=createCrmIntakeGateway(client(()=>({...context,...patch})));await assert.rejects(()=>bad.loadContext(W),(e:unknown)=>e instanceof DataAccessError)}});

test('secure link token is accepted only as exact 64-hex bearer value and never synthesized by client',async()=>{let args:Readonly<Record<string,unknown>>={};const g=createCrmIntakeGateway(client((name,a)=>{assert.equal(name,'issue_intake_link_v1');args=a;return {linkId:SUB,token:TOKEN,expiresAt:'2026-09-09T10:00:00Z'}}));const r=await g.issueIntakeLink(W,F,L,24);assert.equal(r.token,TOKEN);assert.equal(args['p_expires_in_hours'],24);assert.equal(Object.values(args).includes(TOKEN),false);await assert.rejects(()=>g.getPublicIntake('raw-token'),(e:unknown)=>e instanceof DataAccessError&&e.dataCode==='DATA_VALIDATION_FAILED')});

test('public intake parser refuses any response claiming authoritative external submission',async()=>{const form={publicAuthority:'non_authoritative',form:{title:'طلب خدمة',description:null,fields:[{key:'name',label:'الاسم',type:'text',required:true,config:{}}]},expiresAt:'2026-09-09T10:00:00Z',submission:null};const g=createCrmIntakeGateway(client(()=>form));assert.equal((await g.getPublicIntake(TOKEN)).publicAuthority,'non_authoritative');const bad=createCrmIntakeGateway(client(()=>({...form,publicAuthority:'authoritative'})));await assert.rejects(()=>bad.getPublicIntake(TOKEN),(e:unknown)=>e instanceof DataAccessError)});

test('public save validates file size before network and requires server result authoritative=false',async()=>{let calls=0;const g=createCrmIntakeGateway(client((name,args)=>{calls++;assert.equal(name,'save_public_intake_v1');assert.equal(args['p_token'],TOKEN);return {submissionId:SUB,status:'draft',version:1,authoritative:false,pendingUploadCount:1}}));const r=await g.savePublicIntake(TOKEN,{name:'أحمد'},[{fieldKey:'id_doc',fileName:'id.pdf',mimeType:'application/pdf',byteSize:2048}],false);assert.equal(r.authoritative,false);assert.equal(r.pendingUploadCount,1);await assert.rejects(()=>g.savePublicIntake(TOKEN,{name:'أحمد'},[{fieldKey:'id_doc',fileName:'huge.pdf',mimeType:'application/pdf',byteSize:60*1024*1024}],false),(e:unknown)=>e instanceof DataAccessError&&e.dataCode==='DATA_VALIDATION_FAILED');assert.equal(calls,1);const drift=createCrmIntakeGateway(client(()=>({submissionId:SUB,status:'submitted',version:2,authoritative:true,pendingUploadCount:0})));await assert.rejects(()=>drift.savePublicIntake(TOKEN,{name:'أحمد'},[],true),(e:unknown)=>e instanceof DataAccessError)});

test('quotation discount above policy threshold remains an explicit server approval state',async()=>{let captured:Readonly<Record<string,unknown>>={};const g=createCrmIntakeGateway(client((name,args)=>{assert.equal(name,'create_crm_quotation_v1');captured=args;return {id:Q,status:'pending_approval',subtotal:100000,total:85000,discountPercent:15,approvalRequired:true,version:1}}));const result=await g.createQuotation({workspaceId:W,leadId:L,serviceRequestId:null,currency:'IQD',discountPercent:15,validUntil:'2026-09-30',items:[{serviceId:S,description:'تسجيل شركة',quantity:1,unitPrice:100000}]});assert.equal(result['approvalRequired'],true);assert.equal(captured['p_discount_percent'],15);await assert.rejects(()=>g.createQuotation({workspaceId:W,leadId:L,serviceRequestId:null,currency:'IQD',discountPercent:31,validUntil:null,items:[{serviceId:null,description:'x',quantity:1,unitPrice:1}]}),(e:unknown)=>e instanceof DataAccessError)});

test('review approval requires explicit field mapping and never claims core records were created',async()=>{let calls=0;const g=createCrmIntakeGateway(client((name)=>{calls++;assert.equal(name,'review_intake_submission_v1');return {submissionId:SUB,status:'approved',version:2,leadId:L,authoritativeCoreCreated:false}}));await assert.rejects(()=>g.reviewSubmission({workspaceId:W,submissionId:SUB,expectedVersion:1,decision:'approve',mapping:{},note:null}),(e:unknown)=>e instanceof DataAccessError);assert.equal(calls,0);const r=await g.reviewSubmission({workspaceId:W,submissionId:SUB,expectedVersion:1,decision:'approve',mapping:{displayName:'name'},note:null});assert.equal(r['authoritativeCoreCreated'],false);assert.equal(calls,1)});

test('conversion is a single guarded RPC and supports explicit company reuse rather than client-side core writes',async()=>{let args:Readonly<Record<string,unknown>>={};const g=createCrmIntakeGateway(client((name,a)=>{assert.equal(name,'convert_crm_lead_v1');args=a;return {leadId:L,companyId:S,contactId:null,transactionId:Q,wasDuplicate:false}}));const r=await g.convertLead({workspaceId:W,leadId:L,reuseCompanyId:S,transactionType:'تسجيل شركة',department:'مسجل الشركات'});assert.equal(args['p_reuse_company_id'],S);assert.equal(r['wasDuplicate'],false)});
