import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {assertTemplateVersionTransition,isOfficialDraftFinalizable,validateDocumentFactoryDraftContent,validateDocumentFactoryFinalization,validateDocumentFactoryGenerationInput,validateDocumentFactoryReview,validateFactoryTokenSchema,validateOfficialGenerationProvenance,validateTemplateVersionInput} from '../src/features/documents/documentFactoryContract.ts';

const W='11111111-1111-4111-8111-111111111111',T='22222222-2222-4222-8222-222222222222',V='33333333-3333-4333-8333-333333333333',D='44444444-4444-4444-8444-444444444444';
const SCHEMA={recipient:{source:'company',field:'legal_name',required:true},capital:{source:'company',field:'capital',required:false}};

test('accepts bounded immutable template-version input with governed fact tokens',()=>assert.doesNotThrow(()=>validateTemplateVersionInput({workspaceId:W,templateId:T,bodySource:'إلى / {{recipient}}\nرأس المال / {{capital}}',tokenSchema:SCHEMA})));
test('rejects empty or oversized template bodies',()=>{assert.throws(()=>validateTemplateVersionInput({workspaceId:W,templateId:T,bodySource:'',tokenSchema:{}}));assert.throws(()=>validateTemplateVersionInput({workspaceId:W,templateId:T,bodySource:'x'.repeat(1_000_001),tokenSchema:{}}))});
test('rejects undeclared, malformed and unsupported authoritative tokens',()=>{assert.throws(()=>validateFactoryTokenSchema(SCHEMA,'{{missing}}'));assert.throws(()=>validateFactoryTokenSchema(SCHEMA,'{{ recipient }}'));assert.throws(()=>validateFactoryTokenSchema({bad:{source:'company',field:'password'}},'{{bad}}'));assert.throws(()=>validateFactoryTokenSchema({bad:{source:'browser',field:'value'}},'{{bad}}'))});
test('accepts bounded server-resolved generation input and rejects invalid ids',()=>{assert.doesNotThrow(()=>validateDocumentFactoryGenerationInput({workspaceId:W,templateVersionId:V,title:'كتاب رسمي',companyId:D}));assert.throws(()=>validateDocumentFactoryGenerationInput({workspaceId:'bad',templateVersionId:V,title:'كتاب رسمي'}))});
test('governed draft edit review and finalization inputs stay bounded',()=>{assert.equal(validateDocumentFactoryDraftContent('نص رسمي'),'نص رسمي');assert.throws(()=>validateDocumentFactoryDraftContent(''));assert.deepEqual(validateDocumentFactoryReview('approve',' موافق '),{decision:'approve',note:'موافق'});assert.throws(()=>validateDocumentFactoryReview('force',null));assert.doesNotThrow(()=>validateDocumentFactoryFinalization({workspaceId:W,draftId:T,documentId:D,documentVersionId:V}))});
test('template versions may publish but published versions cannot return to draft',()=>{assert.doesNotThrow(()=>assertTemplateVersionTransition('draft','published'));assert.throws(()=>assertTemplateVersionTransition('published','draft'))});
test('official generation accepts verified current OCR provenance',()=>assert.doesNotThrow(()=>validateOfficialGenerationProvenance({templateVersionId:V,factSnapshot:{companyName:'إنجاز'},sources:[{kind:'ocr',entityId:D,sourceVersionId:V,verificationState:'verified',stale:false}]})));
test('official generation rejects unverified OCR',()=>assert.throws(()=>validateOfficialGenerationProvenance({templateVersionId:V,factSnapshot:{},sources:[{kind:'ocr',entityId:D,verificationState:'reviewed',stale:false}]})));
test('official generation rejects stale verified OCR',()=>assert.throws(()=>validateOfficialGenerationProvenance({templateVersionId:V,factSnapshot:{},sources:[{kind:'ocr',entityId:D,verificationState:'verified',stale:true}]})));
test('final artifacts require template version, approval and exact output document version',()=>{assert.equal(isOfficialDraftFinalizable({status:'final',templateVersionId:V,approvedAt:'2026-09-14T00:00:00Z',finalDocumentId:D,finalDocumentVersionId:V}),true);assert.equal(isOfficialDraftFinalizable({status:'final',templateVersionId:V,approvedAt:null,finalDocumentId:D,finalDocumentVersionId:V}),false);assert.equal(isOfficialDraftFinalizable({status:'approved',templateVersionId:V,approvedAt:'2026-09-14T00:00:00Z',finalDocumentId:D,finalDocumentVersionId:V}),false)});
test('Phase 10.3 authority migration keeps immutable template versions and final drafts',()=>{const sql=readFileSync(new URL('../database/migrations/phase_10_3_document_factory_authority.sql',import.meta.url),'utf8');for(const marker of ['create table public.document_template_versions','revoke all on table public.document_template_versions from public,anon,authenticated','document_template_versions_immutable_v1','template_version_id uuid','fact_snapshot jsonb','provenance jsonb','final_document_version_id uuid','require_document_factory_owner_v1','create_document_template_version_v1','publish_document_template_version_v1'])assert.ok(sql.toLowerCase().includes(marker.toLowerCase()),`missing ${marker}`);assert.ok(!/grant\s+(insert|update|delete)[\s\S]{0,120}document_template_versions[\s\S]{0,80}authenticated/i.test(sql),'template version direct mutation must stay closed')});
test('authority hardening prevents draft approval/finalization smuggling',()=>{const sql=readFileSync(new URL('../database/migrations/phase_10_3_document_factory_authority_hardening.sql',import.meta.url),'utf8');for(const marker of ['document_drafts_draft_authority_fields_check','approved_by is null','approved_at is null','finalized_by is null','finalized_at is null','final_document_id is null','final_document_version_id is null'])assert.ok(sql.toLowerCase().includes(marker.toLowerCase()),`missing hardening ${marker}`)});
test('governed runtime closes browser table writes and resolves facts server-side',()=>{const sql=readFileSync(new URL('../database/migrations/phase_10_3_document_factory_runtime.sql',import.meta.url),'utf8');for(const marker of ['validate_document_factory_template_v1','save_document_template_v1','drop policy if exists document_templates_insert_workspace','revoke insert,update,delete on table public.document_templates','drop policy if exists document_drafts_direct_insert_workspace','revoke insert,update,delete on table public.document_drafts','generate_document_draft_v1','private.require_document_factory_member_v1','select * into v_company from public.companies','select * into v_tx from public.transactions','select * into v_contact from public.contacts','select * into v_analysis from public.document_analysis','ENJAZ_DOCUMENT_FACTORY_OCR_NOT_VERIFIED','ENJAZ_DOCUMENT_FACTORY_OCR_STALE','fact_snapshot','provenance'])assert.ok(sql.toLowerCase().includes(marker.toLowerCase()),`missing runtime ${marker}`)});
test('runtime requires current provenance through review approval and exact Vault finalization',()=>{const sql=readFileSync(new URL('../database/migrations/phase_10_3_document_factory_runtime.sql',import.meta.url),'utf8');for(const marker of ['assert_document_factory_provenance_current_v1','update_document_draft_content_v1','submit_document_draft_for_review_v1','review_document_draft_v1','ENJAZ_DOCUMENT_FACTORY_DRAFT_CHECKSUM_DRIFT','finalize_document_draft_v1','public.documents','public.document_versions','ENJAZ_DOCUMENT_FACTORY_OUTPUT_DOCUMENT_NOT_READY','ENJAZ_DOCUMENT_FACTORY_OUTPUT_VERSION_STALE','document.factory.finalized','get_document_factory_v1'])assert.ok(sql.toLowerCase().includes(marker.toLowerCase()),`missing lifecycle ${marker}`);assert.ok(!/update\s+public\.(companies|transactions|contacts|document_analysis)\b/i.test(sql),'factory runtime must never mutate authoritative source facts')});
