import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import {assertTemplateVersionTransition,isOfficialDraftFinalizable,validateOfficialGenerationProvenance,validateTemplateVersionInput} from '../src/features/documents/documentFactoryContract.ts';

const W='11111111-1111-4111-8111-111111111111',T='22222222-2222-4222-8222-222222222222',V='33333333-3333-4333-8333-333333333333',D='44444444-4444-4444-8444-444444444444';

test('accepts bounded immutable template-version input',()=>assert.doesNotThrow(()=>validateTemplateVersionInput({workspaceId:W,templateId:T,bodySource:'إلى / {{recipient}}\nتحية طيبة',tokenSchema:{recipient:{type:'string'}}})));
test('rejects empty or oversized template bodies',()=>{assert.throws(()=>validateTemplateVersionInput({workspaceId:W,templateId:T,bodySource:'',tokenSchema:{}}));assert.throws(()=>validateTemplateVersionInput({workspaceId:W,templateId:T,bodySource:'x'.repeat(1_000_001),tokenSchema:{}}))});
test('template versions may publish but published versions cannot return to draft',()=>{assert.doesNotThrow(()=>assertTemplateVersionTransition('draft','published'));assert.throws(()=>assertTemplateVersionTransition('published','draft'))});
test('official generation accepts verified current OCR provenance',()=>assert.doesNotThrow(()=>validateOfficialGenerationProvenance({templateVersionId:V,factSnapshot:{companyName:'إنجاز'},sources:[{kind:'ocr',entityId:D,sourceVersionId:V,verificationState:'verified',stale:false}]})));
test('official generation rejects unverified OCR',()=>assert.throws(()=>validateOfficialGenerationProvenance({templateVersionId:V,factSnapshot:{},sources:[{kind:'ocr',entityId:D,verificationState:'reviewed',stale:false}]})));
test('official generation rejects stale verified OCR',()=>assert.throws(()=>validateOfficialGenerationProvenance({templateVersionId:V,factSnapshot:{},sources:[{kind:'ocr',entityId:D,verificationState:'verified',stale:true}]})));
test('final artifacts require template version, approval and exact output document version',()=>{assert.equal(isOfficialDraftFinalizable({status:'final',templateVersionId:V,approvedAt:'2026-09-14T00:00:00Z',finalDocumentId:D,finalDocumentVersionId:V}),true);assert.equal(isOfficialDraftFinalizable({status:'final',templateVersionId:V,approvedAt:null,finalDocumentId:D,finalDocumentVersionId:V}),false);assert.equal(isOfficialDraftFinalizable({status:'approved',templateVersionId:V,approvedAt:'2026-09-14T00:00:00Z',finalDocumentId:D,finalDocumentVersionId:V}),false)});
test('Phase 10.3 migration keeps official template versions server-governed and final drafts immutable',()=>{const sql=readFileSync(new URL('../database/migrations/phase_10_3_document_factory_authority.sql',import.meta.url),'utf8');for(const marker of ['create table public.document_template_versions','revoke insert,update,delete on table public.document_template_versions from public,anon,authenticated','document_template_versions_immutable_v1','template_version_id uuid','fact_snapshot jsonb','provenance jsonb','final_document_version_id uuid','document_drafts_direct_update_workspace','status = \'draft\'','require_document_factory_owner_v1','create_document_template_version_v1','publish_document_template_version_v1'])assert.ok(sql.toLowerCase().includes(marker.toLowerCase()),`missing ${marker}`);assert.ok(!/grant\s+(insert|update|delete)[\s\S]{0,120}document_template_versions[\s\S]{0,80}authenticated/i.test(sql),'template version direct mutation must stay closed')});
