import assert from 'node:assert/strict';
import test from 'node:test';
import {assertDocumentIntelligenceTransition,isVerifiedIntelligenceUsable,parseDocumentIntelligenceDetail,validateExtractionRequest,validateReviewInput,validateVerifyInput} from '../src/features/documents/documentIntelligenceContract.ts';

const WS='11111111-1111-4111-8111-111111111111',DOC='22222222-2222-4222-8222-222222222222',VER='33333333-3333-4333-8333-333333333333',AN='44444444-4444-4444-8444-444444444444';
const page={pageNumber:1,text:'شركة إنجاز',confidence:.93,fields:[{key:'company_name',value:'إنجاز',confidence:.91,pageNumber:1,sourceText:'شركة إنجاز',corrected:false}]};
const analysis=(state='review_required',overrides:Record<string,unknown>={})=>({id:AN,documentId:DOC,documentVersionId:VER,sourceVersionNumber:2,analysisVersion:3,state,reviewStatus:'unreviewed',ocrText:'شركة إنجاز',extractedFields:{company_name:{value:'إنجاز',confidence:.91,pageNumber:1}},pages:[page],classification:'certificate',confidence:.93,provider:'test-provider',stale:false,analyzedAt:'2026-09-13T00:00:00Z',reviewedAt:null,verifiedAt:null,failureCode:null,...overrides});
const detail=(a:unknown)=>({schema:'enjaz.document-intelligence.v1',documentId:DOC,currentVersionId:VER,currentVersionNumber:2,analyses:[a]});

test('accepts a version-bound extraction request',()=>assert.doesNotThrow(()=>validateExtractionRequest({workspaceId:WS,documentId:DOC,versionNumber:2})));
test('rejects an invalid source version request',()=>assert.throws(()=>validateExtractionRequest({workspaceId:WS,documentId:DOC,versionNumber:0})));
test('parses review-required extraction with explicit page provenance',()=>{const r=parseDocumentIntelligenceDetail(detail(analysis()));assert.equal(r.analyses[0]?.documentVersionId,VER);assert.equal(r.analyses[0]?.pages[0]?.pageNumber,1)});
test('rejects non-legacy extraction without immutable version provenance',()=>assert.throws(()=>parseDocumentIntelligenceDetail(detail(analysis('review_required',{documentVersionId:null,sourceVersionNumber:null})))));
test('rejects review-ready OCR with no page evidence',()=>assert.throws(()=>parseDocumentIntelligenceDetail(detail(analysis('review_required',{pages:[]})))));
test('rejects page confidence outside 0..1',()=>assert.throws(()=>parseDocumentIntelligenceDetail(detail(analysis('review_required',{pages:[{...page,confidence:1.01}]})))));
test('rejects extracted field lacking page provenance during correction',()=>assert.throws(()=>validateReviewInput({workspaceId:WS,analysisId:AN,decision:'accept',correctedFields:{company_name:{value:'X',confidence:.9}}})));
test('reject decision cannot smuggle corrected extracted values',()=>assert.throws(()=>validateReviewInput({workspaceId:WS,analysisId:AN,decision:'reject',correctedFields:{company_name:{value:'X',confidence:.9,pageNumber:1}}})));
test('verification input is bounded and id-scoped',()=>{assert.doesNotThrow(()=>validateVerifyInput({workspaceId:WS,analysisId:AN,note:'تمت المطابقة مع الأصل'}));assert.throws(()=>validateVerifyInput({workspaceId:WS,analysisId:AN,note:'x'.repeat(1001)}))});
test('lifecycle permits EXTRACT -> REVIEW -> VERIFY only through governed states',()=>{assert.doesNotThrow(()=>assertDocumentIntelligenceTransition('queued','extracting'));assert.doesNotThrow(()=>assertDocumentIntelligenceTransition('extracting','review_required'));assert.doesNotThrow(()=>assertDocumentIntelligenceTransition('review_required','reviewed'));assert.doesNotThrow(()=>assertDocumentIntelligenceTransition('reviewed','verified'));assert.throws(()=>assertDocumentIntelligenceTransition('review_required','verified'));assert.throws(()=>assertDocumentIntelligenceTransition('queued','verified'))});
test('verified-but-stale extraction is never usable as verified intelligence',()=>{assert.equal(isVerifiedIntelligenceUsable({state:'verified',stale:false}),true);assert.equal(isVerifiedIntelligenceUsable({state:'verified',stale:true}),false);assert.equal(isVerifiedIntelligenceUsable({state:'reviewed',stale:false}),false)});
test('legacy OCR stays explicitly derived and unverified',()=>{const legacy=analysis('legacy_unverified',{documentVersionId:null,sourceVersionNumber:null,pages:[],confidence:null,provider:null});const r=parseDocumentIntelligenceDetail(detail(legacy));assert.equal(r.analyses[0]?.state,'legacy_unverified');assert.equal(isVerifiedIntelligenceUsable(r.analyses[0]!),false)});
