import assert from 'node:assert/strict';
import test from 'node:test';
import { ENJAZ_PROCESS_MINING_SCHEMA,buildEmpiricalDelayPrediction,buildEmpiricalNextActivityPrediction,buildProcessEvent,buildProcessPath,classifyBottleneckCandidates as canonicalBottlenecks,type ProcessEventProvenance,type ProcessPath } from '../src/features/process-intelligence/processMiningContract.ts';
import { classifyBottleneckCandidates,predictDelayRisk,predictNextActivity,type ProcessMiningSnapshot } from '../src/features/process-intelligence/processMiningService.ts';

const W='workspace-a',AS_OF='2026-09-12T00:00:00.000Z';
const provenance=(caseId:string,id:string):ProcessEventProvenance=>({schema:ENJAZ_PROCESS_MINING_SCHEMA,workspaceId:W,caseId,sourceDomain:'transaction-lifecycle',sourceEntity:'transaction_activity',sourceEventId:id,sourceAsOf:AS_OF,basis:['id','occurred_at'],derivationVersion:'phase9.6-parity-v1'});
function path(caseId:string,next:string,day:number,hours=1):ProcessPath{const start=new Date(Date.UTC(2026,8,day,8)),end=new Date(start.getTime()+hours*3_600_000);return buildProcessPath([buildProcessEvent({workspaceId:W,caseId,activityKey:'review',labelAr:'مراجعة',occurredAt:start.toISOString(),provenance:provenance(caseId,`${caseId}-a`)}),buildProcessEvent({workspaceId:W,caseId,activityKey:next,labelAr:next,occurredAt:end.toISOString(),provenance:provenance(caseId,`${caseId}-b`)})])}
function snapshot(cases:readonly ProcessPath[]):ProcessMiningSnapshot{return {schema:ENJAZ_PROCESS_MINING_SCHEMA,workspaceId:W,generatedAt:AS_OF,authority:'read_only_derived_process_intelligence',cases,sourceCounts:{transactionActivity:cases.length*2,workflowInstances:0,workflowTransitions:0,fieldAssignments:0,fieldVisits:0,fieldEvidence:0},syncReceiptPolicy:'actor_scoped_integrity_evidence_not_path_input'}}

test('9.6 runtime parity 01 — production bottleneck classification matches canonical contract',()=>{const p=path('c1','approve',1,4);assert.deepEqual(classifyBottleneckCandidates(p,7_200_000),canonicalBottlenecks(p,7_200_000))});
test('9.6 runtime parity 02 — production next-activity result matches canonical empirical contract',()=>{const cases=[path('c1','approve',1),path('c2','approve',2),path('c3','approve',3),path('c4','reject',4)],assumptions=['اختبار parity اتجاهي.'];assert.deepEqual(predictNextActivity(snapshot(cases),'review',assumptions),buildEmpiricalNextActivityPrediction({workspaceId:W,currentActivityKey:'review',historicalPaths:cases,asOf:AS_OF,assumptions}))});
test('9.6 runtime parity 03 — production delay result matches canonical wait-threshold contract',()=>{const cases=[path('c1','approve',1,4),path('c2','approve',2,3),path('c3','approve',3,2),path('c4','approve',4,1)],assumptions=['اختبار parity للتأخر.'];assert.deepEqual(predictDelayRisk(snapshot(cases),'review',7_200_000,assumptions),buildEmpiricalDelayPrediction({workspaceId:W,currentActivityKey:'review',historicalPaths:cases,thresholdMs:7_200_000,asOf:AS_OF,assumptions}))});
