import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import {
  ENJAZ_PROCESS_MINING_SCHEMA,PROCESS_MIN_DIRECTIONAL_CASES,
  ProcessCaseLineageError,ProcessDuplicateSourceEventError,ProcessMiningContractError,ProcessProvenanceRequiredError,ProcessTimeError,ProcessUnsafeIntegerError,ProcessWorkspaceLineageError,
  buildEmpiricalDelayPrediction,buildEmpiricalNextActivityPrediction,buildObservedProcessWaits,buildProcessEvent,buildProcessPath,classifyBottleneckCandidates,parseProcessEventProvenance,
  type ProcessEvent,type ProcessEventProvenance,type ProcessSourceDomain,
} from '../src/features/process-intelligence/processMiningContract.ts';

const AS_OF='2026-09-12T00:00:00.000Z';
const state=JSON.parse(fs.readFileSync(new URL('../docs/PHASE9_6_STATE.json',import.meta.url),'utf8'));
const prior=JSON.parse(fs.readFileSync(new URL('../docs/PHASE9_5_STATE.json',import.meta.url),'utf8'));
const registry=JSON.parse(fs.readFileSync(new URL('../docs/ENJAZ_MAJOR_PRODUCT_SYSTEMS.json',import.meta.url),'utf8'));
const p=(caseId='case-a',id='event-a',overrides:Partial<ProcessEventProvenance>={}):ProcessEventProvenance=>Object.freeze({schema:ENJAZ_PROCESS_MINING_SCHEMA,workspaceId:'workspace-a',caseId,sourceDomain:'workflow' as ProcessSourceDomain,sourceEntity:'workflow_transition_events',sourceEventId:id,sourceAsOf:AS_OF,basis:Object.freeze(['occurred_at','transition_key']),derivationVersion:'phase9.6-closure-v1',...overrides});
const e=(caseId:string,key:string,at:string,i:number,overrides:Partial<ProcessEventProvenance>={}):ProcessEvent=>buildProcessEvent({workspaceId:overrides.workspaceId??'workspace-a',caseId,activityKey:key,labelAr:`نشاط ${key}`,occurredAt:at,provenance:p(caseId,`${caseId}-${i}`,overrides)});
const path=(caseId:string,next:string,index:number)=>buildProcessPath([e(caseId,'review',`2026-09-0${index}T08:00:00.000Z`,1),e(caseId,next,`2026-09-0${index}T09:00:00.000Z`,2)]);
const delayPath=(caseId:string,index:number,hours:number,workspaceId='workspace-a')=>{const a=new Date(Date.UTC(2026,8,index,8)),b=new Date(a.getTime()+hours*3_600_000);return buildProcessPath([e(caseId,'review',a.toISOString(),1,{workspaceId}),e(caseId,'approve',b.toISOString(),2,{workspaceId})])};

test('9.6 closure foundation 01 — predecessor stays closed and Phase 9.6 closes only into authorized 9.7',()=>{assert.equal(prior.status,'CLOSED');assert.equal(prior.phase9_6Allowed,true);assert.equal(state.status,'CLOSED');assert.equal(state.exitGatePassed,true);assert.equal(state.phase9_7Allowed,true);assert.equal(state.nextPhase,'9.7');assert.equal(state.successorStatus,'AUTHORIZED');assert.equal(state.certifiedImplementationMain,'d92059530275ff70e02a05c4f4c1ef930cb1750a')});
test('9.6 closure foundation 02 — provenance parser still rejects incomplete lineage',()=>{assert.ok(parseProcessEventProvenance(p()));for(const bad of [{workspaceId:''},{caseId:''},{sourceDomain:'finance'},{sourceAsOf:'tomorrow'},{basis:[]}])assert.equal(parseProcessEventProvenance({...p(),...bad}),null)});
test('9.6 closure foundation 03 — invalid provenance still fails closed',()=>{assert.throws(()=>buildProcessEvent({workspaceId:'workspace-a',caseId:'case-a',activityKey:'review',labelAr:'مراجعة',occurredAt:'2026-09-01T08:00:00.000Z',provenance:{...p(),schema:'wrong' as typeof ENJAZ_PROCESS_MINING_SCHEMA}}),ProcessProvenanceRequiredError)});
test('9.6 closure foundation 04 — workspace/case lineage drift remains forbidden',()=>{assert.throws(()=>buildProcessEvent({workspaceId:'workspace-b',caseId:'case-a',activityKey:'review',labelAr:'مراجعة',occurredAt:'2026-09-01T08:00:00.000Z',provenance:p()}),ProcessWorkspaceLineageError);assert.throws(()=>buildProcessEvent({workspaceId:'workspace-a',caseId:'case-b',activityKey:'review',labelAr:'مراجعة',occurredAt:'2026-09-01T08:00:00.000Z',provenance:p()}),ProcessCaseLineageError)});
test('9.6 closure foundation 05 — future source events remain forbidden',()=>assert.throws(()=>e('case-a','review','2026-09-13T00:00:00.000Z',1),ProcessTimeError));
test('9.6 closure foundation 06 — decreasing chronology is never normalized',()=>assert.throws(()=>buildProcessPath([e('case-a','late','2026-09-02T10:00:00.000Z',1),e('case-a','early','2026-09-02T09:00:00.000Z',2)]),ProcessTimeError));
test('9.6 closure foundation 07 — equal timestamps remain partial and non-authoritative',()=>{const x=buildProcessPath([e('case-a','review','2026-09-02T09:00:00.000Z',1),e('case-a','approve','2026-09-02T09:00:00.000Z',2)]);assert.equal(x.ordering,'partial');assert.equal(x.authoritative,false);assert.equal(buildObservedProcessWaits(x)[0]!.strictOrderProven,false)});
test('9.6 closure foundation 08 — duplicate authoritative source identity remains rejected',()=>{const q=p('case-a','same'),a=buildProcessEvent({workspaceId:'workspace-a',caseId:'case-a',activityKey:'review',labelAr:'مراجعة',occurredAt:'2026-09-02T09:00:00.000Z',provenance:q}),b=buildProcessEvent({workspaceId:'workspace-a',caseId:'case-a',activityKey:'approve',labelAr:'موافقة',occurredAt:'2026-09-02T10:00:00.000Z',provenance:q});assert.throws(()=>buildProcessPath([a,b]),ProcessDuplicateSourceEventError)});
test('9.6 closure foundation 09 — rework requires repeated observed activity',()=>{const x=buildProcessPath([e('case-a','review','2026-09-02T08:00:00.000Z',1),e('case-a','submit','2026-09-02T09:00:00.000Z',2),e('case-a','review','2026-09-02T10:00:00.000Z',3)]);assert.equal(x.reworkCount,1);assert.deepEqual(x.repeatedActivities,['review'])});
test('9.6 closure foundation 10 — bottlenecks require a governed positive threshold',()=>{const x=buildProcessPath([e('case-a','review','2026-09-02T08:00:00.000Z',1),e('case-a','approve','2026-09-02T12:00:00.000Z',2)]);assert.equal(classifyBottleneckCandidates(x,7_200_000).length,1);assert.throws(()=>classifyBottleneckCandidates(x,0),ProcessUnsafeIntegerError)});
test('9.6 closure foundation 11 — missing duration stays unknown instead of fabricated zero',()=>assert.equal(buildProcessPath([e('case-a','review','2026-09-02T08:00:00.000Z',1)]).observedDurationMs,null));
test('9.6 closure foundation 12 — next activity remains exact, directional and non-authoritative with enough evidence',()=>{assert.equal(PROCESS_MIN_DIRECTIONAL_CASES,4);const x=buildEmpiricalNextActivityPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[path('c1','approve',1),path('c2','approve',2),path('c3','approve',3),path('c4','reject',4)],asOf:AS_OF,assumptions:['دليل إغلاق.']});assert.equal(x.authoritative,false);assert.equal(x.method,'empirical_next_activity_frequency');assert.equal(x.confidence,'directional');assert.equal(x.predictedActivityKey,'approve');assert.equal(x.probabilityBps,7500);assert.equal(x.sampleCount,4)});
test('9.6 closure foundation 13 — insufficient next-activity evidence cannot become directional',()=>{const x=buildEmpiricalNextActivityPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[path('c1','approve',1),path('c2','approve',2),path('c3','reject',3)],asOf:AS_OF,assumptions:['عينة غير كافية.']});assert.equal(x.confidence,'insufficient');assert.equal(x.predictedActivityKey,null);assert.equal(x.probabilityBps,null)});
test('9.6 closure foundation 14 — tied next-activity cohorts expose uncertainty',()=>{const x=buildEmpiricalNextActivityPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[path('c1','approve',1),path('c2','approve',2),path('c3','reject',3),path('c4','reject',4)],asOf:AS_OF,assumptions:['تعادل.']});assert.equal(x.confidence,'insufficient');assert.equal(x.predictedActivityKey,null);assert.equal(x.probabilityBps,null)});
test('9.6 closure foundation 15 — prediction still rejects cross-workspace/future/missing evidence/disclosure',()=>{const cross=buildProcessPath([e('x','review','2026-09-02T08:00:00.000Z',1,{workspaceId:'workspace-b'}),e('x','approve','2026-09-02T09:00:00.000Z',2,{workspaceId:'workspace-b'})]);assert.throws(()=>buildEmpiricalNextActivityPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[cross],asOf:AS_OF,assumptions:['x']}),ProcessWorkspaceLineageError);assert.throws(()=>buildEmpiricalNextActivityPrediction({workspaceId:'workspace-a',currentActivityKey:'missing',historicalPaths:[path('c1','approve',1)],asOf:AS_OF,assumptions:['x']}),ProcessProvenanceRequiredError);assert.throws(()=>buildEmpiricalNextActivityPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[path('c1','approve',1)],asOf:AS_OF,assumptions:[]}),ProcessMiningContractError)});
test('9.6 closure foundation 16 — M18 stays ACTIVE/open for Phase 15 after Phase 9.6 closure',()=>{const m18=registry.systems.find((x:{id:string})=>x.id==='M18');assert.equal(m18?.status,'ACTIVE');assert.deepEqual(m18?.anchors,['9','15']);assert.equal(m18?.closureEvidence,null);assert.equal(state.majorSystem.status,'ACTIVE');assert.equal(state.majorSystem.globalClosureAllowed,false)});
test('9.6 closure foundation 17 — delay prediction stays exact, disclosed and non-authoritative',()=>{const x=buildEmpiricalDelayPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[delayPath('d1',1,4),delayPath('d2',2,3),delayPath('d3',3,2),delayPath('d4',4,1)],thresholdMs:7_200_000,asOf:AS_OF,assumptions:['دليل تأخر.']});assert.equal(x.authoritative,false);assert.equal(x.method,'empirical_wait_threshold_frequency');assert.equal(x.sampleCount,4);assert.equal(x.delayedSampleCount,3);assert.equal(x.confidence,'directional');assert.equal(x.probabilityBps,7500)});
test('9.6 closure foundation 18 — fewer than four proven waits stays insufficient',()=>{const x=buildEmpiricalDelayPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[delayPath('d1',1,4),delayPath('d2',2,3),delayPath('d3',3,1)],thresholdMs:7_200_000,asOf:AS_OF,assumptions:['غير كاف.']});assert.equal(x.sampleCount,3);assert.equal(x.confidence,'insufficient');assert.equal(x.probabilityBps,null)});
test('9.6 closure foundation 19 — equal-time evidence remains excluded from delay samples',()=>{const equal=delayPath('de',4,0),x=buildEmpiricalDelayPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[delayPath('d1',1,4),delayPath('d2',2,3),delayPath('d3',3,1),equal],thresholdMs:7_200_000,asOf:AS_OF,assumptions:['لا زمن متساو.']});assert.equal(equal.ordering,'partial');assert.equal(x.sampleCount,3);assert.equal(x.confidence,'insufficient')});
test('9.6 closure foundation 20 — delay prediction still fails closed on invalid threshold/lineage/disclosure',()=>{const valid=delayPath('d1',1,4),cross=delayPath('dx',2,4,'workspace-b');assert.throws(()=>buildEmpiricalDelayPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[valid],thresholdMs:0,asOf:AS_OF,assumptions:['x']}),ProcessUnsafeIntegerError);assert.throws(()=>buildEmpiricalDelayPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[cross],thresholdMs:7_200_000,asOf:AS_OF,assumptions:['x']}),ProcessWorkspaceLineageError);assert.throws(()=>buildEmpiricalDelayPrediction({workspaceId:'workspace-a',currentActivityKey:'review',historicalPaths:[valid],thresholdMs:7_200_000,asOf:AS_OF,assumptions:[]}),ProcessMiningContractError)});
