import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { AppError } from '../../core/errors/AppError.ts';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import type { CompanyContactContext } from '../../features/companies/companyService.ts';
import { useGovernanceCommandGateway } from '../../features/governance/GovernanceCommandContext.tsx';
import type { AuthorityScope, BeneficialBasis, CapitalChangeType, GovernanceContext, GovernanceRole, HolderKind, OwnershipEntryInput, OwnershipRole, ResolutionType } from '../../features/governance/governanceCommands.ts';
import { useCurrentUserId } from '../../shared/session/CurrentUserIdContext.tsx';
import './governance.css';

type Dialog = 'ownership' | 'beneficial' | 'authority' | 'resolution' | 'capital' | null;
type OwnershipDraft = { key: string; kind: HolderKind; id: string; role: OwnershipRole; percentage: string };
type BeneficialDraft = { key: string; contactId: string; basis: BeneficialBasis; percentage: string };

function today() { const d=new Date(),local=new Date(d.getTime()-d.getTimezoneOffset()*60_000);return local.toISOString().slice(0,10); }
function uuid() { if(typeof crypto==='undefined'||typeof crypto.randomUUID!=='function')throw new Error('Secure UUID unavailable');return crypto.randomUUID(); }
function errorMessage(error:unknown){return error instanceof AppError?error.userMessage:error instanceof Error&&error.message?error.message:'تعذر إكمال عملية الحوكمة.'}
function roleLabel(v:string){return v==='director'?'عضو إدارة':v==='manager'?'مدير مفوض':v==='authorized_person'?'مخول':v==='partner'?'شريك':'مساهم'}
function basisLabel(v:string){return v==='ownership'?'ملكية':v==='voting_rights'?'حقوق تصويت':v==='management_control'?'سيطرة إدارية':'أساس آخر'}
function eventLabel(v:string){const labels:Record<string,string>={'ownership.snapshot':'هيكل الملكية','beneficial_owner.snapshot':'المستفيد الحقيقي','authority.grant':'منح صلاحية','authority.revoke':'سحب صلاحية','resolution.record':'قرار شركة','capital.change':'تغيير رأس المال'};return labels[v]??v}
function resolutionLabel(v:string){const labels:Record<string,string>={appointment:'تعيين',removal:'إعفاء',ownership:'ملكية',capital:'رأس مال',authorization:'تخويل',general:'عام',other:'أخرى'};return labels[v]??v}
function riskLabel(code:string){const labels:Record<string,string>={OWNERSHIP_NOT_CONFIGURED:'هيكل الملكية غير مكتمل',BENEFICIAL_OWNER_MISSING:'المستفيد الحقيقي غير مسجل',REPRESENTATION_AUTHORITY_MISSING:'لا توجد صلاحية تمثيل فعالة',AUTHORITY_EXPIRING:'صلاحية تمثيل على وشك الانتهاء'};return labels[code]??code}
function contactOptions(contacts:readonly CompanyContactContext[]){const seen=new Set<string>();return contacts.flatMap(x=>{const c=x.contact;if(!c||seen.has(c.id))return[];seen.add(c.id);return[{id:c.id,label:c.display_name}]})}
function pctTotal(rows:readonly OwnershipDraft[]){return rows.reduce((sum,row)=>sum+(Number(row.percentage)||0),0)}

function Loading(){return <section className="r2-gov-state" role="status"><span className="r2-gov-orbit"/><div><strong>جارٍ بناء سجل الحوكمة</strong><p>نقرأ الملكية والصلاحيات والقرارات والتاريخ من السجل القانوني الموثوق.</p></div></section>}

export function CompanyGovernancePanel({ companyId, companyLabel, contacts }: Readonly<{ companyId:string; companyLabel:string; contacts:readonly CompanyContactContext[] }>) {
  const gateway=useGovernanceCommandGateway(),factory=useDataLayerFactory(),userId=useCurrentUserId();
  const [workspaceId,setWorkspaceId]=useState<string|null>(null),[context,setContext]=useState<GovernanceContext|null>(null),[status,setStatus]=useState<'loading'|'ready'|'error'>('loading'),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[asOf,setAsOf]=useState(today()),[reload,setReload]=useState(0),[dialog,setDialog]=useState<Dialog>(null),[busy,setBusy]=useState(false);
  const people=useMemo(()=>contactOptions(contacts),[contacts]);
  const [ownershipDate,setOwnershipDate]=useState(today()),[ownershipRows,setOwnershipRows]=useState<OwnershipDraft[]>([]);
  const [beneficialDate,setBeneficialDate]=useState(today()),[beneficialRows,setBeneficialRows]=useState<BeneficialDraft[]>([]);
  const [authorityContact,setAuthorityContact]=useState(''),[authorityRole,setAuthorityRole]=useState<GovernanceRole>('manager'),[authorityScope,setAuthorityScope]=useState<AuthorityScope>('full'),[authorityPowers,setAuthorityPowers]=useState('التوقيع، التمثيل أمام الجهات الرسمية'),[authorityFrom,setAuthorityFrom]=useState(today()),[authorityUntil,setAuthorityUntil]=useState('');
  const [resolutionNumber,setResolutionNumber]=useState(''),[resolutionTitle,setResolutionTitle]=useState(''),[resolutionType,setResolutionType]=useState<ResolutionType>('general'),[resolutionDate,setResolutionDate]=useState(today()),[resolutionNotes,setResolutionNotes]=useState('');
  const [capitalType,setCapitalType]=useState<CapitalChangeType>('increase'),[capitalAmount,setCapitalAmount]=useState(''),[capitalDate,setCapitalDate]=useState(today()),[capitalReason,setCapitalReason]=useState('');

  useEffect(()=>{let active=true;setStatus('loading');setError(null);void(async()=>{if(!userId)throw new Error('انتهت الجلسة.');const ws=await factory.resolveWorkspaceId(userId);if(!ws)throw new Error('مساحة العمل غير متاحة.');const next=await gateway.loadContext(ws,companyId,asOf);if(!active)return;setWorkspaceId(ws);setContext(next);setStatus('ready')})().catch((e:unknown)=>{if(!active)return;setContext(null);setStatus('error');setError(errorMessage(e))});return()=>{active=false}},[asOf,companyId,factory,gateway,reload,userId]);

  function refresh(message?:string){if(message)setNotice(message);setReload(v=>v+1)}
  function startOwnership(){if(!context)return;setOwnershipDate(today());setOwnershipRows(context.ownership.stakes.map(s=>({key:uuid(),kind:s.holderKind,id:s.holderId,role:s.role,percentage:s.percentage})));if(!context.ownership.stakes.length)setOwnershipRows([{key:uuid(),kind:'person',id:people[0]?.id??'',role:'shareholder',percentage:'100'}]);setDialog('ownership');setError(null);setNotice(null)}
  function startBeneficial(){if(!context)return;setBeneficialDate(today());setBeneficialRows(context.beneficialOwners.map(x=>({key:uuid(),contactId:x.contactId,basis:x.basis,percentage:x.percentage??''})));if(!context.beneficialOwners.length&&people[0])setBeneficialRows([{key:uuid(),contactId:people[0].id,basis:'ownership',percentage:'100'}]);setDialog('beneficial');setError(null);setNotice(null)}
  async function run(task:()=>Promise<void>,success:string){if(busy)return;setBusy(true);setError(null);setNotice(null);try{await task();setDialog(null);refresh(success)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}

  async function saveOwnership(e:FormEvent){e.preventDefault();if(!workspaceId||!context)return;const entries:OwnershipEntryInput[]=ownershipRows.map(x=>({kind:x.kind,id:x.id.trim(),role:x.role,percentage:x.percentage.trim()}));await run(()=>gateway.replaceOwnership({workspaceId,companyId,expectedVersion:context.versions.ownership,operationId:uuid(),effectiveFrom:ownershipDate,entries}),'تم تثبيت نسخة جديدة من هيكل الملكية. التاريخ السابق محفوظ.')}
  async function saveBeneficial(e:FormEvent){e.preventDefault();if(!workspaceId||!context)return;await run(()=>gateway.replaceBeneficialOwners({workspaceId,companyId,expectedVersion:context.versions.beneficialOwners,operationId:uuid(),effectiveFrom:beneficialDate,entries:beneficialRows.map(x=>({contactId:x.contactId,basis:x.basis,percentage:x.percentage.trim()||null}))}),'تم تحديث سجل المستفيد الحقيقي مع حفظ التاريخ.')}
  async function saveAuthority(e:FormEvent){e.preventDefault();if(!workspaceId||!context)return;await run(()=>gateway.grantAuthority({workspaceId,companyId,expectedVersion:context.versions.authority,operationId:uuid(),contactId:authorityContact,role:authorityRole,scope:authorityScope,powers:authorityPowers.split(/[،,\n]/).map(x=>x.trim()).filter(Boolean),effectiveFrom:authorityFrom,expiresOn:authorityUntil||null}),'تم منح الصلاحية وتسجيلها في خط الحوكمة.')}
  async function revokeAuthority(grantId:string){if(!workspaceId||!context)return;const reason=window.prompt('سبب سحب الصلاحية؟','انتهاء أو تغيير التخويل');if(!reason?.trim())return;await run(()=>gateway.revokeAuthority({workspaceId,companyId,expectedVersion:context.versions.authority,operationId:uuid(),grantId,effectiveOn:today(),reason}),'تم سحب الصلاحية مع إبقاء سجلها التاريخي.')}
  async function saveResolution(e:FormEvent){e.preventDefault();if(!workspaceId||!context)return;await run(()=>gateway.recordResolution({workspaceId,companyId,expectedVersion:context.versions.resolutions,operationId:uuid(),number:resolutionNumber.trim()||null,title:resolutionTitle,type:resolutionType,effectiveOn:resolutionDate,notes:resolutionNotes.trim()||null}),'تم تسجيل القرار كسجل غير قابل للمحو التاريخي.')}
  async function saveCapital(e:FormEvent){e.preventDefault();if(!workspaceId||!context)return;await run(()=>gateway.recordCapital({workspaceId,companyId,expectedVersion:context.versions.capital,operationId:uuid(),changeType:capitalType,amountAfter:capitalAmount.trim(),effectiveOn:capitalDate,reason:capitalReason}),'تم تحديث رأس المال عبر أمر الحوكمة المعتمد.')}

  if(status==='loading')return <Loading/>;
  if(status==='error'||!context)return <section className="r2-gov-state is-error" role="alert"><div><strong>تعذر تحميل حوكمة الشركة</strong><p>{error??'تعذر تجهيز سجل الحوكمة.'}</p></div><button type="button" onClick={()=>setReload(v=>v+1)}>إعادة المحاولة</button></section>;
  const ownerCount=context.ownership.stakes.length,activeAuthorities=context.authorities.length;
  return <section className="r2-gov" data-phase9-3="governance" data-governance-company={companyId}>
    <header className="r2-gov-hero"><div className="r2-gov-hero__copy"><p className="r2-eyebrow">Phase 9.3 · Corporate Governance · M2</p><h2>مركز حوكمة الشركة</h2><p>سجل زمني واحد لـ <b>{companyLabel}</b> يربط الملكية والمستفيد الحقيقي وصلاحيات التمثيل والقرارات ورأس المال دون كتابة مباشرة على الجداول.</p></div><div className="r2-gov-asof"><span>لقطة الحوكمة في</span><input type="date" aria-label="تاريخ لقطة الحوكمة" value={asOf} onChange={e=>setAsOf(e.target.value)}/><small>{context.canMutate?'صلاحية إدارة كاملة':'قراءة فقط'}</small></div></header>
    {notice&&<p className="r2-gov-notice" role="status">{notice}</p>}{error&&<p className="r2-gov-error" role="alert">{error}</p>}
    <div className="r2-gov-scoreboard">
      <article><span>الملكية</span><strong>{context.ownership.configured?'100%':'—'}</strong><small>{ownerCount} مساهم/شريك</small></article>
      <article><span>المستفيد الحقيقي</span><strong>{context.beneficialOwners.length}</strong><small>إقرار فعال</small></article>
      <article><span>التمثيل</span><strong>{activeAuthorities}</strong><small>صلاحية فعالة</small></article>
      <article><span>رأس المال</span><strong dir="ltr">{context.capital.known&&context.capital.amount?new Intl.NumberFormat('ar-IQ',{maximumFractionDigits:2}).format(context.capital.amount):'—'}</strong><small>{context.capital.source==='governance_history'?'من سجل الحوكمة':'القيمة الحالية'}</small></article>
    </div>
    <div className="r2-gov-riskbar" aria-label="مخاطر الحوكمة">{context.risks.length?context.risks.map(r=><span key={r.code} className={`is-${r.severity}`} title={r.message}>{riskLabel(r.code)}</span>):<span className="is-clear">لا توجد إشارات حوكمة مفتوحة</span>}</div>

    <div className="r2-gov-grid">
      <section className="r2-gov-card r2-gov-card--ownership"><header><div><small>Ownership Registry</small><h3>المساهمون والشركاء</h3></div>{context.canMutate&&<button type="button" onClick={startOwnership}>تحديث الهيكل</button>}</header><div className="r2-gov-list">{context.ownership.stakes.length?context.ownership.stakes.map(s=><article key={s.id}><span className="r2-gov-avatar">{s.holderKind==='company'?'ش':'ف'}</span><div><strong>{s.holderKind==='person'?(people.find(p=>p.id===s.holderId)?.label??'شخص مرتبط'):'شركة مساهمة'}</strong><small>{roleLabel(s.role)} · منذ {s.effectiveFrom}</small></div><b dir="ltr">{s.percentage}%</b></article>):<p className="r2-gov-empty">لم يُعتمد هيكل الملكية بعد.</p>}</div></section>
      <section className="r2-gov-card"><header><div><small>Beneficial Ownership</small><h3>المستفيد الحقيقي</h3></div>{context.canMutate&&<button type="button" onClick={startBeneficial}>تحديث السجل</button>}</header><div className="r2-gov-list">{context.beneficialOwners.length?context.beneficialOwners.map(x=><article key={x.id}><span className="r2-gov-avatar">م</span><div><strong>{x.displayName}</strong><small>{basisLabel(x.basis)} · منذ {x.effectiveFrom}</small></div><b dir="ltr">{x.percentage?`${x.percentage}%`:'سيطرة غير نسبية'}</b></article>):<p className="r2-gov-empty">لا يوجد مستفيد حقيقي فعال في هذه اللقطة.</p>}</div></section>
      <section className="r2-gov-card"><header><div><small>Representation Authority</small><h3>الإدارة والتخويل</h3></div>{context.canMutate&&<button type="button" onClick={()=>{setAuthorityContact(people[0]?.id??'');setDialog('authority');setError(null)}}>منح صلاحية</button>}</header><div className="r2-gov-list">{context.authorities.length?context.authorities.map(x=><article key={x.id}><span className="r2-gov-avatar">ص</span><div><strong>{x.displayName}</strong><small>{roleLabel(x.role)} · {x.scope==='full'?'صلاحية كاملة':x.scope} · {x.powers.join('، ')||'دون قيد وصفي'}</small></div>{context.canMutate?<button className="r2-gov-text-danger" type="button" onClick={()=>void revokeAuthority(x.id)}>سحب</button>:<b>{roleLabel(x.role)}</b>}</article>):<p className="r2-gov-empty">لا توجد صلاحيات تمثيل فعالة.</p>}</div></section>
      <section className="r2-gov-card"><header><div><small>Corporate Resolutions</small><h3>قرارات الشركة</h3></div>{context.canMutate&&<button type="button" onClick={()=>{setDialog('resolution');setError(null)}}>قرار جديد</button>}</header><div className="r2-gov-list">{context.resolutions.length?context.resolutions.slice(0,8).map(x=><article key={x.id}><span className="r2-gov-avatar">ق</span><div><strong>{x.title}</strong><small>{resolutionLabel(x.type)} · {x.effectiveOn}{x.number?` · ${x.number}`:''}</small></div></article>):<p className="r2-gov-empty">لا توجد قرارات مسجلة حتى هذا التاريخ.</p>}</div></section>
    </div>

    <section className="r2-gov-timeline"><header><div><small>Corporate Event Timeline</small><h3>الخط الزمني القانوني</h3></div>{context.canMutate&&<button type="button" onClick={()=>{setDialog('capital');setError(null)}}>تغيير رأس المال</button>}</header><div className="r2-gov-timeline__rail">{context.timeline.length?context.timeline.slice(0,20).map(e=><article key={e.id}><span/><div><strong>{eventLabel(e.type)}</strong><small>{e.effectiveOn} · نسخة {e.version}</small></div></article>):<p className="r2-gov-empty">سيظهر هنا كل حدث حوكمة مؤرخ.</p>}</div></section>

    {dialog&&<div className="r2-gov-modal" role="presentation"><section className="r2-gov-sheet" role="dialog" aria-modal="true" aria-label="أمر حوكمة"><header><div><small>Governed command</small><strong>{dialog==='ownership'?'هيكل الملكية':dialog==='beneficial'?'المستفيد الحقيقي':dialog==='authority'?'منح صلاحية تمثيل':dialog==='resolution'?'قرار شركة':'تغيير رأس المال'}</strong></div><button type="button" aria-label="إغلاق" onClick={()=>!busy&&setDialog(null)}>×</button></header>
      {dialog==='ownership'&&<form onSubmit={e=>void saveOwnership(e)}><label><span>تاريخ النفاذ</span><input type="date" value={ownershipDate} onChange={e=>setOwnershipDate(e.target.value)} required/></label><div className="r2-gov-formrows">{ownershipRows.map((row,index)=><div key={row.key} className="r2-gov-formrow"><select aria-label="نوع المالك" value={row.kind} onChange={e=>setOwnershipRows(a=>a.map((x,i)=>i===index?{...x,kind:e.target.value as HolderKind,id:''}:x))}><option value="person">شخص</option><option value="company">شركة</option></select>{row.kind==='person'?<select aria-label="المساهم أو الشريك" required value={row.id} onChange={e=>setOwnershipRows(a=>a.map((x,i)=>i===index?{...x,id:e.target.value}:x))}><option value="">اختر شخصاً مرتبطاً</option>{people.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select>:<input aria-label="معرف الشركة المالكة" value={row.id} onChange={e=>setOwnershipRows(a=>a.map((x,i)=>i===index?{...x,id:e.target.value}:x))} placeholder="معرف شركة موجودة" required/>}<select aria-label="صفة الملكية" value={row.role} onChange={e=>setOwnershipRows(a=>a.map((x,i)=>i===index?{...x,role:e.target.value as OwnershipRole}:x))}><option value="shareholder">مساهم</option><option value="partner">شريك</option></select><input aria-label="نسبة الملكية" inputMode="decimal" value={row.percentage} onChange={e=>setOwnershipRows(a=>a.map((x,i)=>i===index?{...x,percentage:e.target.value}:x))} placeholder="%" required/><button type="button" aria-label="حذف المالك" onClick={()=>setOwnershipRows(a=>a.filter((_,i)=>i!==index))}>−</button></div>)}</div><div className={`r2-gov-total ${Math.abs(pctTotal(ownershipRows)-100)<1e-9?'is-ok':'is-bad'}`}><span>مجموع الملكية</span><strong dir="ltr">{pctTotal(ownershipRows).toFixed(2)}%</strong></div><button type="button" className="r2-gov-add" onClick={()=>setOwnershipRows(a=>[...a,{key:uuid(),kind:'person',id:'',role:'shareholder',percentage:''}])}>＋ إضافة مساهم/شريك</button><button className="r2-action r2-action--primary" disabled={busy||ownershipRows.length===0} type="submit">{busy?'جارٍ التثبيت…':'اعتماد النسخة الجديدة'}</button></form>}
      {dialog==='beneficial'&&<form onSubmit={e=>void saveBeneficial(e)}><label><span>تاريخ النفاذ</span><input type="date" value={beneficialDate} onChange={e=>setBeneficialDate(e.target.value)} required/></label><div className="r2-gov-formrows">{beneficialRows.map((row,index)=><div key={row.key} className="r2-gov-formrow is-beneficial"><select required value={row.contactId} onChange={e=>setBeneficialRows(a=>a.map((x,i)=>i===index?{...x,contactId:e.target.value}:x))}><option value="">اختر الشخص</option>{people.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select><select value={row.basis} onChange={e=>setBeneficialRows(a=>a.map((x,i)=>i===index?{...x,basis:e.target.value as BeneficialBasis}:x))}><option value="ownership">ملكية</option><option value="voting_rights">حقوق تصويت</option><option value="management_control">سيطرة إدارية</option><option value="other">أخرى</option></select><input inputMode="decimal" value={row.percentage} onChange={e=>setBeneficialRows(a=>a.map((x,i)=>i===index?{...x,percentage:e.target.value}:x))} placeholder="النسبة إن وجدت"/><button type="button" onClick={()=>setBeneficialRows(a=>a.filter((_,i)=>i!==index))}>−</button></div>)}</div><button type="button" className="r2-gov-add" onClick={()=>setBeneficialRows(a=>[...a,{key:uuid(),contactId:'',basis:'ownership',percentage:''}])}>＋ إضافة مستفيد</button><button type="button" className="r2-gov-add" onClick={()=>setBeneficialRows([])}>تسجيل عدم وجود مستفيد فعال</button><button className="r2-action r2-action--primary" disabled={busy} type="submit">{busy?'جارٍ التثبيت…':'اعتماد سجل المستفيد الحقيقي'}</button></form>}
      {dialog==='authority'&&<form onSubmit={e=>void saveAuthority(e)}><label><span>الشخص</span><select required value={authorityContact} onChange={e=>setAuthorityContact(e.target.value)}><option value="">اختر شخصاً مرتبطاً</option>{people.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><div className="r2-gov-two"><label><span>الدور</span><select value={authorityRole} onChange={e=>setAuthorityRole(e.target.value as GovernanceRole)}><option value="director">عضو إدارة</option><option value="manager">مدير مفوض</option><option value="authorized_person">مخول</option></select></label><label><span>نطاق الصلاحية</span><select value={authorityScope} onChange={e=>setAuthorityScope(e.target.value as AuthorityScope)}><option value="full">كاملة</option><option value="limited">محددة</option><option value="joint">مشتركة</option><option value="custom">مخصصة</option></select></label></div><label><span>الصلاحيات — افصل بفاصلة</span><textarea rows={3} value={authorityPowers} onChange={e=>setAuthorityPowers(e.target.value)}/></label><div className="r2-gov-two"><label><span>من</span><input type="date" value={authorityFrom} onChange={e=>setAuthorityFrom(e.target.value)} required/></label><label><span>حتى — اختياري</span><input type="date" value={authorityUntil} onChange={e=>setAuthorityUntil(e.target.value)}/></label></div><button className="r2-action r2-action--primary" disabled={busy} type="submit">{busy?'جارٍ التسجيل…':'منح الصلاحية'}</button></form>}
      {dialog==='resolution'&&<form onSubmit={e=>void saveResolution(e)}><div className="r2-gov-two"><label><span>رقم القرار</span><input value={resolutionNumber} onChange={e=>setResolutionNumber(e.target.value)}/></label><label><span>النوع</span><select value={resolutionType} onChange={e=>setResolutionType(e.target.value as ResolutionType)}><option value="appointment">تعيين</option><option value="removal">إعفاء</option><option value="ownership">ملكية</option><option value="capital">رأس مال</option><option value="authorization">تخويل</option><option value="general">عام</option><option value="other">أخرى</option></select></label></div><label><span>عنوان القرار</span><input required value={resolutionTitle} onChange={e=>setResolutionTitle(e.target.value)}/></label><label><span>تاريخ النفاذ</span><input type="date" required value={resolutionDate} onChange={e=>setResolutionDate(e.target.value)}/></label><label><span>ملاحظات</span><textarea rows={4} value={resolutionNotes} onChange={e=>setResolutionNotes(e.target.value)}/></label><button className="r2-action r2-action--primary" disabled={busy} type="submit">{busy?'جارٍ التسجيل…':'تسجيل القرار'}</button></form>}
      {dialog==='capital'&&<form onSubmit={e=>void saveCapital(e)}><div className="r2-gov-two"><label><span>نوع التغيير</span><select value={capitalType} onChange={e=>setCapitalType(e.target.value as CapitalChangeType)}><option value="set">تثبيت أولي</option><option value="increase">زيادة</option><option value="decrease">تخفيض</option><option value="correction">تصحيح</option></select></label><label><span>رأس المال بعد التغيير</span><input inputMode="decimal" required value={capitalAmount} onChange={e=>setCapitalAmount(e.target.value)} placeholder="100000000"/></label></div><label><span>تاريخ النفاذ</span><input type="date" required value={capitalDate} onChange={e=>setCapitalDate(e.target.value)}/></label><label><span>السبب/السند</span><textarea rows={3} required value={capitalReason} onChange={e=>setCapitalReason(e.target.value)}/></label><aside className="r2-gov-command-note">لا يمكن تعديل رأس المال مباشرة من بيانات الشركة بعد تفعيل 9.3؛ هذا الأمر يكتب التاريخ ويحدّث القيمة الحالية معًا.</aside><button className="r2-action r2-action--primary" disabled={busy} type="submit">{busy?'جارٍ التسجيل…':'اعتماد تغيير رأس المال'}</button></form>}
    </section></div>}
  </section>;
}
