export const ROUTES = Object.freeze({
  root: '/',
  foundation: '/foundation',
  identity: '/foundation/identity',
  tokens: '/foundation/tokens',
  typography: '/foundation/typography',
  components: '/foundation/components',
  motion: '/foundation/motion',
  mobile: '/foundation/mobile',
  patterns: '/foundation/patterns',
  destruction: '/foundation/destruction',
  shellPreview: '/foundation/shell',
  navigationPreview: '/foundation/navigation',
  interactionsPreview: '/foundation/interactions',
  login: '/auth/login',
  signUp: '/auth/signup',
  forgotPassword: '/auth/forgot-password',
  updatePassword: '/auth/update-password',
  appHome: '/app',
  appToday: '/app/today',
  appTransactions: '/app/transactions',
  appCompanies: '/app/companies',
  appMore: '/app/more',
  appPeople: '/app/people',
  appFinance: '/app/finance',
  appWorkflows: '/app/workflows',
  appAutomation: '/app/automation',
  appOperations: '/app/operations',
  appCommand: '/app/command',
  appRisk: '/app/risk',
  appSavedViews: '/app/saved-views',
  appIntelligence: '/app/intelligence',
  appDocuments: '/app/documents',
  appReports: '/app/reports',
  appNotifications: '/app/notifications',
  appFollowUps: '/app/follow-ups',
  appCopilot: '/app/copilot',
} as const);

export type AppRoute = (typeof ROUTES)[keyof typeof ROUTES];
