import {createClient} from 'npm:@supabase/supabase-js@2.114.0';
import {PDFDocument,rgb} from 'npm:pdf-lib@1.17.1';
import fontkit from 'npm:@pdf-lib/fontkit@1.1.1';
import {drawArabicText,measureArabicText} from 'npm:arabic-bidi-shaper@0.1.1/pdf-lib';

const BUCKET='enjaz-documents-private';
const FONT_URL='https://raw.githubusercontent.com/notofonts/noto-fonts/ffebf8c1ee449e544955a7e813c54f9b73848eac/hinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf';
const A4:[number,number]=[595.28,841.89];
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type,x-client-info,apikey','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
type J=Record<string,unknown>;
type RenderJob={id:string;workspace_id:string;source_draft_id:string;requested_by:string|null;status:string;service_run_id:string|null;output_document_id:string|null;output_document_version_id:string|null;plan:J|null};
type Draft={id:string;title:string;compiled_content:string;status:string;company_id:string|null;transaction_id:string|null;template_version_id:string;content_checksum:string;fact_snapshot_checksum:string;approved_at:string|null};
let fontPromise:Promise<Uint8Array>|null=null;
const out=(status:number,body:J)=>new Response(JSON.stringify(body),{status,headers:cors});
const object=(v:unknown):J=>v&&typeof v==='object'&&!Array.isArray(v)?v as J:{};
const text=(v:unknown,max=320)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Error('INVALID_INPUT');return v.trim()};
const uuid=(v:unknown)=>{const s=text(v,64);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new Error('INVALID_UUID');return s};
function secret(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern)try{const p=JSON.parse(modern) as Record<string,string>;if(p.default)return p.default}catch{}const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(legacy)return legacy;throw new Error('SERVER_SECRET_UNAVAILABLE')}
function publicKey(){const k=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY');if(k)return k;throw new Error('SERVER_PUBLIC_KEY_UNAVAILABLE')}
async function sha256(bytes:Uint8Array){const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function arabicFont(){if(!fontPromise)fontPromise=(async()=>{const res=await fetch(FONT_URL,{headers:{Accept:'font/ttf,application/octet-stream'}});if(!res.ok)throw new Error('FONT_FETCH_FAILED');const bytes=new Uint8Array(await res.arrayBuffer());if(bytes.byteLength<100_000||bytes.byteLength>1_000_000)throw new Error('FONT_INVALID');return bytes})();return fontPromise}
function sanitizeFileName(value:string){const base=value.replace(/[\\/\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,180)||'enjaz-official-document';return `${base}.pdf`}
function wrapParagraph(value:string,font:Parameters<typeof measureArabicText>[1],size:number,maxWidth:number){const source=value.replace(/\s+/g,' ').trim();if(!source)return [''];const words=source.split(' '),lines:string[]=[];let line='';for(const word of words){const candidate=line?`${line} ${word}`:word;if(measureArabicText(candidate,font,size)<=maxWidth){line=candidate;continue}if(line)lines.push(line);if(measureArabicText(word,font,size)<=maxWidth){line=word;continue}let chunk='';for(const char of [...word]){const next=chunk+char;if(chunk&&measureArabicText(next,font,size)>maxWidth){lines.push(chunk);chunk=char}else chunk=next}line=chunk}if(line)lines.push(line);return lines.length?lines:['']}
async function renderPdf(draft:Draft){const bytes=await arabicFont(),pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);const font=await pdf.embedFont(bytes,{subset:true});const approved=draft.approved_at?new Date(draft.approved_at):new Date('2026-01-01T00:00:00.000Z'),safeDate=Number.isFinite(approved.getTime())?approved:new Date('2026-01-01T00:00:00.000Z');pdf.setTitle(draft.title);pdf.setAuthor('ENJAZ');pdf.setCreator('ENJAZ Document Factory 10.3');pdf.setProducer('ENJAZ Governed Arabic PDF Renderer');pdf.setCreationDate(safeDate);pdf.setModificationDate(safeDate);
 const margin=56,right=A4[0]-margin,maxWidth=A4[0]-margin*2,bodySize=14,lineHeight=24,titleSize=18;let page=pdf.addPage(A4),y=A4[1]-64;
 const footer=()=>{page.drawLine({start:{x:margin,y:45},end:{x:A4[0]-margin,y:45},thickness:.45,color:rgb(.74,.76,.8)});drawArabicText(page,'مستند مولّد ومعتمد عبر إنجاز',{font,size:9,x:right,y:28,color:rgb(.34,.37,.43)})};
 const nextPage=()=>{footer();page=pdf.addPage(A4);y=A4[1]-64};
 drawArabicText(page,draft.title,{font,size:titleSize,x:right,y,color:rgb(.08,.1,.16)});y-=38;page.drawLine({start:{x:margin,y:y+12},end:{x:right,y:y+12},thickness:1,color:rgb(.86,.72,.15)});y-=12;
 const paragraphs=draft.compiled_content.replace(/\r\n?/g,'\n').split('\n');for(const paragraph of paragraphs){if(!paragraph.trim()){y-=lineHeight*.55;if(y<78)nextPage();continue}for(const line of wrapParagraph(paragraph,font,bodySize,maxWidth)){if(y<78)nextPage();drawArabicText(page,line,{font,size:bodySize,x:right,y,color:rgb(.1,.12,.17)});y-=lineHeight}y-=5}footer();
 const saved=await pdf.save({useObjectStreams:false,addDefaultPage:false,objectsPerTick:50});if(saved.byteLength<1000||String.fromCharCode(...saved.slice(0,5))!=='%PDF-')throw new Error('PDF_INVALID');return new Uint8Array(saved)}
async function safeFail(admin:ReturnType<typeof createClient>,jobId:string,runId:string,code:string,operationId?:string,path?:string){try{if(path)await admin.storage.from(BUCKET).remove([path]);if(operationId)await admin.rpc('fail_document_upload_v1',{p_operation_id:operationId,p_failure_code:code.slice(0,160)});await admin.rpc('fail_document_render_v1',{p_job_id:jobId,p_service_run_id:runId,p_failure_code:code.slice(0,160)})}catch{/* failure evidence remains in the original render path */}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return out(405,{ok:false,error:'METHOD_NOT_ALLOWED'});let stage='input',jobId='',runId='',operationId='',storagePath='';let admin:ReturnType<typeof createClient>|null=null;try{const len=Number(req.headers.get('content-length')||'0');if(Number.isFinite(len)&&len>32768)return out(413,{ok:false,error:'REQUEST_TOO_LARGE'});const auth=req.headers.get('authorization')||'';if(!/^Bearer\s+\S+$/i.test(auth))return out(401,{ok:false,error:'AUTH_REQUIRED'});const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SERVER_URL_UNAVAILABLE');const user=createClient(url,publicKey(),{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),who=await user.auth.getUser();if(who.error||!who.data.user)return out(401,{ok:false,error:'AUTH_INVALID'});admin=createClient(url,secret(),{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const body=object(await req.json()),workspaceId=uuid(body.workspaceId);jobId=uuid(body.jobId);
 stage='job_authority';const got=await user.from('pdf_jobs').select('id,workspace_id,source_draft_id,requested_by,status,service_run_id,output_document_id,output_document_version_id,plan').eq('id',jobId).eq('workspace_id',workspaceId).single();if(got.error||!got.data)return out(404,{ok:false,error:'RENDER_JOB_NOT_FOUND'});const job=got.data as RenderJob;if(job.requested_by!==who.data.user.id)return out(403,{ok:false,error:'RENDER_JOB_ACTOR_MISMATCH'});if(object(job.plan).schema!=='enjaz.document-render.v1')return out(409,{ok:false,error:'RENDER_JOB_SCHEMA_INVALID'});if(job.status==='succeeded')return out(200,{ok:true,jobId,status:'succeeded',documentId:job.output_document_id,documentVersionId:job.output_document_version_id,wasDuplicate:true});if(job.status==='failed'||job.status==='cancelled')return out(409,{ok:false,error:'RENDER_JOB_TERMINAL'});if(job.status!=='queued'&&job.status!=='running')return out(409,{ok:false,error:'RENDER_JOB_STATE_INVALID'});
 stage='draft';const dg=await admin.from('document_drafts').select('id,title,compiled_content,status,company_id,transaction_id,template_version_id,content_checksum,fact_snapshot_checksum,approved_at').eq('workspace_id',workspaceId).eq('id',job.source_draft_id).single();if(dg.error||!dg.data)throw new Error('DRAFT_NOT_FOUND');const draft=dg.data as Draft;if(draft.status!=='approved')throw new Error('DRAFT_NOT_APPROVED');
 runId=job.status==='running'&&job.service_run_id?job.service_run_id:`edge:${crypto.randomUUID()}`;if(job.status==='queued'){stage='mark_running';const marked=await admin.rpc('mark_document_render_running_v1',{p_job_id:jobId,p_service_run_id:runId});if(marked.error)throw marked.error}
 stage='pdf';const pdf=await renderPdf(draft),checksum=await sha256(pdf);operationId=jobId;const fileName=sanitizeFileName(draft.title);
 stage='prepare_vault';const prep=await user.rpc('prepare_document_upload_v1',{p_workspace_id:workspaceId,p_operation_id:operationId,p_title:draft.title,p_original_file_name:fileName,p_mime_type:'application/pdf',p_byte_size:pdf.byteLength,p_document_id:null,p_document_type:'generated-official',p_company_id:draft.company_id,p_transaction_id:draft.transaction_id,p_checksum:checksum});if(prep.error)throw prep.error;const claim=object(prep.data);if(claim.bucket!==BUCKET)throw new Error('VAULT_BUCKET_DRIFT');storagePath=text(claim.path,1200);const documentId=uuid(claim.documentId);
 stage='store';const existing=await admin.storage.from(BUCKET).download(storagePath);if(!existing.error&&existing.data){const old=new Uint8Array(await existing.data.arrayBuffer());if(old.byteLength!==pdf.byteLength||await sha256(old)!==checksum)throw new Error('OUTPUT_OBJECT_DRIFT')}else{const uploaded=await admin.storage.from(BUCKET).upload(storagePath,pdf,{contentType:'application/pdf',cacheControl:'3600',upsert:false});if(uploaded.error)throw uploaded.error}
 stage='ack_vault';const ack=await admin.rpc('acknowledge_document_upload_v1',{p_operation_id:operationId,p_storage_path:storagePath,p_actual_byte_size:pdf.byteLength,p_actual_mime_type:'application/pdf'});if(ack.error)throw ack.error;const ackData=object(ack.data),documentVersionId=uuid(ackData.versionId);
 stage='complete';const completed=await admin.rpc('complete_document_render_v1',{p_job_id:jobId,p_service_run_id:runId,p_document_id:documentId,p_document_version_id:documentVersionId});if(completed.error)throw completed.error;return out(200,{ok:true,jobId,status:'succeeded',documentId,documentVersionId,byteSize:pdf.byteLength,checksum,wasDuplicate:Boolean(object(completed.data).wasDuplicate)})
 }catch(e){const raw=e instanceof Error?e.message:'UNKNOWN',code=raw.replace(/[^A-Za-z0-9_:-]/g,'_').toUpperCase().slice(0,140)||'UNKNOWN';console.error('enjaz-document-render failed',{stage,code});if(admin&&jobId&&runId)await safeFail(admin,jobId,runId,`RENDER_${stage.toUpperCase()}_${code}`,operationId||undefined,storagePath||undefined);if(['INVALID_INPUT','INVALID_UUID'].includes(raw))return out(400,{ok:false,error:raw});return out(500,{ok:false,error:`DOCUMENT_RENDER_${stage.toUpperCase()}_FAILED`})}});
