import {createClient} from 'npm:@supabase/supabase-js@2.114.0';
import {PDFDocument,rgb} from 'npm:pdf-lib@1.17.1';
import fontkit from 'npm:@pdf-lib/fontkit@1.1.1';
import QRCode from 'npm:qrcode@1.5.4';
import {drawArabicText} from 'npm:arabic-bidi-shaper@0.1.1/pdf-lib';

const BUCKET='enjaz-documents-private';
const FONT_URL='https://raw.githubusercontent.com/notofonts/noto-fonts/ffebf8c1ee449e544955a7e813c54f9b73848eac/hinted/ttf/NotoNaskhArabic/NotoNaskhArabic-Regular.ttf';
const A4:[number,number]=[595.28,841.89];
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type,x-client-info,apikey','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
type J=Record<string,unknown>;
type RenderJob={id:string;workspace_id:string;source_draft_id:string;requested_by:string|null;status:string;service_run_id:string|null;output_document_id:string|null;output_document_version_id:string|null;plan:J|null};
type Draft={id:string;title:string;compiled_content:string;status:string;company_id:string|null;transaction_id:string|null;template_version_id:string;content_checksum:string;fact_snapshot_checksum:string;fact_snapshot:J|null;approved_at:string|null};
type UploadSession={id:string;workspace_id:string;document_id:string;document_version_id:string|null;state:string;storage_path:string;mime_type:string;byte_size:number|string;checksum:string|null;original_file_name:string;title:string;document_type:string|null;company_id:string|null;transaction_id:string|null;created_by:string};
type PackItem={position:number;draftId:string;documentId:string;documentVersionId:string;contentChecksum:string;factSnapshotChecksum:string};
type Pack={schema?:string;packId:string;transactionId:string;title:string;status:string;requestedBy:string;manifestChecksum:string;outputDocumentId:string|null;outputDocumentVersionId:string|null;failureCode:string|null;createdAt:string;updatedAt:string;items:PackItem[]};
let fontPromise:Promise<Uint8Array>|null=null;
const out=(status:number,body:J)=>new Response(JSON.stringify(body),{status,headers:cors});
const object=(v:unknown):J=>v&&typeof v==='object'&&!Array.isArray(v)?v as J:{};
const text=(v:unknown,max=320)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>max)throw new Error('INVALID_INPUT');return v.trim()};
const uuid=(v:unknown)=>{const s=text(v,64);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new Error('INVALID_UUID');return s};
const sameNullable=(a:unknown,b:unknown)=>(a??null)===(b??null);
function secret(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern)try{const p=JSON.parse(modern) as Record<string,string>;if(p.default)return p.default}catch{/* fall through */}const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(legacy)return legacy;throw new Error('SERVER_SECRET_UNAVAILABLE')}
function publicKey(){const modern=Deno.env.get('SUPABASE_PUBLISHABLE_KEYS');if(modern)try{const p=JSON.parse(modern) as Record<string,string>;if(p.default)return p.default}catch{/* fall through */}const legacy=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY');if(legacy)return legacy;throw new Error('SERVER_PUBLIC_KEY_UNAVAILABLE')}
async function sha256(bytes:Uint8Array){const digest=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function arabicFont(){if(!fontPromise)fontPromise=(async()=>{const res=await fetch(FONT_URL,{headers:{Accept:'font/ttf,application/octet-stream'}});if(!res.ok)throw new Error('FONT_FETCH_FAILED');const bytes=new Uint8Array(await res.arrayBuffer());if(bytes.byteLength<100_000||bytes.byteLength>1_000_000)throw new Error('FONT_INVALID');return bytes})();return fontPromise}
function sanitizeFileName(value:string){const base=value.replace(/[\\/\u0000-\u001f\u007f]/g,' ').replace(/\s+/g,' ').trim().slice(0,180)||'enjaz-official-document';return `${base}.pdf`}
function wrapParagraph(value:string,size:number,maxWidth:number){const source=value.replace(/\s+/g,' ').trim();if(!source)return [''];const maxChars=Math.max(10,Math.floor(maxWidth/(size*.52))),words=source.split(' '),lines:string[]=[];let line='',used=0;for(const word of words){const chars=[...word];if(chars.length>maxChars){if(line){lines.push(line);line='';used=0}for(let i=0;i<chars.length;i+=maxChars)lines.push(chars.slice(i,i+maxChars).join(''));continue}const next=chars.length+(line?1:0);if(line&&used+next>maxChars){lines.push(line);line=word;used=chars.length}else{line=line?`${line} ${word}`:word;used+=next}}if(line)lines.push(line);return lines.length?lines:['']}
function truthy(v:unknown){if(v==null)return false;if(typeof v==='boolean')return v;if(typeof v==='number')return v!==0;const s=String(v).trim().toLowerCase();return Boolean(s&&!['0','false','null','undefined','لا','none'].includes(s))}
function repeatValues(v:unknown){if(Array.isArray(v))return v.map(x=>String(x??'')).filter(Boolean);if(typeof v!=='string')return v==null?[]:[String(v)];const s=v.trim();if(!s)return[];try{const parsed=JSON.parse(s);if(Array.isArray(parsed))return parsed.map(x=>typeof x==='string'?x:JSON.stringify(x))}catch{/* scalar */}return s.includes('\n')?s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean):s.includes(',')?s.split(',').map(x=>x.trim()).filter(Boolean):[s]}
function applyAdvancedLayout(content:string,facts:J){let result=content;for(let pass=0;pass<12;pass++){const before=result;result=result.replace(/\[\[IF\s+([A-Za-z][A-Za-z0-9_.-]{0,127})\]\]([\s\S]*?)\[\[END\]\]/g,(_,key:string,body:string)=>truthy(facts[key])?body:'');result=result.replace(/\[\[EACH\s+([A-Za-z][A-Za-z0-9_.-]{0,127})\]\]([\s\S]*?)\[\[END\]\]/g,(_,key:string,body:string)=>repeatValues(facts[key]).map(value=>body.split('[[ITEM]]').join(value)).join('\n'));if(before===result)break}if(/\[\[(?:IF|EACH|END|ITEM)\b/i.test(result))throw new Error('LAYOUT_DIRECTIVE_INVALID');return result}
async function qrPng(payload:string){const data=await QRCode.toDataURL(payload,{errorCorrectionLevel:'M',margin:0,width:160});const encoded=data.slice(data.indexOf(',')+1),raw=atob(encoded),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}

async function renderOfficialPdf(draft:Draft){
  const bytes=await arabicFont(),pdf=await PDFDocument.create();pdf.registerFontkit(fontkit);
  const font=await pdf.embedFont(bytes);
  const qr=await pdf.embedPng(await qrPng(`ENJAZ:DRAFT:${draft.id}`));
  const approved=draft.approved_at?new Date(draft.approved_at):new Date('2026-01-01T00:00:00.000Z'),safeDate=Number.isFinite(approved.getTime())?approved:new Date('2026-01-01T00:00:00.000Z');
  pdf.setTitle(draft.title);pdf.setAuthor('ENJAZ');pdf.setCreator('ENJAZ Document Factory 10.3');pdf.setProducer('ENJAZ Governed Arabic PDF Renderer');pdf.setCreationDate(safeDate);pdf.setModificationDate(safeDate);
  const margin=56,right=A4[0]-margin,maxWidth=A4[0]-margin*2,bodySize=14,lineHeight=24,titleSize=18;let page=pdf.addPage(A4),y=A4[1]-64;
  const footer=()=>{page.drawLine({start:{x:margin,y:49},end:{x:A4[0]-margin,y:49},thickness:.45,color:rgb(.74,.76,.8)});page.drawImage(qr,{x:margin,y:9,width:34,height:34});drawArabicText(page,'مستند مولّد ومعتمد عبر إنجاز',{font,size:9,x:right,y:30,color:rgb(.34,.37,.43)});page.drawText(draft.id.toUpperCase(),{font,size:6,x:margin+42,y:26,color:rgb(.42,.44,.5)})};
  const nextPage=()=>{footer();page=pdf.addPage(A4);y=A4[1]-64};
  const drawTextLine=(value:string)=>{for(const line of wrapParagraph(value,bodySize,maxWidth)){if(y<86)nextPage();drawArabicText(page,line,{font,size:bodySize,x:right,y,color:rgb(.1,.12,.17)});y-=lineHeight}y-=5};
  const drawTable=(rows:string[][])=>{const cols=Math.max(1,...rows.map(r=>r.length)),cellWidth=maxWidth/cols;for(const row of rows){const cells=Array.from({length:cols},(_,i)=>row[i]??''),wrapped=cells.map(c=>wrapParagraph(c,11,cellWidth-12)),rowHeight=Math.max(28,...wrapped.map(lines=>lines.length*17+10));if(y-rowHeight<86)nextPage();let x=margin;for(let c=0;c<cols;c++){page.drawRectangle({x,y:y-rowHeight,width:cellWidth,height:rowHeight,borderColor:rgb(.72,.74,.78),borderWidth:.55});let cy=y-16;for(const line of wrapped[c]){drawArabicText(page,line,{font,size:11,x:x+cellWidth-6,y:cy,color:rgb(.1,.12,.17)});cy-=17}x+=cellWidth}y-=rowHeight}y-=10};
  drawArabicText(page,draft.title,{font,size:titleSize,x:right,y,color:rgb(.08,.1,.16)});y-=38;page.drawLine({start:{x:margin,y:y+12},end:{x:right,y:y+12},thickness:1,color:rgb(.86,.72,.15)});y-=12;
  const rendered=applyAdvancedLayout(draft.compiled_content,object(draft.fact_snapshot)),lines=rendered.replace(/\r\n?/g,'\n').split('\n');
  for(let i=0;i<lines.length;){if(lines[i].trim().startsWith('|')&&lines[i].trim().endsWith('|')){const rows:string[][]=[];while(i<lines.length&&lines[i].trim().startsWith('|')&&lines[i].trim().endsWith('|')){const cells=lines[i].trim().slice(1,-1).split('|').map(x=>x.trim());if(!cells.every(c=>/^:?-{3,}:?$/.test(c)))rows.push(cells);i++}if(rows.length)drawTable(rows);continue}if(!lines[i].trim()){y-=lineHeight*.55;if(y<86)nextPage();i++;continue}drawTextLine(lines[i]);i++}
  footer();const saved=await pdf.save({useObjectStreams:false,addDefaultPage:false,objectsPerTick:100});if(saved.byteLength<1000||String.fromCharCode(...saved.slice(0,5))!=='%PDF-')throw new Error('PDF_INVALID');return new Uint8Array(saved)
}

async function renderSubmissionPack(admin:ReturnType<typeof createClient>,pack:Pack){
  const pdf=await PDFDocument.create(),fontBytes=await arabicFont();pdf.registerFontkit(fontkit);const font=await pdf.embedFont(fontBytes),qr=await pdf.embedPng(await qrPng(`ENJAZ:PACK:${pack.packId}`)),created=new Date(pack.createdAt||'2026-01-01T00:00:00.000Z');
  pdf.setTitle(pack.title);pdf.setAuthor('ENJAZ');pdf.setCreator('ENJAZ Document Factory 10.3');pdf.setProducer('ENJAZ Governed Submission Pack Builder');pdf.setCreationDate(Number.isFinite(created.getTime())?created:new Date('2026-01-01T00:00:00.000Z'));pdf.setModificationDate(Number.isFinite(created.getTime())?created:new Date('2026-01-01T00:00:00.000Z'));
  const cover=pdf.addPage(A4),right=A4[0]-56;drawArabicText(cover,pack.title,{font,size:22,x:right,y:A4[1]-90,color:rgb(.08,.1,.16)});drawArabicText(cover,'حزمة تقديم رسمية — إنجاز',{font,size:13,x:right,y:A4[1]-126,color:rgb(.28,.3,.36)});cover.drawImage(qr,{x:56,y:A4[1]-205,width:78,height:78});cover.drawText(pack.packId.toUpperCase(),{font,size:7,x:56,y:A4[1]-220,color:rgb(.42,.44,.5)});let y=A4[1]-270;
  for(const item of [...pack.items].sort((a,b)=>a.position-b.position)){drawArabicText(cover,`المرفق ${item.position} — مرجع ${item.draftId}`,{font,size:11,x:right,y,color:rgb(.12,.14,.19)});y-=24}
  cover.drawText(`MANIFEST ${pack.manifestChecksum}`,{font,size:6,x:56,y:38,color:rgb(.44,.46,.52)});
  for(const item of [...pack.items].sort((a,b)=>a.position-b.position)){const version=await admin.from('document_versions').select('id,workspace_id,document_id,storage_path,mime_type,checksum').eq('id',item.documentVersionId).eq('document_id',item.documentId).single();if(version.error||!version.data||String(version.data.mime_type).toLowerCase()!=='application/pdf')throw new Error('PACK_SOURCE_VERSION_INVALID');const downloaded=await admin.storage.from(BUCKET).download(String(version.data.storage_path));if(downloaded.error||!downloaded.data)throw new Error('PACK_SOURCE_OBJECT_MISSING');const sourceBytes=new Uint8Array(await downloaded.data.arrayBuffer());if(version.data.checksum&&await sha256(sourceBytes)!==version.data.checksum)throw new Error('PACK_SOURCE_OBJECT_DRIFT');const source=await PDFDocument.load(sourceBytes,{ignoreEncryption:false});const copied=await pdf.copyPages(source,source.getPageIndices());for(const p of copied)pdf.addPage(p)}
  const saved=await pdf.save({useObjectStreams:false,addDefaultPage:false,objectsPerTick:100});if(saved.byteLength<1000||String.fromCharCode(...saved.slice(0,5))!=='%PDF-')throw new Error('PACK_PDF_INVALID');return new Uint8Array(saved)
}

async function storedObject(admin:ReturnType<typeof createClient>,path:string,pdf:Uint8Array,checksum:string,required:boolean){const existing=await admin.storage.from(BUCKET).download(path);if(existing.error||!existing.data){if(required)throw new Error('ACKNOWLEDGED_OUTPUT_OBJECT_MISSING');return false}const old=new Uint8Array(await existing.data.arrayBuffer());if(old.byteLength!==pdf.byteLength||await sha256(old)!==checksum)throw new Error('OUTPUT_OBJECT_DRIFT');return true}
function assertSession(session:UploadSession,workspaceId:string,userId:string,draft:Draft,fileName:string,pdf:Uint8Array,checksum:string){if(session.workspace_id!==workspaceId||session.created_by!==userId||session.title!==draft.title||session.original_file_name!==fileName||session.mime_type.toLowerCase()!=='application/pdf'||Number(session.byte_size)!==pdf.byteLength||session.checksum!==checksum||session.document_type!=='generated-official'||!sameNullable(session.company_id,draft.company_id)||!sameNullable(session.transaction_id,draft.transaction_id))throw new Error('VAULT_SESSION_DRIFT')}
function assertPackSession(session:UploadSession,workspaceId:string,userId:string,pack:Pack,fileName:string,pdf:Uint8Array,checksum:string){if(session.workspace_id!==workspaceId||session.created_by!==userId||session.title!==pack.title||session.original_file_name!==fileName||session.mime_type.toLowerCase()!=='application/pdf'||Number(session.byte_size)!==pdf.byteLength||session.checksum!==checksum||session.document_type!=='submission-pack'||session.transaction_id!==pack.transactionId)throw new Error('PACK_VAULT_SESSION_DRIFT')}
async function safeFail(admin:ReturnType<typeof createClient>,jobId:string,runId:string,code:string,operationId?:string,path?:string){try{if(path)await admin.storage.from(BUCKET).remove([path]);if(operationId)await admin.rpc('fail_document_upload_v1',{p_operation_id:operationId,p_failure_code:code.slice(0,160)});await admin.rpc('fail_document_render_v1',{p_job_id:jobId,p_service_run_id:runId,p_failure_code:code.slice(0,160)})}catch{/* evidence remains */}}
async function safePackFail(admin:ReturnType<typeof createClient>,packId:string,runId:string,code:string,operationId?:string,path?:string){try{if(path)await admin.storage.from(BUCKET).remove([path]);if(operationId)await admin.rpc('fail_document_upload_v1',{p_operation_id:operationId,p_failure_code:code.slice(0,160)});await admin.rpc('fail_document_submission_pack_v1',{p_pack_id:packId,p_service_run_id:runId,p_failure_code:code.slice(0,160)})}catch{/* evidence remains */}}

async function handlePack(body:J,workspaceId:string,userId:string,user:ReturnType<typeof createClient>,admin:ReturnType<typeof createClient>){
  const packId=uuid(body.packId),got=await user.rpc('get_document_submission_pack_v1',{p_workspace_id:workspaceId,p_pack_id:packId});if(got.error||!got.data)return out(404,{ok:false,error:'SUBMISSION_PACK_NOT_FOUND'});const pack=got.data as Pack;if(pack.requestedBy!==userId)return out(403,{ok:false,error:'SUBMISSION_PACK_ACTOR_MISMATCH'});if(pack.status==='succeeded')return out(200,{ok:true,mode:'pack',packId,status:'succeeded',documentId:pack.outputDocumentId,documentVersionId:pack.outputDocumentVersionId,wasDuplicate:true});if(pack.status==='failed')return out(409,{ok:false,error:'SUBMISSION_PACK_TERMINAL'});
  let runId='',operationId='',storagePath='',preserveForRetry=false;
  try{runId=pack.status==='running'?`pack:${packId}`:`pack:${crypto.randomUUID()}`;if(pack.status==='queued'){const marked=await admin.rpc('mark_document_submission_pack_running_v1',{p_pack_id:packId,p_service_run_id:runId});if(marked.error)throw marked.error}else if(pack.status!=='running')throw new Error('PACK_STATE_INVALID');else{const refreshed=await user.rpc('get_document_submission_pack_v1',{p_workspace_id:workspaceId,p_pack_id:packId});if(refreshed.error||!refreshed.data)throw refreshed.error??new Error('PACK_REFRESH_FAILED');Object.assign(pack,refreshed.data);const storedRun=String((await admin.from('document_submission_packs').select('service_run_id').eq('id',packId).single()).data?.service_run_id||'');runId=storedRun||runId}preserveForRetry=true;
    const pdf=await renderSubmissionPack(admin,pack),checksum=await sha256(pdf);operationId=packId;const fileName=sanitizeFileName(pack.title);let documentId='',documentVersionId='';const existing=await admin.from('document_upload_sessions').select('id,workspace_id,document_id,document_version_id,state,storage_path,mime_type,byte_size,checksum,original_file_name,title,document_type,company_id,transaction_id,created_by').eq('id',operationId).maybeSingle();if(existing.error)throw existing.error;
    if(existing.data){const session=existing.data as UploadSession;assertPackSession(session,workspaceId,userId,pack,fileName,pdf,checksum);storagePath=text(session.storage_path,1200);documentId=uuid(session.document_id);if(session.state==='acknowledged'){documentVersionId=uuid(session.document_version_id);await storedObject(admin,storagePath,pdf,checksum,true)}else if(session.state!=='prepared')throw new Error('PACK_VAULT_SESSION_TERMINAL')}else{const prep=await user.rpc('prepare_document_upload_v1',{p_workspace_id:workspaceId,p_operation_id:operationId,p_title:pack.title,p_original_file_name:fileName,p_mime_type:'application/pdf',p_byte_size:pdf.byteLength,p_document_id:null,p_document_type:'submission-pack',p_company_id:null,p_transaction_id:pack.transactionId,p_checksum:checksum});if(prep.error)throw prep.error;const claim=object(prep.data);if(claim.bucket!==BUCKET)throw new Error('VAULT_BUCKET_DRIFT');storagePath=text(claim.path,1200);documentId=uuid(claim.documentId)}
    if(!documentVersionId){if(!await storedObject(admin,storagePath,pdf,checksum,false)){const uploaded=await admin.storage.from(BUCKET).upload(storagePath,pdf,{contentType:'application/pdf',cacheControl:'3600',upsert:false});if(uploaded.error)throw uploaded.error}const ack=await admin.rpc('acknowledge_document_upload_v1',{p_operation_id:operationId,p_storage_path:storagePath,p_actual_byte_size:pdf.byteLength,p_actual_mime_type:'application/pdf'});if(ack.error)throw ack.error;documentVersionId=uuid(object(ack.data).versionId)}
    const completed=await admin.rpc('complete_document_submission_pack_v1',{p_pack_id:packId,p_service_run_id:runId,p_document_id:documentId,p_document_version_id:documentVersionId,p_manifest_checksum:pack.manifestChecksum});if(completed.error)throw completed.error;return out(200,{ok:true,mode:'pack',packId,status:'succeeded',documentId,documentVersionId,byteSize:pdf.byteLength,checksum,manifestChecksum:pack.manifestChecksum,wasDuplicate:Boolean(object(completed.data).wasDuplicate)})
  }catch(e){const raw=e instanceof Error?e.message:'UNKNOWN',code=raw.replace(/[^A-Za-z0-9_:-]/g,'_').toUpperCase().slice(0,140)||'UNKNOWN';console.error('submission pack render failed',{code,preserveForRetry});if(!preserveForRetry&&packId&&runId)await safePackFail(admin,packId,runId,`PACK_${code}`,operationId||undefined,storagePath||undefined);return out(raw.includes('DRIFT')||raw.includes('TERMINAL')?409:503,{ok:false,error:'SUBMISSION_PACK_RENDER_RETRYABLE',retryable:true})}
}

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return out(405,{ok:false,error:'METHOD_NOT_ALLOWED'});
  let stage='input',jobId='',runId='',operationId='',storagePath='',preserveForRetry=false;let admin:ReturnType<typeof createClient>|null=null;
  try{const len=Number(req.headers.get('content-length')||'0');if(Number.isFinite(len)&&len>32768)return out(413,{ok:false,error:'REQUEST_TOO_LARGE'});const auth=req.headers.get('authorization')||'';if(!/^Bearer\s+\S+$/i.test(auth))return out(401,{ok:false,error:'AUTH_REQUIRED'});const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SERVER_URL_UNAVAILABLE');const user=createClient(url,publicKey(),{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),who=await user.auth.getUser();if(who.error||!who.data.user)return out(401,{ok:false,error:'AUTH_INVALID'});admin=createClient(url,secret(),{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const body=object(await req.json()),workspaceId=uuid(body.workspaceId);if(body.mode==='pack')return await handlePack(body,workspaceId,who.data.user.id,user,admin);jobId=uuid(body.jobId);
    stage='job_authority';const got=await user.from('pdf_jobs').select('id,workspace_id,source_draft_id,requested_by,status,service_run_id,output_document_id,output_document_version_id,plan').eq('id',jobId).eq('workspace_id',workspaceId).single();if(got.error||!got.data)return out(404,{ok:false,error:'RENDER_JOB_NOT_FOUND'});const job=got.data as RenderJob;if(job.requested_by!==who.data.user.id)return out(403,{ok:false,error:'RENDER_JOB_ACTOR_MISMATCH'});if(object(job.plan).schema!=='enjaz.document-render.v1')return out(409,{ok:false,error:'RENDER_JOB_SCHEMA_INVALID'});if(job.status==='succeeded')return out(200,{ok:true,jobId,status:'succeeded',documentId:job.output_document_id,documentVersionId:job.output_document_version_id,wasDuplicate:true});if(job.status==='failed'||job.status==='cancelled')return out(409,{ok:false,error:'RENDER_JOB_TERMINAL'});if(job.status!=='queued'&&job.status!=='running')return out(409,{ok:false,error:'RENDER_JOB_STATE_INVALID'});
    stage='draft';const dg=await admin.from('document_drafts').select('id,title,compiled_content,status,company_id,transaction_id,template_version_id,content_checksum,fact_snapshot_checksum,fact_snapshot,approved_at').eq('workspace_id',workspaceId).eq('id',job.source_draft_id).single();if(dg.error||!dg.data)throw new Error('DRAFT_NOT_FOUND');const draft=dg.data as Draft;if(draft.status!=='approved')throw new Error('DRAFT_NOT_APPROVED');
    runId=job.status==='running'&&job.service_run_id?job.service_run_id:`edge:${crypto.randomUUID()}`;if(job.status==='queued'){stage='mark_running';const marked=await admin.rpc('mark_document_render_running_v1',{p_job_id:jobId,p_service_run_id:runId});if(marked.error)throw marked.error}preserveForRetry=true;
    stage='pdf';const pdf=await renderOfficialPdf(draft),checksum=await sha256(pdf);operationId=jobId;const fileName=sanitizeFileName(draft.title);let documentId='',documentVersionId='';
    stage='vault_state';const existingSession=await admin.from('document_upload_sessions').select('id,workspace_id,document_id,document_version_id,state,storage_path,mime_type,byte_size,checksum,original_file_name,title,document_type,company_id,transaction_id,created_by').eq('id',operationId).maybeSingle();if(existingSession.error)throw existingSession.error;
    if(existingSession.data){const session=existingSession.data as UploadSession;assertSession(session,workspaceId,who.data.user.id,draft,fileName,pdf,checksum);storagePath=text(session.storage_path,1200);documentId=uuid(session.document_id);if(session.state==='acknowledged'){stage='recover_acknowledged';documentVersionId=uuid(session.document_version_id);await storedObject(admin,storagePath,pdf,checksum,true)}else if(session.state!=='prepared')throw new Error('VAULT_SESSION_TERMINAL')}else{stage='prepare_vault';const prep=await user.rpc('prepare_document_upload_v1',{p_workspace_id:workspaceId,p_operation_id:operationId,p_title:draft.title,p_original_file_name:fileName,p_mime_type:'application/pdf',p_byte_size:pdf.byteLength,p_document_id:null,p_document_type:'generated-official',p_company_id:draft.company_id,p_transaction_id:draft.transaction_id,p_checksum:checksum});if(prep.error)throw prep.error;const claim=object(prep.data);if(claim.bucket!==BUCKET)throw new Error('VAULT_BUCKET_DRIFT');storagePath=text(claim.path,1200);documentId=uuid(claim.documentId)}
    if(!documentVersionId){stage='store';if(!await storedObject(admin,storagePath,pdf,checksum,false)){const uploaded=await admin.storage.from(BUCKET).upload(storagePath,pdf,{contentType:'application/pdf',cacheControl:'3600',upsert:false});if(uploaded.error)throw uploaded.error}stage='ack_vault';const ack=await admin.rpc('acknowledge_document_upload_v1',{p_operation_id:operationId,p_storage_path:storagePath,p_actual_byte_size:pdf.byteLength,p_actual_mime_type:'application/pdf'});if(ack.error)throw ack.error;documentVersionId=uuid(object(ack.data).versionId)}
    stage='complete';const completed=await admin.rpc('complete_document_render_v1',{p_job_id:jobId,p_service_run_id:runId,p_document_id:documentId,p_document_version_id:documentVersionId});if(completed.error)throw completed.error;return out(200,{ok:true,jobId,status:'succeeded',documentId,documentVersionId,byteSize:pdf.byteLength,checksum,identity:`ENJAZ:DRAFT:${draft.id}`,wasDuplicate:Boolean(object(completed.data).wasDuplicate),wasRecovered:job.status==='running'})
  }catch(e){const raw=e instanceof Error?e.message:'UNKNOWN',code=raw.replace(/[^A-Za-z0-9_:-]/g,'_').toUpperCase().slice(0,140)||'UNKNOWN';console.error('enjaz-document-render failed',{stage,code,preserveForRetry});if(admin&&jobId&&runId&&!preserveForRetry)await safeFail(admin,jobId,runId,`RENDER_${stage.toUpperCase()}_${code}`,operationId||undefined,storagePath||undefined);if(['INVALID_INPUT','INVALID_UUID'].includes(raw))return out(400,{ok:false,error:raw});if(preserveForRetry)return out(raw.includes('DRIFT')||raw.includes('TERMINAL')?409:503,{ok:false,error:`DOCUMENT_RENDER_${stage.toUpperCase()}_RETRYABLE`,retryable:true});return out(500,{ok:false,error:`DOCUMENT_RENDER_${stage.toUpperCase()}_FAILED`})}
});
