export const DESIGN_TOKEN_GROUPS = Object.freeze({
  semantic: [
    '--color-canvas',
    '--color-canvas-soft',
    '--color-surface',
    '--color-surface-raised',
    '--color-surface-muted',
    '--color-border',
    '--color-border-strong',
    '--color-text-primary',
    '--color-text-secondary',
    '--color-text-tertiary',
    '--color-text-on-brand',
    '--color-brand-primary',
    '--color-brand-strong',
    '--color-brand-soft',
    '--color-brand-whisper',
    '--color-brand-wash',
    '--color-accent-teal',
    '--color-accent-teal-text',
    '--color-accent-teal-soft',
    '--color-accent-teal-wash',
    '--color-accent-violet',
    '--color-accent-violet-text',
    '--color-accent-violet-soft',
    '--color-success',
    '--color-success-text',
    '--color-success-soft',
    '--color-warning',
    '--color-warning-text',
    '--color-warning-soft',
    '--color-danger',
    '--color-danger-text',
    '--color-danger-soft',
    '--color-info-text',
    '--color-info-soft',
    '--color-focus',
    '--color-overlay',
  ] as const,
  typography: [
    '--font-family-arabic',
    '--font-family-ui',
    '--font-family-latin',
    '--font-family-numeric',
    '--font-family-mono',
    '--font-size-caption',
    '--font-size-label',
    '--font-size-body',
    '--font-size-body-lg',
    '--font-size-subtitle',
    '--font-size-title-sm',
    '--font-size-title-md',
    '--font-size-title-lg',
    '--font-size-display',
    '--font-size-auth-title',
    '--font-size-brand-mark',
    '--font-size-type-display',
    '--font-weight-regular',
    '--font-weight-medium',
    '--font-weight-bold',
    '--font-weight-heavy',
    '--line-height-none',
    '--line-height-display',
    '--line-height-tight',
    '--line-height-title',
    '--line-height-label',
    '--line-height-caption',
    '--line-height-compact',
    '--line-height-body',
    '--line-height-reading',
    '--tracking-arabic',
    '--tracking-ui',
    '--tracking-tight',
    '--tracking-display',
    '--tracking-latin-tight',
    '--font-variant-numeric',
  ] as const,
  geometry: [
    '--radius-xs',
    '--radius-sm',
    '--radius-md',
    '--radius-lg',
    '--radius-xl',
    '--radius-pill',
    '--space-1',
    '--space-2',
    '--space-3',
    '--space-4',
    '--space-5',
    '--space-6',
    '--space-8',
    '--space-10',
    '--space-12',
    '--space-fluid-page',
    '--space-fluid-panel',
    '--space-fluid-hero',
    '--size-page-min',
    '--size-touch-min',
    '--size-control-lg',
    '--size-mark-lg',
    '--size-visual-xl',
    '--size-demo-lg',
    '--size-demo-md',
    '--size-content-max',
    '--size-foundation-max',
    '--size-auth-max',
    '--measure-title-compact',
    '--measure-reading',
    '--size-grid-card-min',
    '--size-swatch-min',
    '--offset-decor-inline',
    '--offset-decor-block',
    '--text-underline-offset',
    '--border-width-thin',
    '--focus-outline-width',
    '--focus-outline-offset',
    '--z-content',
    '--z-skip-link',
    '--z-overlay',
  ] as const,
  elevation: [
    '--shadow-level-1',
    '--shadow-level-2',
    '--shadow-level-3',
    '--shadow-focus-ring',
    '--gradient-brand',
    '--gradient-canvas',
  ] as const,
  motion: [
    '--duration-fast',
    '--duration-standard',
    '--duration-deliberate',
    '--duration-reduced-motion',
    '--easing-standard',
    '--easing-enter',
    '--easing-exit',
    '--press-translate-y',
    '--press-scale',
    '--opacity-disabled',
    '--opacity-muted',
    '--opacity-subtle',
  ] as const,
  components: [
    '--control-height-default',
    '--control-height-large',
    '--control-radius',
    '--control-padding-block',
    '--control-padding-inline',
    '--control-gap',
    '--control-focus-shadow',
    '--field-background',
    '--field-background-focus',
    '--field-border',
    '--field-border-focus',
    '--field-text',
    '--field-placeholder',
    '--field-error',
    '--field-radius',
    '--field-height',
    '--button-primary-background',
    '--button-primary-text',
    '--button-secondary-background',
    '--button-secondary-text',
    '--button-secondary-border',
    '--button-danger-background',
    '--button-danger-text',
    '--button-ghost-text',
    '--button-radius',
    '--button-shadow',
    '--button-shadow-raised',
    '--card-background',
    '--card-background-muted',
    '--card-border',
    '--card-radius',
    '--card-radius-prominent',
    '--card-padding',
    '--card-shadow',
    '--card-shadow-raised',
    '--badge-radius',
    '--badge-padding-block',
    '--badge-padding-inline',
    '--badge-neutral-background',
    '--badge-neutral-text',
    '--badge-brand-background',
    '--badge-brand-text',
    '--badge-success-background',
    '--badge-success-text',
    '--badge-warning-background',
    '--badge-warning-text',
    '--badge-danger-background',
    '--badge-danger-text',
    '--badge-info-background',
    '--badge-info-text',
    '--sheet-background',
    '--sheet-radius',
    '--sheet-shadow',
    '--overlay-background',
    '--overlay-z',
    '--tabs-background',
    '--tabs-selected-background',
    '--tabs-selected-text',
    '--tabs-border',
    '--switch-track',
    '--switch-track-active',
    '--switch-thumb',
    '--progress-track',
    '--progress-value',
    '--skeleton-background',
    '--navigation-background',
    '--navigation-border',
    '--navigation-touch-target',
  ] as const,
} as const);

export type DesignTokenGroup = keyof typeof DESIGN_TOKEN_GROUPS;
export type DesignTokenName = (typeof DESIGN_TOKEN_GROUPS)[DesignTokenGroup][number];

export function cssVar(token: DesignTokenName): `var(${DesignTokenName})` {
  return `var(${token})`;
}

export const DESIGN_TOKEN_COUNT = Object.values(DESIGN_TOKEN_GROUPS).reduce((total, group) => total + group.length, 0);
