import { useState, useSyncExternalStore } from 'react';
import { getTransactionSavedViewBridgeSnapshot, subscribeTransactionSavedViewBridge } from '../../features/transactions/transactionSavedViewBridge.ts';
import type { TransactionListSort, TransactionListView } from '../../features/transactions/transactionListModel.ts';
import { useSavedViews } from '../../features/searchIntelligence/useSearchIntelligence.ts';

const sorts:readonly TransactionListSort[]=['activity-desc','created-desc','fee-desc','fee-asc'];
function requestFrom(def:any){const view=def?.filters?.view,sort=def?.sort,pageSize=def?.pageSize;if(def?.sourceSchema!=='enjaz.transactions.list.v1'||(view!=='current'&&view!=='stalled'&&view!=='archived')||!sorts.includes(sort)||!Number.isSafeInteger(pageSize)||pageSize<1||pageSize>50)return null;return{view:view as TransactionListView,search:String(def.query??'').slice(0,120),sort:sort as TransactionListSort,pageSize:Number(pageSize)}}

export function TransactionSavedViewsDock(){
 const bridge=useSyncExternalStore(subscribeTransactionSavedViewBridge,getTransactionSavedViewBridgeSnapshot,getTransactionSavedViewBridgeSnapshot),saved=useSavedViews('transactions'),[name,setName]=useState(''),[message,setMessage]=useState<string|null>(null),request=bridge.request;if(!request||!bridge.apply)return null;
 const definition={schema:'enjaz.saved-view.v1' as const,domain:'transactions' as const,query:request.search,filters:{view:request.view},sort:request.sort,dateRange:{from:null,to:null},pageSize:request.pageSize,sourceSchema:'enjaz.transactions.list.v1'};
 const create=async()=>{const n=name.normalize('NFKC').replace(/\s+/g,' ').trim();if(!n)return setMessage('اكتب اسماً للمنظر أولاً.');try{await saved.createPersonal(n,definition);setName('');setMessage('تم حفظ المنظر.')}catch{setMessage(saved.errorMessage??'تعذر حفظ المنظر.')}};
 const apply=(item:(typeof saved.items)[number])=>{const next=requestFrom(item.definition);if(!next)return setMessage('المنظر غير متوافق.');bridge.apply!(next);setMessage(`تم تطبيق «${item.name}».`)};
 const rename=async(item:(typeof saved.items)[number])=>{const n=window.prompt('الاسم الجديد',item.name)?.trim();if(!n||n===item.name)return;try{await saved.rename(item,n);setMessage('تمت إعادة التسمية.')}catch{setMessage(saved.errorMessage??'تعذر إعادة التسمية.')}};
 const remove=async(item:(typeof saved.items)[number])=>{if(!window.confirm(`حذف «${item.name}»؟`))return;try{await saved.remove(item);setMessage('تم الحذف.')}catch{setMessage(saved.errorMessage??'تعذر الحذف.')}};
 return <section className="r2-saved-views" data-phase9-2-saved-views="transactions" aria-label="المناظر المحفوظة"><div className="r2-saved-views__head"><div><span>9.2</span><strong>مناظري الذكية</strong></div><small>يحفظ البحث والمنظر والترتيب فقط، بلا نسخ للنتائج.</small></div><div className="r2-saved-views__create"><input aria-label="اسم المنظر المحفوظ" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="اسم المنظر"/><button type="button" disabled={saved.busyId!==null} onClick={()=>void create()}>حفظ المنظر الحالي</button></div>{saved.status==='loading'?<p className="r2-saved-views__state">جارٍ التحميل…</p>:saved.status==='error'?<p className="r2-saved-views__state is-error">{saved.errorMessage}<button type="button" onClick={saved.retry}>إعادة المحاولة</button></p>:<div className="r2-saved-views__list">{saved.items.length?saved.items.map(item=>{const owned=item.ownerUserId===saved.userId,ok=requestFrom(item.definition)!==null;return <article key={item.id} className="r2-saved-view-chip" data-saved-view-id={item.id}><button type="button" className="r2-saved-view-chip__apply" disabled={!ok||saved.busyId===item.id} onClick={()=>apply(item)}><strong>{item.name}</strong><small>{item.visibility==='personal'?'شخصي':item.visibility==='team'?'فريق':'مساحة العمل'}</small></button>{owned?<span className="r2-saved-view-chip__actions"><button type="button" aria-label="إعادة تسمية" onClick={()=>void rename(item)}>✎</button><button type="button" aria-label="حذف" onClick={()=>void remove(item)}>×</button></span>:null}</article>}):<p className="r2-saved-views__state">لا توجد مناظر محفوظة.</p>}</div>}{message?<p className="r2-saved-views__message" role="status">{message}</p>:null}</section>
}
