import { useState, useSyncExternalStore } from 'react';
import { getTransactionSavedViewBridgeSnapshot, subscribeTransactionSavedViewBridge } from '../../features/transactions/transactionSavedViewBridge.ts';
import type { TransactionListSort, TransactionListView } from '../../features/transactions/transactionListModel.ts';
import type { SearchIntelligenceGateway } from '../../features/searchIntelligence/searchIntelligenceCommands.ts';
import { useSavedViews } from '../../features/searchIntelligence/useSearchIntelligence.ts';

const sorts:readonly TransactionListSort[]=['activity-desc','created-desc','fee-desc','fee-asc'];
function requestFrom(def:any){const view=def?.filters?.view,sort=def?.sort,pageSize=def?.pageSize;if(def?.sourceSchema!=='enjaz.transactions.list.v1'||(view!=='current'&&view!=='stalled'&&view!=='archived')||!sorts.includes(sort)||!Number.isSafeInteger(pageSize)||pageSize<1||pageSize>50)return null;return{view:view as TransactionListView,search:def.query as string,sort:sort as TransactionListSort,pageSize:pageSize as number}}

export function TransactionSavedViewsDock({gateway,workspace,userId}:{gateway:SearchIntelligenceGateway;workspace:Promise<string|null>;userId:string}){
 const bridge=useSyncExternalStore(subscribeTransactionSavedViewBridge,getTransactionSavedViewBridgeSnapshot,getTransactionSavedViewBridgeSnapshot),saved=useSavedViews('transactions',gateway,workspace),[name,setName]=useState(''),request=bridge.request;if(!request||!bridge.apply)return null;
 const definition={schema:'enjaz.saved-view.v1' as const,domain:'transactions' as const,query:request.search,filters:{view:request.view},sort:request.sort,dateRange:{from:null,to:null},pageSize:request.pageSize,sourceSchema:'enjaz.transactions.list.v1'};
 const create=async()=>{const n=name.trim();if(!n)return;try{await saved.createPersonal(n,definition);setName('')}catch{}};
 const apply=(item:(typeof saved.items)[number])=>{const next=requestFrom(item.definition);if(next)bridge.apply!(next)};
 const rename=async(item:(typeof saved.items)[number])=>{const n=window.prompt('الاسم الجديد',item.name)?.trim();if(n&&n!==item.name)try{await saved.rename(item,n)}catch{}};
 const remove=async(item:(typeof saved.items)[number])=>{if(window.confirm(`حذف «${item.name}»؟`))try{await saved.remove(item)}catch{}};
 return <section className="r2-saved-views" data-phase9-2-saved-views="transactions" aria-label="المناظر المحفوظة"><div className="r2-saved-views__head"><strong>مناظري</strong></div><div className="r2-saved-views__create"><input aria-label="اسم المنظر" maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="اسم المنظر"/><button type="button" disabled={saved.busyId!==null||!name.trim()} onClick={()=>void create()}>حفظ</button></div>{saved.status==='loading'?<p className="r2-saved-views__state">جارٍ التحميل…</p>:saved.status==='error'?<p className="r2-saved-views__state is-error">{saved.errorMessage}<button type="button" onClick={saved.retry}>إعادة</button></p>:<div className="r2-saved-views__list">{saved.items.length?saved.items.map(item=>{const owned=item.ownerUserId===userId,ok=!!requestFrom(item.definition);return <article key={item.id} className="r2-saved-view-chip" data-saved-view-id={item.id}><button type="button" className="r2-saved-view-chip__apply" disabled={!ok||saved.busyId===item.id} onClick={()=>apply(item)}><strong>{item.name}</strong><small>{item.visibility==='personal'?'شخصي':item.visibility==='team'?'فريق':'المساحة'}</small></button>{owned?<span className="r2-saved-view-chip__actions"><button type="button" aria-label="إعادة تسمية" onClick={()=>void rename(item)}>✎</button><button type="button" aria-label="حذف" onClick={()=>void remove(item)}>×</button></span>:null}</article>}):<p className="r2-saved-views__state">لا توجد مناظر.</p>}</div>}{saved.errorMessage&&saved.status!=='error'?<p className="r2-saved-views__message" role="status">{saved.errorMessage}</p>:null}</section>
}
