import { createClient } from 'npm:@supabase/supabase-js@2.114.0';
const BUCKET='enjaz-intake-private';
const ALLOWED_MIME=['application/pdf','image/jpeg','image/png'];
const MAX_BYTES=52428800;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'content-type,x-client-info,apikey','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
type J=Record<string,unknown>;
type C={fileId:string;submissionId:string;bucket:string;path:string;byteSize:number;mimeType:string;uploadStatus:string;authoritative:false};
const out=(s:number,b:J)=>new Response(JSON.stringify(b),{status:s,headers:cors});
function txt(v:unknown,n:number){if(typeof v!=='string'||!v.trim()||v.length>n)throw new Error('INVALID_INPUT');return v.trim()}
function tok(v:unknown){const s=txt(v,64);if(!/^[0-9a-f]{64}$/.test(s))throw new Error('INVALID_TOKEN');return s}
function uid(v:unknown){const s=txt(v,64);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new Error('INVALID_FILE_ID');return s}
function key(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern){try{const p=JSON.parse(modern) as Record<string,string>;if(typeof p.default==='string'&&p.default)return p.default}catch{}}const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(legacy)return legacy;throw new Error('SERVER_SECRET_UNAVAILABLE')}
function claim(v:unknown):C{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('INVALID_CLAIM');const r=v as J;const c={fileId:uid(r.fileId),submissionId:uid(r.submissionId),bucket:txt(r.bucket,80),path:txt(r.path,240),byteSize:Number(r.byteSize),mimeType:txt(r.mimeType,160),uploadStatus:txt(r.uploadStatus,40),authoritative:false as const};if(c.bucket!==BUCKET||c.uploadStatus!=='pending_upload'||!Number.isSafeInteger(c.byteSize)||c.byteSize<1||c.byteSize>MAX_BYTES||!ALLOWED_MIME.includes(c.mimeType)||r.authoritative!==false)throw new Error('INVALID_CLAIM');return c}
async function bucket(admin:ReturnType<typeof createClient>){const got=await admin.storage.getBucket(BUCKET);if(!got.error&&got.data){if(got.data.public===true)throw new Error('BUCKET_MUST_BE_PRIVATE');return}const made=await admin.storage.createBucket(BUCKET,{public:false,fileSizeLimit:MAX_BYTES,allowedMimeTypes:ALLOWED_MIME});if(made.error&&!/already exists/i.test(made.error.message))throw made.error}
function size(v:unknown){if(!v||typeof v!=='object')return NaN;const r=v as J;if(typeof r.size==='number')return r.size;const m=r.metadata;if(m&&typeof m==='object'&&!Array.isArray(m)){const n=Number((m as J).size);if(Number.isFinite(n))return n}return NaN}
function mime(v:unknown){if(!v||typeof v!=='object')return null;const r=v as J;if(typeof r.contentType==='string')return r.contentType;const m=r.metadata;if(m&&typeof m==='object'&&!Array.isArray(m)){const q=m as J;if(typeof q.mimetype==='string')return q.mimetype;if(typeof q.contentType==='string')return q.contentType}return null}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return out(405,{ok:false,error:'METHOD_NOT_ALLOWED'});let stage='input';try{const len=Number(req.headers.get('content-length')||'0');if(Number.isFinite(len)&&len>16384)return out(413,{ok:false,error:'REQUEST_TOO_LARGE'});const body=await req.json() as J;const action=txt(body.action,32),raw=tok(body.token),fileId=uid(body.fileId);stage='server_config';const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SERVER_URL_UNAVAILABLE');const admin=createClient(url,key(),{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});stage='storage_init';await bucket(admin);stage='prepare_rpc';const p=await admin.rpc('prepare_intake_file_upload_v1',{p_token:raw,p_file_id:fileId});if(p.error)throw p.error;const expected=claim(p.data);if(action==='prepare'){stage='signed_url';const s=await admin.storage.from(BUCKET).createSignedUploadUrl(expected.path,{upsert:false});if(s.error||!s.data)throw s.error??new Error('SIGNED_UPLOAD_UNAVAILABLE');const d=s.data as unknown as J;return out(200,{ok:true,authoritative:false,fileId:expected.fileId,bucket:BUCKET,path:expected.path,byteSize:expected.byteSize,mimeType:expected.mimeType,uploadToken:typeof d.token==='string'?d.token:null,signedUrl:typeof d.signedUrl==='string'?d.signedUrl:null,expiresInSeconds:7200})}if(action==='acknowledge'){stage='storage_info';const info=await admin.storage.from(BUCKET).info(expected.path);if(info.error||!info.data)return out(409,{ok:false,error:'STORAGE_OBJECT_NOT_FOUND'});const actualSize=size(info.data),actualMime=mime(info.data);if(!Number.isSafeInteger(actualSize)||actualSize!==expected.byteSize)return out(409,{ok:false,error:'STORAGE_SIZE_MISMATCH'});if(!actualMime||actualMime.toLowerCase()!==expected.mimeType.toLowerCase())return out(409,{ok:false,error:'STORAGE_MIME_MISMATCH'});stage='ack_rpc';const a=await admin.rpc('acknowledge_intake_file_upload_v1',{p_token:raw,p_file_id:fileId,p_storage_path:expected.path,p_actual_byte_size:actualSize,p_actual_mime_type:actualMime});if(a.error)throw a.error;return out(200,{ok:true,authoritative:false,fileId:expected.fileId,uploadStatus:'acknowledged'})}return out(400,{ok:false,error:'UNKNOWN_ACTION'})}catch(e){const m=e instanceof Error?e.message:'UNKNOWN';if(['INVALID_INPUT','INVALID_TOKEN','INVALID_FILE_ID'].includes(m))return out(400,{ok:false,error:m});console.error('enjaz-intake-upload failed',{stage,kind:e instanceof Error?e.name:'unknown'});return out(500,{ok:false,error:`INTAKE_UPLOAD_${stage.toUpperCase()}_FAILED`})}});
