import { useCallback, useEffect, useMemo, useState } from 'react';
import { DataAccessError } from '../../data/contracts/DataAccessError.ts';
import { useCrmIntakeGateway } from '../../features/crm-intake/CrmIntakeContext.tsx';
import type { CrmIntakeContext, CrmLeadSummary, CrmQuotationSummary } from '../../features/crm-intake/crmIntakeCommands.ts';

type Tab='leads'|'quotes'|'forms'|'review';
const STAGE:Readonly<Record<CrmLeadSummary['stage'],string>>={inquiry:'استفسار',qualified:'مؤهل',quoted:'عرض سعر',accepted:'مقبول',lost:'مفقود',converted:'محول'};
const QUOTE:Readonly<Record<CrmQuotationSummary['status'],string>>={draft:'مسودة',pending_approval:'بانتظار الموافقة',approved:'معتمد',sent:'مرسل',accepted:'مقبول',rejected:'مرفوض',expired:'منتهي'};
function message(e:unknown){if(e instanceof DataAccessError){if(e.dataCode==='DATA_CONFLICT')return'توجد حالة أحدث؛ أعد التحميل.';if(e.dataCode==='DATA_FORBIDDEN')return'لا صلاحية لهذا الإجراء.';if(e.dataCode==='DATA_VALIDATION_FAILED')return'تحقق من البيانات المدخلة.';if(e.dataCode==='DATA_OUTCOME_UNKNOWN')return'نتيجة العملية غير مؤكدة؛ أعد التحميل قبل التكرار.'}return'تعذر تنفيذ العملية.'}
export function LiveCrmIntakeExperience({workspaceId,onLinkIssued}:Readonly<{workspaceId:string;onLinkIssued?:(token:string)=>void}>){
 const gateway=useCrmIntakeGateway(),[ctx,setCtx]=useState<CrmIntakeContext|null>(null),[tab,setTab]=useState<Tab>('leads'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [lead,setLead]=useState({displayName:'',organizationName:'',phone:'',email:'',source:''});
 const [request,setRequest]=useState({leadId:'',serviceId:'',notes:''});
 const [quote,setQuote]=useState({leadId:'',serviceRequestId:'',discount:'15',validUntil:'2026-09-30'});
 const [formTitle,setFormTitle]=useState('طلب خدمة جديد'),[link,setLink]=useState<{linkId:string;token:string;expiresAt:string}|null>(null);
 const load=useCallback(async()=>{try{setError('');setCtx(await gateway.loadContext(workspaceId))}catch(e){setError(message(e))}},[gateway,workspaceId]);
 useEffect(()=>{void load()},[load]);
 const act=async(fn:()=>Promise<unknown>,ok:string)=>{setBusy(true);setError('');setNotice('');try{await fn();setNotice(ok);await load()}catch(e){setError(message(e))}finally{setBusy(false)}};
 const services=ctx?.services.filter(x=>x.active)??[],qualified=ctx?.leads.filter(x=>x.stage==='qualified'||x.stage==='quoted')??[],accepted=ctx?.leads.filter(x=>x.stage==='accepted')??[];
 const serviceById=useMemo(()=>new Map((ctx?.services??[]).map(x=>[x.id,x])),[ctx]);
 if(!ctx)return <section className="p84-card" data-phase84-stage="8.4">{error||'جاري تحميل CRM…'}</section>;
 return <section className="p84-shell" data-phase84-stage="8.4" data-crm-authority="pre_transaction" data-external-authority={ctx.externalSubmissionAuthority} data-finance-write-authority={ctx.financeLedgerWriteAuthority} data-core-conversion="guarded_rpc_only" dir="rtl">
  <header className="p84-hero"><div><span className="p84-kicker">Phase 8.4 · M6 + M17</span><h1>CRM والاستقبال الذكي</h1><p>باب أمامي للعمل الجديد؛ لا شركة ولا معاملة ولا قيد مالي يصبح سلطويًا بلا تحويل داخلي مُراجع.</p></div><div className="p84-authority"><strong>حدود السلطة</strong><span>External: غير سلطوي</span><span>Core: Guarded RPC</span><span>Finance: لا كتابة</span></div></header>
  <nav className="p84-tabs" aria-label="CRM tabs">{([['leads','العملاء والطلبات'],['quotes','عروض الأسعار'],['forms','نماذج وروابط'],['review','طابور المراجعة']] as const).map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
  {(error||notice)&&<div className={error?'p84-message error':'p84-message success'} role="status">{error||notice}</div>}
  {tab==='leads'&&<div className="p84-grid">
   <article className="p84-card"><h2>Lead جديد</h2><label>الاسم<input aria-label="اسم العميل المحتمل" value={lead.displayName} onChange={e=>setLead({...lead,displayName:e.target.value})}/></label><label>الجهة / الشركة<input aria-label="اسم الجهة" value={lead.organizationName} onChange={e=>setLead({...lead,organizationName:e.target.value})}/></label><label>الهاتف<input aria-label="هاتف العميل" value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})}/></label><label>البريد<input aria-label="بريد العميل" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/></label><label>المصدر<input aria-label="مصدر العميل" value={lead.source} onChange={e=>setLead({...lead,source:e.target.value})}/></label><button disabled={busy} onClick={()=>void act(()=>gateway.createLead({workspaceId,displayName:lead.displayName,organizationName:lead.organizationName||null,phone:lead.phone||null,email:lead.email||null,source:lead.source||null,assignedUserId:null}),'تم إنشاء Lead دون إنشاء سجل Core.')}>إنشاء Lead</button></article>
   <article className="p84-card"><h2>طلب خدمة</h2><label>Lead<select aria-label="Lead لطلب الخدمة" value={request.leadId} onChange={e=>setRequest({...request,leadId:e.target.value})}><option value="">اختر</option>{ctx.leads.filter(x=>!['lost','converted'].includes(x.stage)).map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label>الخدمة<select aria-label="الخدمة المطلوبة" value={request.serviceId} onChange={e=>setRequest({...request,serviceId:e.target.value})}><option value="">اختر</option>{services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>ملاحظة<textarea aria-label="ملاحظة طلب الخدمة" value={request.notes} onChange={e=>setRequest({...request,notes:e.target.value})}/></label><button disabled={busy||!request.leadId||!request.serviceId} onClick={()=>void act(()=>gateway.createServiceRequest(workspaceId,request.leadId,request.serviceId,request.notes||null),'تم إنشاء طلب الخدمة.')}>إنشاء طلب خدمة</button></article>
   <article className="p84-card p84-wide"><h2>مسار Lead</h2><div className="p84-list">{ctx.leads.map(x=><div className="p84-row" key={x.id} data-lead-stage={x.stage}><div><strong>{x.displayName}</strong><span>{x.organizationName||'بدون شركة بعد'} · {STAGE[x.stage]}</span></div><div className="p84-actions">{x.stage==='inquiry'&&<button disabled={busy} onClick={()=>void act(()=>gateway.advanceLead(workspaceId,x.id,x.version,'qualified',null),'تم تأهيل Lead.')}>تأهيل</button>}{x.stage==='accepted'&&<button disabled={busy} onClick={()=>void act(()=>gateway.convertLead({workspaceId,leadId:x.id,reuseCompanyId:null,transactionType:'تسجيل شركة',department:'مسجل الشركات'}),'تم التحويل إلى Core عبر RPC محروس.')}>تحويل إلى Core</button>}{x.stage==='converted'&&<span data-conversion-complete="true">Core: {x.convertedTransactionId?.slice(0,8)}</span>}</div></div>)}</div></article>
  </div>}
  {tab==='quotes'&&<div className="p84-grid">
   <article className="p84-card"><h2>عرض سعر</h2><label>Lead<select aria-label="Lead لعرض السعر" value={quote.leadId} onChange={e=>setQuote({...quote,leadId:e.target.value})}><option value="">اختر</option>{qualified.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select></label><label>طلب الخدمة<select aria-label="طلب الخدمة للعرض" value={quote.serviceRequestId} onChange={e=>setQuote({...quote,serviceRequestId:e.target.value})}><option value="">بدون</option>{ctx.serviceRequests.filter(x=>x.leadId===quote.leadId).map(x=><option key={x.id} value={x.id}>{x.serviceName}</option>)}</select></label><label>خصم %<input aria-label="نسبة الخصم" type="number" min="0" max="30" value={quote.discount} onChange={e=>setQuote({...quote,discount:e.target.value})}/></label><label>صالح لغاية<input aria-label="صلاحية العرض" type="date" value={quote.validUntil} onChange={e=>setQuote({...quote,validUntil:e.target.value})}/></label><button disabled={busy||!quote.leadId} onClick={()=>{const req=ctx.serviceRequests.find(x=>x.id===quote.serviceRequestId),service=serviceById.get(req?.serviceId??services[0]?.id??'');if(!service)return;void act(()=>gateway.createQuotation({workspaceId,leadId:quote.leadId,serviceRequestId:quote.serviceRequestId||null,currency:'IQD',discountPercent:Number(quote.discount),validUntil:quote.validUntil||null,items:[{serviceId:service.id,description:service.name,quantity:1,unitPrice:Number(service.basePrice)}]}),'تم إنشاء عرض السعر وفق سياسة الخصم.')}}>إنشاء عرض</button><p className="p84-note">الخصم فوق 10% لا يمر تلقائيًا؛ يحتاج موافقة صريحة.</p></article>
   <article className="p84-card p84-wide"><h2>العروض الحالية</h2><div className="p84-list">{ctx.quotations.map(x=><div className="p84-row" key={x.id} data-quotation-status={x.status}><div><strong>{Number(x.total).toLocaleString('ar-IQ')} {x.currency}</strong><span>{QUOTE[x.status]} · خصم {x.discountPercent}%</span></div><div className="p84-actions">{x.status==='pending_approval'&&<button disabled={busy} onClick={()=>void act(()=>gateway.approveQuotation(workspaceId,x.id,x.version),'تم اعتماد الخصم.')}>اعتماد الخصم</button>}{(x.status==='approved'||x.status==='sent')&&<button disabled={busy} onClick={()=>void act(()=>gateway.acceptQuotation(workspaceId,x.id,x.version),'تم قبول العرض وتحويل Lead إلى Accepted.')}>قبول العرض</button>}</div></div>)}</div></article>
  </div>}
  {tab==='forms'&&<div className="p84-grid">
   <article className="p84-card"><h2>بناء نموذج Intake</h2><label>العنوان العام<input aria-label="عنوان نموذج الاستقبال" value={formTitle} onChange={e=>setFormTitle(e.target.value)}/></label><button disabled={busy} onClick={()=>void act(()=>gateway.saveIntakeForm({workspaceId,formId:null,name:formTitle,publicTitle:formTitle,publicDescription:'أرسل البيانات المطلوبة بأمان. لن تصبح سجلًا داخليًا قبل المراجعة.',active:true,fields:[{key:'name',label:'الاسم',type:'text',required:true},{key:'organization',label:'الشركة',type:'text',required:true},{key:'phone',label:'الهاتف',type:'phone',required:false},{key:'email',label:'البريد',type:'email',required:false},{key:'source',label:'المصدر',type:'text',required:false},{key:'id_doc',label:'مستمسك داعم',type:'file',required:false,config:{allowedMimeTypes:['application/pdf','image/jpeg','image/png'],maxBytes:10485760}}]}),'تم إنشاء نموذج Intake مع قواعد الملفات.')}>إنشاء نموذج</button></article>
   <article className="p84-card"><h2>إصدار رابط آمن</h2><label>النموذج<select aria-label="نموذج الرابط الآمن" id="p84-form-link"><option value="">اختر</option>{ctx.forms.filter(x=>x.active).map(x=><option key={x.id} value={x.id}>{x.publicTitle}</option>)}</select></label><button disabled={busy||ctx.forms.length===0} onClick={()=>{const select=document.getElementById('p84-form-link') as HTMLSelectElement|null,formId=select?.value||ctx.forms[0]?.id;if(!formId)return;void(async()=>{setBusy(true);setError('');try{const issued=await gateway.issueIntakeLink(workspaceId,formId,null,24);setLink(issued);setNotice('تم إصدار الرابط. التوكن يظهر لهذه الجلسة فقط.');onLinkIssued?.(issued.token)}catch(e){setError(message(e))}finally{setBusy(false)}})()}}>إصدار رابط 24 ساعة</button>{link&&<div className="p84-token" data-token-exposure="one-shot"><span>Token مؤقت</span><code>{link.token.slice(0,12)}…{link.token.slice(-8)}</code><small>لا يُخزن خامًا في قاعدة البيانات.</small></div>}</article>
   <article className="p84-card p84-wide"><h2>النماذج</h2><div className="p84-list">{ctx.forms.map(x=><div className="p84-row" key={x.id}><div><strong>{x.publicTitle}</strong><span>{x.fieldCount} حقول · v{x.version}</span></div></div>)}</div></article>
  </div>}
  {tab==='review'&&<article className="p84-card"><h2>طابور المراجعة</h2><p className="p84-note">لا Submission خارجي يتحول إلى Core هنا. الموافقة تنشئ Lead فقط؛ التحويل إلى Core خطوة لاحقة مستقلة.</p><div className="p84-list">{ctx.reviewQueue.length===0?<div className="p84-empty">لا توجد submissions بانتظار المراجعة.</div>:ctx.reviewQueue.map(x=><div className="p84-row" key={x.id} data-review-status={x.status} data-pending-uploads={x.pendingUploadCount}><div><strong>{x.formTitle}</strong><span>{x.status} · ملفات {x.fileCount} · غير مؤكدة {x.pendingUploadCount}</span></div><div className="p84-actions"><button disabled={busy||x.pendingUploadCount>0} onClick={()=>void act(()=>gateway.reviewSubmission({workspaceId,submissionId:x.id,expectedVersion:x.version,decision:'approve',mapping:{displayName:'name',organizationName:'organization',phone:'phone',email:'email',source:'source'},note:'مراجعة داخلية مكتملة'}),'تمت الموافقة وإنشاء Lead فقط؛ Core لم يُنشأ.')}>موافقة وإنشاء Lead</button><button disabled={busy} onClick={()=>void act(()=>gateway.reviewSubmission({workspaceId,submissionId:x.id,expectedVersion:x.version,decision:'reject',mapping:{},note:'مرفوض بعد المراجعة'}),'تم رفض submission.')}>رفض</button>{x.pendingUploadCount>0&&<span className="p84-warning">الموافقة مقفلة حتى اعتراف التخزين بالملف.</span>}</div></div>)}</div><span data-core-created="false" hidden/></article>}
 </section>
}
