import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { CrmIntakeProvider } from '../../features/crm-intake/CrmIntakeContext.tsx';
import type { CrmIntakeContext, CrmIntakeGateway, CrmLeadSummary, CrmQuotationSummary, IntakeFormFieldDefinition, IntakeReviewSummary, PublicIntakeView, ServiceCatalogSummary } from '../../features/crm-intake/crmIntakeCommands.ts';
import { LiveCrmIntakeExperience } from './LiveCrmIntakeExperience.tsx';
import { PublicIntakeExperience } from './PublicIntakeExperience.tsx';
import '../runtime/shell-base.css';
import '../runtime/shell.css';
import '../runtime/accessibility-hardening.css';
import './crm-intake.css';

const W='11111111-1111-4111-8111-111111111111',S1='22222222-2222-4222-8222-222222222221',S2='22222222-2222-4222-8222-222222222222',L0='33333333-3333-4333-8333-333333333330',F0='44444444-4444-4444-8444-444444444440',TOKEN='a'.repeat(64);
let serial=10;const uid=(prefix='55555555-5555-4555-8555-')=>`${prefix}${String(serial++).padStart(12,'0')}`;
let services:ServiceCatalogSummary[]=[{id:S1,code:'COMP-REG',name:'تسجيل شركة',description:'تأسيس وتسجيل شركة جديدة',basePrice:'250000',expectedDurationDays:7,requiredInputs:['هوية','عنوان'],active:true},{id:S2,code:'AMEND',name:'تعديل عقد شركة',description:'تعديل عقد/بيانات شركة قائمة',basePrice:'125000',expectedDurationDays:4,requiredInputs:['عقد حالي'],active:true}];
let leads:CrmLeadSummary[]=[{id:L0,displayName:'ليث حسن',organizationName:'شركة البداية',phone:'07701234567',email:'laith@example.com',source:'إحالة',stage:'inquiry',lostReason:null,version:1,convertedCompanyId:null,convertedTransactionId:null}];
let requests:CrmIntakeContext['serviceRequests']=[];let quotations:CrmQuotationSummary[]=[];
let forms:CrmIntakeContext['forms']=[{id:F0,name:'طلب خدمة جديد',publicTitle:'طلب خدمة جديد',active:true,version:1,fieldCount:6}];
const fields:IntakeFormFieldDefinition[]=[{key:'name',label:'الاسم',type:'text',required:true,config:{}},{key:'organization',label:'الشركة',type:'text',required:true,config:{}},{key:'phone',label:'الهاتف',type:'phone',required:false,config:{}},{key:'email',label:'البريد',type:'email',required:false,config:{}},{key:'source',label:'المصدر',type:'text',required:false,config:{}},{key:'id_doc',label:'مستمسك داعم',type:'file',required:false,config:{allowedMimeTypes:['application/pdf','image/jpeg','image/png'],maxBytes:10485760}}];
type Submission={id:string;status:'draft'|'submitted'|'under_review'|'approved'|'rejected'|'converted';answers:Record<string,string>;version:number;submittedAt:string|null;pendingUploadCount:number;fileCount:number;formId:string};
let submission:Submission|null=null,linkIssued=false;
const context=():CrmIntakeContext=>Object.freeze({authority:'crm_pre_transaction_and_reviewed_intake',externalSubmissionAuthority:'non_authoritative',companyWriteAuthority:'guarded_conversion_rpc_only',transactionWriteAuthority:'guarded_conversion_rpc_only',financeLedgerWriteAuthority:'none',services:Object.freeze([...services]),leads:Object.freeze([...leads]),serviceRequests:Object.freeze([...requests]),quotations:Object.freeze([...quotations]),reviewQueue:Object.freeze(submission&&['submitted','under_review','approved'].includes(submission.status)?[{id:submission.id,formId:submission.formId,formTitle:'طلب خدمة جديد',status:submission.status,submittedAt:submission.submittedAt,version:submission.version,fileCount:submission.fileCount,pendingUploadCount:submission.pendingUploadCount} as IntakeReviewSummary]:[]),forms:Object.freeze([...forms])});
const updateLead=(id:string,fn:(x:CrmLeadSummary)=>CrmLeadSummary)=>{leads=leads.map(x=>x.id===id?fn(x):x)};
const gateway:CrmIntakeGateway={
 async loadContext(workspaceId){if(workspaceId!==W)throw new Error('workspace mismatch');return context()},
 async saveService(input){const id=input.serviceId??uid();services=input.serviceId?services.map(x=>x.id===id?{id,code:input.code,name:input.name,description:input.description,basePrice:String(input.basePrice),expectedDurationDays:input.expectedDurationDays,requiredInputs:input.requiredInputs,active:input.active}:x):[...services,{id,code:input.code,name:input.name,description:input.description,basePrice:String(input.basePrice),expectedDurationDays:input.expectedDurationDays,requiredInputs:input.requiredInputs,active:input.active}];return{id}},
 async createLead(input){const id=uid();leads=[...leads,{id,displayName:input.displayName,organizationName:input.organizationName,phone:input.phone,email:input.email,source:input.source,stage:'inquiry',lostReason:null,version:1,convertedCompanyId:null,convertedTransactionId:null}];return{id,stage:'inquiry',version:1}},
 async advanceLead(workspaceId,leadId,expectedVersion,nextStage,lostReason){const current=leads.find(x=>x.id===leadId);if(workspaceId!==W||!current||current.version!==expectedVersion)throw new Error('stale lead');updateLead(leadId,x=>({...x,stage:nextStage,lostReason:nextStage==='lost'?lostReason:null,version:x.version+1}));return{id:leadId,stage:nextStage,version:expectedVersion+1}},
 async createServiceRequest(workspaceId,leadId,serviceId,notes){if(workspaceId!==W)throw new Error('workspace mismatch');const service=services.find(x=>x.id===serviceId);if(!service)throw new Error('service');const id=uid();requests=[...requests,{id,leadId,serviceId,serviceName:service.name,status:'requested',notes}];return{id,status:'requested'}},
 async createQuotation(input){const current=leads.find(x=>x.id===input.leadId);if(!current||!['qualified','quoted'].includes(current.stage))throw new Error('lead not eligible');const subtotal=input.items.reduce((s,x)=>s+x.quantity*x.unitPrice,0),discount=subtotal*input.discountPercent/100,total=subtotal-discount,id=uid(),status=input.discountPercent>10?'pending_approval':'approved';quotations=[...quotations,{id,leadId:input.leadId,serviceRequestId:input.serviceRequestId,status,currency:input.currency,subtotal:String(subtotal),discountPercent:String(input.discountPercent),discountAmount:String(discount),total:String(total),validUntil:input.validUntil,approvalRequired:input.discountPercent>10,version:1}];updateLead(input.leadId,x=>({...x,stage:'quoted',version:x.version+1}));return{id,status,subtotal,total,discountPercent:input.discountPercent,approvalRequired:input.discountPercent>10,version:1}},
 async approveQuotation(workspaceId,quotationId,expectedVersion){const q=quotations.find(x=>x.id===quotationId);if(workspaceId!==W||!q||q.version!==expectedVersion||q.status!=='pending_approval')throw new Error('quote');quotations=quotations.map(x=>x.id===quotationId?{...x,status:'approved',version:x.version+1}:x);return{id:quotationId,status:'approved',version:expectedVersion+1}},
 async acceptQuotation(workspaceId,quotationId,expectedVersion){const q=quotations.find(x=>x.id===quotationId);if(workspaceId!==W||!q||q.version!==expectedVersion||!['approved','sent'].includes(q.status))throw new Error('quote');quotations=quotations.map(x=>x.id===quotationId?{...x,status:'accepted',version:x.version+1}:x);updateLead(q.leadId,x=>({...x,stage:'accepted',version:x.version+1}));return{id:quotationId,status:'accepted',leadId:q.leadId,version:expectedVersion+1}},
 async saveIntakeForm(input){const id=input.formId??uid();forms=input.formId?forms.map(x=>x.id===id?{...x,name:input.name,publicTitle:input.publicTitle,active:input.active,version:x.version+1,fieldCount:input.fields.length}:x):[...forms,{id,name:input.name,publicTitle:input.publicTitle,active:input.active,version:1,fieldCount:input.fields.length}];return{id,version:1,fieldCount:input.fields.length,active:input.active}},
 async issueIntakeLink(workspaceId,formId,_leadId,expiresInHours){if(workspaceId!==W||!forms.some(x=>x.id===formId)||expiresInHours!==24)throw new Error('link');linkIssued=true;return{linkId:uid(),token:TOKEN,expiresAt:'2026-09-09T18:00:00.000Z'}},
 async revokeIntakeLink(){linkIssued=false;return{revoked:true}},
 async getPublicIntake(token){if(!linkIssued||token!==TOKEN)throw new Error('bad token');const view:PublicIntakeView={publicAuthority:'non_authoritative',form:{title:'طلب خدمة جديد',description:'أرسل بياناتك للمراجعة الداخلية في إنجاز.',fields},expiresAt:'2026-09-09T18:00:00.000Z',submission:submission?{id:submission.id,status:submission.status,answers:submission.status==='draft'?submission.answers:{},version:submission.version,submittedAt:submission.submittedAt}:null};return view},
 async savePublicIntake(token,answers,fileMeta,finalize){if(token!==TOKEN||!linkIssued)throw new Error('bad token');const id=submission?.id??uid(),version=(submission?.version??0)+1;submission={id,status:finalize?'submitted':'draft',answers:{...answers},version,submittedAt:finalize?'2026-09-08T18:10:00.000Z':null,pendingUploadCount:fileMeta.length,fileCount:fileMeta.length,formId:F0};return{submissionId:id,status:submission.status,version,authoritative:false,pendingUploadCount:fileMeta.length}},
 async reviewSubmission(input){if(!submission||input.submissionId!==submission.id||input.expectedVersion!==submission.version)throw new Error('review stale');if(input.decision==='approve'&&submission.pendingUploadCount>0)throw new Error('uploads not acknowledged');if(input.decision==='reject'){submission={...submission,status:'rejected',version:submission.version+1};return{submissionId:submission.id,status:'rejected',authoritativeCoreCreated:false}}const id=uid(),a=submission.answers;leads=[...leads,{id,displayName:a.name||'عميل Intake',organizationName:a.organization||null,phone:a.phone||null,email:a.email||null,source:a.source||'Secure Intake',stage:'inquiry',lostReason:null,version:1,convertedCompanyId:null,convertedTransactionId:null}];submission={...submission,status:'approved',version:submission.version+1};return{submissionId:submission.id,status:'approved',version:submission.version,leadId:id,authoritativeCoreCreated:false}},
 async convertLead(input){const current=leads.find(x=>x.id===input.leadId);if(!current||current.stage!=='accepted')throw new Error('not accepted');const companyId=input.reuseCompanyId??uid(),transactionId=uid();updateLead(input.leadId,x=>({...x,stage:'converted',version:x.version+1,convertedCompanyId:companyId,convertedTransactionId:transactionId}));return{leadId:input.leadId,companyId,contactId:null,transactionId,wasDuplicate:false}}
};
function PreviewApp(){const[publicToken,setPublicToken]=useState<string|null>(null);return <div className="r2-shell" data-r2-runtime-mode="phase84-preview" data-destination="crm" dir="rtl"><main id="r2-main" className="r2-main"><CrmIntakeProvider gateway={Object.freeze(gateway)}>{publicToken?<PublicIntakeExperience token={publicToken} onReturn={()=>setPublicToken(null)}/>:<LiveCrmIntakeExperience workspaceId={W} onLinkIssued={token=>setPublicToken(token)}/>}</CrmIntakeProvider></main></div>}
const root=document.getElementById('phase84-crm-root');if(!root)throw new Error('Phase 8.4 preview root missing');createRoot(root).render(<StrictMode><PreviewApp/></StrictMode>);
