import { useCallback, useEffect, useState } from 'react';
import { DataAccessError } from '../../data/contracts/DataAccessError.ts';
import { useCrmIntakeGateway } from '../../features/crm-intake/CrmIntakeContext.tsx';
import type { IntakeFileMetadata, PublicIntakeView } from '../../features/crm-intake/crmIntakeCommands.ts';
function message(e:unknown){if(e instanceof DataAccessError){if(e.dataCode==='DATA_VALIDATION_FAILED')return'تحقق من الحقول والملفات.';if(e.dataCode==='DATA_FORBIDDEN')return'الرابط منتهي أو ملغى.';if(e.dataCode==='DATA_UNAVAILABLE')return'تعذر الاتصال؛ حاول لاحقًا.'}return'تعذر حفظ الطلب.'}
export function PublicIntakeExperience({token,onReturn}:Readonly<{token:string;onReturn?:()=>void}>){
 const gateway=useCrmIntakeGateway(),[view,setView]=useState<PublicIntakeView|null>(null),[answers,setAnswers]=useState<Record<string,string>>({}),[files,setFiles]=useState<readonly IntakeFileMetadata[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');
 const load=useCallback(async()=>{try{const v=await gateway.getPublicIntake(token);setView(v);if(v.submission?.status==='draft')setAnswers({...v.submission.answers})}catch(e){setError(message(e))}},[gateway,token]);useEffect(()=>{void load()},[load]);
 const save=async(finalize:boolean)=>{setBusy(true);setError('');setStatus('');try{const result=await gateway.savePublicIntake(token,answers,files,finalize);setStatus(finalize?'تم إرسال الطلب للمراجعة الداخلية. لم يصبح سجلًا سلطويًا.':'تم حفظ المسودة بأمان.');setView(v=>v?{...v,submission:{id:result.submissionId,status:result.status,answers,version:result.version,submittedAt:finalize?new Date().toISOString():null}}:v)}catch(e){setError(message(e))}finally{setBusy(false)}};
 if(!view)return <section className="p84-public" data-public-intake="true">{error||'جاري فتح النموذج الآمن…'}</section>;
 const locked=view.submission?.status&&view.submission.status!=='draft';
 return <section className="p84-public" data-public-intake="true" data-public-authority={view.publicAuthority} data-authoritative="false" dir="rtl">
  <header><span className="p84-kicker">ENJAZ Secure Intake</span><h1>{view.form.title}</h1><p>{view.form.description}</p><div className="p84-public-law">هذا النموذج لا يكتب شركة أو معاملة أو قيدًا ماليًا مباشرة. البيانات تمر بطابور مراجعة داخلي.</div></header>
  {(error||status)&&<div className={error?'p84-message error':'p84-message success'} role="status">{error||status}</div>}
  <div className="p84-public-form">{view.form.fields.map(field=>field.type==='file'?<label key={field.key}>{field.label}{field.required&&' *'}<input aria-label={field.label} type="file" disabled={!!locked} accept={Array.isArray(field.config.allowedMimeTypes)?field.config.allowedMimeTypes.join(','):undefined} onChange={e=>{const f=e.target.files?.[0];setFiles(current=>[...current.filter(x=>x.fieldKey!==field.key),...(f?[{fieldKey:field.key,fileName:f.name,mimeType:f.type||'application/octet-stream',byteSize:f.size}]:[])])}}/>{files.some(x=>x.fieldKey===field.key)&&<span className="p84-warning" data-upload-status="pending_upload">تم اختيار الملف محليًا فقط — بانتظار رفع فعلي واعتراف التخزين.</span>}</label>:field.type==='textarea'?<label key={field.key}>{field.label}{field.required&&' *'}<textarea aria-label={field.label} required={field.required} disabled={!!locked} value={answers[field.key]??''} onChange={e=>setAnswers({...answers,[field.key]:e.target.value})}/></label>:field.type==='select'?<label key={field.key}>{field.label}{field.required&&' *'}<select aria-label={field.label} required={field.required} disabled={!!locked} value={answers[field.key]??''} onChange={e=>setAnswers({...answers,[field.key]:e.target.value})}><option value="">اختر</option>{Array.isArray(field.config.options)&&field.config.options.map(x=><option key={String(x)} value={String(x)}>{String(x)}</option>)}</select></label>:<label key={field.key}>{field.label}{field.required&&' *'}<input aria-label={field.label} type={field.type==='email'?'email':'text'} required={field.required} disabled={!!locked} value={answers[field.key]??''} onChange={e=>setAnswers({...answers,[field.key]:e.target.value})}/></label>)}</div>
  <footer className="p84-public-actions">{!locked&&<><button disabled={busy} onClick={()=>void save(false)}>حفظ كمسودة</button><button className="primary" disabled={busy} onClick={()=>void save(true)}>إرسال للمراجعة</button></>}{locked&&<strong data-submission-status={view.submission?.status}>الحالة: {view.submission?.status}</strong>}{onReturn&&<button className="ghost" onClick={onReturn}>العودة للمكتب</button>}</footer>
  <small className="p84-expiry">الرابط صالح حتى {view.expiresAt.slice(0,16).replace('T',' ')}. لا نخزن التوكن في localStorage.</small>
 </section>
}
