import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { DataAccessError } from '../../data/contracts/DataAccessError.ts';
import { OrganizationAssignmentCatalogProvider } from '../../features/organization/OrganizationAssignmentCatalogContext.tsx';
import { OrganizationCommandProvider } from '../../features/organization/OrganizationCommandContext.tsx';
import { OrganizationWorkspaceResolverProvider } from '../../features/organization/OrganizationWorkspaceResolverContext.tsx';
import type { OrganizationAssignableTransaction, OrganizationAssignmentCatalog } from '../../features/organization/organizationAssignmentCatalog.ts';
import type { OrganizationBranch, OrganizationContext, OrganizationDepartment, OrganizationGateway, OrganizationMember, OrganizationOwnershipEvent, OrganizationScopeMembership, OrganizationTeam, OrganizationTransaction } from '../../features/organization/organizationCommands.ts';
import type { OrganizationWorkspaceAccess, OrganizationWorkspaceResolver } from '../../features/organization/organizationWorkspaceResolver.ts';
import { LiveOrganizationExperience } from './LiveOrganizationExperience.tsx';
import '../runtime/shell-base.css';
import '../runtime/shell.css';
import '../runtime/accessibility-hardening.css';
import './organization.css';

const W1='11111111-1111-4111-8111-111111111111',W2='11111111-1111-4111-8111-222222222222';
const OWNER='22222222-2222-4222-8222-111111111111',USER='22222222-2222-4222-8222-222222222222';
const MEMBER='33333333-3333-4333-8333-333333333333',B1='44444444-4444-4444-8444-111111111111',B2='44444444-4444-4444-8444-222222222222',D1='55555555-5555-4555-8555-111111111111',D2='55555555-5555-4555-8555-222222222222',T1='66666666-6666-4666-8666-111111111111',T2='66666666-6666-4666-8666-222222222222',S1='77777777-7777-4777-8777-111111111111',TX1='88888888-8888-4888-8888-111111111111',TX2='88888888-8888-4888-8888-222222222222',C1='99999999-9999-4999-8999-111111111111',C2='99999999-9999-4999-8999-222222222222',O1='aaaaaaaa-aaaa-4aaa-8aaa-111111111111',E1='bbbbbbbb-bbbb-4bbb-8bbb-111111111111';
const WB='44444444-4444-4444-8444-333333333333',WD='55555555-5555-4555-8555-333333333333',WT='66666666-6666-4666-8666-333333333333',WS='77777777-7777-4777-8777-333333333333',WO='aaaaaaaa-aaaa-4aaa-8aaa-333333333333',WE='bbbbbbbb-bbbb-4bbb-8bbb-333333333333';
let serial=40;const uid=(prefix:string)=>`${prefix}${String(serial++).padStart(12,'0')}`;

let members:OrganizationMember[]=[];
let branches:OrganizationBranch[]=[{id:B1,name:'فرع المنصور',code:'MNS',address:'بغداد · المنصور',status:'active',version:1,accessSourceMembershipId:null},{id:B2,name:'فرع الكرادة',code:'KRD',address:'بغداد · الكرادة',status:'active',version:1,accessSourceMembershipId:null}];
let departments:OrganizationDepartment[]=[{id:D1,branchId:B1,name:'قسم الشركات',code:'COMP',status:'active',version:1,accessSourceMembershipId:null},{id:D2,branchId:B2,name:'قسم المتابعة',code:'FOLLOW',status:'active',version:1,accessSourceMembershipId:null}];
let teams:OrganizationTeam[]=[{id:T1,departmentId:D1,name:'فريق التسجيل',code:'REG',status:'active',version:1,accessSourceMembershipId:null},{id:T2,departmentId:D2,name:'فريق الإنجاز',code:'DONE',status:'active',version:1,accessSourceMembershipId:null}];
let scopes:OrganizationScopeMembership[]=[];
let ownerTransactions:OrganizationTransaction[]=[{transactionId:TX1,companyId:C1,companyName:'شركة الرافدين',type:'تسجيل شركة',status:'active',priority:'high',updatedAt:'2026-09-09T06:10:00.000Z',ownershipId:O1,ownershipVersion:1,scopeType:'department',branchId:null,departmentId:D1,teamId:null,accessSourceMembershipId:null}];
let events:OrganizationOwnershipEvent[]=[{id:E1,transactionId:TX1,eventType:'assigned',fromScopeType:null,fromBranchId:null,fromDepartmentId:null,fromTeamId:null,toScopeType:'department',toBranchId:null,toDepartmentId:D1,toTeamId:null,reason:'إسناد افتتاحي لقسم الشركات',actorUserId:OWNER,createdAt:'2026-09-09T06:11:00.000Z'}];
const baseCatalog:OrganizationAssignableTransaction[]=[{transactionId:TX1,companyId:C1,companyName:'شركة الرافدين',type:'تسجيل شركة',status:'active',priority:'high',updatedAt:'2026-09-09T06:10:00.000Z',ownershipId:O1,ownershipVersion:1,scopeType:'department',branchId:null,departmentId:D1,teamId:null},{transactionId:TX2,companyId:C2,companyName:'شركة النهرين',type:'تعديل عقد',status:'active',priority:'normal',updatedAt:'2026-09-09T06:09:00.000Z',ownershipId:null,ownershipVersion:null,scopeType:null,branchId:null,departmentId:null,teamId:null}];

const workforceContext=():OrganizationContext=>{const context:OrganizationContext={
  authority:'organization_structure_scoped_ownership',workspaceTrustAuthority:'legacy_owner_only_unchanged',workforceAuthority:'organization_members_and_scope_memberships',legacyWorkspaceWideAccessForWorkforce:'forbidden',transactionLifecycleWriteAuthority:'none',financeLedgerWriteAuthority:'none',actor:{userId:USER,actorType:'workforce',organizationMemberId:MEMBER},
  members:Object.freeze([{id:MEMBER,userId:USER,status:'active',validFrom:'2026-09-09T05:00:00.000Z',validUntil:null,version:1}]),
  branches:Object.freeze([{id:WB,name:'فرع الرصافة',code:'RSF',address:'بغداد · الرصافة',status:'active',version:1,accessSourceMembershipId:WS}]),
  departments:Object.freeze([{id:WD,branchId:WB,name:'قسم المعاملات',code:'OPS',status:'active',version:1,accessSourceMembershipId:WS}]),
  teams:Object.freeze([{id:WT,departmentId:WD,name:'فريق التنفيذ',code:'EXEC',status:'active',version:1,accessSourceMembershipId:WS}]),
  scopeMemberships:Object.freeze([{id:WS,organizationMemberId:MEMBER,scopeType:'branch',branchId:WB,departmentId:null,teamId:null,scopeRole:'manager',status:'active',validFrom:'2026-09-09T05:00:00.000Z',validUntil:null,version:1}]),
  transactions:Object.freeze([{transactionId:TX1,companyId:C1,companyName:'شركة الرافدين',type:'تسجيل شركة',status:'active',priority:'high',updatedAt:'2026-09-09T06:10:00.000Z',ownershipId:WO,ownershipVersion:1,scopeType:'team',branchId:null,departmentId:null,teamId:WT,accessSourceMembershipId:WS}]),
  ownershipEvents:Object.freeze([{id:WE,transactionId:TX1,eventType:'assigned',fromScopeType:null,fromBranchId:null,fromDepartmentId:null,fromTeamId:null,toScopeType:'team',toBranchId:null,toDepartmentId:null,toTeamId:WT,reason:'إسناد إلى الفريق',actorUserId:USER,createdAt:'2026-09-09T06:12:00.000Z'}])
};return Object.freeze(context)};
const ownerContext=():OrganizationContext=>{const context:OrganizationContext={authority:'organization_structure_scoped_ownership',workspaceTrustAuthority:'legacy_owner_only_unchanged',workforceAuthority:'organization_members_and_scope_memberships',legacyWorkspaceWideAccessForWorkforce:'forbidden',transactionLifecycleWriteAuthority:'none',financeLedgerWriteAuthority:'none',actor:{userId:OWNER,actorType:'owner',organizationMemberId:null},members:Object.freeze([...members]),branches:Object.freeze([...branches]),departments:Object.freeze([...departments]),teams:Object.freeze([...teams]),scopeMemberships:Object.freeze([...scopes]),transactions:Object.freeze([...ownerTransactions]),ownershipEvents:Object.freeze([...events])};return Object.freeze(context)};
const forbid=()=>{throw new DataAccessError('preview workforce write forbidden','DATA_FORBIDDEN')};

const resolver:OrganizationWorkspaceResolver={async listWorkspaces(){const rows:readonly OrganizationWorkspaceAccess[]=[{workspaceId:W1,workspaceName:'مكتب إنجاز الرئيسي',actorType:'owner',organizationMemberId:null},{workspaceId:W2,workspaceName:'مساحة الرصافة المحدودة',actorType:'workforce',organizationMemberId:MEMBER}];return Object.freeze(rows)}};
const catalog:OrganizationAssignmentCatalog={async list(workspaceId){if(workspaceId!==W1)forbid();return Object.freeze(baseCatalog.map(tx=>{const current=ownerTransactions.find(x=>x.transactionId===tx.transactionId);return current?{...tx,ownershipId:current.ownershipId,ownershipVersion:current.ownershipVersion,scopeType:current.scopeType,branchId:current.branchId,departmentId:current.departmentId,teamId:current.teamId}:{...tx,ownershipId:null,ownershipVersion:null,scopeType:null,branchId:null,departmentId:null,teamId:null}}))}};
const gateway:OrganizationGateway={
  async loadContext(workspaceId){if(workspaceId===W1)return ownerContext();if(workspaceId===W2)return workforceContext();throw new Error('workspace mismatch')},
  async setMember(input){if(input.workspaceId!==W1)forbid();const found=members.find(x=>x.userId===input.userId);if(found){members=members.map(x=>x.userId===input.userId?{...x,status:input.status,validUntil:input.validUntil,version:x.version+1}:x);return{memberId:found.id,userId:input.userId,status:input.status,version:found.version+1,wasCreated:false}}const id=uid('33333333-3333-4333-8333-');members=[...members,{id,userId:input.userId,status:input.status,validFrom:'2026-09-09T06:30:00.000Z',validUntil:input.validUntil,version:1}];return{memberId:id,userId:input.userId,status:input.status,version:1,wasCreated:true}},
  async saveBranch(input){if(input.workspaceId!==W1)forbid();if(input.branchId){const row=branches.find(x=>x.id===input.branchId);if(!row||row.version!==input.expectedVersion)throw new DataAccessError('stale','DATA_CONFLICT');branches=branches.map(x=>x.id===input.branchId?{...x,name:input.name,code:input.code,address:input.address,status:input.status,version:x.version+1}:x);return{branchId:input.branchId,version:row.version+1,status:input.status,wasCreated:false}}const id=uid('44444444-4444-4444-8444-');branches=[...branches,{id,name:input.name,code:input.code,address:input.address,status:input.status,version:1,accessSourceMembershipId:null}];return{branchId:id,version:1,status:input.status,wasCreated:true}},
  async saveDepartment(input){if(input.workspaceId!==W1)forbid();if(input.departmentId)throw new Error('preview update not needed');const id=uid('55555555-5555-4555-8555-');departments=[...departments,{id,branchId:input.branchId,name:input.name,code:input.code,status:input.status,version:1,accessSourceMembershipId:null}];return{departmentId:id,version:1,status:input.status,wasCreated:true}},
  async saveTeam(input){if(input.workspaceId!==W1)forbid();if(input.teamId)throw new Error('preview update not needed');const id=uid('66666666-6666-4666-8666-');teams=[...teams,{id,departmentId:input.departmentId,name:input.name,code:input.code,status:input.status,version:1,accessSourceMembershipId:null}];return{teamId:id,version:1,status:input.status,wasCreated:true}},
  async setScopeMembership(input){if(input.workspaceId!==W1)forbid();const member=members.find(x=>x.userId===input.userId&&x.status==='active');if(!member)throw new DataAccessError('member inactive','DATA_VALIDATION_FAILED');const id=input.membershipId??uid('77777777-7777-4777-8777-'),row:OrganizationScopeMembership={id,organizationMemberId:member.id,scopeType:input.target.scopeType,branchId:input.target.branchId,departmentId:input.target.departmentId,teamId:input.target.teamId,scopeRole:input.scopeRole,status:input.status,validFrom:input.validFrom??'2026-09-09T06:30:00.000Z',validUntil:input.validUntil,version:1};scopes=input.membershipId?scopes.map(x=>x.id===id?{...row,version:x.version+1}:x):[...scopes,row];return{membershipId:id,version:1,status:input.status,wasCreated:!input.membershipId}},
  async assignTransaction(input){if(input.workspaceId!==W1&&input.workspaceId!==W2)throw new Error('workspace mismatch');if(input.workspaceId===W2){const current=workforceContext().transactions.find(x=>x.transactionId===input.transactionId);if(!current||input.expectedVersion!==current.ownershipVersion)throw new DataAccessError('stale','DATA_CONFLICT');return{ownershipId:current.ownershipId,version:current.ownershipVersion+1,scopeType:input.target.scopeType,branchId:input.target.branchId,departmentId:input.target.departmentId,teamId:input.target.teamId,wasCreated:false,wasNoop:false}}
    const current=ownerTransactions.find(x=>x.transactionId===input.transactionId),catalogRow=baseCatalog.find(x=>x.transactionId===input.transactionId);if(!catalogRow)throw new Error('transaction');if(current&&input.expectedVersion!==current.ownershipVersion)throw new DataAccessError('stale','DATA_CONFLICT');const ownershipId=current?.ownershipId??uid('aaaaaaaa-aaaa-4aaa-8aaa-'),nextVersion=(current?.ownershipVersion??0)+1,row:OrganizationTransaction={transactionId:input.transactionId,companyId:catalogRow.companyId,companyName:catalogRow.companyName,type:catalogRow.type,status:catalogRow.status,priority:catalogRow.priority,updatedAt:'2026-09-09T06:40:00.000Z',ownershipId,ownershipVersion:nextVersion,scopeType:input.target.scopeType,branchId:input.target.branchId,departmentId:input.target.departmentId,teamId:input.target.teamId,accessSourceMembershipId:null};ownerTransactions=current?ownerTransactions.map(x=>x.transactionId===input.transactionId?row:x):[...ownerTransactions,row];events=[{id:uid('bbbbbbbb-bbbb-4bbb-8bbb-'),transactionId:input.transactionId,eventType:current?'transferred':'assigned',fromScopeType:current?.scopeType??null,fromBranchId:current?.branchId??null,fromDepartmentId:current?.departmentId??null,fromTeamId:current?.teamId??null,toScopeType:row.scopeType,toBranchId:row.branchId,toDepartmentId:row.departmentId,toTeamId:row.teamId,reason:input.reason,actorUserId:OWNER,createdAt:'2026-09-09T06:41:00.000Z'},...events];return{ownershipId,version:nextVersion,scopeType:row.scopeType,branchId:row.branchId,departmentId:row.departmentId,teamId:row.teamId,wasCreated:!current,wasNoop:false}},
  async explainAccess(workspaceId,t){if(workspaceId===W1)return{allowed:true,actorType:'owner',source:'workspace_owner',sourceMembershipId:null};if(workspaceId===W2)return{allowed:true,actorType:'workforce',source:'explicit_or_downward_inherited',sourceMembershipId:WS,sourceScopeType:'branch',sourceRole:'manager',sourceBranchId:WB,sourceDepartmentId:null,sourceTeamId:null};throw new Error(`scope ${t.scopeType}`)}
};

function PreviewApp(){return <div className="ez-r2-root r2-shell" data-r2-runtime-mode="phase85-preview" data-destination="account" dir="rtl"><main id="r2-main" className="r2-shell__main"><OrganizationWorkspaceResolverProvider resolver={Object.freeze(resolver)}><OrganizationAssignmentCatalogProvider catalog={Object.freeze(catalog)}><OrganizationCommandProvider gateway={Object.freeze(gateway)}><LiveOrganizationExperience/></OrganizationCommandProvider></OrganizationAssignmentCatalogProvider></OrganizationWorkspaceResolverProvider></main></div>}
const root=document.getElementById('phase85-organization-root');if(!root)throw new Error('Phase 8.5 preview root missing');createRoot(root).render(<StrictMode><PreviewApp/></StrictMode>);
