import type { FinanceSource } from './financeModel.ts';
import { buildFinanceLedgerSnapshot, financeMoneyToCents } from './financeModel.ts';

const DAY=864e5, KEYS=['0_30','31_60','61_90','91_plus'] as const, LABELS=['0–30 يوم','31–60 يوم','61–90 يوم','أكثر من 90 يوم'] as const;
export type FinanceAgingBucketKey=typeof KEYS[number];
export type FinanceAttentionLevel='watch'|'high'|'critical';
export type FinanceHealthBand='healthy'|'watch'|'high_risk';
export type FinanceSignalSeverity='info'|'watch'|'high';
export interface FinanceAgingBucket{readonly key:FinanceAgingBucketKey;readonly label:string;readonly minDays:number;readonly maxDays:number|null;readonly receivableCount:number;readonly outstandingCents:bigint}
export interface FinanceAttentionItem{readonly transactionId:string;readonly transactionLabel:string;readonly companyId:string;readonly companyLabel:string;readonly outstandingCents:bigint;readonly ageDays:number;readonly agingBucket:FinanceAgingBucketKey;readonly level:FinanceAttentionLevel;readonly reason:string}
export interface CompanyFinancialHealth{readonly companyId:string;readonly companyLabel:string;readonly totalFeesCents:bigint;readonly collectedCents:bigint;readonly outstandingCents:bigint;readonly creditCents:bigint;readonly staleOutstandingCents:bigint;readonly collectionRateBps:number;readonly healthScore:number;readonly band:FinanceHealthBand;readonly reasons:readonly string[]}
export interface FinanceTrendPeriod{readonly monthKey:string;readonly monthLabel:string;readonly collectedCents:bigint;readonly ledgerInCents:bigint;readonly ledgerOutCents:bigint;readonly netCashCents:bigint}
export interface FinanceRunRate{readonly recent30CollectedCents:bigint;readonly previous30CollectedCents:bigint;readonly changeBps:number|null;readonly averageDailyCollectionCents:bigint;readonly projectedNext30AtSameRunRateCents:bigint;readonly samplePaymentCount:number;readonly confidence:'insufficient'|'directional'}
export interface FinanceIntelligenceSignal{readonly id:string;readonly severity:FinanceSignalSeverity;readonly title:string;readonly explanation:string;readonly amountCents:bigint|null}
export interface FinanceIntelligenceSnapshot{readonly asOf:string;readonly agingBasis:'transaction_created_at';readonly agingDisclosure:string;readonly totalOutstandingCents:bigint;readonly totalCreditCents:bigint;readonly aging:readonly FinanceAgingBucket[];readonly attentionQueue:readonly FinanceAttentionItem[];readonly companyHealth:readonly CompanyFinancialHealth[];readonly trends:readonly FinanceTrendPeriod[];readonly runRate:FinanceRunRate;readonly signals:readonly FinanceIntelligenceSignal[];readonly counts:Readonly<{receivables:number;attention:number;companies:number;signals:number}>}
export class FinanceIntelligenceDateError extends Error{constructor(readonly recordType:string,readonly recordId:string,readonly value:string){super(`invalid finance intelligence date: ${recordType}:${recordId}`);this.name='FinanceIntelligenceDateError'}}

const stamp=(v:string,t:string,id:string)=>{const n=Date.parse(v);if(!Number.isFinite(n))throw new FinanceIntelligenceDateError(t,id,v);return n};
const age=(v:string,now:number,id:string)=>Math.max(0,Math.floor((now-stamp(v,'transaction',id))/DAY));
const key=(d:number):FinanceAgingBucketKey=>KEYS[d<=30?0:d<=60?1:d<=90?2:3];
const bps=(a:bigint,b:bigint)=>b>0n?Number((a*10000n)/b):0;
const reversed=(s:FinanceSource,p:{id:string;status:string})=>p.status==='reversed'||s.paymentReversals.some(r=>r.payment_id===p.id);
const month=(d:Date)=>`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;
const txLabel=(t:{legacy_id:string|null;type:string;id:string})=>t.legacy_id?.trim()?`معاملة ${t.legacy_id.trim()}`:t.type||`معاملة ${t.id.slice(0,8)}`;

export function buildFinancialIntelligenceSnapshot(s:FinanceSource,asOfInput:Date|string=new Date()):FinanceIntelligenceSnapshot{
 const d=asOfInput instanceof Date?new Date(asOfInput):new Date(asOfInput);if(!Number.isFinite(d.getTime()))throw new FinanceIntelligenceDateError('as_of','snapshot',String(asOfInput));
 const now=d.getTime(),base=buildFinanceLedgerSnapshot(s),tx=new Map(s.transactions.map(v=>[v.id,v])),total=base.summary.outstandingCents;
 const a=KEYS.map((k,i)=>({key:k,label:LABELS[i],minDays:[0,31,61,91][i]!,maxDays:[30,60,90,null][i] as number|null,receivableCount:0,outstandingCents:0n}));
 const attention:FinanceAttentionItem[]=[],companies=new Map<string,{total:bigint;paid:bigint;open:bigint;credit:bigint;stale:bigint}>();
 for(const r of base.receivables){const t=tx.get(r.transactionId);if(!t)continue;const n=age(t.created_at,now,t.id),i=n<=30?0:n<=60?1:n<=90?2:3;a[i]!.receivableCount++;a[i]!.outstandingCents+=r.outstandingCents;
  const c=companies.get(r.companyId)??{total:0n,paid:0n,open:0n,credit:0n,stale:0n};c.total+=r.feeCents;c.paid+=r.collectedCents;c.open+=r.outstandingCents;c.credit+=r.creditCents;if(n>90)c.stale+=r.outstandingCents;companies.set(r.companyId,c);
  if(r.outstandingCents>0n&&n>30){const q=bps(r.outstandingCents,total),level:FinanceAttentionLevel=n>90||q>=5000?'critical':n>60||q>=3000?'high':'watch';attention.push({transactionId:r.transactionId,transactionLabel:txLabel(t),companyId:r.companyId,companyLabel:r.companyLabel,outstandingCents:r.outstandingCents,ageDays:n,agingBucket:key(n),level,reason:`رصيد مفتوح لأكثر من ${n>90?90:n>60?60:30} يوماً.`})}}
 attention.sort((x,y)=>y.ageDays-x.ageDays||Number(y.outstandingCents-x.outstandingCents));
 const companyHealth=[...companies].map(([companyId,c])=>{const rate=Math.min(10000,bps(c.paid,c.total)),score=Math.max(0,100-Math.min(45,Math.round(Math.min(10000,bps(c.open,c.total||1n))*45/10000))-Math.min(35,Math.round(Math.min(10000,bps(c.stale,c.open||1n))*35/10000))-Math.min(10,Math.round(Math.min(10000,bps(c.credit,c.total||1n))*10/10000))),band:FinanceHealthBand=score>=75?'healthy':score>=50?'watch':'high_risk',reasons:string[]=[];if(c.stale)reasons.push('يوجد رصيد مفتوح تجاوز 90 يوماً من تاريخ إنشاء المعاملة.');if(c.open&&rate<5000)reasons.push('نسبة التحصيل أقل من 50% من الأتعاب المسجلة.');if(c.credit)reasons.push('يوجد رصيد دائن يحتاج تفسيراً أو تخصيصاً.');if(!reasons.length)reasons.push('لا توجد إشارة مالية مرتفعة ضمن قواعد 7.3 الحالية.');const co=s.companies.find(v=>v.id===companyId);return{companyId,companyLabel:co?.display_name?.trim()||co?.legal_name||'شركة غير متاحة',totalFeesCents:c.total,collectedCents:c.paid,outstandingCents:c.open,creditCents:c.credit,staleOutstandingCents:c.stale,collectionRateBps:rate,healthScore:score,band,reasons}}).sort((x,y)=>x.healthScore-y.healthScore);
 const months=Array.from({length:6},(_,i)=>new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()-5+i,1))),tm=new Map(months.map(v=>[month(v),{collected:0n,ledgerIn:0n,ledgerOut:0n}]));let recent=0n,previous=0n,samples=0;
 for(const p of s.payments){if(reversed(s,p))continue;const ms=stamp(p.paid_at,'payment',p.id),v=financeMoneyToCents(p.amount,'payment',p.id),z=tm.get(month(new Date(ms)));if(z)z.collected+=v;if(ms<=now&&ms>=now-30*DAY){recent+=v;samples++}else if(ms<now-30*DAY&&ms>=now-60*DAY)previous+=v}
 for(const e of s.ledger){if(e.status==='reversed')continue;const z=tm.get(month(new Date(stamp(e.occurred_at,'ledger',e.id))));if(!z)continue;const v=financeMoneyToCents(e.amount,'ledger',e.id);e.direction==='out'?z.ledgerOut+=v:z.ledgerIn+=v}
 const trends=months.map(v=>{const m=tm.get(month(v))!,collectedCents=m.collected,ledgerInCents=m.ledgerIn,ledgerOutCents=m.ledgerOut;return{monthKey:month(v),monthLabel:month(v),collectedCents,ledgerInCents,ledgerOutCents,netCashCents:collectedCents+ledgerInCents-ledgerOutCents}}),avg=recent/30n,runRate={recent30CollectedCents:recent,previous30CollectedCents:previous,changeBps:previous?bps(recent-previous,previous):null,averageDailyCollectionCents:avg,projectedNext30AtSameRunRateCents:avg*30n,samplePaymentCount:samples,confidence:(samples>=4?'directional':'insufficient') as 'directional'|'insufficient'};
 const signals:FinanceIntelligenceSignal[]=[];const sig=(id:string,severity:FinanceSignalSeverity,title:string,explanation:string,amountCents:bigint|null=null)=>signals.push({id,severity,title,explanation,amountCents});
 if(base.summary.paymentIntegrityWarnings)sig('payment-integrity','high','مطابقة الدفعات تحتاج مراجعة',`${base.summary.paymentIntegrityWarnings} دفعة تختلف حالتها عن سجل العكس.`);if(a[3]!.outstandingCents)sig('stale-receivables','high','أرصدة قديمة مرتفعة','يوجد رصيد تجاوز 90 يوماً؛ هذا عمر تشغيلي وليس استحقاقاً قانونياً.',a[3]!.outstandingCents);if(base.summary.creditCents)sig('credit-balance','watch','رصيد دائن ظاهر','التحصيل تجاوز الأتعاب الحالية في معاملة واحدة أو أكثر.',base.summary.creditCents);
 const payCount=base.summary.postedPayments+base.summary.reversedPayments;if(payCount&&base.summary.reversedPayments/payCount>=.2)sig('reversal-rate','watch','معدل عكس دفعات مرتفع','نسبة العكوسات في سجل الدفعات الحالي مرتفعة.');const top=base.receivables.filter(v=>v.outstandingCents>0n).sort((x,y)=>x.outstandingCents>y.outstandingCents?-1:1)[0];if(top&&bps(top.outstandingCents,total)>=5000)sig('receivable-concentration','watch','تركيز مرتفع في رصيد واحد',`${top.companyLabel} تمثل 50% أو أكثر من الرصيد المفتوح.`,top.outstandingCents);const last=trends.at(-1);if(last&&last.netCashCents<0n)sig('negative-current-month','watch','حركة نقدية شهرية سالبة','الخروج المسجل تجاوز التحصيل والدخول في الشهر الحالي.',-last.netCashCents);if(!signals.length)sig('no-high-signal','info','لا توجد إشارة مالية مرتفعة حالياً','قواعد 7.3 الحالية لم تكتشف نمطاً يحتاج تصعيداً.');
 return Object.freeze({asOf:d.toISOString(),agingBasis:'transaction_created_at',agingDisclosure:'لا يحتوي نموذج المعاملة الحالي على تاريخ استحقاق مالي مستقل؛ لذلك يقيس 7.3 عمر الرصيد من تاريخ إنشاء المعاملة ولا يصفه كاستحقاق قانوني.',totalOutstandingCents:total,totalCreditCents:base.summary.creditCents,aging:a,attentionQueue:attention,companyHealth,trends,runRate,signals,counts:{receivables:base.receivables.filter(v=>v.outstandingCents>0n).length,attention:attention.length,companies:companyHealth.length,signals:signals.length}});
}
