-- Applied live to project juzxriirhkuzviwnhkbd.
create index audit_events_actor_user_idx on public.audit_events(actor_user_id);
create index calendar_events_company_fk_idx on public.calendar_events(workspace_id, company_id);
create index calendar_events_contact_fk_idx on public.calendar_events(workspace_id, contact_id);
create index calendar_events_transaction_fk_idx on public.calendar_events(workspace_id, transaction_id);
create index communications_company_fk_idx on public.communications(workspace_id, company_id);
create index communications_contact_fk_idx on public.communications(workspace_id, contact_id);
create index companies_merge_target_fk_idx on public.companies(workspace_id, merged_into_id);
create index companies_primary_contact_fk_idx on public.companies(workspace_id, primary_contact_id);
create index contacts_merge_target_fk_idx on public.contacts(workspace_id, merged_into_id);
create index correspondence_company_fk_idx on public.correspondence_registry(workspace_id, company_id);
create index correspondence_document_fk_idx on public.correspondence_registry(workspace_id, document_id);
create index correspondence_transaction_fk_idx on public.correspondence_registry(workspace_id, transaction_id);
create index document_analysis_duplicate_fk_idx on public.document_analysis(workspace_id, duplicate_of_document_id);
create index document_drafts_company_fk_idx on public.document_drafts(workspace_id, company_id);
create index document_drafts_correspondence_fk_idx on public.document_drafts(workspace_id, correspondence_id);
create index document_drafts_template_fk_idx on public.document_drafts(workspace_id, template_id);
create index document_drafts_transaction_fk_idx on public.document_drafts(workspace_id, transaction_id);
create index lifecycle_actor_user_idx on public.entity_lifecycle_events(actor_user_id);
create index fee_changes_actor_user_idx on public.fee_changes(actor_user_id);
create index ledger_company_fk_idx on public.financial_ledger_entries(workspace_id, company_id);
create index notification_deliveries_user_idx on public.notification_deliveries(user_id);
create index notification_preferences_user_idx on public.notification_preferences(user_id);
create index payment_reversals_actor_user_idx on public.payment_reversals(actor_user_id);
create index payments_transaction_company_fk_idx on public.payments(workspace_id, transaction_id, company_id);
create index pdf_jobs_output_document_fk_idx on public.pdf_jobs(workspace_id, output_document_id);
create index pdf_jobs_source_document_fk_idx on public.pdf_jobs(workspace_id, source_document_id);
create index renewals_company_fk_idx on public.renewals(workspace_id, company_id);
create index renewals_transaction_fk_idx on public.renewals(workspace_id, transaction_id);
create index sync_devices_membership_fk_idx on public.sync_devices(workspace_id, user_id);
create index sync_devices_user_idx on public.sync_devices(user_id);
create index transaction_activity_actor_user_idx on public.transaction_activity(actor_user_id);
create index followups_completed_by_idx on public.transaction_followups(completed_by);
create index followups_transaction_fk_idx on public.transaction_followups(workspace_id, transaction_id);
create index transaction_notes_created_by_idx on public.transaction_notes(created_by);
create index transaction_routes_created_by_idx on public.transaction_routes(created_by);
create index transactions_deleted_by_idx on public.transactions(deleted_by);
create index transactions_primary_contact_fk_idx on public.transactions(workspace_id, primary_contact_id);
create index workflow_instances_template_fk_idx on public.workflow_instances(workspace_id, workflow_template_id);
create index workspace_settings_signature_fk_idx on public.workspace_settings(workspace_id, signature_document_id);
create index workspaces_owner_user_idx on public.workspaces(owner_user_id);
