import {createClient} from 'npm:@supabase/supabase-js@2.114.0';

type J=Record<string,unknown>;
type ExtractionClaim={analysisId:string;workspaceId:string;documentId:string;documentVersionId:string;sourceVersionNumber:number;sourceChecksum:string|null;bucket:string;path:string;mimeType:string;byteSize:number;fileName:string;sourceAuthority:string};
type ProviderField={key:string;value:string|null;confidence:number;pageNumber:number;sourceText:string|null;corrected:false};
type ProviderPage={pageNumber:number;text:string;confidence:number;fields:ProviderField[]};
type ProviderResult={text:string;pages:ProviderPage[];extracted:J;classification:string|null;confidence:number;runId:string|null};
type Provider={kind:'azure';name:string;endpoint:string;key:string}|{kind:'generic';name:string;url:string;key:string};

const MAX_BODY=16_384,MAX_PROVIDER_TEXT=8_000_000,MAX_PROVIDER_JSON=12_000_000;
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type,x-client-info,apikey','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const out=(s:number,b:J)=>new Response(JSON.stringify(b),{status:s,headers:cors});
const txt=(v:unknown,n:number)=>{if(typeof v!=='string'||!v.trim()||v.length>n)throw new Error('INVALID_INPUT');return v.trim()};
const uid=(v:unknown)=>{const s=txt(v,64);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new Error('INVALID_UUID');return s};
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as J:(()=>{throw new Error('INVALID_OBJECT')})();
const arr=(v:unknown)=>Array.isArray(v)?v:[];
const boundedConfidence=(v:unknown,fallback=0)=>{const n=Number(v);return Number.isFinite(n)&&n>=0&&n<=1?n:fallback};

function secret(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern)try{const p=JSON.parse(modern) as Record<string,string>;if(p.default)return p.default}catch{}const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(legacy)return legacy;throw new Error('SERVER_SECRET_UNAVAILABLE')}
function publicKey(){const k=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY');if(k)return k;throw new Error('SERVER_PUBLIC_KEY_UNAVAILABLE')}
function normalizeHttpsEndpoint(value:string){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw new Error('OCR_PROVIDER_NOT_CONFIGURED');u.search='';u.hash='';const path=u.pathname.replace(/\/+$/,'');return`${u.origin}${path}`}
function providerConfig():Provider{
  const azureEndpoint=Deno.env.get('ENJAZ_AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT')?.trim(),azureKey=Deno.env.get('ENJAZ_AZURE_DOCUMENT_INTELLIGENCE_KEY')?.trim();
  if(azureEndpoint||azureKey){if(!azureEndpoint||!azureKey)throw new Error('OCR_PROVIDER_NOT_CONFIGURED');return{kind:'azure',name:'azure-document-intelligence/prebuilt-layout-v4',endpoint:normalizeHttpsEndpoint(azureEndpoint),key:azureKey}}
  const url=Deno.env.get('ENJAZ_OCR_PROVIDER_URL')?.trim(),key=Deno.env.get('ENJAZ_OCR_PROVIDER_KEY')?.trim();
  if(!url||!key)throw new Error('OCR_PROVIDER_NOT_CONFIGURED');return{kind:'generic',name:Deno.env.get('ENJAZ_OCR_PROVIDER_NAME')?.trim().slice(0,240)||'external-ocr',url:normalizeHttpsEndpoint(url),key}
}
function claim(v:unknown):ExtractionClaim{const r=obj(v),c={analysisId:uid(r.analysisId),workspaceId:uid(r.workspaceId),documentId:uid(r.documentId),documentVersionId:uid(r.documentVersionId),sourceVersionNumber:Number(r.sourceVersionNumber),sourceChecksum:r.sourceChecksum==null?null:txt(r.sourceChecksum,64).toLowerCase(),bucket:txt(r.bucket,80),path:txt(r.path,1200),mimeType:txt(r.mimeType,160).toLowerCase(),byteSize:Number(r.byteSize),fileName:txt(r.fileName,240),sourceAuthority:txt(r.sourceAuthority,80)};if(c.bucket!=='enjaz-documents-private'||c.sourceAuthority!=='SOURCE_FILE_REMAINS_AUTHORITATIVE'||!Number.isSafeInteger(c.sourceVersionNumber)||c.sourceVersionNumber<1||!Number.isSafeInteger(c.byteSize)||c.byteSize<1||c.byteSize>52_428_800)throw new Error('INVALID_EXTRACTION_CLAIM');return c}
function validateResult(result:ProviderResult){if(result.text.length>MAX_PROVIDER_TEXT||!result.pages.length||result.confidence<0||result.confidence>1)throw new Error('OCR_PROVIDER_RESULT_INVALID');const encoded=JSON.stringify({pages:result.pages,extracted:result.extracted});if(encoded.length>MAX_PROVIDER_JSON)throw new Error('OCR_PROVIDER_RESULT_TOO_LARGE');return result}
function genericProviderResult(v:unknown):ProviderResult{const r=obj(v);if(r.schema!=='enjaz.ocr-provider.v1')throw new Error('OCR_PROVIDER_SCHEMA_INVALID');const text=typeof r.text==='string'&&r.text.length<=MAX_PROVIDER_TEXT?r.text:(()=>{throw new Error('OCR_PROVIDER_TEXT_INVALID')})(),confidence=Number(r.confidence);if(!Number.isFinite(confidence)||confidence<0||confidence>1)throw new Error('OCR_PROVIDER_CONFIDENCE_INVALID');if(!Array.isArray(r.pages)||!r.pages.length)throw new Error('OCR_PROVIDER_PAGES_INVALID');const seen=new Set<number>(),pages=r.pages.map(raw=>{const p=obj(raw),pageNumber=Number(p.pageNumber),pc=Number(p.confidence);if(!Number.isSafeInteger(pageNumber)||pageNumber<1||seen.has(pageNumber)||!Number.isFinite(pc)||pc<0||pc>1||typeof p.text!=='string')throw new Error('OCR_PROVIDER_PAGE_INVALID');seen.add(pageNumber);const fields=Array.isArray(p.fields)?p.fields.map(rawField=>{const f=obj(rawField),key=txt(f.key,160),fc=Number(f.confidence),fp=Number(f.pageNumber);if(!Number.isFinite(fc)||fc<0||fc>1||!Number.isSafeInteger(fp)||fp!==pageNumber||!(f.value==null||typeof f.value==='string')||!(f.sourceText==null||typeof f.sourceText==='string'))throw new Error('OCR_PROVIDER_FIELD_INVALID');return{key,value:f.value??null,confidence:fc,pageNumber:fp,sourceText:f.sourceText??null,corrected:false as const}}):[];return{pageNumber,text:p.text,confidence:pc,fields}}),extracted=obj(r.fields??{});for(const [key,raw] of Object.entries(extracted)){if(!key.trim()||key.length>160)throw new Error('OCR_PROVIDER_FIELD_KEY_INVALID');const f=obj(raw),fc=Number(f.confidence),pageNumber=Number(f.pageNumber);if(!Number.isFinite(fc)||fc<0||fc>1||!Number.isSafeInteger(pageNumber)||pageNumber<1||!(f.value==null||typeof f.value==='string'))throw new Error('OCR_PROVIDER_FIELD_INVALID')}return validateResult({text,pages,extracted,classification:r.classification==null?null:txt(r.classification,240),confidence,runId:r.runId==null?null:txt(r.runId,320)})}
const spans=(v:unknown)=>arr(v).map(s=>obj(s)).map(s=>({offset:Number(s.offset),length:Number(s.length)})).filter(s=>Number.isSafeInteger(s.offset)&&s.offset>=0&&Number.isSafeInteger(s.length)&&s.length>=0);
const pageForOffset=(pages:J[],offset:number)=>{for(const p of pages){const n=Number(p.pageNumber),ps=spans(p.spans);if(Number.isSafeInteger(n)&&n>0&&ps.some(s=>offset>=s.offset&&offset<s.offset+s.length))return n}return Number(pages[0]?.pageNumber)||1};
function azureProviderResult(v:unknown,runId:string|null):ProviderResult{const root=obj(v),a=obj(root.analyzeResult),content=typeof a.content==='string'?a.content:'';if(content.length>MAX_PROVIDER_TEXT)throw new Error('OCR_PROVIDER_TEXT_INVALID');const rawPages=arr(a.pages).map(p=>obj(p));if(!rawPages.length)throw new Error('OCR_PROVIDER_PAGES_INVALID');const pages=rawPages.map(p=>{const pageNumber=Number(p.pageNumber);if(!Number.isSafeInteger(pageNumber)||pageNumber<1)throw new Error('OCR_PROVIDER_PAGE_INVALID');const lines=arr(p.lines).map(x=>obj(x)).map(x=>typeof x.content==='string'?x.content:'').filter(Boolean),words=arr(p.words).map(x=>obj(x)),confidences=words.map(w=>Number(w.confidence)).filter(n=>Number.isFinite(n)&&n>=0&&n<=1),confidence=confidences.length?confidences.reduce((s,n)=>s+n,0)/confidences.length:0;return{pageNumber,text:lines.join('\n'),confidence,fields:[] as ProviderField[]}});const pageMap=new Map(pages.map(p=>[p.pageNumber,p])),extracted:J={},used=new Map<string,number>();for(const raw of arr(a.keyValuePairs)){const pair=obj(raw),keyObj=pair.key&&typeof pair.key==='object'&&!Array.isArray(pair.key)?obj(pair.key):null,valueObj=pair.value&&typeof pair.value==='object'&&!Array.isArray(pair.value)?obj(pair.value):null,keyContent=keyObj&&typeof keyObj.content==='string'?keyObj.content.trim().replace(/\s+/g,' '):'',value=valueObj&&typeof valueObj.content==='string'?valueObj.content.trim():null;if(!keyContent)continue;const n=(used.get(keyContent)||0)+1;used.set(keyContent,n);const suffix=n>1?` #${n}`:'',key=`${keyContent.slice(0,Math.max(1,160-suffix.length))}${suffix}`,pairSpans=[...spans(valueObj?.spans),...spans(keyObj?.spans)],pageNumber=pairSpans.length?pageForOffset(rawPages,pairSpans[0]!.offset):pages[0]!.pageNumber,confidence=boundedConfidence(pair.confidence,0),sourceText=[keyContent,value].filter(Boolean).join(': ').slice(0,20_000)||null,field={key,value,confidence,pageNumber,sourceText,corrected:false as const};extracted[key]={value,confidence,pageNumber};pageMap.get(pageNumber)?.fields.push(field)}const pageConf=pages.map(p=>p.confidence),confidence=pageConf.length?pageConf.reduce((s,n)=>s+n,0)/pageConf.length:0;return validateResult({text:content||pages.map(p=>p.text).join('\n\n'),pages,extracted,classification:'azure-prebuilt-layout',confidence,runId})}
async function timedFetch(input:RequestInfo|URL,init:RequestInit={},ms=30_000){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),ms);try{return await fetch(input,{...init,signal:controller.signal})}finally{clearTimeout(timer)}}
async function runGeneric(admin:ReturnType<typeof createClient>,c:ExtractionClaim,p:Extract<Provider,{kind:'generic'}>){const downloaded=await admin.storage.from(c.bucket).download(c.path);if(downloaded.error||!downloaded.data)throw downloaded.error??new Error('SOURCE_DOWNLOAD_FAILED');if(downloaded.data.size!==c.byteSize)throw new Error('SOURCE_SIZE_DRIFT');const form=new FormData();form.append('file',downloaded.data,c.fileName);form.append('metadata',JSON.stringify({schema:'enjaz.ocr-request.v1',analysisId:c.analysisId,documentId:c.documentId,documentVersionId:c.documentVersionId,sourceVersionNumber:c.sourceVersionNumber,sourceChecksum:c.sourceChecksum,mimeType:c.mimeType,sourceAuthority:c.sourceAuthority,locale:'ar-IQ'}));const response=await timedFetch(p.url,{method:'POST',headers:{Authorization:`Bearer ${p.key}`,'X-Enjaz-OCR-Contract':'enjaz.ocr-provider.v1'},body:form},90_000);if(!response.ok)throw new Error(`OCR_PROVIDER_HTTP_${response.status}`);return genericProviderResult(await response.json())}
async function runAzure(admin:ReturnType<typeof createClient>,c:ExtractionClaim,p:Extract<Provider,{kind:'azure'}>){
  const info=await admin.storage.from(c.bucket).info(c.path);if(info.error||!info.data)throw info.error??new Error('SOURCE_INFO_FAILED');
  const metadata=info.data&&typeof info.data==='object'?'metadata' in info.data?(info.data as J).metadata:null:null,size=metadata&&typeof metadata==='object'?Number((metadata as J).size):Number((info.data as J).size);if(Number.isFinite(size)&&size!==c.byteSize)throw new Error('SOURCE_SIZE_DRIFT');
  const downloaded=await admin.storage.from(c.bucket).download(c.path);if(downloaded.error||!downloaded.data)throw downloaded.error??new Error('SOURCE_DOWNLOAD_FAILED');if(downloaded.data.size!==c.byteSize)throw new Error('SOURCE_SIZE_DRIFT');
  const endpointUrl=new URL(p.endpoint),endpoint=`${p.endpoint}/documentintelligence/documentModels/prebuilt-layout:analyze?api-version=2024-11-30&features=keyValuePairs`;
  const created=await timedFetch(endpoint,{method:'POST',headers:{'Ocp-Apim-Subscription-Key':p.key,'Content-Type':c.mimeType},body:downloaded.data},30_000);if(created.status!==202){const detail=(await created.text().catch(()=>'' )).slice(0,800);throw new Error(`OCR_AZURE_ANALYZE_HTTP_${created.status}${detail?`:${detail}`:''}`)}
  const operationValue=created.headers.get('operation-location');if(!operationValue)throw new Error('OCR_AZURE_OPERATION_LOCATION_MISSING');const operationUrl=new URL(operationValue);if(operationUrl.protocol!=='https:'||operationUrl.origin!==endpointUrl.origin)throw new Error('OCR_AZURE_OPERATION_ORIGIN_INVALID');const operation=operationUrl.toString(),runId=operationUrl.pathname.split('/').filter(Boolean).pop()?.slice(0,320)||null;
  for(let i=0;i<100;i++){await new Promise(r=>setTimeout(r,750));const polled=await timedFetch(operation,{headers:{'Ocp-Apim-Subscription-Key':p.key}},15_000);if(!polled.ok){const detail=(await polled.text().catch(()=>'' )).slice(0,800);throw new Error(`OCR_AZURE_POLL_HTTP_${polled.status}${detail?`:${detail}`:''}`)}const body=await polled.json(),status=typeof body?.status==='string'?body.status.toLowerCase():'';if(status==='succeeded')return azureProviderResult(body,runId);if(status==='failed'||status==='canceled'||status==='cancelled'){const detail=body?.error?JSON.stringify(body.error).slice(0,800):'';throw new Error(`OCR_AZURE_${status.toUpperCase()}${detail?`:${detail}`:''}`)}if(status!=='running'&&status!=='notstarted')throw new Error('OCR_AZURE_STATUS_INVALID')}
  throw new Error('OCR_AZURE_TIMEOUT')
}
async function runProvider(admin:ReturnType<typeof createClient>,c:ExtractionClaim,p:Provider){return p.kind==='azure'?runAzure(admin,c,p):runGeneric(admin,c,p)}
async function fail(admin:ReturnType<typeof createClient>,analysisId:string,code:string,message?:string){await admin.rpc('fail_document_extraction_v1',{p_analysis_id:analysisId,p_failure_code:code,p_failure_message:message?.slice(0,1000)??null})}

Deno.serve(async req=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return out(405,{ok:false,error:'METHOD_NOT_ALLOWED'});
  let stage='input',analysisId:string|null=null;let admin:ReturnType<typeof createClient>|null=null;
  try{
    const len=Number(req.headers.get('content-length')||'0');if(Number.isFinite(len)&&len>MAX_BODY)return out(413,{ok:false,error:'REQUEST_TOO_LARGE'});
    const auth=req.headers.get('authorization')||'';if(!/^Bearer\s+\S+$/i.test(auth))return out(401,{ok:false,error:'AUTH_REQUIRED'});
    const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SERVER_URL_UNAVAILABLE');
    const userClient=createClient(url,publicKey(),{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),who=await userClient.auth.getUser();if(who.error||!who.data.user)return out(401,{ok:false,error:'AUTH_INVALID'});
    admin=createClient(url,secret(),{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
    const body=await req.json() as J,action=txt(body.action,32);if(action!=='extract')return out(400,{ok:false,error:'UNKNOWN_ACTION'});
    const workspaceId=uid(body.workspaceId),documentId=uid(body.documentId),requestId=uid(body.requestId),versionNumber=body.versionNumber==null?null:Number(body.versionNumber);if(versionNumber!==null&&(!Number.isSafeInteger(versionNumber)||versionNumber<1))return out(400,{ok:false,error:'INVALID_VERSION'});
    stage='request';const requested=await userClient.rpc('request_document_extraction_v1',{p_workspace_id:workspaceId,p_request_id:requestId,p_document_id:documentId,p_version_number:versionNumber});if(requested.error)throw requested.error;const safe=obj(requested.data);analysisId=uid(safe.analysisId);const existingState=typeof safe.state==='string'?safe.state:'';if(!['queued','extracting'].includes(existingState))return out(200,{ok:true,analysisId,state:existingState,wasDuplicate:true});
    stage='provider_config';const provider=providerConfig();
    stage='claim';const got=await admin.rpc('get_document_extraction_claim_v1',{p_analysis_id:analysisId});if(got.error)throw got.error;const c=claim(got.data);
    stage='start';const started=await admin.rpc('mark_document_extraction_started_v1',{p_analysis_id:analysisId,p_provider:provider.name,p_provider_run_id:null});if(started.error)throw started.error;
    stage='provider';const result=await runProvider(admin,c,provider);
    stage='complete';const completed=await admin.rpc('complete_document_extraction_v1',{p_analysis_id:analysisId,p_ocr_text:result.text,p_extracted_fields:result.extracted,p_page_results:result.pages,p_classification:result.classification,p_confidence:result.confidence,p_provider:provider.name,p_provider_run_id:result.runId});if(completed.error)throw completed.error;
    const state=completed.data?.state==='superseded'?'superseded':'review_required';return out(200,{ok:true,analysisId,state,sourceAuthoritative:true,provider:provider.name})
  }catch(e){
    const message=e instanceof Error?e.message:'UNKNOWN';if(admin&&analysisId){const code=message==='OCR_PROVIDER_NOT_CONFIGURED'?'OCR_PROVIDER_NOT_CONFIGURED':message.startsWith('SOURCE_')?'OCR_SOURCE_FAILED':'OCR_PROVIDER_FAILED';try{await fail(admin,analysisId,code,message)}catch{}}
    if(['INVALID_INPUT','INVALID_UUID','INVALID_OBJECT','INVALID_VERSION'].includes(message))return out(400,{ok:false,error:message});if(message==='OCR_PROVIDER_NOT_CONFIGURED')return out(503,{ok:false,error:'OCR_PROVIDER_NOT_CONFIGURED'});
    console.error('enjaz-document-intelligence failed',{stage,kind:e instanceof Error?e.name:'unknown'});return out(500,{ok:false,error:`DOCUMENT_INTELLIGENCE_${stage.toUpperCase()}_FAILED`})
  }
});
