import {createClient} from 'npm:@supabase/supabase-js@2.114.0';

type J=Record<string,unknown>;type ExtractionClaim={analysisId:string;workspaceId:string;documentId:string;documentVersionId:string;sourceVersionNumber:number;sourceChecksum:string|null;bucket:string;path:string;mimeType:string;byteSize:number;fileName:string;sourceAuthority:string};
const MAX_BODY=16_384,MAX_PROVIDER_TEXT=8_000_000,MAX_PROVIDER_JSON=12_000_000,cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,content-type,x-client-info,apikey','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const out=(s:number,b:J)=>new Response(JSON.stringify(b),{status:s,headers:cors}),txt=(v:unknown,n:number)=>{if(typeof v!=='string'||!v.trim()||v.length>n)throw new Error('INVALID_INPUT');return v.trim()},uid=(v:unknown)=>{const s=txt(v,64);if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s))throw new Error('INVALID_UUID');return s},obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as J:(()=>{throw new Error('INVALID_OBJECT')})();
function secret(){const modern=Deno.env.get('SUPABASE_SECRET_KEYS');if(modern)try{const p=JSON.parse(modern) as Record<string,string>;if(p.default)return p.default}catch{}const legacy=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(legacy)return legacy;throw new Error('SERVER_SECRET_UNAVAILABLE')}
function publicKey(){const k=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY');if(k)return k;throw new Error('SERVER_PUBLIC_KEY_UNAVAILABLE')}
const providerUrl=()=>{const v=Deno.env.get('ENJAZ_OCR_PROVIDER_URL');if(!v||!/^https:\/\//i.test(v))throw new Error('OCR_PROVIDER_NOT_CONFIGURED');return v},providerKey=()=>{const v=Deno.env.get('ENJAZ_OCR_PROVIDER_KEY');if(!v)throw new Error('OCR_PROVIDER_NOT_CONFIGURED');return v},providerName=()=>Deno.env.get('ENJAZ_OCR_PROVIDER_NAME')?.trim().slice(0,240)||'external-ocr';
function claim(v:unknown):ExtractionClaim{const r=obj(v),c={analysisId:uid(r.analysisId),workspaceId:uid(r.workspaceId),documentId:uid(r.documentId),documentVersionId:uid(r.documentVersionId),sourceVersionNumber:Number(r.sourceVersionNumber),sourceChecksum:r.sourceChecksum==null?null:txt(r.sourceChecksum,64).toLowerCase(),bucket:txt(r.bucket,80),path:txt(r.path,1200),mimeType:txt(r.mimeType,160).toLowerCase(),byteSize:Number(r.byteSize),fileName:txt(r.fileName,240),sourceAuthority:txt(r.sourceAuthority,80)};if(c.bucket!=='enjaz-documents-private'||c.sourceAuthority!=='SOURCE_FILE_REMAINS_AUTHORITATIVE'||!Number.isSafeInteger(c.sourceVersionNumber)||c.sourceVersionNumber<1||!Number.isSafeInteger(c.byteSize)||c.byteSize<1||c.byteSize>52_428_800)throw new Error('INVALID_EXTRACTION_CLAIM');return c}
function providerResult(v:unknown){const r=obj(v);if(r.schema!=='enjaz.ocr-provider.v1')throw new Error('OCR_PROVIDER_SCHEMA_INVALID');const text=typeof r.text==='string'&&r.text.length<=MAX_PROVIDER_TEXT?r.text:(()=>{throw new Error('OCR_PROVIDER_TEXT_INVALID')})(),confidence=Number(r.confidence);if(!Number.isFinite(confidence)||confidence<0||confidence>1)throw new Error('OCR_PROVIDER_CONFIDENCE_INVALID');if(!Array.isArray(r.pages)||!r.pages.length)throw new Error('OCR_PROVIDER_PAGES_INVALID');const seen=new Set<number>(),pages=r.pages.map(raw=>{const p=obj(raw),pageNumber=Number(p.pageNumber),pc=Number(p.confidence);if(!Number.isSafeInteger(pageNumber)||pageNumber<1||seen.has(pageNumber)||!Number.isFinite(pc)||pc<0||pc>1||typeof p.text!=='string')throw new Error('OCR_PROVIDER_PAGE_INVALID');seen.add(pageNumber);const fields=Array.isArray(p.fields)?p.fields.map(rawField=>{const f=obj(rawField),key=txt(f.key,160),fc=Number(f.confidence),fp=Number(f.pageNumber);if(!Number.isFinite(fc)||fc<0||fc>1||!Number.isSafeInteger(fp)||fp!==pageNumber||!(f.value==null||typeof f.value==='string')||!(f.sourceText==null||typeof f.sourceText==='string'))throw new Error('OCR_PROVIDER_FIELD_INVALID');return{key,value:f.value??null,confidence:fc,pageNumber:fp,sourceText:f.sourceText??null,corrected:false}}):[];return{pageNumber,text:p.text,confidence:pc,fields}});const extracted=obj(r.fields??{});for(const [key,raw] of Object.entries(extracted)){if(!key.trim()||key.length>160)throw new Error('OCR_PROVIDER_FIELD_KEY_INVALID');const f=obj(raw),fc=Number(f.confidence),pageNumber=Number(f.pageNumber);if(!Number.isFinite(fc)||fc<0||fc>1||!Number.isSafeInteger(pageNumber)||pageNumber<1||!(f.value==null||typeof f.value==='string'))throw new Error('OCR_PROVIDER_FIELD_INVALID')};const encoded=JSON.stringify({pages,extracted});if(encoded.length>MAX_PROVIDER_JSON)throw new Error('OCR_PROVIDER_RESULT_TOO_LARGE');return{text,pages,extracted,classification:r.classification==null?null:txt(r.classification,240),confidence,runId:r.runId==null?null:txt(r.runId,320)}}
async function fail(admin:ReturnType<typeof createClient>,analysisId:string,code:string,message?:string){await admin.rpc('fail_document_extraction_v1',{p_analysis_id:analysisId,p_failure_code:code,p_failure_message:message?.slice(0,1000)??null})}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});if(req.method!=='POST')return out(405,{ok:false,error:'METHOD_NOT_ALLOWED'});let stage='input',analysisId:string|null=null;let admin:ReturnType<typeof createClient>|null=null;try{const len=Number(req.headers.get('content-length')||'0');if(Number.isFinite(len)&&len>MAX_BODY)return out(413,{ok:false,error:'REQUEST_TOO_LARGE'});const auth=req.headers.get('authorization')||'';if(!/^Bearer\s+\S+$/i.test(auth))return out(401,{ok:false,error:'AUTH_REQUIRED'});const url=Deno.env.get('SUPABASE_URL');if(!url)throw new Error('SERVER_URL_UNAVAILABLE');const userClient=createClient(url,publicKey(),{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}}),who=await userClient.auth.getUser();if(who.error||!who.data.user)return out(401,{ok:false,error:'AUTH_INVALID'});admin=createClient(url,secret(),{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});const body=await req.json() as J,action=txt(body.action,32);if(action!=='extract')return out(400,{ok:false,error:'UNKNOWN_ACTION'});
  const workspaceId=uid(body.workspaceId),documentId=uid(body.documentId),requestId=uid(body.requestId),versionNumber=body.versionNumber==null?null:Number(body.versionNumber);if(versionNumber!==null&&(!Number.isSafeInteger(versionNumber)||versionNumber<1))return out(400,{ok:false,error:'INVALID_VERSION'});
  stage='request';const requested=await userClient.rpc('request_document_extraction_v1',{p_workspace_id:workspaceId,p_request_id:requestId,p_document_id:documentId,p_version_number:versionNumber});if(requested.error)throw requested.error;const safe=obj(requested.data);analysisId=uid(safe.analysisId);const existingState=typeof safe.state==='string'?safe.state:'';if(!['queued','extracting'].includes(existingState))return out(200,{ok:true,analysisId,state:existingState,wasDuplicate:true});
  stage='provider_config';const pUrl=providerUrl(),pKey=providerKey(),pName=providerName();
  stage='claim';const got=await admin.rpc('get_document_extraction_claim_v1',{p_analysis_id:analysisId});if(got.error)throw got.error;const c=claim(got.data);
  stage='start';const started=await admin.rpc('mark_document_extraction_started_v1',{p_analysis_id:analysisId,p_provider:pName,p_provider_run_id:null});if(started.error)throw started.error;
  stage='source_download';const downloaded=await admin.storage.from(c.bucket).download(c.path);if(downloaded.error||!downloaded.data)throw downloaded.error??new Error('SOURCE_DOWNLOAD_FAILED');if(downloaded.data.size!==c.byteSize)throw new Error('SOURCE_SIZE_DRIFT');
  stage='provider';const form=new FormData();form.append('file',downloaded.data,c.fileName);form.append('metadata',JSON.stringify({schema:'enjaz.ocr-request.v1',analysisId:c.analysisId,documentId:c.documentId,documentVersionId:c.documentVersionId,sourceVersionNumber:c.sourceVersionNumber,sourceChecksum:c.sourceChecksum,mimeType:c.mimeType,sourceAuthority:c.sourceAuthority,locale:'ar-IQ'}));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90_000);let response:Response;try{response=await fetch(pUrl,{method:'POST',headers:{Authorization:`Bearer ${pKey}`,'X-Enjaz-OCR-Contract':'enjaz.ocr-provider.v1'},body:form,signal:controller.signal})}finally{clearTimeout(timer)}if(!response.ok)throw new Error(`OCR_PROVIDER_HTTP_${response.status}`);const result=providerResult(await response.json());
  stage='complete';const completed=await admin.rpc('complete_document_extraction_v1',{p_analysis_id:analysisId,p_ocr_text:result.text,p_extracted_fields:result.extracted,p_page_results:result.pages,p_classification:result.classification,p_confidence:result.confidence,p_provider:pName,p_provider_run_id:result.runId});if(completed.error)throw completed.error;return out(200,{ok:true,analysisId,state:'review_required',sourceAuthoritative:true,provider:pName})
}catch(e){const message=e instanceof Error?e.message:'UNKNOWN';if(admin&&analysisId){const code=message==='OCR_PROVIDER_NOT_CONFIGURED'?'OCR_PROVIDER_NOT_CONFIGURED':stage==='provider'?'OCR_PROVIDER_FAILED':stage==='source_download'?'OCR_SOURCE_DOWNLOAD_FAILED':'OCR_PIPELINE_FAILED';try{await fail(admin,analysisId,code,message)}catch{}}
  if(['INVALID_INPUT','INVALID_UUID','INVALID_OBJECT','INVALID_VERSION'].includes(message))return out(400,{ok:false,error:message});if(message==='OCR_PROVIDER_NOT_CONFIGURED')return out(503,{ok:false,error:'OCR_PROVIDER_NOT_CONFIGURED'});console.error('enjaz-document-intelligence failed',{stage,kind:e instanceof Error?e.name:'unknown'});return out(500,{ok:false,error:`DOCUMENT_INTELLIGENCE_${stage.toUpperCase()}_FAILED`})}});
