import { useCallback,useEffect,useMemo,useState } from 'react';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import { useAutomationCommandGateway } from '../../features/automation/AutomationCommandContext.tsx';
import { createCommandCenterOrchestrator,type CommandCenterSnapshot,type CommandWorkflowDecision } from '../../features/command/commandCenter.ts';
import { useFieldOperationsCommandGateway } from '../../features/field-operations/FieldOperationsCommandContext.tsx';
import { useFinanceCommandGateway } from '../../features/finance/FinanceCommandContext.tsx';
import { useGovernmentProcedureCommandGateway } from '../../features/workflow/GovernmentProcedureCommandContext.tsx';
import { useCurrentUserId } from '../../shared/session/CurrentUserIdContext.tsx';
import type { R2DestinationId } from '../architecture/navigation-contract.ts';

type Props=Readonly<{navigate:(id:R2DestinationId)=>void}>;
type Form=Readonly<Record<string,string>>;
const FAIL='تعذر تأكيد الحالة من جميع السلطات الموثوقة. لم يعرض مركز القيادة صورة جزئية قد تكون مضللة.';
const OK='تم تأكيد القرار من السلطة المالكة وإعادة مزامنة مركز القيادة.';

export function LiveCommandCenterExperience({navigate}:Props){
  const userId=useCurrentUserId(),dataFactory=useDataLayerFactory(),finance=useFinanceCommandGateway(),workflow=useGovernmentProcedureCommandGateway(),automation=useAutomationCommandGateway(),field=useFieldOperationsCommandGateway();
  const orchestrator=useMemo(()=>createCommandCenterOrchestrator({dataFactory,finance,workflow,automation,field}),[dataFactory,finance,workflow,automation,field]);
  const [snapshot,setSnapshot]=useState<CommandCenterSnapshot|null|undefined>(),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState<string|null>(null),[form,setForm]=useState<Form>({});
  const put=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  const reload=useCallback(async()=>{if(!userId)throw new Error('AUTH_USER_REQUIRED');setSnapshot(await orchestrator.load(userId));},[orchestrator,userId]);
  useEffect(()=>{void reload().catch(()=>{setSnapshot(null);setMessage(FAIL)})},[reload]);
  const run=async(key:string,operation:(current:CommandCenterSnapshot)=>Promise<unknown>)=>{if(!snapshot||busy)return;setBusy(key);setMessage(null);try{await operation(snapshot);await reload();setMessage(OK)}catch{setMessage('تعذر تأكيد القرار؛ لم يُفترض نجاحه.');try{await reload()}catch{setSnapshot(null)}}finally{setBusy(null)}};
  const decideApproval=(id:string,decision:'approved'|'rejected')=>void run(`a:${id}`,s=>orchestrator.decideAutomationApproval({workspaceId:s.workspaceId,approvalId:id,decision,note:form[`a:${id}`]?.trim()||null,decisionKey:crypto.randomUUID()}));
  const transitionWorkflow=(d:CommandWorkflowDecision,key:string)=>{const t=d.allowedTransitions.find(x=>x.key===key),reason=form[`w:${d.instanceId}:${key}`]?.trim()||null;if(!t)return;if(t.requiresReason&&!reason){setMessage('هذا الانتقال يتطلب سببًا موثقًا قبل التنفيذ.');return}void run(`w:${d.instanceId}:${key}`,s=>orchestrator.transitionWorkflow({workspaceId:s.workspaceId,instanceId:d.instanceId,transitionKey:key,expectedStagePosition:d.currentStagePosition,reason,idempotencyKey:crypto.randomUUID()}))};
  const reassignField=(id:string,version:number)=>{const member=form[`m:${id}`],reason=form[`r:${id}`]?.trim();if(!member||!reason||reason.length<3){setMessage('إعادة الإسناد تحتاج مالكًا جديدًا وسببًا موثقًا.');return}void run(`f:${id}`,s=>orchestrator.reassignField({workspaceId:s.workspaceId,assignmentId:id,expectedVersion:version,assignedUserId:member,reason,clientOperationId:crypto.randomUUID()}))};

  if(snapshot===undefined)return <div className="r2-screen r2-command-live" data-command-stage="8.6" data-command-authority="delegated_existing_domain_gateways_only" data-command-write-authority="none" data-finance-write-authority="none"><header className="r2-command-hero"><div><p className="r2-eyebrow">Phase 8.6 · Global Command Center</p><h1>مركز القيادة</h1></div></header><section className="r2-command-state">جارٍ تكوين صورة القيادة من السلطات الموثوقة…</section></div>;
  if(snapshot===null)return <div className="r2-screen r2-command-live" data-command-stage="8.6" data-command-authority="delegated_existing_domain_gateways_only" data-command-write-authority="none" data-finance-write-authority="none"><header className="r2-command-hero"><div><p className="r2-eyebrow">Phase 8.6 · Global Command Center</p><h1>مركز القيادة</h1></div></header><section className="r2-command-state r2-command-state--error"><strong>لم يتم فتح صورة قيادة جزئية.</strong><p>{FAIL}</p><button className="r2-action r2-action--secondary" onClick={()=>void reload().catch(()=>setMessage(FAIL))}>إعادة المحاولة</button></section></div>;

  const signal=snapshot.home.criticalBlockers+snapshot.home.overdueFollowups+snapshot.automation.pendingApprovals.length+snapshot.finance.reconciliation.integrityWarnings+snapshot.field.metrics.highCriticalBlockers;
  const assignments=snapshot.field.assignments.filter(x=>x.status==='queued'||x.status==='in_progress').slice(0,4);
  const metrics:[string,number,string][]=[['إشارات قرار',signal,'عوائق + تأخير + موافقات + نزاهة'],['العمل النشط',snapshot.home.activeTransactions,`${snapshot.home.stalledTransactions} متلكئة`],['الميدان',snapshot.field.metrics.queuedAssignments+snapshot.field.metrics.activeVisits,`${snapshot.field.metrics.queuedAssignments} إسناد`],['نزاهة المالية',snapshot.finance.reconciliation.integrityWarnings,'قراءة فقط']];
  return <div className="r2-screen r2-command-live" data-command-stage="8.6" data-command-authority="delegated_existing_domain_gateways_only" data-command-write-authority="none" data-finance-write-authority="none">
    <header className="r2-command-hero"><div><p className="r2-eyebrow">Phase 8.6 · Global Command Center</p><h1>مركز القيادة</h1><p className="r2-supporting">قرارات عابرة للمجالات عبر السلطات الأصلية فقط؛ لا كتابة مباشرة ولا سلطة مالية جديدة.</p></div><div className="r2-command-hero__status"><span>Live · Delegated Authority</span><small>صورة موحّدة أو فشل مغلق</small></div></header>
    {message&&<div className="r2-command-alert" role="status">{message}</div>}
    <section className="r2-command-overview" aria-label="نبض القيادة">{metrics.map(([label,value,note],i)=><article className={`r2-command-metric${i===0?' r2-command-metric--focus':''}`} key={label}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>)}</section>
    <section className="r2-command-grid"><article className="r2-command-panel r2-command-panel--decisions"><div className="r2-command-panel__head"><div><p className="r2-eyebrow">Decision Queue</p><h2>قرارات العمل ذات الأولوية</h2></div><button className="r2-command-link" onClick={()=>navigate('transactions')}>المعاملات</button></div>{snapshot.workflowDecisions.length===0?<p className="r2-command-empty">لا توجد قرارات سير عمل ذات أولوية الآن.</p>:<div className="r2-command-stack">{snapshot.workflowDecisions.map(d=><section className="r2-command-decision" data-priority={d.level} key={d.instanceId}><div className="r2-command-decision__copy"><span className="r2-command-badge">{d.level==='critical'?'حرج':d.level==='high'?'مرتفع':'متوسط'}</span><div><strong>{d.title}</strong><small>{d.companyLabel??'شركة غير متاحة'} · المرحلة {d.currentStagePosition}</small></div></div>{d.allowedTransitions.length===0?<p className="r2-command-empty">لا يوجد انتقال مسموح به من الحالة الحالية.</p>:<div className="r2-command-transition-list">{d.allowedTransitions.map(t=>{const k=`w:${d.instanceId}:${t.key}`;return <div className="r2-command-transition" key={t.key}><div><strong>{t.label}</strong><small>{t.requiresReason?'يتطلب سببًا موثقًا':'انتقال مسموح'}</small></div><input aria-label={`سبب ${t.label} — ${d.title}`} value={form[k]??''} onChange={e=>put(k,e.target.value)} placeholder={t.requiresReason?'السبب مطلوب…':'سبب اختياري…'}/><button className="r2-action r2-action--primary" disabled={!!busy} onClick={()=>transitionWorkflow(d,t.key)}>{busy===k?'جارٍ التأكيد…':t.label}</button></div>})}</div>}</section>)}</div>}</article>
      <article className="r2-command-panel r2-command-panel--automation"><div className="r2-command-panel__head"><div><p className="r2-eyebrow">Human Approval</p><h2>موافقات الأتمتة</h2></div><button className="r2-command-link" onClick={()=>navigate('automation')}>الأتمتة</button></div>{snapshot.automation.pendingApprovals.length===0?<p className="r2-command-empty">لا توجد موافقات أتمتة معلقة.</p>:<div className="r2-command-stack">{snapshot.automation.pendingApprovals.map(a=><section className="r2-command-approval" key={a.id}><div><strong>{a.actionSnapshot.type==='workflow_transition'?'انتقال سير عمل حساس':'إجراء أتمتة يحتاج قرارًا'}</strong><small>يبقى التنفيذ خلف الموافقة البشرية</small></div><input aria-label={`ملاحظة قرار الأتمتة ${a.id}`} value={form[`a:${a.id}`]??''} onChange={e=>put(`a:${a.id}`,e.target.value)} placeholder="ملاحظة اختيارية"/><div className="r2-command-actions"><button className="r2-action r2-action--primary" disabled={!!busy} onClick={()=>decideApproval(a.id,'approved')}>موافقة</button><button className="r2-action r2-action--secondary" disabled={!!busy} onClick={()=>decideApproval(a.id,'rejected')}>رفض</button></div></section>)}</div>}</article></section>
    <section className="r2-command-grid r2-command-grid--lower"><article className="r2-command-panel r2-command-panel--field"><div className="r2-command-panel__head"><div><p className="r2-eyebrow">Operational Ownership</p><h2>إعادة إسناد العمل الميداني</h2></div><button className="r2-command-link" onClick={()=>navigate('operations')}>العمليات</button></div>{assignments.length===0?<p className="r2-command-empty">لا توجد إسنادات قابلة لإعادة التوجيه.</p>:<div className="r2-command-stack">{assignments.map(a=><section className="r2-command-field-row" key={a.id}><div><strong>{a.companyName}</strong><small>{a.destinationLabel} · المالك الحالي {a.assignedUserName}</small></div><label><span>المالك الجديد</span><select value={form[`m:${a.id}`]??''} onChange={e=>put(`m:${a.id}`,e.target.value)}><option value="">اختر عضوًا…</option>{snapshot.field.members.filter(m=>m.userId!==a.assignedUserId).map(m=><option key={m.userId} value={m.userId}>{m.displayName}</option>)}</select></label><label><span>سبب إعادة الإسناد</span><input value={form[`r:${a.id}`]??''} onChange={e=>put(`r:${a.id}`,e.target.value)} placeholder="سبب موثق…"/></label><button className="r2-action r2-action--secondary" disabled={!!busy} onClick={()=>reassignField(a.id,a.version)}>إعادة الإسناد</button></section>)}</div>}</article>
      <article className="r2-command-panel r2-command-panel--integrity"><div className="r2-command-panel__head"><div><p className="r2-eyebrow">Authority Boundaries</p><h2>حدود السلطة والنزاهة</h2></div><button className="r2-command-link" onClick={()=>navigate('finance')}>المالية</button></div><dl className="r2-command-integrity"><div><dt>Command write authority</dt><dd>none</dd></div><div><dt>Finance write authority</dt><dd>none</dd></div><div><dt>Reconciliation warnings</dt><dd>{snapshot.finance.reconciliation.integrityWarnings}</dd></div></dl><p className="r2-command-truth">كل كتابة تمر إلى Gateway صاحب السلطة الأصلي مع حراس version/idempotency/approval.</p></article></section>
  </div>;
}
