import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import type { EnjazDataLayerFactory, EnjazWorkspaceDataLayer } from '../../data/createDataLayer.ts';
import type { RowOf } from '../../data/contracts/dataTypes.ts';
import { DataLayerProvider } from '../../data/react/DataLayerContext.tsx';
import { AutomationCommandProvider } from '../../features/automation/AutomationCommandContext.tsx';
import type { AutomationCommandGateway, AutomationEngineContext } from '../../features/automation/automationCommands.ts';
import { FieldOperationsCommandProvider } from '../../features/field-operations/FieldOperationsCommandContext.tsx';
import type { FieldOperationsCommandGateway, FieldOperationsContext } from '../../features/field-operations/fieldOperationsCommands.ts';
import { FinanceCommandProvider } from '../../features/finance/FinanceCommandContext.tsx';
import type { FinanceCommandGateway, FinancePaymentContext } from '../../features/finance/financeCommands.ts';
import { GovernmentProcedureCommandProvider } from '../../features/workflow/GovernmentProcedureCommandContext.tsx';
import type { GovernmentProcedureRuntimeGateway, TransactionWorkflowContext } from '../../features/workflow/governmentProcedureRuntime.ts';
import { CurrentUserIdProvider } from '../../shared/session/CurrentUserIdContext.tsx';
import { LiveCommandCenterExperience } from './LiveCommandCenterExperience.tsx';
import '../runtime/shell-base.css';
import '../runtime/shell.css';
import '../runtime/accessibility-hardening.css';
import './command-center.css';

const W='11111111-1111-4111-8111-111111111111',U='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333',T='44444444-4444-4444-8444-444444444444',B='55555555-5555-4555-8555-555555555555',ASSIGN='66666666-6666-4666-8666-666666666666',M1='77777777-7777-4777-8777-777777777777',M2='88888888-8888-4888-8888-888888888888',APPROVAL='99999999-9999-4999-8999-999999999999',INSTANCE='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
let stage=2,approvalOpen=true,assignedUserId=M1,assignedUserName='سارة علي',assignmentVersion=2;

const transaction:RowOf<'transactions'>={id:T,workspace_id:W,company_id:C,primary_contact_id:null,type:'تسجيل شركة',department:'الشركات',status:'stalled',priority:'urgent',current_fee:1500000,created_at:'2026-09-01T08:00:00.000Z',updated_at:'2026-09-09T08:00:00.000Z',last_activity_at:'2026-09-09T08:00:00.000Z',completed_at:null,archived_at:null,deleted_at:null,deleted_by:null,deletion_reason:null,legacy_id:null,legacy_source:null};
const blocker:RowOf<'transaction_blockers'>={id:B,workspace_id:W,transaction_id:T,title:'توقف يتطلب قرار الإدارة',severity:'critical',note:'لم تتحرك المعاملة بعد استيفاء المتطلبات.',status:'open',opened_at:'2026-09-09T08:00:00.000Z',resolved_at:null};
const company={id:C,workspace_id:W,legal_name:'شركة الرافدين للتجارة العامة',display_name:'شركة الرافدين',capital:null,address:'بغداد',activities:null,registration_number:null,legal_status:null,primary_contact_id:null,status:'active',merged_into_id:null,legacy_id:null,legacy_source:null,created_at:'2026-09-01T08:00:00.000Z',updated_at:'2026-09-09T08:00:00.000Z',archived_at:null,deleted_at:null,deleted_by:null,deletion_reason:null} as RowOf<'companies'>;
const page=<T,>(items:readonly T[])=>Promise.resolve({items,hasMore:false,total:items.length});
const dataFactory:EnjazDataLayerFactory={async resolveWorkspaceId(){return W},forWorkspace(){return {transactions:{list:()=>page([transaction])},followups:{list:()=>page([])},blockers:{list:()=>page([blocker])},payments:{list:()=>page([])},companies:{getById:async()=>company}} as unknown as EnjazWorkspaceDataLayer}};

const financeContext=():FinancePaymentContext=>({cashboxes:Object.freeze([]),engagements:Object.freeze([]),recentReceipts:Object.freeze([]),reconciliation:{postedTotalCents:40000000n,reversedTotalCents:0n,statusWithoutReversal:0,reversalWithoutStatus:0,shadowLedgerEntries:0,integrityWarnings:1,moneyAuthority:'payments_plus_non_payment_ledger'}});
const finance:FinanceCommandGateway={loadContext:async()=>financeContext(),postPayment:async()=>{throw new Error('finance writes forbidden in command preview')},reversePayment:async()=>{throw new Error('finance writes forbidden in command preview')},getReceipt:async()=>{throw new Error('not used')},createCashbox:async()=>{throw new Error('finance writes forbidden in command preview')},createEngagement:async()=>{throw new Error('finance writes forbidden in command preview')}};

const automationContext=():AutomationEngineContext=>({authority:'automation_rules_and_runs',workflowWriteAuthority:'existing_workflow_rpc_only_after_human_approval',financeWriteAuthority:'none',rules:Object.freeze([]),recentRuns:Object.freeze([]),pendingApprovals:Object.freeze(approvalOpen?[{id:APPROVAL,runId:APPROVAL,ruleId:APPROVAL,requestedAt:'2026-09-09T09:00:00.000Z',actionSnapshot:Object.freeze({type:'workflow_transition'})}]:[])});
const automation:AutomationCommandGateway={loadContext:async()=>automationContext(),upsertRule:async()=>{throw new Error('not used')},setRuleEnabled:async()=>{throw new Error('not used')},dispatch:async()=>{throw new Error('not used')},async decideApproval(_workspaceId,approvalId,decision){if(approvalId!==APPROVAL)throw new Error('approval mismatch');approvalOpen=false;return{approvalId,decision,runId:APPROVAL,runStatus:decision==='approved'?'succeeded':'failed',wasDuplicate:false}}};

const fieldContext=():FieldOperationsContext=>({authority:'field_assignments_visits_evidence_receipts',transactionWriteAuthority:'none',workflowWriteAuthority:'existing_workflow_rpc_only',automationWriteAuthority:'existing_automation_rpc_only',financeWriteAuthority:'none',locationPolicy:'optional',metrics:{activeTransactions:1,stalledTransactions:1,highCriticalBlockers:1,pendingAutomationApprovals:approvalOpen?1:0,queuedAssignments:1,activeVisits:0},members:Object.freeze([{userId:M1,displayName:'سارة علي'},{userId:M2,displayName:'أحمد كريم'}]),assignments:Object.freeze([{id:ASSIGN,transactionId:T,transactionType:'تسجيل شركة',transactionStatus:'stalled',companyName:'شركة الرافدين',assignedUserId,assignedUserName,scheduledFor:'2026-09-09',destinationLabel:'دائرة تسجيل الشركات',department:'الشركات',priority:'urgent',status:'queued',version:assignmentVersion,openBlockers:1,nextRequiredAction:'تصعيد'}]),visits:Object.freeze([])});
const field:FieldOperationsCommandGateway={loadContext:async()=>fieldContext(),setLocationPolicy:async()=>{throw new Error('not used')},upsertAssignment:async()=>{throw new Error('not used')},async reassign(_workspaceId,assignmentId,expectedVersion,nextUserId){if(assignmentId!==ASSIGN||expectedVersion!==assignmentVersion)throw new Error('stale');assignedUserId=nextUserId;assignedUserName=nextUserId===M2?'أحمد كريم':'سارة علي';assignmentVersion+=1;return{wasDuplicate:false}},checkIn:async()=>{throw new Error('not used')},checkOut:async()=>{throw new Error('not used')},addEvidence:async()=>{throw new Error('not used')},handoff:async()=>{throw new Error('not used')}};

const workflowContext=():TransactionWorkflowContext=>({authority:'canonical_workflow_instance',transactionId:T,instance:{instanceId:INSTANCE,procedureId:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',branchId:null,currentStagePosition:stage,status:'active',startedAt:'2026-09-01T08:00:00.000Z',completedAt:null,templateSnapshot:Object.freeze({}),pendingRequiredCount:0,stageStates:Object.freeze([]),itemStates:Object.freeze([]),allowedTransitions:Object.freeze(stage===2?[{key:'advance_review',label:'اعتماد الانتقال',kind:'advance',fromStagePosition:2,toStagePosition:3,requiresReason:true}]:[])}});
const workflow:GovernmentProcedureRuntimeGateway={loadCatalog:async()=>{throw new Error('not used')},startProcedure:async()=>{throw new Error('not used')},async transition(input){if(input.instanceId!==INSTANCE||input.expectedStagePosition!==stage)throw new Error('stale stage');stage+=1;return{instanceId:INSTANCE,transitionEventId:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',transitionKey:input.transitionKey,eventKind:'advance',fromStagePosition:stage-1,toStagePosition:stage,currentStagePosition:stage,status:'active',wasDuplicate:false}},loadTransactionContext:async()=>workflowContext()};

function Preview(){const navigate=(id:string)=>{document.documentElement.dataset.lastCommandNavigation=id};return <DataLayerProvider factory={dataFactory}><FinanceCommandProvider gateway={finance}><GovernmentProcedureCommandProvider gateway={workflow}><AutomationCommandProvider gateway={automation}><FieldOperationsCommandProvider gateway={field}><CurrentUserIdProvider userId={U}><main className="ez-r2-root" data-phase86-preview="true"><LiveCommandCenterExperience navigate={navigate as never}/></main></CurrentUserIdProvider></FieldOperationsCommandProvider></AutomationCommandProvider></GovernmentProcedureCommandProvider></FinanceCommandProvider></DataLayerProvider>}
const node=document.getElementById('phase86-command-root');if(!node)throw new Error('phase86 root missing');createRoot(node).render(<StrictMode><Preview/></StrictMode>);
