import {useEffect,useState} from 'react';
import{useDataLayerFactory}from'../../data/react/DataLayerContext.tsx';
import{buildUnifiedCalendarIcs,loadUnifiedCalendar,shiftUnifiedCalendarAnchor,type UnifiedCalendarAuthority,type UnifiedCalendarItem,type UnifiedCalendarSnapshot,type UnifiedCalendarView}from'../../features/scheduling/unifiedCalendar.ts';
type P=Readonly<{workspace:Promise<string|null>}>;type O=readonly[string,string];
const V:readonly[UnifiedCalendarView,string][]=[['day','يوم'],['week','أسبوع'],['month','شهر'],['agenda','أجندة']],S:readonly[UnifiedCalendarAuthority,string][]=[['all','كل المصادر'],['appointment','المواعيد'],['renewal','التجديدات'],['workflow_deadline','مهل سير العمل']],B='r2-action r2-action--secondary',L:Record<string,string>={appointment:'موعد',renewal:'تجديد',workflow_deadline:'مهلة'};
const uniq=(a:O[])=>[...new Map(a)],short=(s:string)=>`${s.slice(0,8)}…`,time=(x:UnifiedCalendarItem,z:string)=>x.startsAt?new Date(x.startsAt).toLocaleString('ar-IQ',{dateStyle:'medium',timeStyle:'short',timeZone:z}):x.dueDate??'دون وقت';
function save(x:UnifiedCalendarSnapshot){const u=URL.createObjectURL(new Blob([buildUnifiedCalendarIcs(x)],{type:'text/calendar'})),a=document.createElement('a');a.href=u;a.download=`enjaz-calendar-${x.businessStartDate}.ics`;a.click();URL.revokeObjectURL(u)}
function F({n,v,o,s}:{n:string;v:string|null;o:readonly O[];s:(x:string)=>void}){return <label className="r2-core-sort"><span>{n}</span><select value={v??''} onChange={e=>s(e.target.value)}>{o.map(([x,y])=><option key={x} value={x}>{y}</option>)}</select></label>}
function X({t,b,r}:{t:string;b:string;r?:()=>void}){return <section className="r2-core-state" role={r?'alert':'status'}><strong>{t}</strong><p>{b}</p>{r&&<button className={B} type="button" onClick={r}>إعادة المحاولة</button>}</section>}
export function LiveUnifiedCalendarExperience({workspace}:P){
 const f=useDataLayerFactory(),[w,setW]=useState<string|null>(null),[view,setView]=useState<UnifiedCalendarView>('month'),[anchor,setAnchor]=useState<string|null>(null),[authority,setAuthority]=useState<UnifiedCalendarAuthority>('all'),[staff,setStaff]=useState<string|null>(null),[company,setCompany]=useState<string|null>(null),[transaction,setTransaction]=useState<string|null>(null),[data,setData]=useState<UnifiedCalendarSnapshot|null>(null),[error,setError]=useState(false),[tick,setTick]=useState(0),[online,setOnline]=useState(()=>navigator.onLine);
 useEffect(()=>{let x=1;workspace.then(v=>x&&setW(v),()=>x&&setError(true));return()=>{x=0}},[workspace]);
 useEffect(()=>{const x=()=>setOnline(navigator.onLine);addEventListener('online',x);addEventListener('offline',x);return()=>{removeEventListener('online',x);removeEventListener('offline',x)}},[]);
 useEffect(()=>{if(!w)return;let x=1;setData(null);setError(false);loadUnifiedCalendar(f,{workspaceId:w,view,anchorDate:anchor,authority,staffMemberId:staff,companyId:company,transactionId:transaction}).then(v=>{if(x){setData(v);setAnchor(a=>a??v.anchorDate)}}).catch(()=>x&&setError(true));return()=>{x=0}},[f,w,view,anchor,authority,staff,company,transaction,tick]);
 const items=data?.items??[],all:O[]=[['','الكل']],opts=(kind:'company'|'transaction'|'staff')=>uniq(items.flatMap(i=>kind==='company'&&i.companyId?[[i.companyId,i.companyLabel??short(i.companyId)]]:kind==='transaction'&&i.transactionId?[[i.transactionId,short(i.transactionId)]]:kind==='staff'?i.staffMemberIds.map(id=>[id,short(id)]):[])as O[]),reload=()=>setTick(x=>x+1),move=(d:-1|1)=>{const a=anchor??data?.anchorDate;if(a)setAnchor(shiftUnifiedCalendarAnchor(a,view,d))};
 return <main className="r2-screen r2-core-today" data-phase11-5d-unified-calendar="live" data-calendar-view={view}>
  <header className="r2-section-heading r2-section-heading--hero"><div><p className="r2-eyebrow">M10 · 11.5-D</p><h1>التقويم والمواعيد</h1><p className="r2-supporting">المواعيد والتجديدات ومهل سير العمل.</p></div>{data&&<button className={B} type="button" onClick={()=>save(data)}>تصدير ICS</button>}</header>
  {!online&&<section className="r2-core-scope-note" data-calendar-offline="true"><strong>دون اتصال</strong><span>قد تكون القراءة قديمة.</span></section>}
  <section className="r2-core-toolbar" aria-label="أدوات التقويم"><F n="العرض" v={view} o={V} s={x=>setView(x as UnifiedCalendarView)}/><F n="المصدر" v={authority} o={S} s={x=>{setAuthority(x as UnifiedCalendarAuthority);setStaff(null)}}/><F n="الشركة" v={company} o={[...all,...opts('company')]} s={x=>setCompany(x||null)}/><F n="المعاملة" v={transaction} o={[...all,...opts('transaction')]} s={x=>setTransaction(x||null)}/><F n="الموظف" v={staff} o={[...all,...opts('staff')]} s={x=>{setStaff(x||null);if(x)setAuthority('appointment')}}/><button className={B} type="button" onClick={()=>move(-1)}>السابق</button><button className={B} type="button" onClick={()=>setAnchor(data?.businessToday??null)}>اليوم</button><button className={B} type="button" onClick={()=>move(1)}>التالي</button><button className={B} type="button" onClick={reload}>تحديث</button></section>
  {error?<X t="تعذر تحميل التقويم" b="تعذر التحقق من المصدر." r={reload}/>:!data?<X t="جارٍ تجهيز التقويم" b="تتم القراءة من المصادر الحاكمة."/>:<><section className="r2-core-focus" data-calendar-summary="canonical"><div><span>{data.workspaceTimezone}</span><h2>{items.length} عنصرًا</h2><p>{data.businessStartDate} — {data.businessEndDate}</p></div><div className="r2-core-focus__stats">{[['overdue','متأخر'],['due_today','اليوم']].map(([x,y])=><span key={x}><strong>{items.filter(i=>i.attentionState===x).length}</strong> {y}</span>)}<span><strong>{items.filter(i=>i.source==='appointment').length}</strong> موعد</span></div></section><section className="r2-core-scope-note" data-calendar-export-boundary="outbound_projection_only"><strong>تصدير أحادي الاتجاه</strong><span>ICS ليس مصدر حقيقة لإنجاز.</span></section><section className="r2-core-work-list" data-calendar-items="canonical">{items.length?items.map(i=><article className={`r2-core-work-row is-${i.attentionState==='overdue'?'overdue':i.attentionState==='upcoming'?'upcoming':'action'}`} key={`${i.source}:${i.id}`} data-calendar-source={i.source} data-attention={i.attentionState}><div className="r2-core-work-row__signal"><span>{L[i.source]}</span><strong>{i.dueDate?.slice(8)??'•'}</strong></div><div className="r2-core-work-row__copy"><strong>{i.title}</strong><p>{i.companyLabel??'دون ارتباط'}</p><small>{time(i,data.workspaceTimezone)} · {i.status}{i.confirmationStatus?` · تأكيد ${i.confirmationStatus}`:''}{i.attendanceOutcome?` · حضور ${i.attendanceOutcome}`:''}</small></div></article>):<X t="لا توجد عناصر" b="لا توجد عناصر ضمن المرشحات الحالية."/>}</section></>}
 </main>
}
