import { useEffect,useState } from 'react';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import { useSchedulingCommandGateway } from '../../features/scheduling/SchedulingCommandContext.tsx';
import { localInputForInstant,workspaceLocalDateTimeToInstant } from '../../features/scheduling/calendarTime.ts';
import { buildUnifiedCalendarIcs,loadUnifiedCalendar,shiftUnifiedCalendarAnchor,type UnifiedCalendarAuthority,type UnifiedCalendarItem,type UnifiedCalendarSnapshot,type UnifiedCalendarView } from '../../features/scheduling/unifiedCalendar.ts';

type Props=Readonly<{workspace:Promise<string|null>}>;
const VIEWS:readonly [UnifiedCalendarView,string][]=[['day','يوم'],['week','أسبوع'],['month','شهر'],['agenda','أجندة']];
const SOURCES:readonly [UnifiedCalendarAuthority,string][]=[['all','كل المصادر'],['appointment','المواعيد'],['renewal','التجديدات'],['workflow_deadline','مهل سير العمل']];
const label=(item:UnifiedCalendarItem)=>item.source==='appointment'?'موعد':item.source==='renewal'?'تجديد':'مهلة سير عمل';
const short=(value:string)=>`${value.slice(0,8)}…`;
function failure(error:unknown){const code=(error as {dataCode?:string}|null)?.dataCode;if(code==='DATA_CONFLICT')return 'تغيرت البيانات أو ظهر تعارض من جلسة أخرى. أوقفت الكتابة وحدّثت التقويم.';if(code==='DATA_OUTCOME_UNKNOWN')return 'تعذر تأكيد نتيجة الكتابة. حدّث التقويم قبل إعادة المحاولة.';return error instanceof Error&&error.message?error.message:'تعذر إكمال العملية.'}
function when(item:UnifiedCalendarItem,timeZone:string){if(item.startsAt)return new Intl.DateTimeFormat('ar-IQ',{dateStyle:'medium',timeStyle:'short',timeZone}).format(new Date(item.startsAt));return item.dueDate??'دون وقت'}
function download(snapshot:UnifiedCalendarSnapshot){const url=URL.createObjectURL(new Blob([buildUnifiedCalendarIcs(snapshot)],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`enjaz-calendar-${snapshot.businessStartDate}.ics`;a.click();URL.revokeObjectURL(url)}

export function LiveUnifiedCalendarExperience({workspace}:Props){
 const factory=useDataLayerFactory(),commands=useSchedulingCommandGateway();
 const [workspaceId,setWorkspaceId]=useState<string|null>(null),[view,setView]=useState<UnifiedCalendarView>('month'),[anchor,setAnchor]=useState<string|null>(null),[authority,setAuthority]=useState<UnifiedCalendarAuthority>('all');
 const [staff,setStaff]=useState<string|null>(null),[company,setCompany]=useState<string|null>(null),[transaction,setTransaction]=useState<string|null>(null),[snapshot,setSnapshot]=useState<UnifiedCalendarSnapshot|null>(null);
 const [loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[revision,setRevision]=useState(0),[online,setOnline]=useState(()=>navigator.onLine),[busy,setBusy]=useState<string|null>(null);
 const [editing,setEditing]=useState<UnifiedCalendarItem|null>(null),[local,setLocal]=useState(''),[reason,setReason]=useState('');
 useEffect(()=>{let live=true;workspace.then(id=>{if(live)setWorkspaceId(id)}).catch(()=>{if(live)setError('تعذر تحديد مساحة العمل.')});return()=>{live=false}},[workspace]);
 useEffect(()=>{const sync=()=>setOnline(navigator.onLine);addEventListener('online',sync);addEventListener('offline',sync);return()=>{removeEventListener('online',sync);removeEventListener('offline',sync)}},[]);
 useEffect(()=>{if(!workspaceId)return;let live=true;setLoading(true);setError(null);loadUnifiedCalendar(factory,{workspaceId,view,anchorDate:anchor,authority,staffMemberId:staff,companyId:company,transactionId:transaction}).then(data=>{if(live){setSnapshot(data);setAnchor(value=>value??data.anchorDate);setLoading(false)}}).catch(e=>{if(live){setError(failure(e));setLoading(false)}});return()=>{live=false}},[factory,workspaceId,view,anchor,authority,staff,company,transaction,revision]);
 const reload=()=>setRevision(v=>v+1),move=(direction:-1|1)=>{const date=anchor??snapshot?.anchorDate;if(date)setAnchor(shiftUnifiedCalendarAnchor(date,view,direction))};
 const act=async(item:UnifiedCalendarItem,work:()=>Promise<unknown>,ok:string)=>{if(!online){setNotice('أنت دون اتصال؛ لم تُنفذ أي كتابة.');return}setBusy(item.id);setNotice(null);try{await work();setNotice(ok)}catch(e){setNotice(failure(e))}finally{setBusy(null);reload()}};
 const attendance=(item:UnifiedCalendarItem,outcome:'attended'|'missed')=>{if(!workspaceId||item.version===null)return;const wid=workspaceId,version=item.version;void act(item,()=>commands.recordCalendarEventAttendance({workspaceId:wid,eventId:item.id,operationId:crypto.randomUUID(),expectedVersion:version,outcome}),outcome==='attended'?'تم تسجيل الحضور.':'تم تسجيل عدم الحضور.')};
 const edit=(item:UnifiedCalendarItem)=>{if(snapshot&&item.startsAt){setEditing(item);setLocal(localInputForInstant(item.startsAt,snapshot.workspaceTimezone));setReason('')}};
 const reschedule=()=>{const item=editing,originalStart=item?.startsAt??null;if(!workspaceId||!snapshot||!item||item.version===null||originalStart===null||!local||!reason.trim())return;const wid=workspaceId,version=item.version,originalEnd=item.endsAt,tz=snapshot.workspaceTimezone,why=reason.trim(),localValue=local;void act(item,async()=>{if(!item.staffMemberIds.length)throw new Error('لا يمكن إعادة الجدولة دون موظف معيّن صراحةً.');const startsAt=workspaceLocalDateTimeToInstant(localValue,tz),oldStartMs=Date.parse(originalStart),oldEndMs=originalEnd===null?oldStartMs:Date.parse(originalEnd),duration=Math.max(0,oldEndMs-oldStartMs),endsAt=duration?new Date(Date.parse(startsAt)+duration).toISOString():null,conflict=await commands.checkCalendarEventStaffConflicts({workspaceId:wid,startsAt,endsAt,staffMemberIds:item.staffMemberIds,excludeEventId:item.id});if(conflict.state!=='clear')throw new Error(conflict.state==='conflict'?'يوجد تعارض فعلي مع موعد آخر.':'تعذر إثبات خلو الفترة من التعارض؛ أوقفت العملية.');await commands.rescheduleCalendarEvent({workspaceId:wid,eventId:item.id,operationId:crypto.randomUUID(),expectedVersion:version,startsAt,endsAt,reason:why});setEditing(null)},'تمت إعادة الجدولة بعد فحص التعارض.')};
 const items=snapshot?.items??[],companies=[...new Map(items.filter(x=>x.companyId).map(x=>[x.companyId!,x.companyLabel??short(x.companyId!)]))],transactions=[...new Set(items.flatMap(x=>x.transactionId?[x.transactionId]:[]))],staffMembers=[...new Set(items.flatMap(x=>x.staffMemberIds))];
 return <main className="r2-screen r2-core-today" data-phase11-5d-unified-calendar="live" data-calendar-view={view}>
  <header className="r2-section-heading r2-section-heading--hero"><div><p className="r2-eyebrow">M10 · 11.5-D</p><h1>التقويم والمواعيد</h1><p className="r2-supporting">عرض موحّد من حقائق المواعيد والتجديدات ومهل سير العمل، دون مخزن ظل.</p></div>{snapshot?<button className="r2-action r2-action--secondary" type="button" onClick={()=>download(snapshot)}>تصدير ICS</button>:null}</header>
  {!online?<section className="r2-core-scope-note" data-calendar-offline="true"><strong>دون اتصال</strong><span>القراءة قد تكون قديمة، وكل الكتابات متوقفة حتى عودة الاتصال.</span></section>:null}
  {notice?<section className="r2-core-scope-note" role="status"><strong>حالة العملية</strong><span>{notice}</span></section>:null}
  <section className="r2-core-toolbar" aria-label="أدوات التقويم">
   <label className="r2-core-sort"><span>العرض</span><select value={view} onChange={e=>setView(e.target.value as UnifiedCalendarView)}>{VIEWS.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
   <label className="r2-core-sort"><span>المصدر</span><select value={authority} onChange={e=>{setAuthority(e.target.value as UnifiedCalendarAuthority);setStaff(null)}}>{SOURCES.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
   <label className="r2-core-sort"><span>الشركة</span><select value={company??''} onChange={e=>setCompany(e.target.value||null)}><option value="">الكل</option>{companies.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
   <label className="r2-core-sort"><span>المعاملة</span><select value={transaction??''} onChange={e=>setTransaction(e.target.value||null)}><option value="">الكل</option>{transactions.map(id=><option key={id} value={id}>{short(id)}</option>)}</select></label>
   <label className="r2-core-sort"><span>الموظف</span><select value={staff??''} onChange={e=>{setStaff(e.target.value||null);if(e.target.value)setAuthority('appointment')}}><option value="">الكل</option>{staffMembers.map(id=><option key={id} value={id}>{short(id)}</option>)}</select></label>
   <button className="r2-action r2-action--secondary" type="button" onClick={()=>move(-1)}>السابق</button><button className="r2-action r2-action--secondary" type="button" onClick={()=>setAnchor(snapshot?.businessToday??null)}>اليوم</button><button className="r2-action r2-action--secondary" type="button" onClick={()=>move(1)}>التالي</button>
  </section>
  {snapshot?<section className="r2-core-focus" data-calendar-summary="canonical"><div><span>{snapshot.workspaceTimezone}</span><h2>{items.length} عنصرًا</h2><p>{snapshot.businessStartDate} — {snapshot.businessEndDate}</p></div><div className="r2-core-focus__stats"><span><strong>{items.filter(x=>x.attentionState==='overdue').length}</strong> متأخر</span><span><strong>{items.filter(x=>x.attentionState==='due_today').length}</strong> اليوم</span><span><strong>{items.filter(x=>x.source==='appointment').length}</strong> موعد</span></div></section>:null}
  {loading?<section className="r2-core-state" role="status"><strong>جارٍ تجهيز التقويم</strong><p>تتم القراءة من المصادر الحاكمة.</p></section>:error?<section className="r2-core-state" role="alert"><strong>تعذر تحميل التقويم</strong><p>{error}</p><button className="r2-action r2-action--secondary" type="button" onClick={reload}>إعادة المحاولة</button></section>:!items.length?<section className="r2-core-state"><strong>لا توجد عناصر</strong><p>لا توجد مواعيد أو تجديدات أو مهل ضمن النطاق والمرشحات الحالية.</p></section>:<section className="r2-core-work-list" data-calendar-items="canonical">{items.map(item=><article className={`r2-core-work-row is-${item.attentionState==='overdue'?'overdue':item.attentionState==='upcoming'?'upcoming':'action'}`} key={`${item.source}:${item.id}`} data-calendar-source={item.source} data-attention={item.attentionState}><div className="r2-core-work-row__signal"><span>{label(item)}</span><strong>{item.dueDate?.slice(8)??'•'}</strong></div><div className="r2-core-work-row__copy"><strong>{item.title}</strong><p>{item.companyLabel??'دون شركة مسماة'}</p><small>{when(item,snapshot!.workspaceTimezone)} · {item.status}</small>{item.source==='appointment'&&item.status==='scheduled'&&item.version?<div><button className="r2-action r2-action--secondary" type="button" disabled={busy===item.id} onClick={()=>edit(item)}>إعادة جدولة</button><button className="r2-action r2-action--secondary" type="button" disabled={busy===item.id||item.attendanceOutcome!==null} onClick={()=>attendance(item,'attended')}>حضر</button><button className="r2-action r2-action--secondary" type="button" disabled={busy===item.id||item.attendanceOutcome!==null} onClick={()=>attendance(item,'missed')}>لم يحضر</button></div>:null}{editing?.id===item.id?<div className="r2-core-toolbar" data-reschedule-editor="true"><label className="r2-core-sort"><span>الوقت الجديد ({snapshot!.workspaceTimezone})</span><input type="datetime-local" value={local} onChange={e=>setLocal(e.target.value)}/></label><label className="r2-core-sort"><span>السبب</span><input value={reason} maxLength={1200} onChange={e=>setReason(e.target.value)}/></label><button className="r2-action r2-action--primary" type="button" disabled={busy===item.id||!reason.trim()||!local} onClick={reschedule}>فحص التعارض واعتماد</button><button className="r2-action r2-action--secondary" type="button" onClick={()=>setEditing(null)}>إلغاء</button></div>:null}</div></article>)}</section>}
 </main>;
}
