import { useEffect,useState } from 'react';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import { buildUnifiedCalendarIcs,loadUnifiedCalendar,shiftUnifiedCalendarAnchor,type UnifiedCalendarAuthority,type UnifiedCalendarItem,type UnifiedCalendarSnapshot,type UnifiedCalendarView } from '../../features/scheduling/unifiedCalendar.ts';

type Props=Readonly<{workspace:Promise<string|null>}>;type Option=readonly [string,string];
const VIEWS:readonly [UnifiedCalendarView,string][]=[['day','يوم'],['week','أسبوع'],['month','شهر'],['agenda','أجندة']];
const SOURCES:readonly [UnifiedCalendarAuthority,string][]=[['all','كل المصادر'],['appointment','المواعيد'],['renewal','التجديدات'],['workflow_deadline','مهل سير العمل']];
const BTN='r2-action r2-action--secondary',LABEL:Record<string,string>={appointment:'موعد',renewal:'تجديد',workflow_deadline:'مهلة سير عمل'},short=(v:string)=>`${v.slice(0,8)}…`,unique=(v:readonly Option[])=>[...new Map(v)];
const when=(item:UnifiedCalendarItem,tz:string)=>item.startsAt?new Date(item.startsAt).toLocaleString('ar-IQ',{dateStyle:'medium',timeStyle:'short',timeZone:tz}):item.dueDate??'دون وقت';
function save(s:UnifiedCalendarSnapshot){const u=URL.createObjectURL(new Blob([buildUnifiedCalendarIcs(s)],{type:'text/calendar;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=`enjaz-calendar-${s.businessStartDate}.ics`;a.click();URL.revokeObjectURL(u)}
function Filter({name,value,options,set}:{name:string;value:string|null;options:readonly Option[];set:(value:string)=>void}){return <label className="r2-core-sort"><span>{name}</span><select value={value??''} onChange={e=>set(e.target.value)}>{options.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>}
function State({title,body,retry}:{title:string;body:string;retry?:()=>void}){return <section className="r2-core-state" role={retry?'alert':'status'}><strong>{title}</strong><p>{body}</p>{retry?<button className={BTN} type="button" onClick={retry}>إعادة المحاولة</button>:null}</section>}

export function LiveUnifiedCalendarExperience({workspace}:Props){
 const factory=useDataLayerFactory();
 const [workspaceId,setWorkspaceId]=useState<string|null>(null),[view,setView]=useState<UnifiedCalendarView>('month'),[anchor,setAnchor]=useState<string|null>(null),[authority,setAuthority]=useState<UnifiedCalendarAuthority>('all'),[staff,setStaff]=useState<string|null>(null),[company,setCompany]=useState<string|null>(null),[transaction,setTransaction]=useState<string|null>(null),[snapshot,setSnapshot]=useState<UnifiedCalendarSnapshot|null>(null),[error,setError]=useState(false),[revision,setRevision]=useState(0),[online,setOnline]=useState(()=>navigator.onLine);
 useEffect(()=>{let live=true;workspace.then(id=>{if(live)setWorkspaceId(id)}).catch(()=>{if(live)setError(true)});return()=>{live=false}},[workspace]);
 useEffect(()=>{const sync=()=>setOnline(navigator.onLine);addEventListener('online',sync);addEventListener('offline',sync);return()=>{removeEventListener('online',sync);removeEventListener('offline',sync)}},[]);
 useEffect(()=>{if(!workspaceId)return;let live=true;setSnapshot(null);setError(false);loadUnifiedCalendar(factory,{workspaceId,view,anchorDate:anchor,authority,staffMemberId:staff,companyId:company,transactionId:transaction}).then(data=>{if(live){setSnapshot(data);setAnchor(v=>v??data.anchorDate)}}).catch(()=>{if(live)setError(true)});return()=>{live=false}},[factory,workspaceId,view,anchor,authority,staff,company,transaction,revision]);
 const move=(direction:-1|1)=>{const date=anchor??snapshot?.anchorDate;if(date)setAnchor(shiftUnifiedCalendarAnchor(date,view,direction))},retry=()=>setRevision(v=>v+1),items=snapshot?.items??[];
 const companies=unique(items.flatMap(x=>x.companyId?[[x.companyId,x.companyLabel??short(x.companyId)] as const]:[])),transactions=unique(items.flatMap(x=>x.transactionId?[[x.transactionId,short(x.transactionId)] as const]:[])),staffMembers=unique(items.flatMap(x=>x.staffMemberIds.map(id=>[id,short(id)] as const))),all:Option[]=[['','الكل']];
 return <main className="r2-screen r2-core-today" data-phase11-5d-unified-calendar="live" data-calendar-view={view}>
  <header className="r2-section-heading r2-section-heading--hero"><div><p className="r2-eyebrow">M10 · 11.5-D</p><h1>التقويم والمواعيد</h1><p className="r2-supporting">المواعيد والتجديدات ومهل سير العمل من مصادرها الحاكمة.</p></div>{snapshot?<button className={BTN} type="button" onClick={()=>save(snapshot)}>تصدير ICS</button>:null}</header>
  {!online?<section className="r2-core-scope-note" data-calendar-offline="true"><strong>دون اتصال</strong><span>قد تكون القراءة قديمة؛ لا تُنفذ أوامر M10 من هذه الطبقة.</span></section>:null}
  <section className="r2-core-toolbar" aria-label="أدوات التقويم">
   <Filter name="العرض" value={view} options={VIEWS} set={v=>setView(v as UnifiedCalendarView)}/><Filter name="المصدر" value={authority} options={SOURCES} set={v=>{setAuthority(v as UnifiedCalendarAuthority);setStaff(null)}}/><Filter name="الشركة" value={company} options={[...all,...companies]} set={v=>setCompany(v||null)}/><Filter name="المعاملة" value={transaction} options={[...all,...transactions]} set={v=>setTransaction(v||null)}/><Filter name="الموظف" value={staff} options={[...all,...staffMembers]} set={v=>{setStaff(v||null);if(v)setAuthority('appointment')}}/>
   <button className={BTN} type="button" onClick={()=>move(-1)}>السابق</button><button className={BTN} type="button" onClick={()=>setAnchor(snapshot?.businessToday??null)}>اليوم</button><button className={BTN} type="button" onClick={()=>move(1)}>التالي</button><button className={BTN} type="button" onClick={retry}>تحديث</button>
  </section>
  {error?<State title="تعذر تحميل التقويم" body="تعذر التحقق من المصدر الحاكم." retry={retry}/>:!snapshot?<State title="جارٍ تجهيز التقويم" body="تتم القراءة من المصادر الحاكمة."/>:<><section className="r2-core-focus" data-calendar-summary="canonical"><div><span>{snapshot.workspaceTimezone}</span><h2>{items.length} عنصرًا</h2><p>{snapshot.businessStartDate} — {snapshot.businessEndDate}</p></div><div className="r2-core-focus__stats"><span><strong>{items.filter(x=>x.attentionState==='overdue').length}</strong> متأخر</span><span><strong>{items.filter(x=>x.attentionState==='due_today').length}</strong> اليوم</span><span><strong>{items.filter(x=>x.source==='appointment').length}</strong> موعد</span></div></section><section className="r2-core-scope-note" data-calendar-export-boundary="outbound_projection_only"><strong>حد التصدير</strong><span>ICS أحادي الاتجاه؛ التقويم الخارجي ليس مصدر حقيقة لإنجاز.</span></section><section className="r2-core-work-list" data-calendar-items="canonical">{items.length?items.map(item=><article className={`r2-core-work-row is-${item.attentionState==='overdue'?'overdue':item.attentionState==='upcoming'?'upcoming':'action'}`} key={`${item.source}:${item.id}`} data-calendar-source={item.source} data-attention={item.attentionState}><div className="r2-core-work-row__signal"><span>{LABEL[item.source]}</span><strong>{item.dueDate?.slice(8)??'•'}</strong></div><div className="r2-core-work-row__copy"><strong>{item.title}</strong><p>{item.companyLabel??'دون ارتباط مسمى'}</p><small>{when(item,snapshot.workspaceTimezone)} · {item.status}{item.confirmationStatus?` · تأكيد ${item.confirmationStatus}`:''}{item.attendanceOutcome?` · حضور ${item.attendanceOutcome}`:''}</small></div></article>):<State title="لا توجد عناصر" body="لا توجد عناصر ضمن النطاق والمرشحات الحالية."/>}</section></>}
 </main>;
}
