import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import type { EnjazDataLayerFactory } from '../../data/createDataLayer.ts';
import type { RowOf } from '../../data/contracts/dataTypes.ts';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import { useCurrentUserId } from '../../shared/session/CurrentUserIdContext.tsx';
import { useCompanyDirectory } from '../../features/companies/useCompanies.ts';
import { buildContactListSnapshot, normalizeContactListRequest, type ContactListFilter, type ContactListRequest, type ContactListSort } from '../../features/contacts/contactModel.ts';
import { ContactDomainError, addCompanyContactRelationship, endCompanyContactRelationship, loadContactListSource, loadContactProfileSource, saveContact, type ContactProfileSource } from '../../features/contacts/contactService.ts';
import { buildContact360Source } from '../../features/entity360/entity360Service.ts';
import { Entity360Panel } from './Entity360Panel.tsx';

type Contact=RowOf<'contacts'>;
const safe=(x:unknown)=>x instanceof ContactDomainError?x.message:'تعذر إكمال العملية.';
const Fail=({text,retry}:{text:string;retry?:()=>void})=><div className="r2-contacts-error" role="alert"><span>{text}</span>{retry&&<button onClick={retry}>إعادة المحاولة</button>}</div>;
function Editor({factory,userId,mode,contact,done,cancel}:{factory:EnjazDataLayerFactory;userId:string;mode:'create'|'edit';contact:Contact|null;done:(r:Contact)=>void;cancel:()=>void}){
 const operation=useRef(globalThis.crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget),status=f.get('status')==='inactive'?'inactive':'active';setBusy(true);setError(null);try{done(await saveContact(factory,userId,mode,{displayName:String(f.get('displayName')??''),contactType:String(f.get('contactType')??''),phone:String(f.get('phone')??''),email:String(f.get('email')??''),notes:String(f.get('notes')??''),status},{contactId:contact?.id??null,expectedUpdatedAt:contact?.updated_at??null,createOperationId:operation.current}))}catch(x){setError(safe(x))}finally{setBusy(false)}};
 const field=(label:string,name:string,value:string,type='text')=><label><span>{label}</span><input name={name} type={type} defaultValue={value} required={name==='displayName'||name==='contactType'} maxLength={name==='email'?254:name==='phone'?80:200} disabled={busy}/></label>;
 return <section className="r2-contacts-editor" aria-label={mode==='create'?'إضافة جهة اتصال':'تعديل جهة اتصال'}><header><h2>{mode==='create'?'جهة اتصال جديدة':'تعديل البيانات'}</h2><button onClick={cancel} disabled={busy}>إلغاء</button></header>{error&&<Fail text={error}/>}<form className="r2-contacts-form" onSubmit={e=>void submit(e)}>{field('الاسم','displayName',contact?.display_name??'')}{field('النوع / الصفة','contactType',contact?.contact_type??'contact')}{field('الهاتف','phone',contact?.phone??'','tel')}{field('البريد الإلكتروني','email',contact?.email??'','email')}<label className="is-wide"><span>ملاحظات</span><textarea name="notes" defaultValue={contact?.notes??''} maxLength={2000} disabled={busy}/></label><label><span>الحالة</span><select name="status" defaultValue={contact?.status==='inactive'?'inactive':'active'}><option value="active">نشطة</option><option value="inactive">غير نشطة</option></select></label><button className="is-primary" type="submit" disabled={busy}>حفظ</button></form></section>}
function Relations({factory,userId,contactId,reload}:{factory:EnjazDataLayerFactory;userId:string;contactId:string;reload:()=>void}){
 const companies=useCompanyDirectory(),items=companies.snapshot?.items??[],operation=useRef(globalThis.crypto.randomUUID()),[companyId,setCompanyId]=useState(''),[kind,setKind]=useState('محامٍ'),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!companyId&&items[0])setCompanyId(items[0].id)},[companyId,items]);
 const add=async()=>{if(busy||!companyId||!kind.trim())return;setBusy(true);setError(null);try{await addCompanyContactRelationship(factory,userId,{relationOperationId:operation.current,companyId,contactId,relationType:kind});operation.current=globalThis.crypto.randomUUID();reload()}catch(x){setError(safe(x))}finally{setBusy(false)}};
 return <section className="r2-contacts-relation-create"><h3>إضافة علاقة مع شركة</h3>{error&&<Fail text={error}/>}<label><span>ابحث عن الشركة</span><input value={companies.request.search} onChange={e=>companies.setSearch(e.target.value)}/></label><label><span>الشركة</span><select value={companyId} onChange={e=>setCompanyId(e.target.value)}>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label><span>نوع العلاقة</span><input value={kind} onChange={e=>setKind(e.target.value)}/></label><button className="is-primary" disabled={!companyId||!kind.trim()||busy} onClick={()=>void add()}>ربط بالشركة</button></section>}
function Profile({factory,userId,source,reload,edit}:{factory:EnjazDataLayerFactory;userId:string;source:ContactProfileSource;reload:()=>void;edit:(r:Contact)=>void}){
 const [error,setError]=useState<string|null>(null),{contact,companyRelations}=source;
 const end=async(id:string)=>{setError(null);try{await endCompanyContactRelationship(factory,userId,id,new Date().toISOString());reload()}catch(x){setError(safe(x))}};
 return <article className="r2-contacts-profile" data-contact-profile={contact.id}><header className="r2-contacts-identity"><div><h2>{contact.display_name}</h2><span>{contact.contact_type}</span></div><button onClick={()=>edit(contact)} disabled={contact.merged_into_id!==null}>تعديل البيانات</button></header>{error&&<Fail text={error}/>}<Entity360Panel source={buildContact360Source(source)}/><section className="r2-contacts-section"><h3>إدارة علاقات الشركات</h3><span>company_contacts</span><div className="r2-contacts-relations">{companyRelations.filter(x=>x.current).map(x=><div key={x.relation.id}><div><strong>{x.company?.display_name||x.company?.legal_name||'شركة غير متاحة'}</strong><span>{x.relation.relation_type}</span></div><button onClick={()=>void end(x.relation.id)}>إنهاء العلاقة</button></div>)}</div></section><Relations factory={factory} userId={userId} contactId={contact.id} reload={reload}/><aside className="r2-contacts-boundary">primary_contact_id يبقى مصدر علاقة المعاملة. Phase 6.3 توحّد العرض فقط، والمالية الكاملة في Phase 7.</aside></article>}
export function ConnectedPeople(){
 const factory=useDataLayerFactory(),userId=useCurrentUserId(),[attempt,setAttempt]=useState(0),[source,setSource]=useState<Awaited<ReturnType<typeof loadContactListSource>>['source']|null>(null),[loadError,setLoadError]=useState<string|null>(null),[request,setRequest]=useState<ContactListRequest>(normalizeContactListRequest()),[selected,setSelected]=useState<string|null>(null),[profileAttempt,setProfileAttempt]=useState(0),[profile,setProfile]=useState<ContactProfileSource|null>(null),[profileError,setProfileError]=useState<string|null>(null),[editor,setEditor]=useState<{mode:'create'|'edit';contact:Contact|null}|null>(null);
 useEffect(()=>{let live=true;if(!userId){setLoadError('انتهت الجلسة.');setSource(null);return()=>{live=false}}setLoadError(null);void loadContactListSource(factory,userId).then(x=>{if(live)setSource(x.source)}).catch(x=>{if(live){setSource(null);setLoadError(safe(x))}});return()=>{live=false}},[attempt,factory,userId]);
 const snapshot=useMemo(()=>source?buildContactListSnapshot(source,request):null,[request,source]),items=snapshot?.items??[];
 useEffect(()=>{if(!selected&&items[0])setSelected(items[0].id)},[items,selected]);
 useEffect(()=>{let live=true;if(!selected||!userId){setProfile(null);setProfileError(null);return()=>{live=false}}setProfile(null);setProfileError(null);void loadContactProfileSource(factory,userId,selected).then(x=>{if(live)setProfile(x.source)}).catch(x=>{if(live)setProfileError(safe(x))});return()=>{live=false}},[factory,profileAttempt,selected,userId]);
 const set=(patch:Partial<ContactListRequest>)=>setRequest(x=>normalizeContactListRequest({...x,...patch})),reloadList=()=>setAttempt(x=>x+1),reloadProfile=()=>setProfileAttempt(x=>x+1);
 if(!userId)return <Fail text="انتهت الجلسة."/>;
 return <section className="r2-screen r2-contacts-screen" data-phase6-2="lawyers-contacts" data-contact-source="workspace"><header className="r2-contacts-header"><h1>المحامون وجهات الاتصال</h1><button className="is-primary" onClick={()=>setEditor({mode:'create',contact:null})}>جهة اتصال جديدة</button></header>{editor?<Editor factory={factory} userId={userId} {...editor} cancel={()=>setEditor(null)} done={r=>{setEditor(null);setSelected(r.id);reloadList();reloadProfile()}}/>:<div className="r2-contacts-workspace"><aside className="r2-contacts-directory"><label><span>بحث الأشخاص</span><input value={request.search} onChange={e=>set({search:e.target.value,page:0})}/></label><div className="r2-contacts-filters"><button className={request.filter==='all'?'is-active':''} onClick={()=>set({filter:'all' as ContactListFilter,page:0})}>الكل {snapshot?.counts.all??0}</button><button className={request.filter==='lawyers'?'is-active':''} onClick={()=>set({filter:'lawyers' as ContactListFilter,page:0})}>المحامون {snapshot?.counts.lawyers??0}</button><button className={request.filter==='active'?'is-active':''} onClick={()=>set({filter:'active' as ContactListFilter,page:0})}>النشطون {snapshot?.counts.active??0}</button></div><label><span>الترتيب</span><select value={request.sort} onChange={e=>set({sort:e.target.value as ContactListSort,page:0})}><option value="activity-desc">الأحدث نشاطًا</option><option value="name-asc">الاسم</option></select></label>{loadError&&<Fail text={loadError} retry={reloadList}/>}<div className="r2-contacts-list">{items.map(x=><button key={x.id} className={x.id===selected?'is-active':''} onClick={()=>setSelected(x.id)}><span><strong>{x.displayName}</strong><small>{x.contactType}</small></span></button>)}</div>{snapshot&&snapshot.pageCount>1&&<nav className="r2-contacts-pagination"><button disabled={!snapshot.hasPrevious} onClick={()=>set({page:snapshot.page-1})}>السابق</button><span>{snapshot.page+1}/{snapshot.pageCount}</span><button disabled={!snapshot.hasMore} onClick={()=>set({page:snapshot.page+1})}>التالي</button></nav>}</aside><main className="r2-contacts-main">{profile?<Profile factory={factory} userId={userId} source={profile} reload={reloadProfile} edit={contact=>setEditor({mode:'edit',contact})}/>:profileError?<Fail text={profileError} retry={reloadProfile}/>:selected?<div className="r2-contacts-loading">جارٍ التحميل…</div>:<div className="r2-contacts-empty">اختر شخصًا</div>}</main></div>}</section>}
