import { useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type { RowOf } from '../../data/contracts/dataTypes.ts';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import { useCurrentUserId } from '../../shared/session/CurrentUserIdContext.tsx';
import { useCompanyDirectory } from '../../features/companies/useCompanies.ts';
import { ContactDomainError, addCompanyContactRelationship, endCompanyContactRelationship, saveContact } from '../../features/contacts/contactService.ts';
import { useContactDirectory, useContactProfile } from '../../features/contacts/useContacts.ts';

type Contact=RowOf<'contacts'>;
const safe=(x:unknown)=>x instanceof ContactDomainError?x.message:'تعذر إكمال العملية.';
const Fail=({text,retry}:{text:string;retry?:()=>void})=><div className="r2-contacts-error" role="alert"><span>{text}</span>{retry&&<button onClick={retry}>إعادة المحاولة</button>}</div>;
function Editor({mode,contact,done,cancel}:{mode:'create'|'edit';contact:Contact|null;done:(r:Contact)=>void;cancel:()=>void}){
 const factory=useDataLayerFactory(),userId=useCurrentUserId(),operation=useRef(globalThis.crypto.randomUUID()),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(busy||!userId)return;const f=new FormData(e.currentTarget),status=f.get('status')==='inactive'?'inactive':'active';setBusy(true);setError(null);try{done(await saveContact(factory,userId,mode,{displayName:String(f.get('displayName')??''),contactType:String(f.get('contactType')??''),phone:String(f.get('phone')??''),email:String(f.get('email')??''),notes:String(f.get('notes')??''),status},{contactId:contact?.id??null,expectedUpdatedAt:contact?.updated_at??null,createOperationId:operation.current}))}catch(x){setError(safe(x))}finally{setBusy(false)}};
 const field=(label:string,name:string,value:string,type='text')=><label><span>{label}</span><input name={name} type={type} defaultValue={value} required={name==='displayName'||name==='contactType'} maxLength={name==='email'?254:name==='phone'?80:200} disabled={busy}/></label>;
 return <section className="r2-contacts-editor" aria-label={mode==='create'?'إضافة جهة اتصال':'تعديل جهة اتصال'}><header><h2>{mode==='create'?'جهة اتصال جديدة':'تعديل البيانات'}</h2><button onClick={cancel} disabled={busy}>إلغاء</button></header>{error&&<Fail text={error}/>}<form className="r2-contacts-form" onSubmit={e=>void submit(e)}>{field('الاسم','displayName',contact?.display_name??'')}{field('النوع / الصفة','contactType',contact?.contact_type??'contact')}{field('الهاتف','phone',contact?.phone??'','tel')}{field('البريد الإلكتروني','email',contact?.email??'','email')}<label className="is-wide"><span>ملاحظات</span><textarea name="notes" defaultValue={contact?.notes??''} maxLength={2000} disabled={busy}/></label><label><span>الحالة</span><select name="status" defaultValue={contact?.status==='inactive'?'inactive':'active'}><option value="active">نشطة</option><option value="inactive">غير نشطة</option></select></label><button className="is-primary" type="submit" disabled={busy}>حفظ</button></form></section>}
function Relations({contactId,reload}:{contactId:string;reload:()=>void}){
 const factory=useDataLayerFactory(),userId=useCurrentUserId(),companies=useCompanyDirectory(),items=companies.snapshot?.items??[],operation=useRef(globalThis.crypto.randomUUID());
 const [companyId,setCompanyId]=useState(''),[kind,setKind]=useState('محامٍ'),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!companyId&&items[0])setCompanyId(items[0].id)},[companyId,items]);
 const add=async()=>{if(!userId||busy||!companyId||!kind.trim())return;setBusy(true);setError(null);try{await addCompanyContactRelationship(factory,userId,{relationOperationId:operation.current,companyId,contactId,relationType:kind});operation.current=globalThis.crypto.randomUUID();reload()}catch(x){setError(safe(x))}finally{setBusy(false)}};
 return <section className="r2-contacts-relation-create"><h3>إضافة علاقة مع شركة</h3>{error&&<Fail text={error}/>}<label><span>ابحث عن الشركة</span><input value={companies.request.search} onChange={e=>companies.setSearch(e.target.value)}/></label><label><span>الشركة</span><select value={companyId} onChange={e=>setCompanyId(e.target.value)}>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label><span>نوع العلاقة</span><input value={kind} onChange={e=>setKind(e.target.value)}/></label><button className="is-primary" disabled={!companyId||!kind.trim()||busy} onClick={()=>void add()}>ربط بالشركة</button></section>}
function Profile({id,edit}:{id:string;edit:(r:Contact)=>void}){
 const p=useContactProfile(id),factory=useDataLayerFactory(),userId=useCurrentUserId(),[error,setError]=useState<string|null>(null);
 if(p.status==='loading')return <div className="r2-contacts-loading">جارٍ التحميل…</div>;if(!p.source)return <Fail text={p.errorMessage??'تعذر تحميل الملف.'} retry={p.retry}/>;
 const{contact,companyRelations,transactions,truncated}=p.source,fee=transactions.reduce((n,x)=>n+x.current_fee,0),precise=Number.isSafeInteger(Math.round(fee*100));
 const end=async(relationId:string)=>{if(!userId)return;setError(null);try{await endCompanyContactRelationship(factory,userId,relationId,new Date().toISOString());p.retry()}catch(x){setError(safe(x))}};
 return <article className="r2-contacts-profile" data-contact-profile={contact.id}><header className="r2-contacts-identity"><div><h2>{contact.display_name}</h2><span>{contact.contact_type}</span></div><button onClick={()=>edit(contact)} disabled={contact.merged_into_id!==null}>تعديل البيانات</button></header>{error&&<Fail text={error}/>}<div className="r2-contacts-facts"><div><span>الهاتف</span><strong>{contact.phone??'غير مسجل'}</strong></div><div><span>البريد</span><strong>{contact.email??'غير مسجل'}</strong></div><div><span>المعاملات</span><strong>{transactions.length}{truncated.transactions?'+':''}</strong></div><div><span>الأتعاب المرتبطة</span><strong>{precise?fee.toLocaleString('ar-IQ'):'غير آمنة'}{truncated.transactions?' · جزئي':''}</strong></div></div>{(truncated.companyRelations||truncated.transactions)&&<aside className="r2-contacts-truncated">النتائج مقتطعة عند حد القراءة الآمن.</aside>}<section className="r2-contacts-section"><h3>علاقات الشركات</h3><div className="r2-contacts-relations">{companyRelations.map(x=><div key={x.relation.id}><div><strong>{x.company?.display_name||x.company?.legal_name||'شركة غير متاحة'}</strong><span>{x.relation.relation_type} · {x.current?'حالية':'منتهية'}</span></div>{x.current&&<button onClick={()=>void end(x.relation.id)}>إنهاء العلاقة</button>}</div>)}</div></section><Relations contactId={contact.id} reload={p.retry}/><section className="r2-contacts-section"><h3>المعاملات المرتبطة</h3><span>primary_contact_id</span><div className="r2-contacts-context-list">{transactions.map(x=><div key={x.id}><strong>{x.type}</strong><span>{x.status}</span></div>)}</div></section>{contact.notes&&<p className="r2-contacts-notes">{contact.notes}</p>}<aside className="r2-contacts-boundary">company_contacts هو مصدر علاقة الشركة. Company/Lawyer 360° في Phase 6.3 والمالية الكاملة في Phase 7.</aside></article>}
export function ConnectedPeople(){const d=useContactDirectory(),items=d.snapshot?.items??[];const[selected,setSelected]=useState<string|null>(null),[editor,setEditor]=useState<{mode:'create'|'edit';contact:Contact|null}|null>(null);useEffect(()=>{if(!selected&&items[0])setSelected(items[0].id)},[items,selected]);return <section className="r2-screen r2-contacts-screen" data-phase6-2="lawyers-contacts" data-contact-source="workspace"><header className="r2-contacts-header"><h1>المحامون وجهات الاتصال</h1><button className="is-primary" onClick={()=>setEditor({mode:'create',contact:null})}>جهة اتصال جديدة</button></header>{editor?<Editor {...editor} cancel={()=>setEditor(null)} done={r=>{setEditor(null);setSelected(r.id);d.retry()}}/>:<div className="r2-contacts-workspace"><aside className="r2-contacts-directory"><label><span>بحث الأشخاص</span><input value={d.request.search} onChange={e=>d.setSearch(e.target.value)}/></label><div className="r2-contacts-filters"><button className={d.request.filter==='all'?'is-active':''} onClick={()=>d.setFilter('all')}>الكل {d.snapshot?.counts.all??0}</button><button className={d.request.filter==='lawyers'?'is-active':''} onClick={()=>d.setFilter('lawyers')}>المحامون {d.snapshot?.counts.lawyers??0}</button><button className={d.request.filter==='active'?'is-active':''} onClick={()=>d.setFilter('active')}>النشطون {d.snapshot?.counts.active??0}</button></div><label><span>الترتيب</span><select value={d.request.sort} onChange={e=>d.setSort(e.target.value as 'activity-desc'|'name-asc')}><option value="activity-desc">الأحدث نشاطًا</option><option value="name-asc">الاسم</option></select></label>{d.status==='error'&&<Fail text={d.errorMessage??'تعذر تحميل الدليل.'} retry={d.retry}/>}<div className="r2-contacts-list">{items.map(x=><button key={x.id} className={x.id===selected?'is-active':''} onClick={()=>setSelected(x.id)}><span><strong>{x.displayName}</strong><small>{x.contactType}</small></span></button>)}</div>{d.snapshot&&d.snapshot.pageCount>1&&<nav className="r2-contacts-pagination"><button disabled={!d.snapshot.hasPrevious} onClick={()=>d.setPage(d.snapshot!.page-1)}>السابق</button><span>{d.snapshot.page+1}/{d.snapshot.pageCount}</span><button disabled={!d.snapshot.hasMore} onClick={()=>d.setPage(d.snapshot!.page+1)}>التالي</button></nav>}</aside><main className="r2-contacts-main">{selected?<Profile id={selected} edit={contact=>setEditor({mode:'edit',contact})}/>:<div className="r2-contacts-empty">اختر شخصًا</div>}</main></div>}</section>}
