import { useEffect, useState } from 'react';
import type { RowOf } from '../../data/contracts/dataTypes.ts';
import { useCompanyDirectory } from '../../features/companies/useCompanies.ts';
import { useContactDirectory, useContactEditor, useContactProfile, useContactRelationshipActions } from '../../features/contacts/useContacts.ts';

type Contact = RowOf<'contacts'>;
const Fail = ({ text, retry }: { text: string; retry?: () => void }) => <div className="r2-contacts-error" role="alert"><span>{text}</span>{retry && <button onClick={retry}>إعادة المحاولة</button>}</div>;

function Editor({ mode, contact, done, cancel }: { mode: 'create' | 'edit'; contact: Contact | null; done: (row: Contact) => void; cancel: () => void }) {
  const x = useContactEditor(mode, contact), busy = x.state === 'saving';
  useEffect(() => { if (x.savedContact) done(x.savedContact); }, [done, x.savedContact]);
  const input = (label: string, name: 'displayName'|'contactType'|'phone'|'email') => <label><span>{label}</span><input value={x.draft[name]} onChange={e => x.update(name,e.target.value)} disabled={busy}/>{x.errors[name] && <small>{x.errors[name]}</small>}</label>;
  return <section className="r2-contacts-editor" aria-label={mode === 'create' ? 'إضافة جهة اتصال' : 'تعديل جهة اتصال'}><header><h2>{mode === 'create' ? 'جهة اتصال جديدة' : 'تعديل البيانات'}</h2><button onClick={cancel}>إلغاء</button></header>{x.errorMessage && <Fail text={x.errorMessage}/>}<div className="r2-contacts-form">{input('الاسم','displayName')}{input('النوع / الصفة','contactType')}{input('الهاتف','phone')}{input('البريد الإلكتروني','email')}<label className="is-wide"><span>ملاحظات</span><textarea value={x.draft.notes} onChange={e=>x.update('notes',e.target.value)} disabled={busy}/></label><label><span>الحالة</span><select value={x.draft.status} onChange={e=>x.update('status',e.target.value)}><option value="active">نشطة</option><option value="inactive">غير نشطة</option></select></label></div><footer><button className="is-primary" onClick={()=>void x.save()} disabled={busy}>حفظ</button></footer></section>;
}

function Relations({ contactId, reload }: { contactId: string; reload: () => void }) {
  const companies = useCompanyDirectory(), act = useContactRelationshipActions(reload), items = companies.snapshot?.items ?? [];
  const [companyId,setCompanyId]=useState(''), [kind,setKind]=useState('محامٍ');
  useEffect(()=>{ if(!companyId&&items[0]) setCompanyId(items[0].id); },[companyId,items]);
  return <section className="r2-contacts-relation-create"><h3>إضافة علاقة مع شركة</h3>{act.errorMessage&&<Fail text={act.errorMessage}/>}<label><span>ابحث عن الشركة</span><input value={companies.request.search} onChange={e=>companies.setSearch(e.target.value)}/></label><label><span>الشركة</span><select value={companyId} onChange={e=>setCompanyId(e.target.value)}>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><label><span>نوع العلاقة</span><input value={kind} onChange={e=>setKind(e.target.value)}/></label><button className="is-primary" disabled={!companyId||!kind.trim()||act.state==='saving'} onClick={()=>void act.addCompany({companyId,contactId,relationType:kind})}>ربط بالشركة</button></section>;
}

function Profile({ id, edit }: { id:string; edit:(row:Contact)=>void }) {
  const p=useContactProfile(id), act=useContactRelationshipActions(p.retry);
  if(p.status==='loading') return <div className="r2-contacts-loading">جارٍ التحميل…</div>;
  if(!p.source) return <Fail text={p.errorMessage??'تعذر تحميل الملف.'} retry={p.retry}/>;
  const {contact,companyRelations,transactions,truncated}=p.source;
  return <article className="r2-contacts-profile" data-contact-profile={contact.id}><header className="r2-contacts-identity"><div><h2>{contact.display_name}</h2><span>{contact.contact_type}</span></div><button onClick={()=>edit(contact)} disabled={contact.merged_into_id!==null}>تعديل البيانات</button></header><div className="r2-contacts-facts"><div><span>الهاتف</span><strong>{contact.phone??'غير مسجل'}</strong></div><div><span>البريد</span><strong>{contact.email??'غير مسجل'}</strong></div><div><span>المعاملات</span><strong>{transactions.length}{truncated.transactions?'+':''}</strong></div></div>{(truncated.companyRelations||truncated.transactions)&&<aside className="r2-contacts-truncated">النتائج مقتطعة عند حد القراءة الآمن.</aside>}<section className="r2-contacts-section"><h3>علاقات الشركات</h3><div className="r2-contacts-relations">{companyRelations.map(x=><div key={x.relation.id}><div><strong>{x.company?.display_name||x.company?.legal_name||'شركة غير متاحة'}</strong><span>{x.relation.relation_type} · {x.current?'حالية':'منتهية'}</span></div>{x.current&&<button onClick={()=>void act.endCompany(x.relation.id)}>إنهاء العلاقة</button>}</div>)}</div></section><Relations contactId={contact.id} reload={p.retry}/><section className="r2-contacts-section"><h3>المعاملات المرتبطة</h3><span>primary_contact_id</span><div className="r2-contacts-context-list">{transactions.map(x=><div key={x.id}><strong>{x.type}</strong><span>{x.status}</span></div>)}</div></section>{contact.notes&&<p className="r2-contacts-notes">{contact.notes}</p>}<aside className="r2-contacts-boundary">company_contacts هو مصدر علاقة الشركة. Company/Lawyer 360° في Phase 6.3 والمالية في Phase 7.</aside></article>;
}

export function ConnectedPeople(){
  const d=useContactDirectory(), items=d.snapshot?.items??[];
  const [selected,setSelected]=useState<string|null>(null), [editor,setEditor]=useState<{mode:'create'|'edit';contact:Contact|null}|null>(null);
  useEffect(()=>{if(!selected&&items[0])setSelected(items[0].id)},[items,selected]);
  return <section className="r2-screen r2-contacts-screen" data-phase6-2="lawyers-contacts" data-contact-source="workspace"><header className="r2-contacts-header"><h1>المحامون وجهات الاتصال</h1><button className="is-primary" onClick={()=>setEditor({mode:'create',contact:null})}>جهة اتصال جديدة</button></header>{editor?<Editor {...editor} cancel={()=>setEditor(null)} done={row=>{setEditor(null);setSelected(row.id);d.retry()}}/>:<div className="r2-contacts-workspace"><aside className="r2-contacts-directory"><label><span>بحث الأشخاص</span><input value={d.request.search} onChange={e=>d.setSearch(e.target.value)}/></label><div className="r2-contacts-filters"><button className={d.request.filter==='all'?'is-active':''} onClick={()=>d.setFilter('all')}>الكل {d.snapshot?.counts.all??0}</button><button className={d.request.filter==='lawyers'?'is-active':''} onClick={()=>d.setFilter('lawyers')}>المحامون {d.snapshot?.counts.lawyers??0}</button><button className={d.request.filter==='active'?'is-active':''} onClick={()=>d.setFilter('active')}>النشطون {d.snapshot?.counts.active??0}</button></div>{d.status==='error'&&<Fail text={d.errorMessage??'تعذر تحميل الدليل.'} retry={d.retry}/>}<div className="r2-contacts-list">{items.map(x=><button key={x.id} className={x.id===selected?'is-active':''} onClick={()=>setSelected(x.id)}><span><strong>{x.displayName}</strong><small>{x.contactType}</small></span></button>)}</div>{d.snapshot&&d.snapshot.pageCount>1&&<nav className="r2-contacts-pagination"><button disabled={!d.snapshot.hasPrevious} onClick={()=>d.setPage(d.snapshot!.page-1)}>السابق</button><span>{d.snapshot.page+1}/{d.snapshot.pageCount}</span><button disabled={!d.snapshot.hasMore} onClick={()=>d.setPage(d.snapshot!.page+1)}>التالي</button></nav>}</aside><main className="r2-contacts-main">{selected?<Profile id={selected} edit={contact=>setEditor({mode:'edit',contact})}/>:<div className="r2-contacts-empty">اختر شخصًا</div>}</main></div>}</section>;
}
