import fs from 'node:fs';

const root=new URL('../',import.meta.url);
const read=(p)=>fs.readFileSync(new URL(p,root),'utf8');
const exists=(p)=>fs.existsSync(new URL(p,root));
const json=(p)=>JSON.parse(read(p));
const roadmap=read('docs/ENJAZ_MASTER_ROADMAP.md');
const readme=read('README.md');
const major=json('docs/ENJAZ_MAJOR_PRODUCT_SYSTEMS.json');
const errors=[];
const req=(v,m)=>{if(!v)errors.push(m)};
const marker=(s,m,l)=>req(s.includes(m),`${l} missing marker: ${m}`);
const checkOrder=(items,label)=>{let last=-1;for(const item of items){const pos=roadmap.indexOf(item);if(pos<0)errors.push(`${label}: missing ${item}`);else if(pos<=last)errors.push(`${label}: out of order ${item}`);last=Math.max(last,pos)}};
const closed=(path,label)=>{if(!exists(path)){errors.push(`${label} state missing: ${path}`);return null}const s=json(path);if(s.status!=='CLOSED'||s.exitGatePassed!==true)errors.push(`${label} must remain CLOSED with exitGatePassed=true`);for(const f of ['unresolvedDefectCount','criticalDefectCount','highDefectCount','functionalBlockerCount'])if(f in s&&s[f]!==0)errors.push(`${label} ${f} must remain zero`);return s};

checkOrder(['# Phase 0 — Product Freeze & Migration Contract','# Phase 1 — Engineering Foundation','# Phase 2 — ENJAZ Design System 1.0','# Phase 3 — Application Shell & Navigation','# Phase 4 — Home, Daily Work & Executive Overview','# Phase 5 — Transactions Core','# Phase 6 — Companies & People','# Phase 7 — Finance','# Phase 8 — Workflow, Automation & Operations','# Phase 9 — Risk, Governance & Intelligence','# Phase 10 — Documents, Vault, OCR & Reports','# Phase 11 — Notifications, Follow-ups, Client & Communications','# Phase 12 — ENJAZ AI & Knowledge Agent','# Phase 13 — Legacy Import & Reconciliation','# Phase 14 — Full-system Integration, API & Real E2E','# Phase 15 — Performance, Security, Reliability & Enterprise Controls','# Phase 16 — Final Visual & UX Destruction','# Phase 17 — Release Candidate & Production Validation','# Phase 18 — Final Delivery & Handoff'],'delivery phases');
checkOrder(['## 8.1 — Workflow Engine & Government Procedure OS — M1','## 8.2 — Automation Engine','## 8.3 — Operations Center + Field Operations — M5','## 8.4 — CRM, Service Catalog & Smart Intake — M6 + M17','## 8.5 — Multi-Branch / Departments / Teams — M15 foundation','## 8.6 — Global Command Center','## 8.7 — Operations Zero-Escape Destruction Gate'],'Phase 8 sequence');
checkOrder(['## 9.1 — Smart Risk Engine','## 9.2 — Smart Saved Views & Cross-domain Search Intelligence','## 9.3 — Corporate Governance & Ownership Engine — M2','## 9.4 — Regulatory / Knowledge Base Engine — M8 foundation','## 9.5 — Business Intelligence & Forecasting Center — M13','## 9.6 — Process Mining & Predictive Operations — M18','## 9.7 — Intelligence Zero-Escape Gate'],'Phase 9 sequence');
for(const m of ['ENJAZ 1.0 — Delivered','Zero-Escape closure law for M1–M18','Current position — canonical reconciled state','Major-system anchor matrix','Gate Escape','## 9.6 — Process Mining & Predictive Operations — M18','Derive actual process paths from authoritative histories.','Detect bottlenecks, rework and delay patterns; prediction must expose confidence and evidence.'])marker(roadmap,m,'roadmap');

req(major.schemaVersion===2&&major.status==='GOVERNING_AMENDMENT','major-system registry must remain governing amendment schema v2');
req(major.majorSystemCount===18&&major.systems?.length===18,'major-system registry must contain exactly M1-M18');
req(major.closureGateProfile==='ZERO_ESCAPE_V1'&&major.closureAuthority==='deployed-merged-sha','major-system closure authority drifted');
req(major.closedPhasesReopened===false&&major.phaseOrderChanged===false,'major-system amendment must not silently reopen/reorder historical phases');
const names=new Map([['M1','Government Procedure Operating System'],['M2','Corporate Governance & Ownership Engine'],['M3','Client Portal'],['M4','Omnichannel Communications Hub'],['M5','ENJAZ Field Operations / Runner Mode'],['M6','Service Catalog, CRM & Commercial Intake'],['M7','Document Factory & Official Form Engine'],['M8','Regulatory / Knowledge Base Engine'],['M9','Agentic ENJAZ Copilot'],['M10','Scheduling, Appointments & Deadline Engine'],['M11','Integration Platform / API / Webhooks'],['M12','Compliance, Audit & Evidence Center'],['M13','Business Intelligence & Forecasting Center'],['M14','Backup, Restore & Workspace Portability'],['M15','Multi-Branch, Departments & Team Operating Model'],['M16','Engagements, Contracts & Retainers'],['M17','Smart Intake Forms & Secure Submission Links'],['M18','Process Mining & Predictive Operations']]);
for(const [id,name] of names){const s=major.systems.find(x=>x.id===id);req(s?.name===name,`major-system registry drifted: ${id}`);marker(roadmap,`${id} | ${name}`,'roadmap anchor matrix');marker(readme,`**${id} — ${name}**`,'README major systems')}
for(const id of ['M1','M2','M5','M6']){const s=major.systems.find(x=>x.id===id);req(s?.status==='CLOSURE_CANDIDATE',`${id} must remain CLOSURE_CANDIDATE`);req(typeof s?.closureEvidence==='string'&&s.closureEvidence.startsWith('docs/'),`${id} closure candidate must retain evidence`)}
for(const id of ['M8','M13','M15','M17','M18'])req(major.systems.find(x=>x.id===id)?.status==='ACTIVE',`${id} must remain ACTIVE while governing anchors are open`);
const m8=major.systems.find(x=>x.id==='M8'),m13=major.systems.find(x=>x.id==='M13'),m18=major.systems.find(x=>x.id==='M18');
req(m8?.anchors?.join(',')==='9,12'&&m8?.closureEvidence===null,'M8 anchors/global closure drifted');
req(m13?.anchors?.join(',')==='9,15'&&m13?.closureEvidence===null,'M13 anchors/global closure drifted');
req(m18?.anchors?.join(',')==='9,15'&&m18?.closureEvidence===null,'M18 anchors/global closure drifted');
for(const id of ['M3','M4','M7','M9','M10','M11','M12','M14','M16'])req(major.systems.find(x=>x.id===id)?.status==='PLANNED',`${id} must remain PLANNED`);

for(const [p,l] of [['docs/PHASE5_5_TRANSACTION_DESTRUCTION_STATE.json','Phase 5.5'],['docs/PHASE6_1_COMPANIES_STATE.json','Phase 6.1'],['docs/PHASE6_2_LAWYERS_CONTACTS_STATE.json','Phase 6.2'],['docs/PHASE6_3_COMPANY_LAWYER_360_STATE.json','Phase 6.3'],['docs/PHASE6_4_COMPANIES_PEOPLE_DESTRUCTION_STATE.json','Phase 6.4'],['docs/PHASE7_1_FINANCIAL_LEDGER_STATE.json','Phase 7.1'],['docs/PHASE7_2_STATE.json','Phase 7.2'],['docs/PHASE7_3_STATE.json','Phase 7.3'],['docs/PHASE7_4_STATE.json','Phase 7.4'],['docs/PHASE7_5_STATE.json','Phase 7.5'],['docs/PHASE8_1_STATE.json','Phase 8.1'],['docs/PHASE8_2_STATE.json','Phase 8.2'],['docs/PHASE8_3_STATE.json','Phase 8.3'],['docs/PHASE8_4_STATE.json','Phase 8.4'],['docs/PHASE8_5_STATE.json','Phase 8.5'],['docs/PHASE8_6_STATE.json','Phase 8.6'],['docs/PHASE8_7_STATE.json','Phase 8.7'],['docs/PHASE9_1_STATE.json','Phase 9.1'],['docs/PHASE9_2_STATE.json','Phase 9.2'],['docs/PHASE9_3_STATE.json','Phase 9.3']])closed(p,l);
const p94=closed('docs/PHASE9_4_STATE.json','Phase 9.4'),p95=closed('docs/PHASE9_5_STATE.json','Phase 9.5');
req(p94?.phase9_5Allowed===true&&p94?.nextPhase==='9.5'&&p94?.successorStatus==='AUTHORIZED','Phase 9.4 successor evidence must remain 9.5');
req(p94?.majorSystem?.id==='M8'&&p94?.majorSystem?.status==='ACTIVE'&&p94?.majorSystem?.globalClosureAllowed===false,'Phase 9.4 must preserve M8 globally open');
req(p94?.postMergeRecertification?.workflowCount===23&&p94?.postMergeRecertification?.successCount===23&&p94?.postMergeRecertification?.failureCount===0,'Phase 9.4 exact-main 23/23 evidence drifted');
req(p94?.publishedLiveCertification?.pagesPreviewRunId===34677705458&&p94?.publishedLiveCertification?.liveExternalRunId===34677729775,'Phase 9.4 published evidence drifted');
req(p95?.phase9_6Allowed===true&&p95?.nextPhase==='9.6'&&p95?.successorStatus==='AUTHORIZED','Phase 9.5 successor evidence must authorize 9.6');
req(p95?.majorSystem?.id==='M13'&&p95?.majorSystem?.status==='ACTIVE'&&p95?.majorSystem?.anchors?.join(',')==='9,15'&&p95?.majorSystem?.globalClosureAllowed===false,'Phase 9.5 must preserve M13 globally open');
req(p95?.postMergeRecertification?.workflowCount===25&&p95?.postMergeRecertification?.successCount===25&&p95?.postMergeRecertification?.failureCount===0,'Phase 9.5 exact-main 25/25 evidence drifted');
req(p95?.publishedLiveCertification?.status==='PASS'&&p95?.publishedLiveCertification?.directLoadReloadTestsPassed===7,'Phase 9.5 published-live 7/7 evidence drifted');
for(const p of ['docs/PHASE9_4_CLOSURE.md','docs/PHASE9_4_POSTMERGE_RECERTIFICATION.md','docs/PHASE9_5_CLOSURE.md','docs/PHASE9_5_POSTMERGE_RECERTIFICATION.md'])req(exists(p),`missing closure evidence: ${p}`);

req(exists('docs/PHASE9_6_STATE.json')&&exists('docs/PHASE9_6_KICKOFF.md'),'Phase 9.6 kickoff/state must exist once M18 is ACTIVE');
if(exists('docs/PHASE9_6_STATE.json')){const p96=json('docs/PHASE9_6_STATE.json'),t=p96.projectQualityConstitution?.tracks||{};req(p96.phase==='9.6'&&['IN_PROGRESS','CLOSED'].includes(p96.status),'Phase 9.6 lifecycle invalid');req(p96.baseCommit==='295ad9dd308e391e7d92b1e27de74c859b0a20b1','Phase 9.6 base must remain formal Phase 9.5 closure SHA');req(p96.majorSystem?.id==='M18'&&p96.majorSystem?.status==='ACTIVE'&&p96.majorSystem?.anchors?.join(',')==='9,15'&&p96.majorSystem?.globalClosureAllowed===false,'Phase 9.6 M18 lifecycle drifted');req(p96.javascriptBudgetBytes===670000&&p96.budgetIncreaseAllowed===false,'Phase 9.6 must preserve 670000-byte ceiling');if(p96.status==='IN_PROGRESS'){req(p96.exitGatePassed===false&&p96.phase9_7Allowed===false&&p96.nextPhase===null&&p96.successorStatus==='LOCKED','Open Phase 9.6 must keep 9.7 locked');req(t.product==='IN_PROGRESS'&&['NOT_STARTED','IN_PROGRESS'].includes(t.uiUx)&&t.engineering==='IN_PROGRESS'&&['NOT_STARTED','IN_PROGRESS'].includes(t.certification),'Open Phase 9.6 quality tracks drifted');marker(readme,'الحالة الرسمية: **Phase 9.6 — Process Mining & Predictive Operations — M18 🟡 IN PROGRESS — FOUNDATION**','README');marker(readme,'**Phase 9.6 — Process Mining & Predictive Operations — M18: 🟡 IN PROGRESS — FOUNDATION.**','README');marker(readme,'**Phase 9.6 هي المرحلة المفتوحة الآن؛ Phase 9.7+ مقفلة حتى إغلاق 9.6.**','README')}else{req(p96.exitGatePassed===true&&p96.phase9_7Allowed===true&&p96.nextPhase==='9.7'&&p96.successorStatus==='AUTHORIZED','Closed Phase 9.6 must authorize only 9.7');req(t.product==='PASS'&&t.uiUx==='PASS'&&t.engineering==='PASS'&&t.certification==='PASS','Closed Phase 9.6 requires four PASS tracks')}}

if(errors.length){console.error(`ENJAZ ROADMAP AUDIT FAIL (${errors.length})`);errors.forEach(e=>console.error(`- ${e}`));process.exitCode=1}else console.log('ENJAZ ROADMAP AUDIT PASS — Phases 0-18 ordered; 9.4/9.5 closure preserved; M18 ACTIVE with anchors 9+15; Phase 9.6 governed and Phase 9.7 locked while open.');
