const {test,expect}=require('@playwright/test');
const baseURL=process.env.PHASE85_BASE_URL||'http://127.0.0.1:4185/';
const USER='22222222-2222-4222-8222-999999999999';
const WORKFORCE_SOURCE='77777777';
async function open(page){await page.goto(`${baseURL}phase8-5-preview.html`,{waitUntil:'networkidle'});await expect(page.locator('[data-organization-stage="8.5"]')).toBeVisible();await expect(page.locator('[data-organization-authority="organization_structure_scoped_ownership"]')).toBeVisible();await expect(page.locator('[data-workspace-trust-authority="legacy_owner_only_unchanged"]')).toBeVisible();await expect(page.locator('[data-workforce-authority="organization_members_and_scope_memberships"]')).toBeVisible();await expect(page.locator('[data-legacy-workspace-wide-access="forbidden"]')).toBeVisible();await expect(page.locator('[data-transaction-lifecycle-write-authority="none"]')).toBeVisible();await expect(page.locator('[data-finance-write-authority="none"]')).toBeVisible();await expect(page.getByRole('heading',{name:'مساحة العمل والهيكل التنظيمي'})).toBeVisible()}
async function selectTransactionByCompany(page,companyName){const select=page.getByLabel('المعاملة');const value=await select.locator('option').filter({hasText:companyName}).first().getAttribute('value');expect(value).toBeTruthy();await select.selectOption(value)}
for(const width of [1280,430,390,360,320])test(`Phase 8.5 organization remains overflow-safe at ${width}px`,async({page})=>{await page.setViewportSize({width,height:width>800?900:840});await open(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.getByRole('tab',{name:'الأشخاص والصلاحيات'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1);await page.getByRole('tab',{name:'ملكية العمل'}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)});

test('owner builds branch → department → team hierarchy through guarded controls',async({page})=>{await open(page);await expect(page.getByText('عرض المالك الموحد')).toBeVisible();await page.getByLabel('اسم الفرع').fill('فرع الاختبار');await page.getByLabel('رمز الفرع').fill('TST');await page.getByLabel('عنوان الفرع').fill('بغداد · اختبار');await page.getByRole('button',{name:'إضافة الفرع'}).click();const tree=page.getByLabel('الهيكل التنظيمي',{exact:true});await expect(tree.getByRole('heading',{name:'فرع الاختبار'})).toBeVisible();await page.getByLabel('اسم القسم').fill('قسم الاختبار');await page.getByLabel('فرع القسم').selectOption({label:'فرع الاختبار'});await page.getByLabel('رمز القسم').fill('DEP');await page.getByRole('button',{name:'إضافة القسم'}).click();await expect(tree.getByText('قسم الاختبار',{exact:true})).toBeVisible();await page.getByLabel('اسم الفريق').fill('فريق الاختبار');await page.getByLabel('قسم الفريق').selectOption({label:'قسم الاختبار'});await page.getByLabel('رمز الفريق').fill('TEAM');await page.getByRole('button',{name:'إضافة الفريق'}).click();await expect(tree.getByText('فريق الاختبار',{exact:true})).toBeVisible()});

test('owner adds canonical Auth workforce identity then grants explicit branch manager source',async({page})=>{await open(page);await page.getByRole('tab',{name:'الأشخاص والصلاحيات'}).click();await page.getByLabel('User UUID',{exact:true}).fill(USER);await page.getByRole('button',{name:'حفظ العضو'}).click();await expect(page.getByText('تم الحفظ وفق صلاحيات M15.')).toBeVisible();await page.getByLabel('User UUID للنطاق',{exact:true}).fill(USER);await page.getByLabel('نوع النطاق',{exact:true}).selectOption('branch');await page.getByLabel('النطاق',{exact:true}).selectOption({label:'فرع المنصور'});await page.getByLabel('دور النطاق',{exact:true}).selectOption('manager');await page.getByRole('button',{name:'حفظ النطاق'}).click();await expect(page.getByText('مدير · نشطة')).toBeVisible();await expect(page.locator('.r2-org-membership').filter({hasText:USER.slice(0,8)})).toBeVisible()});

test('owner assigns then transfers operational ownership without lifecycle or finance authority',async({page})=>{await open(page);await page.getByRole('tab',{name:'ملكية العمل'}).click();await selectTransactionByCompany(page,'شركة النهرين');await page.getByLabel('نوع النطاق',{exact:true}).selectOption('branch');await page.getByLabel('النطاق',{exact:true}).selectOption({label:'فرع الكرادة'});await page.getByLabel('سبب الإسناد أو النقل').fill('إسناد أولي للفرع المختص');await page.getByRole('button',{name:'إسناد المعاملة'}).click();await expect(page.locator('.r2-org-transaction').filter({hasText:'شركة النهرين'})).toBeVisible();await selectTransactionByCompany(page,'شركة النهرين');await page.getByLabel('نوع النطاق',{exact:true}).selectOption('team');await page.getByLabel('النطاق',{exact:true}).selectOption({label:'فريق الإنجاز'});await page.getByLabel('سبب الإسناد أو النقل').fill('تحويل للفريق المنفذ');await page.getByRole('button',{name:'نقل الملكية التشغيلية'}).click();await expect(page.locator('.r2-org-event').filter({hasText:'تحويل للفريق المنفذ'})).toBeVisible();await expect(page.locator('[data-transaction-lifecycle-write-authority="none"]')).toBeVisible();await expect(page.locator('[data-finance-write-authority="none"]')).toBeVisible()});

test('workforce view is branch-scoped, downward inherited and never exposes owner-wide siblings',async({page})=>{await open(page);await page.getByLabel('مساحة العمل').selectOption({label:'مساحة الرصافة المحدودة · موظف'});await expect(page.getByText('عرض موظف محدود النطاق')).toBeVisible();await expect(page.getByRole('heading',{name:'فرع الرصافة'})).toBeVisible();await expect(page.getByText('قسم المعاملات',{exact:true})).toBeVisible();await expect(page.getByText('فريق التنفيذ',{exact:true})).toBeVisible();await expect(page.getByText('فرع المنصور')).toHaveCount(0);await expect(page.getByText('فرع الكرادة')).toHaveCount(0);await expect(page.locator('.r2-org-branch[data-scope-source="77777777-7777-4777-8777-333333333333"]')).toBeVisible();await expect(page.locator('.r2-org-department[data-scope-source="77777777-7777-4777-8777-333333333333"]')).toBeVisible();await expect(page.locator('.r2-org-team[data-scope-source="77777777-7777-4777-8777-333333333333"]')).toBeVisible();await expect(page.getByText('إدارة المالك')).toHaveCount(0);await page.getByRole('tab',{name:'ملكية العمل'}).click();const visibleTransaction=page.locator('.r2-org-transaction').filter({hasText:'شركة الرافدين'});await expect(visibleTransaction).toBeVisible();await expect(visibleTransaction.locator('.r2-org-source code')).toHaveText(WORKFORCE_SOURCE);await expect(page.getByText('شركة النهرين')).toHaveCount(0)});
