import { useEffect,useMemo,useState } from 'react';
import { useDataLayerFactory } from '../../data/react/DataLayerContext.tsx';
import { useProcessMiningHistoryGateway } from '../../features/process-intelligence/ProcessMiningHistoryContext.tsx';
import { ProcessProvenanceRequiredError,classifyBottleneckCandidates,type ProcessPath } from '../../features/process-intelligence/processMiningContract.ts';
import { loadProcessMiningSnapshot,predictDelayRisk,predictNextActivity,type ProcessMiningSnapshot } from '../../features/process-intelligence/processMiningService.ts';
import { useCurrentUserId } from '../../shared/session/CurrentUserIdContext.tsx';
import { IntelligenceViewTabs } from './IntelligenceViewTabs.tsx';

type Status='loading'|'ready'|'error';
type ActivityOption=Readonly<{key:string;label:string;count:number}>;
type BottleneckRow=Readonly<{caseId:string;from:string;to:string;durationMs:number}>;
const THRESHOLD_HOURS=[4,24,72] as const;

function durationLabel(ms:number|null):string{
 if(ms===null)return 'غير معروف';
 const minutes=Math.floor(ms/60_000);if(minutes<60)return `${minutes.toLocaleString('ar-IQ')} دقيقة`;
 const hours=Math.floor(minutes/60),days=Math.floor(hours/24),rest=hours%24;
 if(days>0)return rest>0?`${days.toLocaleString('ar-IQ')} يوم و${rest.toLocaleString('ar-IQ')} ساعة`:`${days.toLocaleString('ar-IQ')} يوم`;
 return `${hours.toLocaleString('ar-IQ')} ساعة`;
}
function probabilityLabel(value:number|null):string{return value===null?'—':`${(value/100).toLocaleString('ar-IQ',{maximumFractionDigits:2})}%`}
function latestTime(path:ProcessPath):number{return path.events.length?Date.parse(path.events.at(-1)!.occurredAt):0}
function pathSources(path:ProcessPath):string{return [...new Set(path.events.map(event=>event.provenance.sourceDomain))].join(' · ')}
function activityOptions(snapshot:ProcessMiningSnapshot):readonly ActivityOption[]{
 const map=new Map<string,{label:string;count:number}>();
 for(const path of snapshot.cases)for(let i=0;i<path.events.length-1;i+=1){const event=path.events[i]!,current=map.get(event.activityKey);if(current)current.count+=1;else map.set(event.activityKey,{label:event.labelAr,count:1})}
 return Object.freeze([...map.entries()].map(([key,value])=>Object.freeze({key,label:value.label,count:value.count})).sort((a,b)=>b.count-a.count||a.label.localeCompare(b.label,'ar')));
}
function activityLabel(snapshot:ProcessMiningSnapshot,key:string|null):string{
 if(!key)return '—';for(const path of snapshot.cases)for(const event of path.events)if(event.activityKey===key)return event.labelAr;return key;
}
function Hero(){return <div className="r2-section-heading r2-section-heading--hero"><div><p className="r2-eyebrow">M18 · Process Mining · Phase 9.6</p><h1>ذكاء العمليات</h1><p>إعادة بناء المسارات الفعلية من تاريخ إنجاز الموثّق، مع كشف إعادة العمل والاختناقات وتوقعات اتجاهية معلنة الدليل والثقة. التوقع لا يغيّر أي مصدر ولا يمثل حقيقة مستقبلية.</p></div></div>}
function Empty({title,body}:{title:string;body:string}){return <section className="r2-destination-placeholder"><p className="r2-eyebrow">M18 · Process Intelligence</p><h2>{title}</h2><p>{body}</p></section>}

export function ProcessIntelligencePanel({snapshot}:{readonly snapshot:ProcessMiningSnapshot}){
 const options=useMemo(()=>activityOptions(snapshot),[snapshot]);
 const [activity,setActivity]=useState('');
 const [thresholdHours,setThresholdHours]=useState<number>(24);
 useEffect(()=>{if(!options.length){setActivity('');return}if(!options.some(item=>item.key===activity))setActivity(options[0]!.key)},[activity,options]);
 const thresholdMs=thresholdHours*3_600_000;
 const recent=useMemo(()=>[...snapshot.cases].sort((a,b)=>latestTime(b)-latestTime(a)||a.caseId.localeCompare(b.caseId)).slice(0,6),[snapshot]);
 const rework=useMemo(()=>[...snapshot.cases].filter(path=>path.reworkCount>0).sort((a,b)=>b.reworkCount-a.reworkCount||latestTime(b)-latestTime(a)).slice(0,6),[snapshot]);
 const bottlenecks=useMemo<readonly BottleneckRow[]>(()=>Object.freeze(snapshot.cases.flatMap(path=>classifyBottleneckCandidates(path,thresholdMs).map(wait=>Object.freeze({caseId:path.caseId,from:wait.fromActivityKey,to:wait.toActivityKey,durationMs:wait.durationMs}))).sort((a,b)=>b.durationMs-a.durationMs||a.caseId.localeCompare(b.caseId)).slice(0,8)),[snapshot,thresholdMs]);
 const nextPrediction=useMemo(()=>{if(!activity)return {value:null,error:''};try{return {value:predictNextActivity(snapshot,activity),error:''}}catch(cause){if(cause instanceof ProcessProvenanceRequiredError)return {value:null,error:''};return {value:null,error:cause instanceof Error?cause.message:'تعذر اشتقاق توقع النشاط التالي.'}}},[activity,snapshot]);
 const delayPrediction=useMemo(()=>{if(!activity)return {value:null,error:''};try{return {value:predictDelayRisk(snapshot,activity,thresholdMs),error:''}}catch(cause){if(cause instanceof ProcessProvenanceRequiredError)return {value:null,error:''};return {value:null,error:cause instanceof Error?cause.message:'تعذر اشتقاق توقع التأخر.'}}},[activity,snapshot,thresholdMs]);
 return <section className="r2-screen" dir="rtl" data-phase9-6-runtime="process-intelligence" data-process-authority="read-only-derived" data-process-provenance="required" data-process-prediction-authority="directional-non-authoritative">
  <IntelligenceViewTabs/><Hero/>
  <section className="r2-search-live-group" data-process-source-integrity="true"><div className="r2-search-live-group__title"><strong>سلامة المصدر</strong><span>موثّق</span></div><article className="r2-search-result"><span className="r2-search-result__icon" aria-hidden="true">✓</span><span><strong>نفس مساحة العمل · تاريخ المصدر فقط</strong><small>{snapshot.workspaceId} · توليد {new Date(snapshot.generatedAt).toLocaleString('ar-IQ')}</small><small>{snapshot.sourceCounts.transactionActivity.toLocaleString('ar-IQ')} نشاط معاملة · {snapshot.sourceCounts.workflowTransitions.toLocaleString('ar-IQ')} انتقال سير · {snapshot.sourceCounts.fieldVisits.toLocaleString('ar-IQ')} زيارة · {snapshot.sourceCounts.fieldEvidence.toLocaleString('ar-IQ')} دليل ميداني</small><small data-process-sync-receipt-policy={snapshot.syncReceiptPolicy}>إيصالات المزامنة actor-scoped هي دليل سلامة فقط وليست جزءًا من مسار العملية.</small></span></article></section>
  <section className="r2-search-live-group" data-process-analysis-controls="true"><div className="r2-search-live-group__title"><strong>نقطة التحليل</strong><span>{options.length.toLocaleString('ar-IQ')}</span></div><div className="r2-placeholder-actions">{options.slice(0,8).map(item=><button type="button" key={item.key} className={`r2-action ${activity===item.key?'r2-action--primary':'r2-action--secondary'}`} aria-pressed={activity===item.key} data-process-activity={item.key} onClick={()=>setActivity(item.key)}>{item.label} · {item.count.toLocaleString('ar-IQ')}</button>)}</div><div className="r2-placeholder-actions" data-process-threshold-controls="true">{THRESHOLD_HOURS.map(hours=><button type="button" key={hours} className={`r2-action ${thresholdHours===hours?'r2-action--primary':'r2-action--secondary'}`} aria-pressed={thresholdHours===hours} data-process-threshold-hours={hours} onClick={()=>setThresholdHours(hours)}>عتبة {hours.toLocaleString('ar-IQ')} ساعة</button>)}</div></section>
  <section className="r2-search-live-group" data-process-paths="true"><div className="r2-search-live-group__title"><strong>المسارات الفعلية المرصودة</strong><span>{snapshot.cases.length.toLocaleString('ar-IQ')}</span></div>{recent.length?recent.map(path=><article className="r2-launcher-group" key={path.caseId} data-process-case={path.caseId} data-process-ordering={path.ordering} data-process-authoritative="false"><h2>معاملة {path.caseId}</h2><div className="r2-launcher-list">{path.events.map(event=><div className="r2-launcher-row" key={`${event.provenance.sourceDomain}:${event.provenance.sourceEventId}`} data-process-event={event.activityKey}><span className="r2-launcher-row__icon" aria-hidden="true">●</span><span className="r2-launcher-row__copy"><strong>{event.labelAr}</strong><small>{new Date(event.occurredAt).toLocaleString('ar-IQ')} · {event.provenance.sourceDomain}</small></span></div>)}</div><p>{path.ordering==='partial'?'ترتيب جزئي: توجد أحداث متزامنة ولا يُفترض بينها تسلسل صارم.':'ترتيب زمني مثبت'} · المدة {durationLabel(path.observedDurationMs)} · المصادر {pathSources(path)}</p></article>):<Empty title="لا توجد مسارات مرصودة" body="لا يعرض إنجاز مسارًا مصطنعًا عندما لا توجد أحداث مصدر مؤهلة."/>}</section>
  <div className="r2-launcher-groups" data-process-diagnostics="true">
   <section className="r2-launcher-group" data-process-rework="true"><h2>إعادة العمل المرصودة</h2><div className="r2-launcher-list">{rework.length?rework.map(path=><article className="r2-launcher-row" key={path.caseId}><span className="r2-launcher-row__icon" aria-hidden="true">↻</span><span className="r2-launcher-row__copy"><strong>معاملة {path.caseId}</strong><small>{path.repeatedActivities.map(key=>activityLabel(snapshot,key)).join(' · ')||'—'}</small></span><strong>{path.reworkCount.toLocaleString('ar-IQ')}</strong></article>):<p>لا توجد إعادة عمل مرصودة ضمن الحالات الحالية.</p>}</div></section>
   <section className="r2-launcher-group" data-process-bottlenecks="true"><h2>مرشحو الاختناق · عتبة {thresholdHours.toLocaleString('ar-IQ')} ساعة</h2><div className="r2-launcher-list">{bottlenecks.length?bottlenecks.map((item,index)=><article className="r2-launcher-row" key={`${item.caseId}:${item.from}:${item.to}:${index}`}><span className="r2-launcher-row__icon" aria-hidden="true">!</span><span className="r2-launcher-row__copy"><strong>{activityLabel(snapshot,item.from)} ← {activityLabel(snapshot,item.to)}</strong><small>معاملة {item.caseId} · threshold معلنة · انتظار مرصود بترتيب مثبت</small></span><strong>{durationLabel(item.durationMs)}</strong></article>):<p>لا يوجد انتظار مرصود يتجاوز العتبة الحالية.</p>}</div></section>
  </div>
  <section className="r2-search-live-group" data-process-predictions="true" data-process-authoritative="false"><div className="r2-search-live-group__title"><strong>التوقعات الاتجاهية</strong><span>غير ملزمة</span></div>
   <article className="r2-search-result" data-process-next-prediction="true" data-process-prediction-method={nextPrediction.value?.method??'empirical_next_activity_frequency'} data-process-prediction-confidence={nextPrediction.value?.confidence??'insufficient'}><span className="r2-search-result__icon" aria-hidden="true">→</span><span><strong>النشاط التالي بعد {activityLabel(snapshot,activity||null)}</strong>{nextPrediction.error?<small>{nextPrediction.error}</small>:nextPrediction.value?<><small>{nextPrediction.value.confidence==='directional'?'اتجاهي':'عينات غير كافية'} · {nextPrediction.value.method} · {nextPrediction.value.sampleCount.toLocaleString('ar-IQ')} عينة · احتمال {probabilityLabel(nextPrediction.value.probabilityBps)}</small><small>{nextPrediction.value.assumptions[0]} · دليل المصدر {nextPrediction.value.provenance.length.toLocaleString('ar-IQ')} سجل نسب</small></>:<small>لا توجد عينة تاريخية مؤهلة لتوقع النشاط التالي.</small>}</span><strong>{activityLabel(snapshot,nextPrediction.value?.predictedActivityKey??null)}</strong></article>
   <article className="r2-search-result" data-process-delay-prediction="true" data-process-prediction-method={delayPrediction.value?.method??'empirical_wait_threshold_frequency'} data-process-prediction-confidence={delayPrediction.value?.confidence??'insufficient'} data-process-delay-threshold-ms={thresholdMs}><span className="r2-search-result__icon" aria-hidden="true">⏱</span><span><strong>احتمال تجاوز عتبة {thresholdHours.toLocaleString('ar-IQ')} ساعة</strong>{delayPrediction.error?<small>{delayPrediction.error}</small>:delayPrediction.value?<><small>{delayPrediction.value.confidence==='directional'?'اتجاهي':'عينات غير كافية'} · {delayPrediction.value.method} · {delayPrediction.value.sampleCount.toLocaleString('ar-IQ')} عينة · {delayPrediction.value.delayedSampleCount.toLocaleString('ar-IQ')} تجاوزت العتبة</small><small>{delayPrediction.value.assumptions[0]} · لا تدخل الأحداث متساوية الزمن في عينة التأخر</small></>:<small>لا توجد مدد انتظار ذات ترتيب مثبت تكفي لهذا التوقع.</small>}</span><strong>{probabilityLabel(delayPrediction.value?.probabilityBps??null)}</strong></article>
  </section>
 </section>;
}

export function ProcessIntelligenceCenter(){
 const userId=useCurrentUserId(),dataFactory=useDataLayerFactory(),historyGateway=useProcessMiningHistoryGateway(),[status,setStatus]=useState<Status>('loading'),[snapshot,setSnapshot]=useState<ProcessMiningSnapshot|null>(null),[error,setError]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let live=true;setStatus('loading');setError('');void (async()=>{try{if(!userId)throw new Error('لا توجد جلسة مستخدم صالحة.');if(!historyGateway)throw new Error('قناة تاريخ العمليات المعتمدة غير متاحة.');const result=await loadProcessMiningSnapshot({dataFactory,historyGateway},userId);if(live){setSnapshot(result);setStatus('ready')}}catch(cause){if(live){setSnapshot(null);setError(cause instanceof Error?cause.message:'تعذر تحميل ذكاء العمليات.');setStatus('error')}}})();return()=>{live=false}},[dataFactory,historyGateway,reload,userId]);
 if(status==='ready'&&snapshot)return <ProcessIntelligencePanel snapshot={snapshot}/>;
 return <section className="r2-screen" dir="rtl" data-phase9-6-runtime="process-intelligence" data-process-authority="read-only-derived" data-process-provenance="required"><IntelligenceViewTabs/><Hero/>{status==='loading'?<Empty title="جارٍ إعادة بناء المسارات الفعلية…" body="يتم جمع تاريخ المعاملات وسير العمل والعمليات الميدانية من مصادرها المعتمدة قبل اشتقاق أي مسار أو توقع."/>:<section className="r2-destination-placeholder" role="alert"><p className="r2-eyebrow">Fail closed</p><h2>تعذر بناء ذكاء العمليات</h2><p>{error}</p><div className="r2-placeholder-actions"><button type="button" className="r2-action r2-action--primary" onClick={()=>setReload(value=>value+1)}>إعادة المحاولة</button></div></section>}</section>;
}
