import { useEffect,useMemo,useState,type ReactNode } from 'react';
import { useProcessRuntimeFactory } from '../../features/process-intelligence/ProcessMiningHistoryContext.tsx';
import type { ProcessRuntimeGateway,RuntimeSnapshot } from '../../features/process-intelligence/processMiningRuntime.ts';
import { useCurrentUserId } from '../../shared/session/CurrentUserIdContext.tsx';
import { IntelligenceViewTabs } from './IntelligenceViewTabs.tsx';

type Status='loading'|'ready'|'error';type Attrs=Record<string,string|number|boolean>;
const H=[4,24,72] as const,NEXT='empirical_next_activity_frequency',DELAY='empirical_wait_threshold_frequency',L:Record<string,string>={transaction_created:'إنشاء',transaction_archived:'أرشفة',transaction_restored:'استعادة',transaction_completed:'إكمال',transaction_reactivated:'تفعيل',payment_posted:'دفعة',payment_reversed:'عكس',assignment_created:'تكليف',handoff:'تسليم',visit_check_in:'زيارة',visit_completed:'منجز',visit_failed:'متعذر',photo:'صورة',document:'مستند',receipt:'إيصال',other:'دليل',start:'بدء',advance:'انتقال',complete:'إكمال',reopen:'فتح'};
const date=(s:string)=>s.slice(0,16).replace('T',' '),probability=(n:number|null)=>n===null?'—':`${n/100}%`,duration=(n:number|null)=>n===null?'غير معروف':n<3600000?`${Math.floor(n/60000)}د`:`${Math.floor(n/3600000)}س`;
function label(k:string|null){if(!k)return '—';const [a,b,c]=k.split(':'),v=L[b!]??L[c!]??c??b??k;return a==='workflow'&&c?`${v} · ${c}`:v}
function Head({title,count}:{title:string;count:string|number}){return <div className="r2-search-live-group__title"><strong>{title}</strong><span>{count}</span></div>}
function Row({icon,title,sub,value,attrs}:{icon:string;title:string;sub?:ReactNode;value?:ReactNode;attrs?:Attrs}){return <article className="r2-launcher-row" {...attrs}><span className="r2-launcher-row__icon">{icon}</span><span className="r2-launcher-row__copy"><strong>{title}</strong>{sub&&<small>{sub}</small>}</span>{value!==undefined&&<strong>{value}</strong>}</article>}
function Empty({title,body}:{title:string;body:string}){return <section className="r2-destination-placeholder"><h2>{title}</h2><p>{body}</p></section>}
function Hero(){return <div className="r2-section-heading r2-section-heading--hero"><div><p className="r2-eyebrow">M18</p><h1>ذكاء العمليات</h1></div></div>}
function options(s:RuntimeSnapshot){const m=new Map<string,number>();for(const c of s.c)for(let i=0;i<c[5].length-1;i++){const k=c[5][i]![0];m.set(k,(m.get(k)??0)+1)}return [...m].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))}

export function ProcessIntelligencePanel({snapshot,runtime}:{snapshot:RuntimeSnapshot;runtime:ProcessRuntimeGateway}){
 const opts=useMemo(()=>options(snapshot),[snapshot]),[key,setKey]=useState(''),[hours,setHours]=useState<number>(24),threshold=hours*3600000;
 useEffect(()=>{if(!opts.length)setKey('');else if(!opts.some(x=>x[0]===key))setKey(opts[0]![0])},[key,opts]);
 const paths=snapshot.c.slice(0,6),rework=snapshot.c.filter(c=>c[3]).slice(0,6),bottlenecks=runtime.bottlenecks(snapshot,threshold),next=key?runtime.next(snapshot,key):null,delay=key?runtime.delay(snapshot,key,threshold):null;
 return <section className="r2-screen" dir="rtl" data-phase9-6-runtime="process-intelligence" data-process-authority="read-only-derived" data-process-provenance="required"><IntelligenceViewTabs/><Hero/>
  <section className="r2-search-live-group"><Head title="المصدر" count="موثّق"/><Row icon="✓" title="موثّق" sub={<>{date(snapshot.a)}<br/><span data-process-sync-receipt-policy="actor_scoped_integrity_evidence_not_path_input">إيصالات المزامنة دليل سلامة فقط وليست جزءًا من مسار العملية.</span></>}/></section>
  <section className="r2-search-live-group"><Head title="التحليل" count={opts.length}/><div className="r2-placeholder-actions">{opts.slice(0,8).map(([k,n])=><button type="button" key={k} className={`r2-action ${key===k?'r2-action--primary':'r2-action--secondary'}`} aria-pressed={key===k} onClick={()=>setKey(k)}>{label(k)} · {n}</button>)}</div><div className="r2-placeholder-actions">{H.map(h=><button type="button" key={h} className={`r2-action ${hours===h?'r2-action--primary':'r2-action--secondary'}`} aria-pressed={hours===h} data-process-threshold-hours={h} onClick={()=>setHours(h)}>{h}س</button>)}</div></section>
  <section className="r2-search-live-group" data-process-paths="true"><Head title="المسارات" count={snapshot.c.length}/>{paths.length?paths.map(c=><article className="r2-launcher-group" key={c[0]} data-process-case={c[0]} data-process-ordering={c[1]?'partial':'strict'} data-process-authoritative="false"><h2>معاملة {c[0]}</h2><div className="r2-launcher-list">{c[5].map(e=><Row key={e[2]} icon="●" title={label(e[0])} sub={date(e[1])} attrs={{'data-process-event':e[0]}}/>)}</div><p>{c[1]?'ترتيب جزئي؛ لا يُفترض بينها تسلسل صارم.':'ترتيب مثبت'} · {duration(c[2])}</p></article>):<Empty title="لا توجد مسارات مرصودة" body="لا يعرض إنجاز مسارًا مصطنعًا."/>}</section>
  <div className="r2-launcher-groups"><section className="r2-launcher-group" data-process-rework="true"><h2>إعادة العمل</h2><div className="r2-launcher-list">{rework.length?rework.map(c=><Row key={c[0]} icon="↻" title={`معاملة ${c[0]}`} sub={c[4].map(label).join(' · ')} value={c[3]}/>):<p>لا توجد.</p>}</div></section><section className="r2-launcher-group" data-process-bottlenecks="true"><h2>الاختناق · {hours}س</h2><div className="r2-launcher-list">{bottlenecks.length?bottlenecks.map((b,i)=><Row key={`${b[0]}:${i}`} icon="!" title={`${label(b[1])} ← ${label(b[2])}`} sub={`معاملة ${b[0]} · threshold معلنة`} value={duration(b[3])}/>):<p>لا يوجد.</p>}</div></section></div>
  <section className="r2-search-live-group"><Head title="التوقعات" count="غير ملزمة"/><Row icon="→" title={`التالي بعد ${label(key)}`} sub={next?`${next[0]?'اتجاهي':'عينات غير كافية'} · ${NEXT} · ${next[3]} عينة · دليل المصدر ${next[4]}`:'لا عينة مؤهلة.'} value={next?<>{label(next[1])} · {probability(next[2])}</>:'—'} attrs={{'data-process-next-prediction':'true','data-process-prediction-method':NEXT,'data-process-prediction-confidence':next?.[0]?'directional':'insufficient'}}/><Row icon="⏱" title={`تجاوز ${hours}س`} sub={delay?`${delay[0]?'اتجاهي':'عينات غير كافية'} · ${DELAY} · ${delay[2]} عينة · ${delay[3]} تأخر · لا تدخل الأحداث متساوية الزمن في عينة التأخر`:'لا مدد مثبتة.'} value={delay?probability(delay[1]):'—'} attrs={{'data-process-delay-prediction':'true','data-process-prediction-method':DELAY,'data-process-prediction-confidence':delay?.[0]?'directional':'insufficient','data-process-delay-threshold-ms':threshold}}/></section>
 </section>;
}

export function ProcessIntelligenceCenter(){const userId=useCurrentUserId(),factory=useProcessRuntimeFactory(),[state,setState]=useState<[Status,RuntimeSnapshot|null,ProcessRuntimeGateway|null,string]>(['loading',null,null,'']),[reload,setReload]=useState(0);useEffect(()=>{let live=true;setState(['loading',null,null,'']);void(async()=>{try{if(!userId)throw Error('لا توجد جلسة صالحة.');if(!factory)throw Error('قناة تاريخ العمليات المعتمدة غير متاحة.');const r=await factory(),s=await r.load(userId);if(live)setState(['ready',s,r,''])}catch{if(live)setState(['error',null,null,'تعذر التحقق من مصدر العمليات.'])}})();return()=>{live=false}},[factory,reload,userId]);if(state[0]==='ready'&&state[1]&&state[2])return <ProcessIntelligencePanel snapshot={state[1]} runtime={state[2]}/>;return <section className="r2-screen" dir="rtl" data-phase9-6-runtime="process-intelligence" data-process-authority="read-only-derived" data-process-provenance="required"><IntelligenceViewTabs/><Hero/>{state[0]==='loading'?<Empty title="جارٍ إعادة بناء المسارات الفعلية…" body="موثقة."/>:<section className="r2-destination-placeholder" role="alert"><p className="r2-eyebrow">Fail closed</p><h2>تعذر بناء ذكاء العمليات</h2><p>{state[3]}</p><div className="r2-placeholder-actions"><button type="button" className="r2-action r2-action--primary" onClick={()=>setReload(x=>x+1)}>إعادة المحاولة</button></div></section>}</section>}
