import { useEffect,useMemo,useState,type ReactNode } from 'react';
import { useProcessRuntimeFactory } from '../../features/process-intelligence/ProcessMiningHistoryContext.tsx';
import type { ProcessRuntimeGateway,RuntimeSnapshot } from '../../features/process-intelligence/processMiningRuntime.ts';
import { useCurrentUserId } from '../../shared/session/CurrentUserIdContext.tsx';
import { IntelligenceViewTabs } from './IntelligenceViewTabs.tsx';

type Status='loading'|'ready'|'error';type Attrs=Record<string,string|number|boolean>;
const H=[4,24,72] as const,N='ar-IQ',NEXT='empirical_next_activity_frequency',DELAY='empirical_wait_threshold_frequency';
const f=(n:number)=>n.toLocaleString(N),date=(s:string)=>new Date(s).toLocaleString(N),probability=(n:number|null)=>n===null?'—':`${(n/100).toLocaleString(N,{maximumFractionDigits:2})}%`,duration=(n:number|null)=>n===null?'غير معروف':n<3600000?`${f(Math.floor(n/60000))} د`:`${f(Math.floor(n/3600000))} س`;
const T:Record<string,string>={transaction_created:'إنشاء',transaction_archived:'أرشفة',transaction_restored:'استعادة',transaction_completed:'إكمال',transaction_reactivated:'إعادة تفعيل',payment_posted:'دفعة',payment_reversed:'عكس دفعة'},F:Record<string,string>={assignment_created:'تكليف',handoff:'تسليم',visit_check_in:'بدء زيارة',visit_completed:'إكمال زيارة',visit_failed:'تعذر الزيارة'},E:Record<string,string>={photo:'صورة',document:'مستند',receipt:'إيصال',other:'دليل'},W:Record<string,string>={start:'بدء',advance:'انتقال',complete:'إكمال',reopen:'إعادة فتح'};
function label(k:string|null){if(!k)return '—';const [a,b,c]=k.split(':');if(a==='transaction')return T[b!]??b!;if(a==='field')return b==='evidence'?(E[c!]??c!):(F[b!]??b!);return `${W[b!]??b} · ${c??''}`}
const domain=(k:string)=>k[0]==='t'?'معاملة':k[0]==='w'?'سير':'ميداني';
function Head({title,count}:{title:string;count:string|number}){return <div className="r2-search-live-group__title"><strong>{title}</strong><span>{typeof count==='number'?f(count):count}</span></div>}
function Row({icon,title,sub,value,attrs}:{icon:string;title:string;sub?:ReactNode;value?:ReactNode;attrs?:Attrs}){return <article className="r2-launcher-row" {...attrs}><span className="r2-launcher-row__icon">{icon}</span><span className="r2-launcher-row__copy"><strong>{title}</strong>{sub&&<small>{sub}</small>}</span>{value!==undefined&&<strong>{value}</strong>}</article>}
function Empty({title,body}:{title:string;body:string}){return <section className="r2-destination-placeholder"><p className="r2-eyebrow">M18 · Process</p><h2>{title}</h2><p>{body}</p></section>}
function Hero(){return <div className="r2-section-heading r2-section-heading--hero"><div><p className="r2-eyebrow">M18 · 9.6</p><h1>ذكاء العمليات</h1><p>مسارات فعلية وتوقعات اتجاهية من تاريخ إنجاز الموثق؛ قراءة مشتقة فقط.</p></div></div>}
function options(s:RuntimeSnapshot){const m=new Map<string,number>();for(const c of s.c)for(let i=0;i<c[5].length-1;i++){const k=c[5][i]![0];m.set(k,(m.get(k)??0)+1)}return [...m].sort((a,b)=>b[1]-a[1]||label(a[0]).localeCompare(label(b[0]),'ar'))}

export function ProcessIntelligencePanel({snapshot,runtime}:{snapshot:RuntimeSnapshot;runtime:ProcessRuntimeGateway}){
 const opts=useMemo(()=>options(snapshot),[snapshot]),[key,setKey]=useState(''),[hours,setHours]=useState<number>(24),threshold=hours*3600000;
 useEffect(()=>{if(!opts.length)setKey('');else if(!opts.some(x=>x[0]===key))setKey(opts[0]![0])},[key,opts]);
 const paths=snapshot.c.slice(0,6),rework=snapshot.c.filter(c=>c[3]).slice(0,6),bottlenecks=runtime.bottlenecks(snapshot,threshold),next=key?runtime.next(snapshot,key):null,delay=key?runtime.delay(snapshot,key,threshold):null;
 return <section className="r2-screen" dir="rtl" data-phase9-6-runtime="process-intelligence" data-process-authority="read-only-derived" data-process-provenance="required"><IntelligenceViewTabs/><Hero/>
  <section className="r2-search-live-group"><Head title="سلامة المصدر" count="موثّق"/><Row icon="✓" title="نفس مساحة العمل · تاريخ المصدر" sub={<>{snapshot.w} · {date(snapshot.a)}<br/><span data-process-sync-receipt-policy="actor_scoped_integrity_evidence_not_path_input">إيصالات المزامنة دليل سلامة فقط وليست جزءًا من مسار العملية.</span></>}/></section>
  <section className="r2-search-live-group"><Head title="نقطة التحليل" count={opts.length}/><div className="r2-placeholder-actions">{opts.slice(0,8).map(([k,n])=><button type="button" key={k} className={`r2-action ${key===k?'r2-action--primary':'r2-action--secondary'}`} aria-pressed={key===k} onClick={()=>setKey(k)}>{label(k)} · {f(n)}</button>)}</div><div className="r2-placeholder-actions">{H.map(h=><button type="button" key={h} className={`r2-action ${hours===h?'r2-action--primary':'r2-action--secondary'}`} aria-pressed={hours===h} data-process-threshold-hours={h} onClick={()=>setHours(h)}>{f(h)} ساعة</button>)}</div></section>
  <section className="r2-search-live-group" data-process-paths="true"><Head title="المسارات الفعلية المرصودة" count={snapshot.c.length}/>{paths.length?paths.map(c=><article className="r2-launcher-group" key={c[0]} data-process-case={c[0]} data-process-ordering={c[1]?'partial':'strict'} data-process-authoritative="false"><h2>معاملة {c[0]}</h2><div className="r2-launcher-list">{c[5].map(e=><Row key={e[2]} icon="●" title={label(e[0])} sub={`${date(e[1])} · ${domain(e[0])} · ${e[2]}`} attrs={{'data-process-event':e[0]}}/>)}</div><p>{c[1]?'ترتيب جزئي؛ لا يُفترض بينها تسلسل صارم.':'ترتيب زمني مثبت'} · {duration(c[2])}</p></article>):<Empty title="لا توجد مسارات مرصودة" body="لا يعرض إنجاز مسارًا مصطنعًا دون أحداث مصدر."/>}</section>
  <div className="r2-launcher-groups"><section className="r2-launcher-group" data-process-rework="true"><h2>إعادة العمل المرصودة</h2><div className="r2-launcher-list">{rework.length?rework.map(c=><Row key={c[0]} icon="↻" title={`معاملة ${c[0]}`} sub={c[4].map(label).join(' · ')} value={f(c[3])}/>):<p>لا توجد إعادة عمل مرصودة.</p>}</div></section><section className="r2-launcher-group" data-process-bottlenecks="true"><h2>مرشحو الاختناق · {f(hours)} ساعة</h2><div className="r2-launcher-list">{bottlenecks.length?bottlenecks.map((b,i)=><Row key={`${b[0]}:${i}`} icon="!" title={`${label(b[1])} ← ${label(b[2])}`} sub={`معاملة ${b[0]} · threshold معلنة`} value={duration(b[3])}/>):<p>لا يوجد انتظار يتجاوز العتبة.</p>}</div></section></div>
  <section className="r2-search-live-group"><Head title="التوقعات الاتجاهية" count="غير ملزمة"/><Row icon="→" title={`التالي بعد ${label(key)}`} sub={next?`${next[0]?'اتجاهي':'عينات غير كافية'} · ${NEXT} · ${f(next[3])} عينة · دليل المصدر ${f(next[4])}`:'لا توجد عينة تاريخية مؤهلة.'} value={next?<>{label(next[1])} · {probability(next[2])}</>:'—'} attrs={{'data-process-next-prediction':'true','data-process-prediction-method':NEXT,'data-process-prediction-confidence':next?.[0]?'directional':'insufficient'}}/><Row icon="⏱" title={`تجاوز ${f(hours)} ساعة`} sub={delay?`${delay[0]?'اتجاهي':'عينات غير كافية'} · ${DELAY} · ${f(delay[2])} عينة · ${f(delay[3])} تأخر · لا تدخل الأحداث متساوية الزمن في عينة التأخر`:'لا توجد مدد انتظار مثبتة.'} value={delay?probability(delay[1]):'—'} attrs={{'data-process-delay-prediction':'true','data-process-prediction-method':DELAY,'data-process-prediction-confidence':delay?.[0]?'directional':'insufficient','data-process-delay-threshold-ms':threshold}}/></section>
 </section>;
}

export function ProcessIntelligenceCenter(){const userId=useCurrentUserId(),factory=useProcessRuntimeFactory(),[state,setState]=useState<[Status,RuntimeSnapshot|null,ProcessRuntimeGateway|null,string]>(['loading',null,null,'']),[reload,setReload]=useState(0);useEffect(()=>{let live=true;setState(['loading',null,null,'']);void(async()=>{try{if(!userId)throw Error('لا توجد جلسة صالحة.');if(!factory)throw Error('قناة تاريخ العمليات المعتمدة غير متاحة.');const r=await factory(),s=await r.load(userId);if(live)setState(['ready',s,r,''])}catch(e){if(live)setState(['error',null,null,e instanceof Error?e.message:'تعذر تحميل ذكاء العمليات.'])}})();return()=>{live=false}},[factory,reload,userId]);if(state[0]==='ready'&&state[1]&&state[2])return <ProcessIntelligencePanel snapshot={state[1]} runtime={state[2]}/>;return <section className="r2-screen" dir="rtl" data-phase9-6-runtime="process-intelligence" data-process-authority="read-only-derived" data-process-provenance="required"><IntelligenceViewTabs/><Hero/>{state[0]==='loading'?<Empty title="جارٍ إعادة بناء المسارات الفعلية…" body="يتم التحقق من تاريخ المصادر قبل أي اشتقاق."/>:<section className="r2-destination-placeholder" role="alert"><p className="r2-eyebrow">Fail closed</p><h2>تعذر بناء ذكاء العمليات</h2><p>{state[3]}</p><div className="r2-placeholder-actions"><button type="button" className="r2-action r2-action--primary" onClick={()=>setReload(x=>x+1)}>إعادة المحاولة</button></div></section>}</section>}
