import type { EnjazSupabaseClient } from '../../core/supabase/client.ts';
import { DataAccessError, normalizeDataFailure, normalizeThrownDataFailure, type DataFailureLike } from '../../data/contracts/DataAccessError.ts';

export type SavedViewDomain='transactions'|'companies'|'people'|'procedures'|'documents';
export type SavedViewVisibility='personal'|'team'|'workspace';
export type SavedViewDefinition=Readonly<{schema:'enjaz.saved-view.v1';domain:SavedViewDomain;query:string;filters:Readonly<Record<string,string|number|boolean|null>>;sort:string|null;dateRange:Readonly<{from:string|null;to:string|null}>;pageSize:number|null;sourceSchema:string|null}>;
export type SavedViewRecord=Readonly<{id:string;workspaceId:string;ownerUserId:string;name:string;domain:SavedViewDomain;visibility:SavedViewVisibility;teamId:string|null;definition:SavedViewDefinition;version:number;createdAt:string;updatedAt:string}>;
export type GlobalSearchResultReference=Readonly<{schema:'enjaz.global-search-result.v1';domain:SavedViewDomain;entityId:string;title:string;subtitle:string|null;destination:string}>;
export type SavedViewWriteResult=Readonly<{savedViewId:string;version:number;replayed:boolean;wasCreated?:boolean;deleted?:boolean}>;
export type SaveSavedViewInput=Readonly<{workspaceId:string;savedViewId:string|null;expectedVersion:number|null;operationId:string;name:string;visibility?:SavedViewVisibility;teamId?:string|null;definition:SavedViewDefinition}>;
export interface SearchIntelligenceGateway{listSavedViews(workspaceId:string):Promise<readonly SavedViewRecord[]>;saveSavedView(input:SaveSavedViewInput):Promise<SavedViewWriteResult>;deleteSavedView(workspaceId:string,savedViewId:string,expectedVersion:number,operationId:string):Promise<SavedViewWriteResult>;globalSearch(workspaceId:string,query:string,limitPerDomain?:number):Promise<readonly GlobalSearchResultReference[]>}

type Row=Record<string,unknown>;type RpcResponse={readonly data:unknown;readonly error:DataFailureLike|null};type RpcClient={rpc(name:string,args:Readonly<Record<string,unknown>>):PromiseLike<RpcResponse>};
const domains:readonly SavedViewDomain[]=['transactions','companies','people','procedures','documents'];
const fail=(m:string,validation=false):never=>{throw new DataAccessError(m,validation?'DATA_VALIDATION_FAILED':'DATA_OPERATION_FAILED')};
const obj=(v:unknown):Row|null=>v!==null&&typeof v==='object'&&!Array.isArray(v)?v as Row:null,pos=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>0,domain=(v:unknown):v is SavedViewDomain=>domains.includes(v as SavedViewDomain),visibility=(v:unknown):v is SavedViewVisibility=>v==='personal'||v==='team'||v==='workspace';
const row=(v:unknown,m:string):Row=>obj(v)??fail(m);
function definition(v:unknown,validation=false):SavedViewDefinition{const r=row(v,'Invalid saved-view definition'),f=obj(r.filters),d=obj(r.dateRange);if(r.schema!=='enjaz.saved-view.v1'||!domain(r.domain)||typeof r.query!=='string'||r.query.length>120||!f||(r.sort!==null&&typeof r.sort!=='string')||!d||(d.from!==null&&typeof d.from!=='string')||(d.to!==null&&typeof d.to!=='string')||(r.pageSize!==null&&(!pos(r.pageSize)||Number(r.pageSize)>100))||(r.sourceSchema!==null&&typeof r.sourceSchema!=='string'))fail('Invalid saved-view definition',validation);return r as unknown as SavedViewDefinition}
function view(v:unknown):SavedViewRecord{const r=row(v,'Invalid saved view'),d=definition(r.definition);if(d.domain!==r.domain||typeof r.id!=='string'||typeof r.workspaceId!=='string'||typeof r.ownerUserId!=='string'||typeof r.name!=='string'||!visibility(r.visibility)||(r.teamId!==null&&typeof r.teamId!=='string')||!pos(r.version)||typeof r.createdAt!=='string'||typeof r.updatedAt!=='string')fail('Invalid saved view');return r as unknown as SavedViewRecord}
function write(v:unknown):SavedViewWriteResult{const r=row(v,'Invalid saved-view write result');if(typeof r.savedViewId!=='string'||!pos(r.version)||typeof r.replayed!=='boolean')fail('Invalid saved-view write result');return r as unknown as SavedViewWriteResult}
function result(v:unknown):GlobalSearchResultReference{const r=row(v,'Invalid search result');if(r.schema!=='enjaz.global-search-result.v1'||!domain(r.domain)||typeof r.entityId!=='string'||!r.entityId||r.entityId.length>128||typeof r.title!=='string'||!r.title||r.title.length>180||(r.subtitle!==null&&(typeof r.subtitle!=='string'||r.subtitle.length>220))||typeof r.destination!=='string'||r.destination.length>320||!r.destination.startsWith('/app/'))fail('Invalid search result');return r as unknown as GlobalSearchResultReference}
async function rpc(c:RpcClient,n:string,a:Readonly<Record<string,unknown>>,w=false,t=15_000):Promise<unknown>{let timer:ReturnType<typeof setTimeout>|undefined;try{const x:RpcResponse=await Promise.race([Promise.resolve(c.rpc(n,a)),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new DataAccessError(w?'Write outcome unknown':'Read timed out',w?'DATA_OUTCOME_UNKNOWN':'DATA_UNAVAILABLE')),t)})]);if(x.error)throw normalizeDataFailure(x.error);return x.data}catch(e){throw normalizeThrownDataFailure(e,w?'write':'read')}finally{if(timer!==undefined)clearTimeout(timer)}}

export function createSearchIntelligenceGateway(client:EnjazSupabaseClient,timeout=15_000):SearchIntelligenceGateway{if(!pos(timeout)||timeout>120_000)throw new Error('Invalid RPC timeout');const c=client as unknown as RpcClient;return {
async listSavedViews(workspaceId:string){const x=await rpc(c,'list_saved_views_v1',{p_workspace_id:workspaceId},false,timeout);if(!Array.isArray(x))fail('Invalid saved-view list');return (x as unknown[]).map(view)},
async saveSavedView(input:SaveSavedViewInput){const name=input.name.normalize('NFKC').replace(/\s+/g,' ').trim().slice(0,80),v=input.visibility??'personal',team=input.teamId??null,d=definition(input.definition,true);if(!name||!visibility(v)||(v==='team')!==(team!==null)||(input.savedViewId===null)!==(input.expectedVersion===null))fail('Invalid saved-view boundary',true);return write(await rpc(c,'save_saved_view_v1',{p_workspace_id:input.workspaceId,p_saved_view_id:input.savedViewId,p_expected_version:input.expectedVersion,p_operation_id:input.operationId,p_name:name,p_visibility:v,p_team_id:team,p_definition:d},true,timeout))},
async deleteSavedView(workspaceId:string,savedViewId:string,expectedVersion:number,operationId:string){if(!pos(expectedVersion))fail('Invalid saved-view version',true);return write(await rpc(c,'delete_saved_view_v1',{p_workspace_id:workspaceId,p_saved_view_id:savedViewId,p_expected_version:expectedVersion,p_operation_id:operationId},true,timeout))},
async globalSearch(workspaceId:string,query:string,limitPerDomain=8){const q=query.normalize('NFKC').replace(/\s+/g,' ').trim().slice(0,120);if(q.length<2)return[];if(!pos(limitPerDomain)||limitPerDomain>10)fail('Invalid search limit',true);const x=await rpc(c,'global_search_v1',{p_workspace_id:workspaceId,p_query:q,p_limit_per_domain:limitPerDomain},false,timeout);if(!Array.isArray(x))fail('Invalid search result');return (x as unknown[]).map(result)}
}}
