import type { EnjazSupabaseClient } from '../../core/supabase/client.ts';
import { DataAccessError, normalizeDataFailure, normalizeThrownDataFailure, type DataFailureLike } from '../../data/contracts/DataAccessError.ts';

export type SavedViewDomain='transactions'|'companies'|'people'|'procedures'|'documents';
export type SavedViewVisibility='personal'|'team'|'workspace';
export type SavedViewDefinition=Readonly<{schema:'enjaz.saved-view.v1';domain:SavedViewDomain;query:string;filters:Readonly<Record<string,string|number|boolean|null>>;sort:string|null;dateRange:Readonly<{from:string|null;to:string|null}>;pageSize:number|null;sourceSchema:string|null}>;
export type SavedViewRecord=Readonly<{id:string;workspaceId:string;ownerUserId:string;name:string;domain:SavedViewDomain;visibility:SavedViewVisibility;teamId:string|null;definition:SavedViewDefinition;version:number;createdAt:string;updatedAt:string}>;
export type GlobalSearchResultReference=Readonly<{schema:'enjaz.global-search-result.v1';domain:SavedViewDomain;entityId:string;title:string;subtitle:string|null;destination:string}>;
export type SavedViewWriteResult=Readonly<{savedViewId:string;version:number;replayed:boolean;wasCreated?:boolean;deleted?:boolean}>;
export type SaveSavedViewInput=Readonly<{workspaceId:string;savedViewId:string|null;expectedVersion:number|null;operationId:string;name:string;visibility?:SavedViewVisibility;teamId?:string|null;definition:SavedViewDefinition}>;
export interface SearchIntelligenceGateway{listSavedViews(workspaceId:string):Promise<readonly SavedViewRecord[]>;saveSavedView(input:SaveSavedViewInput):Promise<SavedViewWriteResult>;deleteSavedView(workspaceId:string,savedViewId:string,expectedVersion:number,operationId:string):Promise<SavedViewWriteResult>;globalSearch(workspaceId:string,query:string,limitPerDomain?:number):Promise<readonly GlobalSearchResultReference[]>}

type RpcResponse={readonly data:unknown;readonly error:DataFailureLike|null};type RpcClient={rpc(name:string,args:Readonly<Record<string,unknown>>):PromiseLike<RpcResponse>};
const domains=['transactions','companies','people','procedures','documents'] as const,visibilities=['personal','team','workspace'] as const;
const obj=(v:unknown)=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:null;
const pos=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>0;
const err=(m:string,c:'DATA_OPERATION_FAILED'|'DATA_VALIDATION_FAILED'='DATA_OPERATION_FAILED')=>new DataAccessError(m,c);
const domain=(v:unknown):v is SavedViewDomain=>domains.includes(v as SavedViewDomain);
const visibility=(v:unknown):v is SavedViewVisibility=>visibilities.includes(v as SavedViewVisibility);
function definition(v:unknown):SavedViewDefinition|null{const r=obj(v),f=obj(r?.filters),dr=obj(r?.dateRange);if(!r||r.schema!=='enjaz.saved-view.v1'||!domain(r.domain)||typeof r.query!=='string'||r.query.length>120||!f||(r.sort!==null&&typeof r.sort!=='string')||!dr||(dr.from!==null&&typeof dr.from!=='string')||(dr.to!==null&&typeof dr.to!=='string')||(r.pageSize!==null&&(!pos(r.pageSize)||Number(r.pageSize)>100))||(r.sourceSchema!==null&&typeof r.sourceSchema!=='string'))return null;return r as unknown as SavedViewDefinition}
function view(v:unknown):SavedViewRecord{const r=obj(v),d=definition(r?.definition);if(!r||!d||d.domain!==r.domain||typeof r.id!=='string'||typeof r.workspaceId!=='string'||typeof r.ownerUserId!=='string'||typeof r.name!=='string'||!visibility(r.visibility)||(r.teamId!==null&&typeof r.teamId!=='string')||!pos(r.version)||typeof r.createdAt!=='string'||typeof r.updatedAt!=='string')throw err('Invalid saved view');return Object.freeze({id:r.id,workspaceId:r.workspaceId,ownerUserId:r.ownerUserId,name:r.name,domain:d.domain,visibility:r.visibility,teamId:r.teamId as string|null,definition:d,version:Number(r.version),createdAt:r.createdAt,updatedAt:r.updatedAt})}
function write(v:unknown):SavedViewWriteResult{const r=obj(v);if(!r||typeof r.savedViewId!=='string'||!pos(r.version)||typeof r.replayed!=='boolean')throw err('Invalid saved-view write result');return Object.freeze({savedViewId:r.savedViewId,version:Number(r.version),replayed:r.replayed,...(typeof r.wasCreated==='boolean'?{wasCreated:r.wasCreated}:{}),...(typeof r.deleted==='boolean'?{deleted:r.deleted}:{})})}
function result(v:unknown):GlobalSearchResultReference|null{const r=obj(v);if(!r||r.schema!=='enjaz.global-search-result.v1'||!domain(r.domain)||typeof r.entityId!=='string'||!r.entityId||typeof r.title!=='string'||!r.title||(r.subtitle!==null&&typeof r.subtitle!=='string')||typeof r.destination!=='string'||!r.destination.startsWith('/app/'))return null;return Object.freeze({schema:'enjaz.global-search-result.v1',domain:r.domain,entityId:r.entityId.slice(0,128),title:r.title.slice(0,180),subtitle:r.subtitle===null?null:r.subtitle.slice(0,220),destination:r.destination.slice(0,320)})}
async function rpc(c:RpcClient,n:string,a:Readonly<Record<string,unknown>>,w=false,t=15_000):Promise<unknown>{let timer:ReturnType<typeof setTimeout>|undefined;const deadline=new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new DataAccessError(w?'Write outcome unknown':'Read timed out',w?'DATA_OUTCOME_UNKNOWN':'DATA_UNAVAILABLE')),t)});try{const x=await Promise.race([Promise.resolve(c.rpc(n,a)),deadline]);if(x.error)throw normalizeDataFailure(x.error);return x.data}catch(e){throw normalizeThrownDataFailure(e,w?'write':'read')}finally{if(timer!==undefined)clearTimeout(timer)}}

export function createSearchIntelligenceGateway(client:EnjazSupabaseClient,timeout=15_000):SearchIntelligenceGateway{if(!pos(timeout)||timeout>120_000)throw new Error('Invalid RPC timeout');const c=client as unknown as RpcClient;return Object.freeze({
async listSavedViews(workspaceId:string){const x=await rpc(c,'list_saved_views_v1',{p_workspace_id:workspaceId},false,timeout);if(!Array.isArray(x))throw err('Invalid saved-view list');return Object.freeze(x.map(view))},
async saveSavedView(input:SaveSavedViewInput){const name=input.name.normalize('NFKC').replace(/\s+/g,' ').trim().slice(0,80),v=input.visibility??'personal',team=input.teamId??null,d=definition(input.definition);if(!name||!visibility(v)||!d||(v==='team')!==(team!==null)||(input.savedViewId===null)!==(input.expectedVersion===null))throw err('Invalid saved-view boundary','DATA_VALIDATION_FAILED');return write(await rpc(c,'save_saved_view_v1',{p_workspace_id:input.workspaceId,p_saved_view_id:input.savedViewId,p_expected_version:input.expectedVersion,p_operation_id:input.operationId,p_name:name,p_visibility:v,p_team_id:team,p_definition:d},true,timeout))},
async deleteSavedView(workspaceId:string,savedViewId:string,expectedVersion:number,operationId:string){if(!pos(expectedVersion))throw err('Invalid saved-view version','DATA_VALIDATION_FAILED');return write(await rpc(c,'delete_saved_view_v1',{p_workspace_id:workspaceId,p_saved_view_id:savedViewId,p_expected_version:expectedVersion,p_operation_id:operationId},true,timeout))},
async globalSearch(workspaceId:string,query:string,limitPerDomain=8){const q=query.normalize('NFKC').replace(/\s+/g,' ').trim().slice(0,120);if(q.length<2)return Object.freeze([]);if(!pos(limitPerDomain)||limitPerDomain>10)throw err('Invalid search limit','DATA_VALIDATION_FAILED');const x=await rpc(c,'global_search_v1',{p_workspace_id:workspaceId,p_query:q,p_limit_per_domain:limitPerDomain},false,timeout);if(!Array.isArray(x))throw err('Invalid search result');const y=x.map(result);if(y.some(v=>v===null))throw err('Global-search contract drifted');return Object.freeze(y as GlobalSearchResultReference[])}
})}
